In [48]:
import os
import camelot
import pandas as pd
from tqdm import tqdm
from IPython.display import display
import warnings
import re
import numpy as np
import pdfplumber

warnings.filterwarnings("ignore")

folder = os.getcwd()
pdf_files = [os.path.join(folder, f) for f in os.listdir(folder) if f.lower().endswith(".pdf")]


def extract_numbers(name):

    nums = re.findall(r'\d+', name)
    return tuple(map(int, nums))

replacements = {
    'Ⅰ': 'I',
    'Ⅱ': 'II',
    'Ⅲ': 'III',
    'Ⅳ': 'IV',
    'Ⅴ': 'V',
    'Ⅵ': 'VI',
    'Ⅶ': 'VII',
    'Ⅷ': 'VIII',
    'Ⅸ': 'IX',
    'Ⅹ': 'X'
}

def extract_tables_camelot(pdf_path: str, out_dir="tables", pages="all", title_height=120):

    os.makedirs(out_dir, exist_ok=True)

    tables_lattice = camelot.read_pdf(
        pdf_path,
        pages=pages,
        flavor="lattice",
        line_scale=80
    )

    lattice_pages = set()
    text_pages = set()

    with pdfplumber.open(pdf_path) as pdf:

        for i, t in enumerate(tables_lattice):

            page_num = int(t.page)          
            page_idx = page_num - 1        
            lattice_pages.add(page_num)

            t.to_csv(
                os.path.join(out_dir, f"lattice_p{page_num}_{i}.csv"),
                index=False
            )

            page = pdf.pages[page_idx]

            x1, y1, x2, y2 = t._bbox
            page_w = page.width
            page_h = page.height

            table_top = page_h - y2

            left   = max(0, min(x1, page_w))
            right  = max(0, min(x2, page_w))
            top    = max(0, min(table_top - title_height, page_h))
            bottom = max(0, min(table_top, page_h))

            if right > left and bottom > top:
                title_box = (left, top, right, bottom)
                title_text = page.crop(title_box, strict=False).extract_text(
                    x_tolerance=2,
                    y_tolerance=2
                ) or ""

                if title_text.strip():
                    text_pages.add(page_num)
            else:
                title_text = ""

            with open(
                os.path.join(out_dir, f"text_p{page_num}_{i}.txt"),
                "w",
                encoding="utf-8"
            ) as f:
                f.write(title_text.strip())

    return None       



def join_ordered(series):
    vals = series.dropna().astype(str).str.strip()
    vals = [v for v in vals if v]
    seen = set()
    result = []
    for v in vals:
        if v not in seen:
            seen.add(v)
            result.append(v)
    return "; ".join(result) if result else None



def merge_parts(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if 'Qty' in df.columns:
        agg_map = {
            "Qty": "sum",
        }
    elif 'Код материалов' in df.columns:
        agg_map = {
            "Кол-во": "sum",
        }
    elif '件数' in df.columns:
        agg_map = {
            '件数': 'sum'
        }
    elif 'Units' in df.columns:
        agg_map = {
            'Units': 'sum'
        }

    if "Item and Spec" in df.columns:

        agg_map["Item and Spec"] = join_ordered
    if "Remark" in df.columns:
        agg_map["Remark"] = join_ordered

    if 'Наименование и спецификация' in df.columns:
        agg_map['Наименование и спецификация'] = join_ordered

    if 'Примечание' in df.columns:
        agg_map['Примечание'] = join_ordered

    if 'Версия' in df.columns:
        agg_map['Версия'] = join_ordered

    if 'Rev.' in df.columns:
        agg_map['Rev.'] = join_ordered

    if "名称及规格" in df.columns:
        agg_map["名称及规格"] = join_ordered

    if "备注" in df.columns:
        agg_map["备注"] = join_ordered

    if "Section" in df.columns:
        agg_map["Section"] = join_ordered


    if 'Material No.' in df.columns:
        df_agg = df.groupby("Material No.", as_index=False).agg(agg_map)
    elif 'Код материалов' in df.columns:
        df_agg = df.groupby("Код материалов", as_index=False).agg(agg_map)
    elif '物料编码' in df.columns:
        df_agg = df.groupby("物料编码", as_index=False).agg(agg_map)


    return df_agg

b = 18
e = b+1

for i, pth in enumerate(tqdm(pdf_files[b:e])):
    
    filename = os.path.basename(pth)          
    filename = os.path.splitext(filename)[0]
    print(f'Обработка файла: {filename}')

    # extract_tables_camelot(pth, filename, pages="all", title_height=800)

    dfs = []

    for file in sorted(os.listdir(filename), key=extract_numbers):

        if not file.startswith("lattice_") or not file.lower().endswith(".csv"):
            continue

        path = os.path.join(filename, file)

        if os.path.getsize(path) == 0:  
            continue
        df_i = pd.read_csv(path, converters={1: str})

        required_cols = ['NO.', 'Код материалов', 'No.', 'Код мат-ла', 'Serial No.', 'Part No.', '物料编码']

        if (
            df_i.empty
            or df_i.shape[1] < 4
            or not any(col in df_i.columns for col in required_cols)
            ):
            continue

        # если китаец насрал пробел в начале таблицы
        if 'NO.' in df_i.iloc[0].values or 'Material No.' in df_i.iloc[0].values:
            df_i.columns = df_i.iloc[0]  
            df_i = df_i[1:].reset_index(drop=True) 

        if 'NO.' in df_i.columns:
            df_i = df_i.drop("NO.", axis=1)
        if 'No.' in df_i.columns:
            df_i = df_i.drop("No.", axis=1)
        elif '№ п/п' in df_i.columns:
            df_i = df_i.drop("№ п/п", axis=1)
        elif '№ \nп/п' in df_i.columns:
            df_i = df_i.drop('№ \nп/п', axis=1)
        elif 'Serial No.' in df_i.columns:
            df_i = df_i.drop('Serial No.', axis=1)
        elif '序号' in df_i.columns:
            df_i = df_i.drop('序号', axis=1)

        idx = file.replace("lattice_", "").rsplit(".", 1)[0]
        section_val = os.path.join(filename, f"text_{idx}.txt")
        
        with open(section_val, "r", encoding="utf-8") as f:
            lines = f.read().splitlines()

        skip_titles = [
            'Руководство по деталъная структура',
            'Альбом чертежей деталей и узлов коленчатого подъемника для высотных работ',
            'Альбом чертежей деталей и компонентов',
            'Parts Manual'
        ]

        if lines and lines[0] in skip_titles:
            lines = lines[1:]
                
        if lines and lines[0] == 'Альбом чертежей деталей и узлов коленчатого':
            lines = lines[2:]

        lines_joined = " ".join(lines)
            
        df_i["Section"] = lines_joined
        

        df_i = df_i[df_i.iloc[:, 0].replace('', pd.NA).notna()]
        display(df_i)
        df_i = df_i[df_i.iloc[:, 0] != '/']
        dfs.append(df_i)

    df_all = pd.concat(dfs, ignore_index=True)
    display(df_all)
    df_all.to_excel('dfs.xlsx', index=False)

    for old_col in ['Наименование и \nспецификация', 'Наименование и \r\nспецификация']:
        if old_col in df_all.columns:
            if 'Наименование и спецификация' in df_all.columns:
                df_all['Наименование и спецификация'] = df_all.loc[:, old_col].combine_first(df_all['Наименование и спецификация'])
            else:
                df_all['Наименование и спецификация'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Наименование и спецификация' in df_all.columns:
        col = df_all.pop("Наименование и спецификация")  
        df_all.insert(1, "Наименование и спецификация", col) 
                
    if 'Name and Spec.' in df_all.columns:
        if 'Item and Spec' in df_all.columns:
            df_all['Item and Spec'] = df_all.loc[:, 'Name and Spec.'].combine_first(df_all['Item and Spec'])
        else:
            df_all['Item and Spec'] = df_all['Name and Spec.']
        df_all = df_all.drop(columns='Name and Spec.')
        col = df_all.pop("Item and Spec")  
        df_all.insert(1, "Item and Spec", col)  
        
    if 'Spec and Item' in df_all.columns:
        if 'Item and Spec' in df_all.columns:
            df_all['Item and Spec'] = df_all.loc[:, 'Spec and Item'].combine_first(df_all['Item and Spec'])
        else:
            df_all['Item and Spec'] = df_all['Spec and Item']
        df_all = df_all.drop(columns='Spec and Item')
        col = df_all.pop("Item and Spec")  
        df_all.insert(1, "Item and Spec", col)  

    if 'Версия  Кол-' in df_all.columns:
        df_all['Версия'] = df_all.loc[:, 'Версия  Кол-'].combine_first(df_all['Версия'])
        df_all = df_all.drop(columns='Версия  Кол-')

    if 'во' in df_all.columns:
        df_all['Кол-\nво'] = df_all.loc[:, 'во'].combine_first(df_all['Кол-\nво'])
        df_all = df_all.drop(columns='во')

    if 'Nombre y especificación' in df_all.columns:
        df_all['Наименование и спецификация'] = df_all.loc[:, 'Nombre y especificación'].combine_first(df_all['Наименование и спецификация'])
        df_all = df_all.drop(columns='Nombre y especificación')
        col = df_all.pop("Наименование и спецификация")  
        df_all.insert(1, "Наименование и спецификация", col)  
    
    if 'Примечани\nе' in df_all.columns:
        df_all['Примечание'] = df_all.loc[:, 'Примечани\nе'].combine_first(df_all['Примечание'])
        df_all = df_all.drop(columns='Примечани\nе')

    if 'Part No.' in df_all.columns:
        if 'Material No.' in df_all.columns:
            df_all['Material No.'] = df_all.loc[:, 'Part No.'].combine_first(df_all['Material No.'])
        else:
            df_all['Material No.'] = df_all['Part No.']
        df_all = df_all.drop(columns='Part No.')
        col = df_all.pop("Material No.")  
        df_all.insert(0, "Material No.", col)  

    if 'Código de material' in df_all.columns:
        df_all['Код материалов'] = df_all.loc[:, 'Código de material'].combine_first(df_all['Код материалов'])
        df_all = df_all.drop(columns='Código de material')
        col = df_all.pop("Код материалов")  
        df_all.insert(0, "Код материалов", col)  

    if 'Кол-\nво' in df_all.columns:
        if 'Кол-во' in df_all.columns:
            df_all['Кол-во'] = df_all.loc[:, 'Кол-\nво'].combine_first(df_all['Кол-во'])
        else:
            df_all['Кол-во'] = df_all['Кол-\nво']
        df_all = df_all.drop(columns='Кол-\nво')
        col = df_all.pop('Кол-во')  
        df_all.insert(2, 'Кол-во', col)  

    if 'Qty.' in df_all.columns:
        if 'Qty' in df_all.columns:
            df_all['Qty'] = df_all.loc[:, 'Qty.'].combine_first(df_all['Qty'])
        else:
            df_all['Qty'] = df_all['Qty.']
        df_all = df_all.drop(columns='Qty.')
        col = df_all.pop('Qty')  
        df_all.insert(2, 'Qty', col)  

    if 'Кол-\r\nво' in df_all.columns:
        if 'Кол-во' in df_all.columns:
            df_all['Кол-во'] = df_all.loc[:, 'Кол-\r\nво'].combine_first(df_all['Кол-во'])
        else:
            df_all['Кол-во'] = df_all['Кол-\r\nво']
        df_all = df_all.drop(columns='Кол-\r\nво')
        col = df_all.pop('Кол-во')  
        df_all.insert(2, 'Кол-во', col)  

    if 'Cantidad' in df_all.columns:
        df_all['Кол-во'] = df_all.loc[:, 'Cantidad'].combine_first(df_all['Кол-во'])
        df_all = df_all.drop(columns='Cantidad')
        col = df_all.pop('Кол-во')  
        df_all.insert(2, 'Кол-во', col)  

    if 'Unit' in df_all.columns:
        df_all['Qty'] = df_all.loc[:, 'Unit'].combine_first(df_all['Qty'])
        df_all = df_all.drop(columns='Unit')
        col = df_all.pop('Qty')  
        df_all.insert(2, 'Qty', col)  

    if 'Note' in df_all.columns and 'Remark' in df_all.columns:
        df_all['Remark'] = df_all.loc[:, 'Note'].combine_first(df_all['Remark'])
        df_all = df_all.drop(columns='Note')
        col = df_all.pop('Remark')  
        df_all.insert(2, 'Remark', col)  
    elif 'Note' in df_all.columns and 'Remark' not in df_all.columns:
        df_all['Remark'] = df_all['Note']
        df_all = df_all.drop(columns='Note')
        col = df_all.pop('Remark')  
        df_all.insert(3, 'Remark', col)  

    if 'Observaciones' in df_all.columns and 'Примечание' in df_all.columns:
        df_all['Примечание'] = df_all.loc[:, 'Observaciones'].combine_first(df_all['Примечание'])
        df_all = df_all.drop(columns='Observaciones')
        col = df_all.pop('Примечание')  
        df_all.insert(3, 'Примечание', col) 

    if 'Кол-в\nо \nштук' in df_all.columns and 'Кол-во \nштук' in df_all.columns:
        df_all['Кол-во \nштук'] = df_all.loc[:, 'Кол-в\nо \nштук'].combine_first(df_all['Кол-во \nштук'])
        df_all = df_all.drop(columns='Кол-в\nо \nштук')

    if 'Кол-\nво \nшту\nк' in df_all.columns and 'Кол-во \nштук' in df_all.columns:
        df_all['Кол-во \nштук'] = df_all.loc[:, 'Кол-\nво \nшту\nк'].combine_first(df_all['Кол-во \nштук'])
        df_all = df_all.drop(columns='Кол-\nво \nшту\nк')

    if 'Кол-во \nштук' in df_all.columns and 'Кол-во' not in df_all.columns:
        df_all['Кол-во'] = df_all['Кол-во \nштук']
        df_all = df_all.drop(columns='Кол-во \nштук')
        col = df_all.pop('Кол-во')  
        df_all.insert(2, 'Кол-во', col)  
    
    if 'Код мат-ла' in df_all.columns and 'Код материалов' not in df_all.columns:
        df_all['Код материалов'] = df_all['Код мат-ла']
        df_all = df_all.drop(columns='Код мат-ла')
        col = df_all.pop('Код материалов')  
        df_all.insert(0, 'Код материалов', col)  

    if 'Кол-во' in df_all.columns:
        df_all['Кол-во'] = df_all['Кол-во'].replace('/', 0)
        df_all['Кол-во'] = df_all['Кол-во'].fillna(0)
        df_all['Кол-во'] = df_all['Кол-во'].astype(int)

    if 'Qty' in df_all.columns:
        df_all['Qty'] = df_all['Qty'].replace('/', 0)
        df_all['Qty'] = df_all['Qty'].fillna(0)
        df_all['Qty'] = df_all['Qty'].astype(int)

    if '件数' in df_all.columns:
        df_all['件数'] = df_all['件数'].replace('/', 0)
        df_all['件数'] = df_all['件数'].replace('、', 0)
        df_all['件数'] = df_all['件数'].fillna(0)
        df_all['件数'] = df_all['件数'].astype(int)

    df_all.to_excel('df_all.xlsx', index=False)
    df_all = pd.read_excel('df_all.xlsx')
    display(df_all.head())

    test_1 = pd.read_excel('dfs.xlsx')
    assert test_1.shape[0] == df_all.shape[0]

    if 'Material No.' in df_all.columns:
        df_all['Material No.'] = df_all['Material No.'].str.split('\n').str[0]
        df_all = df_all[~df_all['Material No.'].astype(str).str.startswith('NO-NUMBER')]

    cols = df_all.select_dtypes(include='object').columns
    df_all[cols] = (df_all[cols].replace(r'\s*\n\s*', ' ', regex=True))
    df_all[cols] = df_all[cols].replace(replacements, regex=True)

    if 'Item and Spec' in df_all.columns:
        df_all['Item and Spec'] = df_all['Item and Spec'].replace('/', np.nan)
    
    if '物料编码' in df_all.columns:
        mask = df_all['物料编码'].str.contains(r'^\d+\s+\D', na=False)
        extracted = df_all.loc[mask, '物料编码'].str.extract(r'^(\d+)\s+(.*)$')
        df_all.loc[mask, '物料编码'] = extracted[0]
        df_all.loc[mask, '名称及规格'] = extracted[1]

    df_merged = merge_parts(df_all) 
    assert (df_all.shape[0] - df_all.iloc[:, 0].duplicated().sum() - df_merged.shape[0]) == 0

    lst = ['ZS1623RT', 'ZA10RJE', 'ZA14J', 'ZA14JE-Li', 'ZA14NJE', 'ZA16J', 'ZA16JERT', 'ZA18J', 'ZA20J', 'ZA20JE', 'ZA20JERT', 'ZA22J-V' ,'ZA22J', 'ZA24J', 'ZA32J(H-образ.)', 'ZA32J(X-образ.)', 'ZT42J-V', 'ZA42J', 'lol']
    df_merged['Models'] = lst[b]

    df_merged.to_excel(f'{filename}.xlsx', index=False)

  0%|          | 0/1 [00:00<?, ?it/s]

Обработка файла: ZS 0407 - 1414 HDS

,Material No.,Item and Spec,Units,Remark,Section
0,00775700000001040,Lower sliding block I,1,NaN,ZS1414 Series Pin Installation
1,00775600300001140,Gasket,2,NaN,ZS1414 Series Pin Installation
2,1054400310,Composite bush,2,NaN,ZS1414 Series Pin Installation
3,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS1414 Series Pin Installation
4,1040000025,Bolt M10×80-8.8,2,GB/T5783-2000,ZS1414 Series Pin Installation
5,00775700000001020,Lower sliding axle,1,NaN,ZS1414 Series Pin Installation
6,00775700000001050,Lower sliding block II,1,NaN,ZS1414 Series Pin Installation
7,00775600000001070,Upper stationary axle,4,NaN,ZS1414 Series Pin Installation
8,00775700000001060,Upper sliding block,2,NaN,ZS1414 Series Pin Installation
9,1040300526,Washer 12,8,GB/T97.1-2002,ZS1414 Series Pin Installation
10,1040000807,Bolt M12×120-8.8,4,GB/T5782-2000,ZS1414 Series Pin Installation
11,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS1414 Series Pin Installation
12,1054400309,Composite bush,4,NaN,ZS1414 Series Pin Installation
13,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS1414 Series Pin Installation
14,1040300063,Washer 8,1,GB/T93-1987,ZS1414 Series Pin Installation
15,1040300066,Washer 8,1,GB/T97.1-2002,ZS1414 Series Pin Installation
16,00775600000001050,Articulated pin,1,NaN,ZS1414 Series Pin Installation
17,00775700000001030,Lower stationary axle,1,NaN,ZS1414 Series Pin Installation
18,00775700000001070,Upper sliding block,2,NaN,ZS1414 Series Pin Installation
19,00775700100000000,Work platform,1,NaN,ZS1414 Series Pin Installation
20,00775700300000000,Scissor arm,1,NaN,ZS1414 Series Pin Installation
21,00775702800000000,Chassis(ZS1414HD-Li),1,NaN,ZS1414 Series Pin Installation
22,00775702810000000,Chassis(ZS1414HD),1,NaN,ZS1414 Series Pin Installation
23,00775702820000000,Chassis(ZS1414DC-Li)(Indoor Series),1,NaN,ZS1414 Series Pin Installation
24,00775702830000000,Chassis(ZS1414DC) (Indoor Series),1,NaN,ZS1414 Series Pin Installation
25,00775702860000000,Chassis(ZS1414HA-Li),1,NaN,ZS1414 Series Pin Installation
26,00775702870000000,Chassis(ZS1414HA),1,NaN,ZS1414 Series Pin Installation
27,00775702850000000,Chassis(ZS1414AC-Li) (Indoor Series),1,NaN,ZS1414 Series Pin Installation
28,00775702880000000,Chassis(ZS1414AC) (Indoor Series),1,NaN,ZS1414 Series Pin Installation
29,007757028E0000000,Chassis(ZS1414DC-Li) (Outdoor Series),1,2022.10 Revise,ZS1414 Series Pin Installation
30,007757028D0000000,Chassis(ZS1414DC) (Outdoor Series),1,2022.10 Revise,ZS1414 Series Pin Installation
31,007757028G0000000,Chassis(ZS1414AC-Li) (Outdoor Series),1,2022.10 Revise,ZS1414 Series Pin Installation
32,007757028F0000000,Chassis(ZS1414AC) (Outdoor Series),1,2022.10 Revise,ZS1414 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775700000001040,Lower sliding block I,1,NaN,ZS1212 Series Pin Installation
1,1040000025,Bolt M10×80-8.8,2,GB/T5783-2000,ZS1212 Series Pin Installation
2,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS1212 Series Pin Installation
3,00775600000001040,Lower sliding axle,1,NaN,ZS1212 Series Pin Installation
4,00775700000001050,Lower sliding block II,1,NaN,ZS1212 Series Pin Installation
5,00775600000001070,Upper stationary axle,4,NaN,ZS1212 Series Pin Installation
6,1040000807,Bolt M12×110-8.8,4,GB/T5782-2000,ZS1212 Series Pin Installation
7,1040300526,Washer 12,8,GB/T97.1-2002,ZS1212 Series Pin Installation
8,00775700000001060,Upper sliding block,2,NaN,ZS1212 Series Pin Installation
9,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS1212 Series Pin Installation
10,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS1212 Series Pin Installation
11,1040300063,Washer 8,1,GB/T93-1987,ZS1212 Series Pin Installation
12,1040300066,Washer 8,1,GB/T97.1-2002,ZS1212 Series Pin Installation
13,00775600000001050,Articulated pin,1,NaN,ZS1212 Series Pin Installation
14,00775600000001080,Lower stationary axle,1,NaN,ZS1212 Series Pin Installation
15,00775700000001070,Upper sliding block,2,NaN,ZS1212 Series Pin Installation
16,00775600100000000,Work platform,1,NaN,ZS1212 Series Pin Installation
17,00775600310000000,Scissor arm,1,NaN,ZS1212 Series Pin Installation
18,00775602800000000,Chassis(ZS1212HD),1,NaN,ZS1212 Series Pin Installation
19,00775602810000000,Chassis(ZS1212DC) (Indoor Series),1,NaN,ZS1212 Series Pin Installation
20,00775602820000000,Chassis(ZS1212HD-Li),1,NaN,ZS1212 Series Pin Installation
21,00775602830000000,Chassis(ZS1212DC-Li) (Indoor Series),1,NaN,ZS1212 Series Pin Installation
22,00775602840000000,Chassis(ZS1212HA-Li),1,NaN,ZS1212 Series Pin Installation
23,00775602850000000,Chassis(ZS1212AC-Li) (Indoor Series),1,NaN,ZS1212 Series Pin Installation
24,00775602860000000,Chassis(ZS1212HA),1,NaN,ZS1212 Series Pin Installation
25,00775602870000000,Chassis(ZS1212AC) (Indoor Series),1,NaN,ZS1212 Series Pin Installation
26,00775602880000000,Chassis(ZS1212DC) (Outdoor Series),1,2022.10 Revise,ZS1212 Series Pin Installation
27,007756028D0000000,Chassis(ZS1212DC-Li) (Outdoor Series),1,2022.10 Revise,ZS1212 Series Pin Installation
28,007756028F0000000,Chassis(ZS1212AC) (Outdoor Series),1,2022.10 Revise,ZS1212 Series Pin Installation
29,007756028G0000000,Chassis(ZS1212AC-Li) (Outdoor Series),1,2022.10 Revise,ZS1212 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775700000001040,Lower sliding block I,1,NaN,ZS1012 Series Pin Installation
1,1040000025,Bolt M10×80-8.8,2,GB/T5783-2000,ZS1012 Series Pin Installation
2,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS1012 Series Pin Installation
3,00775600000001040,Lower sliding axle,1,NaN,ZS1012 Series Pin Installation
4,00775700000001050,Lower sliding block II,1,NaN,ZS1012 Series Pin Installation
5,00775600000001070,Upper stationary axle,4,NaN,ZS1012 Series Pin Installation
6,1040000807,Bolt M12×110-8.8,4,GB/T5782-2000,ZS1012 Series Pin Installation
7,1040300526,Washer 12,8,GB/T97.1-2002,ZS1012 Series Pin Installation
8,00775700000001060,Upper sliding block,2,NaN,ZS1012 Series Pin Installation
9,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS1012 Series Pin Installation
10,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS1012 Series Pin Installation
11,1040300063,Washer 8,1,GB/T93-1987,ZS1012 Series Pin Installation
12,1040300066,Washer 8,1,GB/T97.1-2002,ZS1012 Series Pin Installation
13,00775600000001050,Articulated pin,1,NaN,ZS1012 Series Pin Installation
14,00775600000001080,Lower stationary axle,1,NaN,ZS1012 Series Pin Installation
15,00775700000001070,Upper sliding block,2,NaN,ZS1012 Series Pin Installation
16,00775600100000000,Work platform,1,NaN,ZS1012 Series Pin Installation
17,00775500320000000,Scissor arm,1,NaN,ZS1012 Series Pin Installation
18,00775502800000000,Chassis(ZS1012HD),1,NaN,ZS1012 Series Pin Installation
19,00775502810000000,Chassis(ZS1012DC),1,NaN,ZS1012 Series Pin Installation
20,00775502820000000,Chassis(ZS1012HD-Li),1,NaN,ZS1012 Series Pin Installation
21,00775502830000000,Chassis(ZS1012DC-Li),1,NaN,ZS1012 Series Pin Installation
22,00775502840000000,Chassis(ZS1012HA-Li),1,NaN,ZS1012 Series Pin Installation
23,00775502850000000,Chassis(ZS1012AC-Li),1,NaN,ZS1012 Series Pin Installation
24,00775502860000000,Chassis(ZS1012HA),1,NaN,ZS1012 Series Pin Installation
25,00775502870000000,Chassis(ZS1012AC),1,NaN,ZS1012 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775700000001040,Lower sliding block I,1,NaN,ZS0812 Series Pin Installation
1,1040000025,Bolt M10×80-8.8,2,GB/T5783-2000,ZS0812 Series Pin Installation
2,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS0812 Series Pin Installation
3,00775600000001040,Lower sliding axle,1,NaN,ZS0812 Series Pin Installation
4,00775700000001050,Lower sliding block II,1,NaN,ZS0812 Series Pin Installation
5,00775600000001070,Upper stationary axle,4,NaN,ZS0812 Series Pin Installation
6,1040000807,Bolt M12×110-8.8,4,GB/T5782-2000,ZS0812 Series Pin Installation
7,1040300526,Washer 12,8,GB/T97.1-2002,ZS0812 Series Pin Installation
8,00775700000001060,Upper sliding block,2,NaN,ZS0812 Series Pin Installation
9,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS0812 Series Pin Installation
10,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0812 Series Pin Installation
11,1040300063,Washer 8,1,GB/T93-1987,ZS0812 Series Pin Installation
12,1040300066,Washer 8,1,GB/T97.1-2002,ZS0812 Series Pin Installation
13,00775600000001050,Articulated pin,1,NaN,ZS0812 Series Pin Installation
14,00775600000001080,Lower stationary axle,1,NaN,ZS0812 Series Pin Installation
15,00775700000001070,Upper sliding block,2,NaN,ZS0812 Series Pin Installation
16,00775600100000000,Work platform,1,NaN,ZS0812 Series Pin Installation
17,00775400330000000,Scissor arm,1,NaN,ZS0812 Series Pin Installation
18,00775402850000000,Chassis(ZS0812DC),1,NaN,ZS0812 Series Pin Installation
19,00775402880000000,Chassis(ZS0812DC-Li),1,NaN,ZS0812 Series Pin Installation
20,007754028B0000000,Chassis(ZS0812HA-Li),1,NaN,ZS0812 Series Pin Installation
21,007754028C0000000,Chassis(ZS0812HA),1,NaN,ZS0812 Series Pin Installation
22,007754028J0000000,Chassis(ZS0812AC),1,NaN,ZS0812 Series Pin Installation
23,007754028K0000000,Chassis(ZS0812AC-Li),1,NaN,ZS0812 Series Pin Installation
24,007754028X0000000,Chassis(ZS0812HD-Li),1,2022.10 Revise,ZS0812 Series Pin Installation
25,007754028W0000000,Chassis(ZS0812HD),1,2022.10 Revise,ZS0812 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775400000001050,Lower sliding block I,2,NaN,ZS0808 Series Pin Installation
1,1040000025,Bolt M10×80-8.8,2,GB/T5783-2000,ZS0808 Series Pin Installation
2,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS0808 Series Pin Installation
3,00775400000001040,Lower sliding axle,1,NaN,ZS0808 Series Pin Installation
4,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0808 Series Pin Installation
5,1040300063,Washer 8,1,GB/T93-1987,ZS0808 Series Pin Installation
6,1040300066,Washer 8,1,GB/T97.1-2002,ZS0808 Series Pin Installation
7,00775600000001050,Articulated pin,1,NaN,ZS0808 Series Pin Installation
8,00775400000001020,Lower stationary axle,1,NaN,ZS0808 Series Pin Installation
9,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS0808 Series Pin Installation
10,1040300526,Washer 12,8,GB/T97.1-2002,ZS0808 Series Pin Installation
11,00775700000001070,Upper sliding block,2,NaN,ZS0808 Series Pin Installation
12,1040000807,Bolt M12×120-8.8,4,GB/T5782-2000,ZS0808 Series Pin Installation
13,00775600000001070,Upper stationary axle,4,NaN,ZS0808 Series Pin Installation
14,00775400100000000,Work platform,1,NaN,ZS0808 Series Pin Installation
15,00775400300000000,Scissor arm,1,NaN,ZS0808 Series Pin Installation
16,00775402800000000,Chassis(ZS0808HD),1,NaN,ZS0808 Series Pin Installation
17,00775402810000000,Chassis(ZS0808DC) (Indoor Series),1,NaN,ZS0808 Series Pin Installation
18,00775402820000000,Chassis(ZS0808HD-Li),1,NaN,ZS0808 Series Pin Installation
19,00775402840000000,Chassis(ZS0808DC-Li) (Indoor Series),1,NaN,ZS0808 Series Pin Installation
20,00775402870000000,Chassis(ZS0808HA-Li),1,NaN,ZS0808 Series Pin Installation
21,00775402860000000,Chassis(ZS0808AC-Li) (Indoor Series),1,NaN,ZS0808 Series Pin Installation
22,00775402890000000,Chassis(ZS0808HA),1,NaN,ZS0808 Series Pin Installation
23,007754028A0000000,Chassis(ZS0808AC) (Indoor Series),1,NaN,ZS0808 Series Pin Installation
24,007754028U0000000,Chassis(ZS0808DC) (Outdoor Series),1,2022.10 Revise,ZS0808 Series Pin Installation
25,007754028R0000000,Chassis(ZS0808DC-Li) (Outdoor Series),1,2022.10 Revise,ZS0808 Series Pin Installation
26,007754028S0000000,Chassis(ZS0808AC) (Outdoor Series),1,2022.10 Revise,ZS0808 Series Pin Installation
27,007754028T0000000,Chassis(ZS0808AC-Li) (Outdoor Series),1,2022.10 Revise,ZS0808 Series Pin Installation
28,00775700000001060,Upper sliding block,2,NaN,ZS0808 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775400000001050,Lower sliding block I,2,NaN,ZS0608 Series Pin Installation
1,1040000025,Bolt M10×80-8.8,2,GB/T5783-2000,ZS0608 Series Pin Installation
2,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS0608 Series Pin Installation
3,00775400000001040,Lower sliding axle,1,NaN,ZS0608 Series Pin Installation
4,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0608 Series Pin Installation
5,1040300063,Washer 8,1,GB/T93-1987,ZS0608 Series Pin Installation
6,1040300066,Washer 8,1,GB/T97.1-2002,ZS0608 Series Pin Installation
7,00775600000001050,Articulated pin,1,NaN,ZS0608 Series Pin Installation
8,00775400000001020,Lower stationary axle,1,NaN,ZS0608 Series Pin Installation
9,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS0608 Series Pin Installation
10,1040300526,Washer 12,8,GB/T97.1-2002,ZS0608 Series Pin Installation
11,00775700000001070,Upper sliding block,2,NaN,ZS0608 Series Pin Installation
12,1040000807,Bolt M12×120-8.8,4,GB/T5782-2000,ZS0608 Series Pin Installation
13,00775600000001070,Upper stationary axle,4,NaN,ZS0608 Series Pin Installation
14,00775400100000000,Work platform,1,NaN,ZS0608 Series Pin Installation
15,00775300300000000,Scissor arm,1,NaN,ZS0608 Series Pin Installation
16,00775402800000000,Chassis(ZS0608HD),1,NaN,ZS0608 Series Pin Installation
17,00775402810000000,Chassis(ZS0608DC),1,NaN,ZS0608 Series Pin Installation
18,00775402820000000,Chassis(ZS0608HD-Li),1,NaN,ZS0608 Series Pin Installation
19,00775402840000000,Chassis(ZS0608DC-Li),1,NaN,ZS0608 Series Pin Installation
20,00775700000001060,Upper sliding block,2,NaN,ZS0608 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775300000011040,Lower sliding block,2,NaN,ZS0607 Series Pin Installation
1,1040000072,Bolt M10×65-8.8,2,GB/T5783-2000,ZS0607 Series Pin Installation
2,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS0607 Series Pin Installation
3,00775300000011030,Lower sliding axle,1,NaN,ZS0607 Series Pin Installation
4,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0607 Series Pin Installation
5,1040300063,Washer 8,1,GB/T93-1987,ZS0607 Series Pin Installation
6,1040300066,Washer 8,1,GB/T97.1-2002,ZS0607 Series Pin Installation
7,00775600000001050,Articulated pin,1,NaN,ZS0607 Series Pin Installation
8,00775300000011020,Lower stationary axle,1,NaN,ZS0607 Series Pin Installation
9,1040200507,Nut M12-8,4,GB/T889.1-2000,ZS0607 Series Pin Installation
10,1040300526,Washer 12,8,GB/T97.1-2002,ZS0607 Series Pin Installation
11,00775300000011080,Upper sliding block,2,NaN,ZS0607 Series Pin Installation
12,1040000807,Bolt M12×120-8.8,4,GB/T5782-2000,ZS0607 Series Pin Installation
13,00775300000011060,Upper stationary axle,4,NaN,ZS0607 Series Pin Installation
14,00775300100000000,Work platform,1,NaN,ZS0607 Series Pin Installation
15,00775300310000000,Scissor arm,1,NaN,ZS0607 Series Pin Installation
16,00775302800000000,Chassis(ZS0607HD),1,NaN,ZS0607 Series Pin Installation
17,00775302810000000,Chassis(ZS0607DC),1,NaN,ZS0607 Series Pin Installation
18,00775302820000000,Chassis(ZS0607HD-Li),1,NaN,ZS0607 Series Pin Installation
19,00775302830000000,Chassis(ZS0607DC-Li),1,NaN,ZS0607 Series Pin Installation
20,00775302880000000,Chassis(ZS0607HA-Li),1,NaN,ZS0607 Series Pin Installation
21,00775302870000000,Chassis(ZS0607AC-Li) (Indoor Series),1,NaN,ZS0607 Series Pin Installation
22,007753028C0000000,Chassis(ZS0607HA),1,NaN,ZS0607 Series Pin Installation
23,007753028A0000000,Chassis(ZS0607AC) (Indoor Series),1,NaN,ZS0607 Series Pin Installation
24,00775302890000000,Chassis(ZS0607ACW),1,NaN,ZS0607 Series Pin Installation
25,007753028D0000000,Chassis(ZS0607ACW-Li),1,NaN,ZS0607 Series Pin Installation
26,007753028B0000000,Chassis(ZS0607DCS),1,2022.10 Revise,ZS0607 Series Pin Installation
27,007753028Q0000000,Chassis(ZS0607AC) (Outdoor Series),1,2022.10 Revise,ZS0607 Series Pin Installation
28,007753028R0000000,Chassis(ZS0607AC-Li) (Outdoor Series),1,2022.10 Revise,ZS0607 Series Pin Installation
29,00775300000011050,Upper sliding block,2,NaN,ZS0607 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040000431,Bolt M8×100-8.8,4,GB/T5783-2000,ZS0407 Series Pin Installation
1,1040300066,Washer 8,9,GB/T97.1-2002,ZS0407 Series Pin Installation
2,00775200001001080,Upper sliding block,2,NaN,ZS0407 Series Pin Installation
3,00775200001001030,Upper stationary axle,4,NaN,ZS0407 Series Pin Installation
4,1040200503,Nut M8,6,GB/T889.1-2000,ZS0407 Series Pin Installation
5,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0407 Series Pin Installation
6,1040300063,Washer 8,1,GB/T93-1987,ZS0407 Series Pin Installation
7,00775600000001050,Articulated pin,1,NaN,ZS0407 Series Pin Installation
8,00775200001001050,Lower stationary axle,1,NaN,ZS0407 Series Pin Installation
9,00775200001001020,Upper sliding block,2,NaN,ZS0407 Series Pin Installation
10,00775200001001070,Lower sliding block,2,NaN,ZS0407 Series Pin Installation
11,00775200001001040,Lower sliding axle,1,NaN,ZS0407 Series Pin Installation
12,1040000469,Bolt M8×55-8.8,2,GB/T5783-2000,ZS0407 Series Pin Installation
13,00775200100000000,Work platform,1,NaN,ZS0407 Series Pin Installation
14,00775200310000000,Scissor arm,1,NaN,ZS0407 Series Pin Installation
15,00775202800000000,Chassis(ZS0407DC) \n(Indoor Series),1,NaN,ZS0407 Series Pin Installation
16,00775202810000000,Chassis(ZS0407DC-Li) \n(Indoor Series),1,NaN,ZS0407 Series Pin Installation
17,00775202870000000,Chassis(ZS0407DC) \n(Outdoor Series),1,2022.10 Revise,ZS0407 Series Pin Installation
18,00775202880000000,Chassis(ZS0407DC-Li) \n(Outdoor Series),1,2022.10 Revise,ZS0407 Series Pin Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1020104278,Platform control assembly,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
1,00775606300410000,Platform control box,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
2,1040300051,Washer 6,13,GB/T97.1-2002,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
3,1040300062,Washer 6,13,GB/T93-1987,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
4,1040100055,Screw M6×20-8.8,6,GB/T70.1-2000,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
5,1040000096,Bolt M6×12-8.8,3,GB/T5783-2000,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
6,1021404307,Inclination switch,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
7,1020521762,Inclination switch,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
8,1040100618,Screw M4×16-8.8,10,GB/T818-2000,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
9,1040300044,Washer 4,8,GB/T93-1987,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
10,1040301697,Washer 4,8,GB/T97.1-2002,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
11,1029906635,LED Strobe light,2,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
12,1029906206,Shield,2,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
13,00775706320601010,Installation bracket,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
14,00775306320601020,Installation \nbracket(ZS0607series),1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
15,1021404319,Angle sensor,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
16,00775706320601020,Screw,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
17,1040300067,Washer10,1,GB/T93-1987,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
18,1040100127,Screw M6×12-8.8,4,GB/T70.1-2000,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
19,00775706300201020,Limit guard,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
20,00775306320201020,Limit guard \n(ZS0607series),1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
21,1040102716,Screw M4×35,4,GB/T70.1-2000,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
22,1020520944,Limit switch,2,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
23,00775706300201010,Limit bracket,1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
24,00775306320201010,Limit bracket \n(ZS0607series),1,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
25,1040201605,Locknut M4-8,4,GB/T889.1-2000,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
26,00775600000001030,Limit block,2,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
27,00775300000011070,Limit block \n(ZS0607series),2,NaN,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...

,Material No.,Item and Spec,Units,Remark,Section
0,1040103333,Screw M6×12-8.8 \n(Only Outdoor Series),2,2022.10 Revise,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
1,007754028R0201020,Limit bracket \n(Only Outdoor Series),1,2022.10 Revise,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
2,1040102775,Bolt M6×40-8.8 \n(Only Outdoor Series),2,2022.10 Revise,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
3,1040302410,Washer 6 \n(Only Outdoor Series),2,2022.10 Revise,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
4,1040201664,Nut M6-8 \n(Only Outdoor Series),2,2022.10 Revise,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...
5,1040000096,Limit switch \n(Only Outdoor Series),1,2022.10 Revise,ZS1414/1212/1012/0812/0808/0608/0607 Series Ac...

,Material No.,Item and Spec,Units,Remark,Section
0,1040100055,Screw M6×20-8.8,4,GB/T70.1-2000,ZS0407 Series Accessory Installation
1,1040300051,Washer 6,12,GB/T97.1-2002,ZS0407 Series Accessory Installation
2,1040300062,Washer 6,12,GB/T93-1987,ZS0407 Series Accessory Installation
3,1020104278,Platform control assembly,1,NaN,ZS0407 Series Accessory Installation
4,00775606300411010,Platform control box,1,NaN,ZS0407 Series Accessory Installation
5,1040100618,Screw M4×35,6,GB/T818-2000,ZS0407 Series Accessory Installation
6,1040201605,Locknut M4-8,6,GB/T889.1-2000,ZS0407 Series Accessory Installation
7,1020521041,Limit switch,3,NaN,ZS0407 Series Accessory Installation
8,00775206310201030,Limit bracket,1,NaN,ZS0407 Series Accessory Installation
9,1040100127,Screw M6×12-8.8,8,GB/T70.1-2000,ZS0407 Series Accessory Installation
10,00775206310201010,Limit guard,1,NaN,ZS0407 Series Accessory Installation
11,1040102341,Screw M5×12-8.8,6,GB/T70.1-2000,ZS0407 Series Accessory Installation
12,1040300048,Washer 5,6,GB/T97.1-2002,ZS0407 Series Accessory Installation
13,1040300060,Washer 5,6,GB/T93-1987,ZS0407 Series Accessory Installation
14,1020521469,Inclination switch,1,NaN,ZS0407 Series Accessory Installation
15,00775200001001060,Limit block \n(Indoor Series),2,NaN,ZS0407 Series Accessory Installation
16,00775200351001060,Limit block \n(Outdoor Series),2,2022.10 Revise,ZS0407 Series Accessory Installation
17,1021404034,Angle sensor,1,NaN,ZS0407 Series Accessory Installation
18,1040100618,Screw M4×16-8.8,6,GB/T818-2000,ZS0407 Series Accessory Installation
19,1040300044,Washer 4,6,GB/T93-1987,ZS0407 Series Accessory Installation
20,1040301697,Washer 4,6,GB/T97.1-2002,ZS0407 Series Accessory Installation
21,1029906635,LED Strobe light,2,NaN,ZS0407 Series Accessory Installation
22,1029906206,Shield,3,NaN,ZS0407 Series Accessory Installation
23,00775206310201020,Lamp holder,3,NaN,ZS0407 Series Accessory Installation
24,1040200867,Nut M5,6,GB/T889.1-2000,ZS0407 Series Accessory Installation
25,1040100055,Screw M5×20-8.8,6,GB/T70.1-2000,ZS0407 Series Accessory Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040103333,Screw M6×12-8.8 \n(Only Outdoor Series),2,2022.10 Revise,ZS0407 Series Accessory Installation
1,007754028R0201020,Limit bracket \n(Only Outdoor Series),1,2022.10 Revise,ZS0407 Series Accessory Installation
2,1040102775,Bolt M6×40-8.8 \n(Only Outdoor Series),2,2022.10 Revise,ZS0407 Series Accessory Installation
3,1040302410,Washer 6 \n(Only Outdoor Series),2,2022.10 Revise,ZS0407 Series Accessory Installation
4,1040201664,Nut M6-8 \n(Only Outdoor Series),2,2022.10 Revise,ZS0407 Series Accessory Installation
5,1040000096,Limit switch \n(Only Outdoor Series),1,2022.10 Revise,ZS0407 Series Accessory Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040200097,Nut M20-8,2,GB/T6170-2000,ZS1414 Series Chassis Counterweight
1,1040300038,Washer 20,2,GB/T93-1987,ZS1414 Series Chassis Counterweight
2,1040300106,Washer 20,4,GB/T97.1-2002,ZS1414 Series Chassis Counterweight
3,00775602800001280,Steel CTW II,1,2022.10 Revise,ZS1414 Series Chassis Counterweight
4,00775602800001310,Weld CTW II,1,NaN,ZS1414 Series Chassis Counterweight
5,1040000202,Bolt M20×200-8.8,2,GB/T5782-2000,ZS1414 Series Chassis Counterweight

,Material No.,Item and Spec,Units,Remark,Section
0,1040000202,Bolt M20×200-8.8,5,GB/T5783-2000,ZS1212 Series Chassis Counterweight
1,1040300106,Washer 20,10,GB/T97.1-2002,ZS1212 Series Chassis Counterweight
2,00775602800001280,Steel CTW II,1,2022.10 Revise,ZS1212 Series Chassis Counterweight
3,00775602800001310,Weld CTW II,1,NaN,ZS1212 Series Chassis Counterweight
4,1040300038,Washer 20,5,GB/T93-1987,ZS1212 Series Chassis Counterweight
5,1040200097,Nut M20-8,5,GB/T6170-2000,ZS1212 Series Chassis Counterweight
6,00775602800001290,Steel CTW I,1,2022.10 Revise,ZS1212 Series Chassis Counterweight
7,00775602800001320,Weld CTW I,1,NaN,ZS1212 Series Chassis Counterweight

,Material No.,Item and Spec,Units,Remark,Section
0,1040000030,Bolt M20×110-8.8,2,GB/T5783-2000,ZS1012 Series Chassis Counterweight
1,1040300106,Washer 20,10,GB/T97.1-2002,ZS1012 Series Chassis Counterweight
2,00775602800001260,Steel CTW,1,NaN,ZS1012 Series Chassis Counterweight
3,1040300038,Washer 20,5,GB/T93-1987,ZS1012 Series Chassis Counterweight
4,1040200097,Nut M20-8,5,GB/T6170-2000,ZS1012 Series Chassis Counterweight
5,00775602800001290,Steel CTW I,1,2022.10 Revise,ZS1012 Series Chassis Counterweight
6,00775602800001320,Weld CTW I,1,NaN,ZS1012 Series Chassis Counterweight
7,1040000202,Bolt M20×200-8.8,3,GB/T5783-2000,ZS1012 Series Chassis Counterweight

,Material No.,Item and Spec,Units,Remark,Section
0,1040000030,Bolt M20×110-8.8,2.0,GB/T5783-2000,ZS0812 Series Chassis Counterweight
1,1040300106,Washer 20,10.0,GB/T97.1-2002,ZS0812 Series Chassis Counterweight
2,00775602800001280,Steel CTW II \n(Only ZS0812DC/AC Series),1.0,2022.10 Revise,ZS0812 Series Chassis Counterweight
3,00775602800001310,Weld CTW II \n(Only ZS0812DC/AC Series),1.0,2022.10 Revise,ZS0812 Series Chassis Counterweight
4,00775602800001260,Steel CTW II \n(Only ZS0812HA Series),NaN,NaN,ZS0812 Series Chassis Counterweight
5,1040300038,Washer 20,5.0,GB/T93-1987,ZS0812 Series Chassis Counterweight
6,1040200097,Nut M20-8,5.0,GB/T6170-2000,ZS0812 Series Chassis Counterweight
7,00775602800001290,Steel CTW I,1.0,2022.10 Revise,ZS0812 Series Chassis Counterweight
8,00775602800001320,Weld CTW I,1.0,NaN,ZS0812 Series Chassis Counterweight
9,00775602800001280,Steel CTW II \n(Only ZS0812HD Series),1.0,2022.10 Revise,ZS0812 Series Chassis Counterweight
10,1040000202,Bolt M20×200-8.8,3.0,GB/T5783-2000,ZS0812 Series Chassis Counterweight

,Material No.,Item and Spec,Units,Remark,Section
0,1040000202,Bolt M20×200-8.8,2,GB/T5783-2000,ZS0808/ZS0608 Series Chassis Counterweight
1,1040300106,Washer 20,4,GB/T97.1-2002,ZS0808/ZS0608 Series Chassis Counterweight
2,00775402800001070,Steel CTW,1,NaN,ZS0808/ZS0608 Series Chassis Counterweight
3,1040300038,Washer 20,2,GB/T93-1987,ZS0808/ZS0608 Series Chassis Counterweight
4,1040200097,Nut M20-8,2,GB/T6170-2000,ZS0808/ZS0608 Series Chassis Counterweight

,Material No.,Item and Spec,Units,Remark,Section
0,1040102717,Screw M8×40,4,GB/T70.3-2000,ZS1414 Series Chassis Tray
1,00775602800001140,Nylon spacer,2,NaN,ZS1414 Series Chassis Tray
2,00775602800001200,Adjustable pad,4,NaN,ZS1414 Series Chassis Tray
3,00775302800001100,Tray pin,4,NaN,ZS1414 Series Chassis Tray
4,00775602800001010,Copper washer,4,NaN,ZS1414 Series Chassis Tray
5,1040300106,Washer 20-200HV,4,GB/T97.1-2002,ZS1414 Series Chassis Tray
6,1040300167,Retaining ring 20,4,GB/T894.1-1986,ZS1414 Series Chassis Tray
7,00775702800400000,Hydraulic Tray (ZS1414HD series),1,NaN,ZS1414 Series Chassis Tray
8,00775702820400000,Hydraulic Tray (ZS1414DC series),1,NaN,ZS1414 Series Chassis Tray
9,00775702870200000,Hydraulic Tray (ZS1414HA/AC \nseries),1,NaN,ZS1414 Series Chassis Tray
10,00775702800200000,Frame (ZS1414DC/AC/HA/HD \nZS1414HD-Li/HA-Li) ...,1,NaN,ZS1414 Series Chassis Tray
11,007757028D0200000,Frame (ZS1414DC/AC) \n(Outdoor Series),1,2022.10 Revise,ZS1414 Series Chassis Tray
12,00775702820200000,Frame (ZS1414DC-Li/AC-Li) \n(Indoor Series),1,NaN,ZS1414 Series Chassis Tray
13,007757028E0200000,Frame (ZS1414DC-Li/AC-Li) \n(Outdoor Series),1,2022.10 Revise,ZS1414 Series Chassis Tray
14,00775702810200000,Battery Tray \n(ZS1414HD/DC/HA/AC),1,NaN,ZS1414 Series Chassis Tray
15,00775702800600000,Battery Tray \n(ZS1414HD-Li/DC-Li/ \nZS1414HA-...,1,NaN,ZS1414 Series Chassis Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040102717,Screw M8×40,4,GB/T70.3-2000,ZS1212/ZS1012/ZS0812 Series Chassis Tray
1,00775602800001140,Nylon spacer,2,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
2,00775602800001200,Adjustable pad,4,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
3,00775302800001100,Tray pin,4,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
4,00775602800001010,Copper washer,4,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
5,1040300106,Washer 20-200HV,4,GB/T97.1-2002,ZS1212/ZS1012/ZS0812 Series Chassis Tray
6,1040300167,Retaining ring 20,4,GB/T894.1-1986,ZS1212/ZS1012/ZS0812 Series Chassis Tray
7,1040100127,Screw M6×12-8.8,10,GB/T70.1-2000,ZS1212/ZS1012/ZS0812 Series Chassis Tray
8,1040300062,Washer 6,10,GB/T93-1987,ZS1212/ZS1012/ZS0812 Series Chassis Tray
9,00775602800001120,Side bumper stripe \n(ZS1012/ZS1212/ZS0812 ser...,2,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
10,00775602800600000,Hydraulic Tray \n(ZS1212HD/ZS1012HD/ZS0812 \ns...,1,2022.10 Revise,ZS1212/ZS1012/ZS0812 Series Chassis Tray
11,00775602810400000,Hydraulic Tray \n(ZS1212DC/ZS1012DC/ \nZS0812D...,1,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
12,00775602860200000,Hydraulic Tray \n (ZS1212HA/AC、 \nZS1012HA/AC...,1,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray

,Material No.,Item and Spec,Units,Remark,Section
0,00775602800400000,Frame \n(ZS1212/ZS1012/ZS0812DC \nZS1212/ZS101...,1,2022.10 Revise,ZS1212/ZS1012/ZS0812 Series Chassis Tray
1,00775602880400000,Frame (ZS1212DC/AC) \n(Outdoor Series),1,2022.10 Revise,ZS1212/ZS1012/ZS0812 Series Chassis Tray
2,00775602830400000,Frame \n(ZS1212/ZS1012/ZS0812DC-Li \nZS1212/ZS...,1,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
3,007756028D0400000,Frame (ZS1212DC-Li/AC-Li) \n(Outdoor Series),1,2022.10 Revise,ZS1212/ZS1012/ZS0812 Series Chassis Tray
4,00775602801600000,Battery Tray \n(ZS1212HD/DC/HA/AC),1,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
5,00775502800400000,Battery Tray \n(ZS1012HD/DC/HA/AC \nZS0812 HD/...,1,NaN,ZS1212/ZS1012/ZS0812 Series Chassis Tray
6,00775602820200000,Battery Tray \n(ZS1212HD-Li/DC-Li/ \nZS1212H...,1,2022.10 Revise,ZS1212/ZS1012/ZS0812 Series Chassis Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040102717,Screw M8×40,4,GB/T70.3-2000,ZS0808/ZS0608 Series Chassis Tray
1,00775602800001140,Nylon spacer,2,NaN,ZS0808/ZS0608 Series Chassis Tray
2,00775602800001200,Adjustable pad,4,NaN,ZS0808/ZS0608 Series Chassis Tray
3,1040100127,Screw M6×12-8.8,10,GB/T70.1-2000,ZS0808/ZS0608 Series Chassis Tray
4,1040300051,Washer 6,10,GB/T97.1-2002,ZS0808/ZS0608 Series Chassis Tray
5,00775602800001120,Side bumper stripe,2,NaN,ZS0808/ZS0608 Series Chassis Tray
6,00775302800001100,Tray pin I,4,NaN,ZS0808/ZS0608 Series Chassis Tray
7,00775602800001010,Copper washer,4,NaN,ZS0808/ZS0608 Series Chassis Tray
8,1040300167,Retaining ring 20,4,GB/T894.1-1986,ZS0808/ZS0608 Series Chassis Tray
9,00775402800800000,Hydraulic Tray \n(ZS0808HD/ZS0608HD series),1,NaN,ZS0808/ZS0608 Series Chassis Tray
10,00775402810400000,Hydraulic Tray \n(ZS0808DC/ZS0608DC series),1,NaN,ZS0808/ZS0608 Series Chassis Tray
11,00775602860200000,Hydraulic Tray \n (ZS0808HA/AC series),1,NaN,ZS0808/ZS0608 Series Chassis Tray
12,00775502800200000,Battery Tray (ZS0808HD/DC/HA/AC \nZS0608HD/DC),1,NaN,ZS0808/ZS0608 Series Chassis Tray
13,00775402821000000,Battery Tray \n (ZS0808HD-Li/DC-Li/ \nZS0608H...,1,NaN,ZS0808/ZS0608 Series Chassis Tray
14,00775402800200000,Frame (Indoor Series),1,NaN,ZS0808/ZS0608 Series Chassis Tray
15,007754028S0200000,Frame (ZS0808DC/AC) \n(Outdoor Series),1,2022.10 Revise,ZS0808/ZS0608 Series Chassis Tray
16,00775402840200000,Frame \n(ZS0808DC-Li/AC-Li \nZS0608DC-Li) (Ind...,1,NaN,ZS0808/ZS0608 Series Chassis Tray
17,007754028R0200000,Frame (ZS0808DC-Li/AC-Li) \n(Outdoor Series),1,2022.10 Revise,ZS0808/ZS0608 Series Chassis Tray
18,1040300106,Washer 20,4,GB/T97.1-2002,ZS0808/ZS0608 Series Chassis Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040102356,Screw M8×25,4,GB/T70.3-2000,ZS0607 Series Chassis Tray
1,00775302800001040,Nylon spacer,2,NaN,ZS0607 Series Chassis Tray
2,00775602800001200,Adjustable pad,4,NaN,ZS0607 Series Chassis Tray
3,00775302800001100,Tray pin I,4,NaN,ZS0607 Series Chassis Tray
4,00775602800001010,Copper washer,4,NaN,ZS0607 Series Chassis Tray
5,1040300154,Retaining ring 25,4,GB/T894.1-1986,ZS0607 Series Chassis Tray
6,00775302800800000,Hydraulic Tray (ZS0607HD),1,NaN,ZS0607 Series Chassis Tray
7,00775302810200000,Hydraulic Tray (ZS0607DC),1,NaN,ZS0607 Series Chassis Tray
8,00775302880400000,Hydraulic Tray (ZS0607HA),1,NaN,ZS0607 Series Chassis Tray
9,00775302890800000,Hydraulic Tray \n (ZS0607AC/ACW),1,NaN,ZS0607 Series Chassis Tray
10,007753028B1200000,Hydraulic Tray (ZS0607DCS),1,2022.10 Revise,ZS0607 Series Chassis Tray
11,00775302830600000,Battery Tray \n(ZS0607HD/DC/HA/AC/ACW),1,NaN,ZS0607 Series Chassis Tray
12,00775302830400000,Battery Tray \n (ZS0607HD-Li/DC-Li/HA-Li/ \nZ...,1,NaN,ZS0607 Series Chassis Tray
13,007753028B2000000,Battery Tray (ZS0607DCS),1,2022.10 Revise,ZS0607 Series Chassis Tray
14,00775302800200000,Frame (ZS0607HD/HA series),1,NaN,ZS0607 Series Chassis Tray
15,00775302830200000,Frame (ZS0607DC-Li/AC-Li) \n(Indoor Series),1,NaN,ZS0607 Series Chassis Tray
16,007753028R0200000,Frame (ZS0607AC-Li) \n(Outdoor Series),1,2022.10 Revise,ZS0607 Series Chassis Tray
17,00775302811200000,Frame (ZS0607DC/AC) \n(Indoor Series),1,NaN,ZS0607 Series Chassis Tray
18,007753028Q0200000,Frame (ZS0607AC) \n(Outdoor Series),1,2022.10 Revise,ZS0607 Series Chassis Tray
19,007753028B2400000,Frame (ZS0607DCS),1,2022.10 Revise,ZS0607 Series Chassis Tray
20,00775302890600000,Frame (ZS0607ACW),1,NaN,ZS0607 Series Chassis Tray
21,007753028D0200000,Frame (ZS0607ACW-Li),1,NaN,ZS0607 Series Chassis Tray
22,1040300106,Washer,4,GB/T97.1-2002,ZS0607 Series Chassis Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040300062,Washer 6,8,GB/T93-1987,ZS0407 Series Chassis Tray
1,1040101212,Screw M6×20-8.8,8,GB/T818-2000,ZS0407 Series Chassis Tray
2,1039905229,Slide,2,NaN,ZS0407 Series Chassis Tray
3,1040100620,Screw M6×16-8.8,8,GB/T818-2000,ZS0407 Series Chassis Tray
4,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS0407 Series Chassis Tray
5,1040200506,Nut M6-8,8,GB/T889.1-2000,ZS0407 Series Chassis Tray
6,00775202800800000,Tray (ZS0407DC),1,NaN,ZS0407 Series Chassis Tray
7,00775202810400000,Tray (ZS0407DC-Li),1,NaN,ZS0407 Series Chassis Tray
8,00775202800200000,Frame (ZS0407DC) \n(Indoor Series),1,NaN,ZS0407 Series Chassis Tray
9,00775202870200000,Frame (ZS0407DC) \n(Outdoor Series),1,2022.10 Revise,ZS0407 Series Chassis Tray
10,00775202810200000,Frame (ZS0407DC-Li) \n(Indoor Series),1,NaN,ZS0407 Series Chassis Tray
11,00775202880200000,Frame (ZS0407DC-Li) \n(Outdoor Series),1,2022.10 Revise,ZS0407 Series Chassis Tray
12,1040300062,Washer 6,8,GB/T93-1987,ZS0407 Series Chassis Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1030800538,Tire,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
1,00775602801000000,Left steering wheel carrier,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
2,1010100889,Motor,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
3,1040200507,Nut M12-8,8,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
4,1040000225,Bolt M12×90,8,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
5,00775602801800000,Right steering wheel carrier,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
6,00775702801600000,Steering linkage \n (ZS1414HA/HD Series),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
7,00775602803400000,Steering linkage,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
8,1010201394,Steering cylinder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
9,1040500034,Pin B20×60,2,GB/T882-1986,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
10,1040500394,Split pin 5×40,2,GB/T91-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
11,1040300106,Washer 20,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
12,00775602800001050,Wearing ring,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
13,1054400312,Composite bush 57×63×38,4,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
14,1054400313,Composite bush 25×30×12.5,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
15,1054400314,Composite bush 25×30×15,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
16,1040301847,Washer 10,2,GB/T5287-1985,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
17,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
18,1040000116,Bolt M10×20-8.8,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
19,1040300054,Washer 12,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
20,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
21,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
22,00775602800001040,End cover,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
23,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
24,1990201348,Cover plate,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
25,1019901543,Twin tube clamp,3,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
26,1040100728,Screw M8×110-8.8,1,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...
27,1040500535,Split pin 4×80,2,GB/T91-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Front...

,Material No.,Item and Spec,Units,Remark,Section
0,1030800580,Tire,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
1,00775602810600000,Left steering wheel carrier,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
2,1020005637,Electric machinery \n(ZS1414/1212/1012/0812DC),2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
3,1020005532,Electric machinery \n(ZS1212/1012/0812AC),2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
4,1020005626,Electric machinery \n(ZS1414AC),2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
5,1040000970,Bolt 3/8－16UNC-30-8.8,12,GB/T5786-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
6,00775602810800000,Right steering wheel carrier,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
7,00775702801600000,Steering linkage \n(ZS1414DC/AC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
8,00775602803400000,Steering linkage,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
9,1010201394,Steering cylinder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
10,1040500034,Pin B20×60,2,GB/T882-1986,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
11,1040500394,Split pin 5×40,2,GB/T91-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
12,1040300106,Washer 20,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
13,00775602800001050,Wearing ring,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
14,1054400312,Composite bush 57×63×38,4,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
15,1054400313,Composite bush 25×30×12.5,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
16,1054400314,Composite bush 25×30×15,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
17,1040301847,Washer 10,2,GB/T5287-1985,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
18,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
19,1040000116,Bolt M10×20-8.8,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
20,1040300054,Washer 12,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
21,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
22,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
23,00775602800001040,End cover,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
24,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
25,1990201348,Cover plate,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
26,1019901543,Twin tube clamp,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
27,1990201778,Twin tube clamp,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
28,1040100501,Screw M8×100-8.8,1,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...
29,1040005784,Bolt M12×1.5×35-8.8,10,GB/T16674.2-2004,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Front-wheel ...

,Material No.,Item and Spec,Units,Remark,Section
0,1030800580,Tire,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
1,00775602810600000,Left steering wheel carrier,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
2,1020005637,Electric machinery \n(ZS1414/1212/ \n1012/0812...,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
3,1020005532,Electric machinery \n(ZS1212/1012/0812AC-Li),2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
4,1020005626,Electric machinery \n(ZS1414AC-Li),2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
5,1040000970,Bolt 3/8－16UNC-30-8.8,12,GB/T5786-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
6,00775602810800000,Right steering wheel carrier,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
7,00775702801600000,Steering linkage \n (ZS1414DC-Li/AC-Li),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
8,00775602803400000,Steering linkage,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
9,1010201394,Steering cylinder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
10,1040500034,Pin B20×60,2,GB/T882-1986,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
11,1040500394,Split pin 5×40,2,GB/T91-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
12,1040300106,Washer 20,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
13,00775602800001050,Wearing ring,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
14,1054400312,Composite bush 57×63×38,4,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
15,1054400313,Composite bush 25×30×12.5,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
16,1054400314,Composite bush 25×30×15,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
17,1040301847,Washer 10,2,GB/T5287-1985,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
18,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
19,1040000116,Bolt M10×20-8.8,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
20,1040300054,Washer 12,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
21,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
22,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...

,Material No.,Item and Spec,Units,Remark,Section
0,00775602800001040,End cover,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
1,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
2,1990201348,Cover plate,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
3,1019901543,Twin tube clamp,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
4,1990201778,Twin tube clamp,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
5,1040100501,Screw M8×100-8.8,1,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
6,1040005784,Bolt M12×1.5×35-8.8,10,GB/T16674.2-2004,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
7,00775302830001010,Brake cover,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
8,1020202270,Brake Module,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
9,00775302830001020,Resistance cover,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...
10,1020605470,Braking resistor,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC)-Li Front-whe...

,Material No.,Item and Spec,Units,Remark,Section
0,1030800538,Tire,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
1,00775402800400000,Left steering wheel carrier,1,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
2,1010100895,Motor,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
3,1040000225,Bolt M12×90,8,GB/T5783-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
4,1040200507,Nut M12-8,8,GB/T889.1-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
5,1040300526,Washer 12,10,GB/T97.1-2002,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
6,00775402800600000,Right steering wheel carrier,1,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
7,00775402802000000,Steering linkage,1,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
8,1010201406,Steering cylinder,1,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
9,1040500034,Pin B20×60,2,GB/T882-1986,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
10,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
11,1040300106,Washer 20,2,GB/T97.1-2002,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
12,00775602800001050,Wearing ring,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
13,1054400312,Composite bush 57×63×38,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
14,1054400313,Composite bush 25×30×12.5,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
15,1054400315,Composite bush 57×63×30,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
16,1054400314,Composite bush 25×30×15,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
17,1040301847,Washer 10,2,GB/T5287-1985,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
18,1040300067,Washer 10,2,GB/T93-1987,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
19,1040000116,Bolt M10×20-8.8,2,GB/T5783-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
20,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
21,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
22,00775602800001040,End cover,2,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
23,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
24,1990201348,Cover plate,1,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
25,1019901543,Twin tube clamp,3,NaN,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
26,1040100728,Screw M8×110-8.8,1,GB/T70.1-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...
27,1040500535,Split pin 4×80,2,GB/T91-2000,ZS0808/ZS0608HD(HA) Series Front-wheel Steerin...

,Material No.,Item and Spec,Units,Remark,Section
0,1030800580,Tire,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
1,00775402810600000,Left steering wheel carrier,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
2,1020005625,Electric machinery \n(ZS0808AC),2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
3,1020005637,Electric machinery \n(ZS0808/0608DC),2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
4,1040000970,Bolt 3/8-16UNC-30-8.8,12,GB/T5786-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
5,00775402810800000,Right steering wheel carrier,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
6,00775402802000000,Steering linkage,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
7,1010201406,Steering cylinder,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
8,1040500034,Pin B20×60,2,GB/T882-1986,ZS0808/ZS0608DC(AC) Front-wheel Steering System
9,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
10,1040300106,Washer 20,2,GB/T97.1-2002,ZS0808/ZS0608DC(AC) Front-wheel Steering System
11,00775602800001050,Wearing ring,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
12,1054400312,Composite bush 57×63×38,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
13,1054400313,Composite bush 25×30×12.5,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
14,1054400315,Composite bush 57×63×30,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
15,1054400314,Composite bush 25×30×15,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
16,1040301847,Washer 10,2,GB/T5287-1985,ZS0808/ZS0608DC(AC) Front-wheel Steering System
17,1040300067,Washer 10,2,GB/T93-1987,ZS0808/ZS0608DC(AC) Front-wheel Steering System
18,1040000116,Bolt M10×20-8.8,2,GB/T5783-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
19,1040300526,Washer 12,2,GB/T97.1-2002,ZS0808/ZS0608DC(AC) Front-wheel Steering System
20,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
21,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
22,00775602800001040,End cover,2,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
23,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
24,1990201348,Cover plate,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
25,1019901543,Twin tube clamp,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
26,1990201778,Twin tube clamp,1,NaN,ZS0808/ZS0608DC(AC) Front-wheel Steering System
27,1040100501,Screw M8×100-8.8,1,GB/T70.1-2000,ZS0808/ZS0608DC(AC) Front-wheel Steering System
28,1040005784,Bolt M12×1.5×35-8.8,10,GB/T16674.2-2004,ZS0808/ZS0608DC(AC) Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,1030800580,Tire,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
1,00775402810600000,Left steering wheel carrier,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
2,1020005625,Electric machinery \n(ZS0808AC-Li),2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
3,1020005637,Electric machinery \n(ZS0808/0608DC-Li),2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
4,1040000970,Bolt 3/8-16UNC-30-8.8,12,GB/T5786-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
5,00775402810800000,Right steering wheel carrier,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
6,00775402802000000,Steering linkage,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
7,1010201406,Steering cylinder,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
8,1040500034,Pin B20×60,2,GB/T882-1986,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
9,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
10,1040300106,Washer 20,2,GB/T97.1-2002,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
11,00775602800001050,Wearing ring,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
12,1054400312,Composite bush 57×63×38,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
13,1054400313,Composite bush 25×30×12.5,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
14,1054400315,Composite bush 57×63×30,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
15,1054400314,Composite bush 25×30×15,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
16,1040301847,Washer 10,2,GB/T5287-1985,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
17,1040300067,Washer 10,2,GB/T93-1987,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
18,1040000116,Bolt M10×20-8.8,2,GB/T5783-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
19,1040300526,Washer 12,2,GB/T97.1-2002,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
20,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...

,Material No.,Item and Spec,Units,Remark,Section
0,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
1,00775602800001040,End cover,2,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
2,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
3,1990201348,Cover plate,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
4,1019901543,Twin tube clamp,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
5,1990201778,Twin tube clamp,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
6,1040100501,Screw M8×100-8.8,1,GB/T70.1-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
7,1040005784,Bolt M12×1.5×35-8.8,10,GB/T16674.2-2004,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
8,1040300048,Washer 5-200HV,10,GB/T97.1-2002,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
9,1040300060,Washer 5,10,GB/T93-1987,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
10,1040100378,Screw M5×20-8.8,6,GB/T70.1-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
11,1020605470,Braking resistor,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
12,00775302830001020,Resistance cover,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
13,1020202270,Brake Module,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
14,00775302830001010,Brake cover,1,NaN,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...
15,1040102341,Screw M5×12-8.8,4,GB/T70.1-2000,ZS0808/ZS0608DC(AC)-Li Front-wheel Steering Sy...

,Material No.,Item and Spec,Units,Remark,Section
0,1030800592,Tire,2,NaN,ZS0607HD(HA) Series Front-wheel Steering System
1,00775302800400000,Left steering wheel carrier,1,NaN,ZS0607HD(HA) Series Front-wheel Steering System
2,1010100895,Motor,2,NaN,ZS0607HD(HA) Series Front-wheel Steering System
3,1040000225,Bolt M12×90,8,GB/T5783-2000,ZS0607HD(HA) Series Front-wheel Steering System
4,1040200507,Nut M12-8,8,GB/T889.1-2000,ZS0607HD(HA) Series Front-wheel Steering System
5,00775302800600000,Right steering wheel carrier,1,NaN,ZS0607HD(HA) Series Front-wheel Steering System
6,00775302800001060,Steering linkage,1,NaN,ZS0607HD(HA) Series Front-wheel Steering System
7,1010201475,Steering cylinder,1,NaN,ZS0607HD(HA) Series Front-wheel Steering System
8,1040500038,Pin B20×50,2,GB/T882-1986,ZS0607HD(HA) Series Front-wheel Steering System
9,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0607HD(HA) Series Front-wheel Steering System
10,00775302800001050,Copper washer I,4,NaN,ZS0607HD(HA) Series Front-wheel Steering System
11,00775302800001030,Wearing ring,2,NaN,ZS0607HD(HA) Series Front-wheel Steering System
12,1054400310,Composite bush,4,NaN,ZS0607HD(HA) Series Front-wheel Steering System
13,1054400339,Composite bush,2,NaN,ZS0607HD(HA) Series Front-wheel Steering System
14,1040300081,Washer12,2,GB/T96.1-2002,ZS0607HD(HA) Series Front-wheel Steering System
15,1040200507,Nut M12,2,GB/T889.1-2000,ZS0607HD(HA) Series Front-wheel Steering System
16,1040300054,Washer 12,2,GB/T93-1987,ZS0607HD(HA) Series Front-wheel Steering System
17,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS0607HD(HA) Series Front-wheel Steering System
18,1040100058,Screw M6×16-8.8,2,GB/T70.1-2000,ZS0607HD(HA) Series Front-wheel Steering System
19,00775302800001020,End cover,2,NaN,ZS0607HD(HA) Series Front-wheel Steering System
20,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS0607HD(HA) Series Front-wheel Steering System
21,1990201348,Cover plate,1,NaN,ZS0607HD(HA) Series Front-wheel Steering System
22,1019901543,Twin tube clamp,3,NaN,ZS0607HD(HA) Series Front-wheel Steering System
23,1040100728,Screw M8×110-8.8,1,GB/T70.1-2000,ZS0607HD(HA) Series Front-wheel Steering System
24,1040500535,Pin 4×80,2,GB/T91-2000,ZS0607HD(HA) Series Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,1030800656,Tire,2.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
1,1030801028,Tire (ZS0607DCS),2.0,2022.10 Revise,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
2,00775302810400000,Left steering wheel carrier,1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
3,00775302890400000,Left steering wheel carrier \n(ZS0607ACW),1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
4,00775302870400000,Left steering wheel carrier \n(ZS0607AC),1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
5,007753028B1400000,Left steering wheel carrier \n(ZS0607DCS),NaN,2022.10 Revise,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
6,1020005638,Electric machinery (ZS0607DC),2.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
7,1020005624,Electric machinery \n(ZS0607AC/ACW),2.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
8,007753028B1600000,Front wheel bearing block \n(ZS0607DCS),2.0,2022.10 Revise,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
9,1040000970,Bolt 3/8-16UNC-30-8.8,12.0,GB/T5786-2000,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
10,1040000574,Bolt M10×30-10.9 (ZS0607DCS),12.0,2022.10 Revise,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
11,00775302810400000,Right steering wheel carrier \n(ZS0607DC),1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
12,00775302890200000,Right steering wheel carrier \n(ZS0607ACW),1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
13,00775302870600000,Right steering wheel carrier \n(ZS0607AC),1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
14,007753028B2200000,Right steering wheel carrier \n(ZS0607DCS),1.0,2022.10 Revise,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
15,00775302800001060,Steering linkage,1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
16,1010201475,Steering cylinder,1.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
17,1040500038,Pin B20×50,2.0,GB/T882-1986,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
18,1040500394,Split pin 5×40,2.0,GB/T91-2000,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
19,00775302800001050,Copper washer I,4.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
20,00775302800001030,Wearing ring,2.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
21,1054400310,Composite bush,4.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
22,1054400339,Composite bush,2.0,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,1040300081,Washer 12,2,GB/T96.1-2002,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
1,1040200507,Bolt M12,2,GB/T889.1-2000,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
2,1040300054,Washer 12,2,GB/T93-1987,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
3,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
4,1040100058,Screw M6×16-8.8,2,GB/T70.1-2000,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
5,00775302800001020,End cover,2,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
6,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
7,1990201348,Cover plate,1,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
8,1019901543,Twin tube clamp,1,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
9,1990201778,Twin tube clamp,1,NaN,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
10,1040100501,Screw M8×100-8.8,1,GB/T70.1-2008,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System
11,1040005789,Bolt M12×1.5×30-8.8,10,GB/T16674.2-2004,ZS0607DC(AC/ACW/DCS) Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,1030800656,Tire,2,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
1,00775302810400000,Left steering wheel carrier,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
2,00775302890400000,Left steering wheel carrier \n(ZS0607ACW-Li),1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
3,00775302870400000,Left steering wheel carrier \n(ZS0607AC-Li),1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
4,1020005638,Electric machinery \n (ZS0607DC-Li),2,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
5,1020005624,Electric machinery \n(ZS0607AC/ACW-Li),2,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
6,1040000970,Bolt 3/8-16UNC-30-8.8,12,GB/T5786-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
7,00775302810400000,Right steering wheel carrier \n(ZS0607DC-Li),1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
8,00775302890200000,Right steering wheel carrier \n(ZS0607ACW-Li),1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
9,00775302870600000,Right steering wheel carrier \n(ZS0607AC-Li),1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
10,00775302800001060,Steering linkage,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
11,1010201475,Steering cylinder,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
12,1040500038,Pin B20×50,2,GB/T882-1986,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
13,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
14,00775302800001050,Copper washer I,4,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
15,00775302800001030,Wearing ring,2,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
16,1054400310,Composite bush,4,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
17,1054400339,Composite bush,2,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
18,1040300081,washer 12,2,GB/T96.1-2002,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
19,1040200507,Nut M12,2,GB/T889.1-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
20,1040300054,washer 12,2,GB/T93-1987,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
21,1040100157,Screw M12×20-8.8,2,GB/T70.1-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
22,1040100058,Screw M6×16-8.8,2,GB/T70.1-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
23,00775302800001020,End cover,2,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
24,1040200503,Nut M8-8,1,GB/T889.1-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,1990201348,Cover plate,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
1,1019901543,Twin tube clamp,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
2,1990201778,Twin tube clamp,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
3,1040100501,Screw M8×100-8.8,1,GB/T70.1-2008,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
4,1040005789,Bolt M12×1.5×30-8.8,10,GB/T16674.2-2004,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
5,1040300048,Washer 5-200HV,10,GB/T97.1-2002,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
6,1040300060,Washer 5,10,GB/T93-1987,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
7,1040100378,Screw M5×20-8.8,6,GB/T70.1-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
8,1020605470,Braking resistor,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
9,00775302830001020,Resistance cover,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
10,1020202270,Brake Module,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
11,00775302830001010,Brake cover,1,NaN,ZS0607DC(AC/ACW)-Li Front-wheel Steering System
12,1040102341,Screw M5×12-8.8,4,GB/T70.1-2000,ZS0607DC(AC/ACW)-Li Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,00775302800001020,End cover,2,NaN,ZS0407DC Front-wheel Steering System
1,1054400310,Composite bush,4,NaN,ZS0407DC Front-wheel Steering System
2,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0407DC Front-wheel Steering System
3,1040300054,Washer 12,2,GB/T93-1987,ZS0407DC Front-wheel Steering System
4,1040100157,Screw M12×20-8.8,1,GB/T70.1-2000,ZS0407DC Front-wheel Steering System
5,00775302800001030,Wearing ring,2,NaN,ZS0407DC Front-wheel Steering System
6,00775202802400000,Right steering wheel carrier,1,NaN,ZS0407DC Front-wheel Steering System
7,1030800683,Tire,4,NaN,ZS0407DC Front-wheel Steering System
8,1040300247,Washer 16-200HV,4,GB/T96.1-2002,ZS0407DC Front-wheel Steering System
9,1040200742,Nut M16×1.5-10,4,GB/T6183.2-2000,ZS0407DC Front-wheel Steering System
10,00775202800001080,Cover,4,NaN,ZS0407DC Front-wheel Steering System
11,1040300044,Washer 4,12,GB/T93-1987,ZS0407DC Front-wheel Steering System
12,1040100618,Nut M4×16-8.8,12,GB/T818-2000,ZS0407DC Front-wheel Steering System
13,1040500038,Pin B20×50,2,GB/T882-1986,ZS0407DC Front-wheel Steering System
14,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0407DC Front-wheel Steering System
15,1010201475,Steering cylinder,1,NaN,ZS0407DC Front-wheel Steering System
16,00775302800001050,Copper washer I,4,NaN,ZS0407DC Front-wheel Steering System
17,1040200507,Nut M12-8,2,GB/T889.1-2000,ZS0407DC Front-wheel Steering System
18,1040300081,Washer 12-140HV,2,GB/T96.1-2002,ZS0407DC Front-wheel Steering System
19,00775202800001030,Steering Linkage,1,NaN,ZS0407DC Front-wheel Steering System
20,1054400339,Composite bush,2,NaN,ZS0407DC Front-wheel Steering System
21,00775202802600000,Front-wheel bearing \nchock assembly,2,NaN,ZS0407DC Front-wheel Steering System
22,1040300067,Washer 10,12,GB/T93-1987,ZS0407DC Front-wheel Steering System
23,1040001680,Bolt M10×30-8.8,12,GB/T5783-2000,ZS0407DC Front-wheel Steering System
24,00775202802200000,Left steering wheel carrier,1,NaN,ZS0407DC Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,00775302800001020,End cover,2,NaN,ZS0407DC-Li Front-wheel Steering System
1,1054400310,Composite bush,4,NaN,ZS0407DC-Li Front-wheel Steering System
2,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0407DC-Li Front-wheel Steering System
3,1040300054,Washer 12,2,GB/T93-1987,ZS0407DC-Li Front-wheel Steering System
4,1040100157,Screw M12×20-8.8,1,GB/T70.1-2000,ZS0407DC-Li Front-wheel Steering System
5,00775302800001030,Wearing ring,2,NaN,ZS0407DC-Li Front-wheel Steering System
6,00775202802400000,Right steering wheel \ncarrier,1,NaN,ZS0407DC-Li Front-wheel Steering System
7,1030800683,Tire,4,NaN,ZS0407DC-Li Front-wheel Steering System
8,1040300247,Washer 16-200HV,4,GB/T96.1-2002,ZS0407DC-Li Front-wheel Steering System
9,1040200742,Nut M16×1.5-10,4,GB/T6183.2-2000,ZS0407DC-Li Front-wheel Steering System
10,00775202800001080,Cover,4,NaN,ZS0407DC-Li Front-wheel Steering System
11,1040300044,Washer 4,12,GB/T93-1987,ZS0407DC-Li Front-wheel Steering System
12,1040100618,Nut M4×16-8.8,12,GB/T818-2000,ZS0407DC-Li Front-wheel Steering System
13,1040500038,Pin B20×50,2,GB/T882-1986,ZS0407DC-Li Front-wheel Steering System
14,1040500394,Split pin 5×40,2,GB/T91-2000,ZS0407DC-Li Front-wheel Steering System
15,1010201475,Steering cylinder,1,NaN,ZS0407DC-Li Front-wheel Steering System
16,00775302800001050,Copper washer I,4,NaN,ZS0407DC-Li Front-wheel Steering System
17,1040200507,Nut M12-8,2,GB/T889.1-2000,ZS0407DC-Li Front-wheel Steering System
18,1040300081,Washer 12-140HV,2,GB/T96.1-2002,ZS0407DC-Li Front-wheel Steering System
19,00775202800001030,Steering Linkage,1,NaN,ZS0407DC-Li Front-wheel Steering System
20,1054400339,Composite bush,2,NaN,ZS0407DC-Li Front-wheel Steering System
21,00775202802600000,Front-wheel bearing \nchock assembly,2,NaN,ZS0407DC-Li Front-wheel Steering System
22,1040300067,Washer 10,12,GB/T93-1987,ZS0407DC-Li Front-wheel Steering System
23,1040001680,Bolt M10×30-8.8,12,GB/T5783-2000,ZS0407DC-Li Front-wheel Steering System
24,00775202802200000,Left steering wheel carrier,1,NaN,ZS0407DC-Li Front-wheel Steering System
25,00775302830001010,Brake cover,1,NaN,ZS0407DC-Li Front-wheel Steering System
26,1020202270,Brake Module,1,NaN,ZS0407DC-Li Front-wheel Steering System
27,00775302830001020,Resistance cover,1,NaN,ZS0407DC-Li Front-wheel Steering System
28,1020605470,Braking resistor,1,NaN,ZS0407DC-Li Front-wheel Steering System

,Material No.,Item and Spec,Units,Remark,Section
0,1030800538,Tire,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
1,1040500535,Split pin 4×80,2,GB/T91-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
2,1040000126,Bolt M12×100-8.8,8,GB/T5782-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
3,1040300526,Washer 12,14,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
4,1040200507,Nut M12-8,14,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
5,1019901335,Brake,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
6,1040004201,Bolt M12×40-8.8,6,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
7,00775602803200000,Ladder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
8,00775402850200000,Ladder (ZS0812HA/HD),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
9,00775602801601010,Coil III,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
10,1010305937,Manual pump,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
11,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
12,1040300061,Washer 10,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
13,1040000970,Screw 3/8-16UNC-30-8.8,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
14,1100700162,T handle (Red),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
15,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
16,1040300051,Washer 6,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
17,00775605200401030,Lower stay wire bracket,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
18,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
19,00775602800001180,Coil II,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
20,00775602801601040,Protecting bush II,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
21,00775302802400000,Box holder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder
22,1020605443,Residual current circuit breaker,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA) Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,1030800538,Tire,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
1,1040500535,Split pin 4×80,2,GB/T91-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
2,1040000126,Bolt M12×100-8.8,8,GB/T5782-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
3,1040300526,Washer 12,14,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
4,1040200507,Nut M12-8,14,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
5,1059900526,Brake,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
6,1040004201,Bolt M12×40-8.8,6,GB/T801-1998,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
7,00775602803200000,Ladder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
8,00775402850200000,Ladder (ZS0812DC/AC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
9,00775602801601010,Coil III,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
10,1100700162,T handle (Red),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
11,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
12,1040300051,Washer 6,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
13,00775605200401030,Lower stay wire bracket,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
14,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
15,00775602800001180,Coil II,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
16,00775602801601040,Protecting bush II,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
17,00775302802400000,Box holder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder
18,1020605443,Residual current circuit breaker,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC(AC) Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,1030800538,Tire,2,NaN,ZS0808/ZS0608HD(HA) Series Ladder
1,1040500535,Split pin 4×80,2,GB/T91-2000,ZS0808/ZS0608HD(HA) Series Ladder
2,1040000225,Bolt M12×90-8.8,8,GB/T5783-2000,ZS0808/ZS0608HD(HA) Series Ladder
3,1040300526,Washer 12,14,GB/T97.1-2002,ZS0808/ZS0608HD(HA) Series Ladder
4,1040200507,Nut M12-8,14,GB/T889.1-2000,ZS0808/ZS0608HD(HA) Series Ladder
5,1019901335,Brake,2,NaN,ZS0808/ZS0608HD(HA) Series Ladder
6,1040004201,Bolt M12×40-8.8,6,GB/T801-1998,ZS0808/ZS0608HD(HA) Series Ladder
7,00775402801800000,Ladder,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
8,00775602801601010,Coil III,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
9,1010305937,Manuel pump,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
10,1040300067,Washer 10,2,GB/T93-1987,ZS0808/ZS0608HD(HA) Series Ladder
11,1040300061,Washer 10,2,GB/T97.1-2002,ZS0808/ZS0608HD(HA) Series Ladder
12,1040000970,Bolt 3/8-16UNC-30-8.8,2,NaN,ZS0808/ZS0608HD(HA) Series Ladder
13,1100700162,T handle (Red),1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
14,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0808/ZS0608HD(HA) Series Ladder
15,1040300051,Washer 6,2,GB/T97.1-2002,ZS0808/ZS0608HD(HA) Series Ladder
16,00775605200401030,Lower stay wire bracket,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
17,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0808/ZS0608HD(HA) Series Ladder
18,00775602800001180,Coil II,2,NaN,ZS0808/ZS0608HD(HA) Series Ladder
19,00775602801601040,Protecting bush II,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
20,00775302802400000,Box holder,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder
21,1020605443,Residual current circuit breaker,1,NaN,ZS0808/ZS0608HD(HA) Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,1030800538,Tire,2,NaN,ZS0808/ZS0608DC(AC) Series Ladder
1,1040500535,Split pin 4×80,2,GB/T91-2000,ZS0808/ZS0608DC(AC) Series Ladder
2,1040000225,Bolt M12×90-8.8,8,GB/T5783-2000,ZS0808/ZS0608DC(AC) Series Ladder
3,1040300526,Washer 12,14,GB/T97.1-2002,ZS0808/ZS0608DC(AC) Series Ladder
4,1040200507,Nut M12-8,14,GB/T889.1-2000,ZS0808/ZS0608DC(AC) Series Ladder
5,1059900526,Brake,2,NaN,ZS0808/ZS0608DC(AC) Series Ladder
6,1040004201,Bolt M12×40-8.8,6,GB/T801-1998,ZS0808/ZS0608DC(AC) Series Ladder
7,00775402801800000,Ladder,1,NaN,ZS0808/ZS0608DC(AC) Series Ladder
8,00775602801601010,Coil III,1,NaN,ZS0808/ZS0608DC(AC) Series Ladder
9,1100700162,T handle (Red),1,NaN,ZS0808/ZS0608DC(AC) Series Ladder
10,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(AC) Series Ladder
11,1040300051,Washer 6,2,GB/T97.1-2002,ZS0808/ZS0608DC(AC) Series Ladder
12,00775605200401030,Lower stay wire bracket,1,NaN,ZS0808/ZS0608DC(AC) Series Ladder
13,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0808/ZS0608DC(AC) Series Ladder
14,00775602800001180,Coil II,2,NaN,ZS0808/ZS0608DC(AC) Series Ladder
15,00775602801601040,Protecting bush II,1,NaN,ZS0808/ZS0608DC(AC) Series Ladder
16,00775302802400000,Box holder,1,NaN,ZS0808/ZS0608DC(AC) Series Ladder
17,1020605443,Residual current circuit breaker,1,NaN,ZS0808/ZS0608DC(AC) Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,1030800592,Tire,2,NaN,ZS0607HD/HA Series Ladder
1,1040500535,Split pin 4×80,2,GB/T91-2000,ZS0607HD/HA Series Ladder
2,1040000225,Bolt M12×90-8.8,8,GB/T5783-2000,ZS0607HD/HA Series Ladder
3,1040300526,Washer 12,12,GB/T97.1-2002,ZS0607HD/HA Series Ladder
4,1040200507,Nut M12-8,12,GB/T889.1-2000,ZS0607HD/HA Series Ladder
5,1019901335,Brake,2,NaN,ZS0607HD/HA Series Ladder
6,1029907622,Vehicle-mounted battery \ncharger (ZS0607HD/HA),1,NaN,ZS0607HD/HA Series Ladder
7,1029907624,Vehicle-mounted battery \ncharger (ZS0607HD-Li...,1,NaN,ZS0607HD/HA Series Ladder
8,00775306320410000,Battery charger Tray,1,NaN,ZS0607HD/HA Series Ladder
9,00775302802200000,Ladder,1,NaN,ZS0607HD/HA Series Ladder
10,1040004201,Bolt M12×40-8.8,4,GB/T801-1998,ZS0607HD/HA Series Ladder
11,00775602801601010,Coil III,1,NaN,ZS0607HD/HA Series Ladder
12,1010305937,Manual pump,1,NaN,ZS0607HD/HA Series Ladder
13,1040300067,Washer 10,2,GB/T93-1987,ZS0607HD/HA Series Ladder
14,1040300061,Washer 10,2,GB/T97.1-2002,ZS0607HD/HA Series Ladder
15,1040000970,Bolt 3/8－16UNC-30-8.8,2,NaN,ZS0607HD/HA Series Ladder
16,1100700162,T handle (Red),1,NaN,ZS0607HD/HA Series Ladder
17,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0607HD/HA Series Ladder
18,1040300051,Washer 6,6,GB/T97.1-2002,ZS0607HD/HA Series Ladder
19,00775605200401030,Lower stay wire bracket,1,NaN,ZS0607HD/HA Series Ladder
20,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0607HD/HA Series Ladder
21,00775302800001070,Protective cover,1,NaN,ZS0607HD/HA Series Ladder
22,1040100127,Screw M6×12-8.8,4,GB/T70.1-2000,ZS0607HD/HA Series Ladder
23,00775602800001180,Coil II,2,NaN,ZS0607HD/HA Series Ladder
24,00775602801601040,Protecting bush II,1,NaN,ZS0607HD/HA Series Ladder
25,00775302802400000,Box holder,1,NaN,ZS0607HD/HA Series Ladder
26,1020605443,Residual current circuit breaker,1,NaN,ZS0607HD/HA Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,1030800655,Tire,2,NaN,ZS0607DC/AC Series Ladder
1,1040500535,Split pin 4×80,2,GB/T91-2000,ZS0607DC/AC Series Ladder
2,1040000225,Bolt M12×90-8.8,8,GB/T5783-2000,ZS0607DC/AC Series Ladder
3,1040300526,Washer 12,12,GB/T97.1-2002,ZS0607DC/AC Series Ladder
4,1040200507,Nut M12-8,12,GB/T889.1-2000,ZS0607DC/AC Series Ladder
5,1059900526,Brake,2,NaN,ZS0607DC/AC Series Ladder
6,1029907622,Vehicle-mounted battery \ncharger (ZS0607DC/AC),1,NaN,ZS0607DC/AC Series Ladder
7,1029907624,Vehicle-mounted battery \ncharger (ZS0607DC-Li...,1,NaN,ZS0607DC/AC Series Ladder
8,00775306320410000,Battery charger Tray,1,NaN,ZS0607DC/AC Series Ladder
9,00775302802200000,Ladder,1,NaN,ZS0607DC/AC Series Ladder
10,1040004201,Bolt M12×40-8.8,4,GB/T801-1998,ZS0607DC/AC Series Ladder
11,00775602801601010,Coil III,1,NaN,ZS0607DC/AC Series Ladder
12,1100700162,T handle (Red),1,NaN,ZS0607DC/AC Series Ladder
13,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0607DC/AC Series Ladder
14,1040300051,Washer 6,6,GB/T97.1-2002,ZS0607DC/AC Series Ladder
15,00775605200401030,Lower stay wire bracket,1,NaN,ZS0607DC/AC Series Ladder
16,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0607DC/AC Series Ladder
17,00775302800001070,Protective cover,1,NaN,ZS0607DC/AC Series Ladder
18,1040100127,Screw M6×12-8.8,4,GB/T70.1-2000,ZS0607DC/AC Series Ladder
19,00775602800001180,Coil II,2,NaN,ZS0607DC/AC Series Ladder
20,00775602801601040,Protecting bush II,1,NaN,ZS0607DC/AC Series Ladder
21,00775302802400000,Box holder,1,NaN,ZS0607DC/AC Series Ladder
22,1020605443,Residual current circuit breaker,1,NaN,ZS0607DC/AC Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,00775302802200000,Battery charger Tray,1,NaN,ZS0607DCS Series Ladder
1,1040202857,Nut M12-10,4,GB/T889.1-2000,ZS0607DCS Series Ladder
2,1040302490,Washer 12-200HV,4,GB/T97.1-2002,ZS0607DCS Series Ladder
3,1040004201,Bolt M12×40-8.8,4,GB/T801-1998,ZS0607DCS Series Ladder
4,1020005738,Vehicle-mounted battery \ncharger,1,NaN,ZS0607DCS Series Ladder
5,007753028B0001010,Safety cover,1,NaN,ZS0607DCS Series Ladder
6,1040300771,Washer 6-200HV,4,GB/T97.1-2002,ZS0607DCS Series Ladder
7,1040301610,Washer 6,4,GB/T93-1987,ZS0607DCS Series Ladder
8,1040104082,Screw M6×12-8.8,4,GB/T70.1-2000,ZS0607DCS Series Ladder
9,1020099136,Electric machinery,1,NaN,ZS0607DCS Series Ladder
10,007753028B1800000,Motor seat,2,NaN,ZS0607DCS Series Ladder
11,1040301503,Washer 12,8,GB/T93-1987,ZS0607DCS Series Ladder
12,1040004644,Bolt M12×45-10.9,8,GB/T5783-2000,ZS0607DCS Series Ladder
13,1020099135,Electric machinery,1,NaN,ZS0607DCS Series Ladder
14,1030801028,Tire,2,NaN,ZS0607DCS Series Ladder
15,007753028B1601050,Hexagon slotted nut,2,NaN,ZS0607DCS Series Ladder
16,1040500535,Bin 4×80,2,GB/T91-2000,ZS0607DCS Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,1030800655,Tire,2.0,NaN,ZS0607ACW Series Ladder
1,1040500535,Split pin 4×80,2.0,GB/T91-2000,ZS0607ACW Series Ladder
2,1040000807,Bolt M12×120-8.8,8.0,GB/T5782-2000,ZS0607ACW Series Ladder
3,1040300526,Washer 12,12.0,GB/T97.1-2002,ZS0607ACW Series Ladder
4,1040200507,Nut M12-8,12.0,GB/T889.1-2000,ZS0607ACW Series Ladder
5,1059900526,Brake,2.0,NaN,ZS0607ACW Series Ladder
6,00775302890001090,Counterweight,1.0,NaN,ZS0607ACW Series Ladder
7,00775302890001080,Battery charger Tray,NaN,NaN,ZS0607ACW Series Ladder
8,00775302891000000,Ladder,1.0,NaN,ZS0607ACW Series Ladder
9,1040001680,Bolt M10×30-8.8,4.0,GB/T5783-2016,ZS0607ACW Series Ladder
10,00775602801601010,Coil III,1.0,NaN,ZS0607ACW Series Ladder
11,1100700162,T handle (Red),1.0,NaN,ZS0607ACW Series Ladder
12,1040100055,Screw M6×20-8.8,2.0,GB/T70.1-2000,ZS0607ACW Series Ladder
13,1040300051,Washer 6,2.0,GB/T97.1-2002,ZS0607ACW Series Ladder
14,00775605200401030,Lower stay wire bracket,1.0,NaN,ZS0607ACW Series Ladder
15,1040200506,Nut M6-8,2.0,GB/T889.1-2000,ZS0607ACW Series Ladder
16,00775302890001010,Protective cover,1.0,NaN,ZS0607ACW Series Ladder
17,1040100127,Screw M6×12-8.8,4.0,GB/T70.1-2000,ZS0607ACW Series Ladder
18,00775602800001180,Coil II,2.0,NaN,ZS0607ACW Series Ladder
19,00775602801601040,Protecting bush II,1.0,NaN,ZS0607ACW Series Ladder
20,1040000288,Bolt M8×25-8.8,4.0,GB/T5783-2000,ZS0607ACW Series Ladder
21,1040300063,Washer 8,4.0,GB/T93-1987,ZS0607ACW Series Ladder
22,1040300094,Washer 8-140HV,4.0,GB/T96.1-2002,ZS0607ACW Series Ladder
23,00775302890001120,Ladder mounting plate,2.0,NaN,ZS0607ACW Series Ladder
24,1040100105,Screw M6×25-8.8,8.0,GB/T70.1-2000,ZS0607ACW Series Ladder
25,1040300062,Washer 6,8.0,GB/T93-1987,ZS0607ACW Series Ladder
26,1040300093,Washer 6-200HV,12.0,GB/T96.1-2002,ZS0607ACW Series Ladder
27,00775302890001070,Counterweight pressing plate,1.0,NaN,ZS0607ACW Series Ladder
28,1040100237,Screw M6×30-8.8,2.0,GB/T70.1-2000,ZS0607ACW Series Ladder
29,1020999046,Vehicle-mounted battery \ncharger,1.0,NaN,ZS0607ACW Series Ladder
30,00775302890001110,Waterproof cover plate,1.0,NaN,ZS0607ACW Series Ladder
31,1020605443,Residual current circuit breaker,1.0,NaN,ZS0607ACW Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,00775202803000000,Ladder,1,NaN,ZS0407DC Series Ladder
1,00775202800001150,Sealing plate I,1,NaN,ZS0407DC Series Ladder
2,1040000108,Bolt M12×30-8.8,4,GB/T5783-2000,ZS0407DC Series Ladder
3,1040300054,Washer12,4,GB/T93-1987,ZS0407DC Series Ladder
4,1040300526,Washer12,4,GB/T97.1-2002,ZS0407DC Series Ladder
5,1040100127,Screw M6×12-8.8,5,GB/T70.1-2000,ZS0407DC Series Ladder
6,1040300062,Washer 6,5,GB/T93-1987,ZS0407DC Series Ladder
7,1040300051,Washer 6,5,GB/T97.1-2002,ZS0407DC Series Ladder
8,1020099123,Left motor,1,Containing hexagon \nsocket bolt 3/8”-\n24UNF×...,ZS0407DC Series Ladder
9,1040300061,Washer 10-200HV,16,GB/T97.1-2002,ZS0407DC Series Ladder
10,1040300067,Washer 10,16,GB/T93-1987,ZS0407DC Series Ladder
11,1040002435,Bolt M10×35-8.8,8,GB/T5783-2000,ZS0407DC Series Ladder
12,00775202801800000,Motor seat,2,NaN,ZS0407DC Series Ladder
13,1020099122,Right motor,1,Containing hexagon \nsocket bolt 3/8”-\n24UNF×...,ZS0407DC Series Ladder
14,1030800538,Tire,2,NaN,ZS0407DC Series Ladder
15,1040300247,Washer 16-200HV,2,GB/T96.1-2002,ZS0407DC Series Ladder
16,1040200742,Nut M16×1.5-10,2,GB/T6183.2-2000,ZS0407DC Series Ladder
17,00775202800001080,Cover,2,NaN,ZS0407DC Series Ladder
18,1040300044,Washer 4,6,GB/T93-1987,ZS0407DC Series Ladder
19,1040100618,Screw M4×16-8.8,6,GB/T818-2000,ZS0407DC Series Ladder
20,00775202800001130,Box holder,1,NaN,ZS0407DC Series Ladder
21,1020605443,Residual current circuit breaker,1,NaN,ZS0407DC Series Ladder

,Material No.,Item and Spec,Units,Remark,Section
0,00775702800800000,Left pothole plate.,1,NaN,ZS1414 Series Pothole Guard
1,1040500054,Split pin 4×40,8,GB/T91-2000,ZS1414 Series Pothole Guard
2,1040300052,Washer 16,12,GB/T97.1-2002,ZS1414 Series Pothole Guard
3,1040501520,Pin B16×50,6,GB/T882-2000,ZS1414 Series Pothole Guard
4,1040500111,Pin B16×90,2,GB/T882-1986,ZS1414 Series Pothole Guard
5,00775602800001130,Crank gasket,2,NaN,ZS1414 Series Pothole Guard
6,1040300066,Washer 8-200HV,4,GB/T97.1-2002,ZS1414 Series Pothole Guard
7,1040300063,Washer 8,4,GB/T93-1987,ZS1414 Series Pothole Guard
8,1040201078,Nut M8,2,GB/T6170-2000,ZS1414 Series Pothole Guard
9,00775702800001020,Crank linkage,2,NaN,ZS1414 Series Pothole Guard
10,00775602801400000,Crank,2,NaN,ZS1414 Series Pothole Guard
11,1040500383,Pin B8×50,2,GB/T882-1986,ZS1414 Series Pothole Guard
12,1040500212,Split pin 3.2×20,2,GB/T91-2000,ZS1414 Series Pothole Guard
13,00775602800001060,Crank trolley,2,NaN,ZS1414 Series Pothole Guard
14,00775602800001070,Crank Pin,2,NaN,ZS1414 Series Pothole Guard
15,1040300094,Washer 8-140HV,2,GB/T96.1-2002,ZS1414 Series Pothole Guard
16,1110100353,Gas spring,2,NaN,ZS1414 Series Pothole Guard
17,1040000288,Bolt M8×25,10,GB/T5783-2000,ZS1414 Series Pothole Guard
18,00775702801400000,Guide mechanism,2,NaN,ZS1414 Series Pothole Guard
19,1040200503,Nut M8-8,10,GB/T889.1-2000,ZS1414 Series Pothole Guard
20,00775602803000000,Tray lock seat I,1,NaN,ZS1414 Series Pothole Guard
21,00775702801000000,Right pothole plate,1,NaN,ZS1414 Series Pothole Guard
22,00775602802800000,Tray lock seat II,1,NaN,ZS1414 Series Pothole Guard
23,1020705980,Conduction band,2,NaN,ZS1414 Series Pothole Guard
24,1040200100,Nut M4-8,4,GB/T6170-2000,ZS1414 Series Pothole Guard
25,1040300044,Washer 4,4,GB/T93-1987,ZS1414 Series Pothole Guard
26,1040301697,Washer 4-160HV,4,GB/T97.1-2002,ZS1414 Series Pothole Guard
27,1020520944,Limit switch (ZS1414DC/HA),2,NaN,ZS1414 Series Pothole Guard
28,1020521804,Limit switch (ZS1414HD/AC),2,NaN,ZS1414 Series Pothole Guard
29,1040101189,Screw M4×40-8.8,4,GB/T70.1-2000,ZS1414 Series Pothole Guard
30,00775606300201050,Switch plate,2,NaN,ZS1414 Series Pothole Guard
31,00775606300201060,Switch shield,2,NaN,ZS1414 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775602802000000,Left pothole plate.,1,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
1,1040500054,Split pin 4×40,8,GB/T91-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
2,1040300052,Washer 16,12,GB/T97.1-2002,ZS1212/ZS1012/ZS0812 Series Pothole Guard
3,1040501520,Pin B16×50,6,GB/T882-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
4,1040500111,Pin B16×90,2,GB/T882-1986,ZS1212/ZS1012/ZS0812 Series Pothole Guard
5,00775602800001130,Crank gasket,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
6,1040300066,Washer 8-200HV,4,GB/T97.1-2002,ZS1212/ZS1012/ZS0812 Series Pothole Guard
7,1040300063,Washer 8,4,GB/T93-1987,ZS1212/ZS1012/ZS0812 Series Pothole Guard
8,1040201078,Nut M8,2,GB/T6170-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
9,00775602800001080,Crank linkage,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
10,00775602801400000,Crank,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
11,1040500383,Pin B8×50,2,GB/T882-1986,ZS1212/ZS1012/ZS0812 Series Pothole Guard
12,1040500212,Split pin 3.2×20,2,GB/T91-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
13,00775602800001060,Crank trolley,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
14,00775602800001070,Crank Pin,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
15,1040300094,Washer 8-140HV,2,GB/T96.1-2002,ZS1212/ZS1012/ZS0812 Series Pothole Guard
16,1110100353,Gas spring,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
17,1040000288,Bolt M8×25,10,GB/T5783-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
18,00775602801200000,Guide mechanism,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
19,1040200503,Nut M8-8,10,GB/T889.1-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775602803000000,Tray lock seat I,1,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
1,00775602802200000,Right pothole plate,1,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
2,00775602802800000,Tray lock seat II,1,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
3,1020705980,Conduction band,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
4,1040200100,Nut M4-8,4,GB/T6170-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
5,1040300044,Washer 4,4,GB/T93-1987,ZS1212/ZS1012/ZS0812 Series Pothole Guard
6,1040301697,Washer 4-160HV,4,GB/T97.1-2002,ZS1212/ZS1012/ZS0812 Series Pothole Guard
7,1020520944,Limit switch \n(ZS1212/1012/0812DC \nZS1212/10...,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
8,1020521804,Limit switch \n(ZS1212/1012/0812AC \nZS1212/10...,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
9,1040101189,Screw M4×40-8.8,4,GB/T70.1-2000,ZS1212/ZS1012/ZS0812 Series Pothole Guard
10,00775606300201050,Switch plate,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard
11,00775606300201060,Switch shield,2,NaN,ZS1212/ZS1012/ZS0812 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775602802000000,Left pothole plate.,1,NaN,ZS0808/ZS0608 Series Pothole Guard
1,1040500054,Split pin 4×40,8,GB/T91-2000,ZS0808/ZS0608 Series Pothole Guard
2,1040300052,Washer 16,12,GB/T97.1-2002,ZS0808/ZS0608 Series Pothole Guard
3,1040501520,Pin B16×50,6,GB/T882-2000,ZS0808/ZS0608 Series Pothole Guard
4,1040500111,Pin B16×90,2,GB/T882-1986,ZS0808/ZS0608 Series Pothole Guard
5,00775602800001130,Crank gasket,2,NaN,ZS0808/ZS0608 Series Pothole Guard
6,1040300066,Washer 8,8,GB/T97.1-2002,ZS0808/ZS0608 Series Pothole Guard
7,1040300063,Washer 8,8,GB/T93-1987,ZS0808/ZS0608 Series Pothole Guard
8,1040201078,Nut M8,2,GB/T6170-2000,ZS0808/ZS0608 Series Pothole Guard
9,00775402800001040,Crank linkage,2,NaN,ZS0808/ZS0608 Series Pothole Guard
10,00775602801400000,Crank,2,NaN,ZS0808/ZS0608 Series Pothole Guard
11,1040500383,Pin B8×50,2,GB/T882-1986,ZS0808/ZS0608 Series Pothole Guard
12,1040500212,Split pin 3.2×20,2,GB/T91-2000,ZS0808/ZS0608 Series Pothole Guard
13,00775602800001060,Crank trolley,2,NaN,ZS0808/ZS0608 Series Pothole Guard
14,00775602800001070,Crank Pin,2,NaN,ZS0808/ZS0608 Series Pothole Guard
15,1040300094,Washer 8,2,GB/T96.1-2002,ZS0808/ZS0608 Series Pothole Guard
16,1110100353,Gas spring,2,NaN,ZS0808/ZS0608 Series Pothole Guard
17,1040000288,Bolt M8×25,10,GB/T5783-2000,ZS0808/ZS0608 Series Pothole Guard
18,00775402801200000,Guide mechanism,2,NaN,ZS0808/ZS0608 Series Pothole Guard
19,1040200503,Nut M8-8,10,GB/T889.1-2000,ZS0808/ZS0608 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775602803000000,Tray lock seat I,1,NaN,ZS0808/ZS0608 Series Pothole Guard
1,00775602802200000,Right pothole plate,1,NaN,ZS0808/ZS0608 Series Pothole Guard
2,00775602802800000,Tray lock seat II,1,NaN,ZS0808/ZS0608 Series Pothole Guard
3,1020705980,Conduction band,2,NaN,ZS0808/ZS0608 Series Pothole Guard
4,1040200100,Nut M4-8,4,GB/T6170-2000,ZS0808/ZS0608 Series Pothole Guard
5,1040300044,Washer 4,4,GB/T93-1987,ZS0808/ZS0608 Series Pothole Guard
6,1040301697,Washer 4,4,GB/T97.1-2002,ZS0808/ZS0608 Series Pothole Guard
7,1020521804,Limit switch \n(ZS0808/ZS0608HD \nZS0808AC),2,NaN,ZS0808/ZS0608 Series Pothole Guard
8,1020520944,Limit switch \n(ZS0808/ZS0608DC \n(ZS0808HA),2,NaN,ZS0808/ZS0608 Series Pothole Guard
9,1040101189,Screw M4×40-8.8,4,GB/T70.1-2000,ZS0808/ZS0608 Series Pothole Guard
10,00775606300201050,Switch plate,2,NaN,ZS0808/ZS0608 Series Pothole Guard
11,00775606300201060,Switch shield,2,NaN,ZS0808/ZS0608 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775302801600000,Left pothole plate. \n(ZS0607HD/HA/DCS),1,2022.10 Revise,ZS0607 Series Pothole Guard
1,00775302811400000,Left pothole plate. \n(ZS0607DC/AC/ACW),1,NaN,ZS0607 Series Pothole Guard
2,1040500054,Split pin 4×40,8,GB/T91-2000,ZS0607 Series Pothole Guard
3,1040300052,Washer 16,6,GB/T97.1-2002,ZS0607 Series Pothole Guard
4,1040501520,Pin B16×50,4,GB/T882-2000,ZS0607 Series Pothole Guard
5,1040500111,Pin B16×90,2,GB/T882-1986,ZS0607 Series Pothole Guard
6,00775602800001130,Crank gasket,2,NaN,ZS0607 Series Pothole Guard
7,1040300066,Washer 8,8,GB/T97.1-2002,ZS0607 Series Pothole Guard
8,1040300063,Washer 8,8,GB/T93-1987,ZS0607 Series Pothole Guard
9,1040201078,Nut M8,2,GB/T6170-2000,ZS0607 Series Pothole Guard
10,00775302800001010,Crank linkage \n(ZS0607HD/HA/DCS),2,2022.10 Revise,ZS0607 Series Pothole Guard
11,00775302810001010,Crank linkage \n(ZS0607DC/AC/ACW),2,NaN,ZS0607 Series Pothole Guard
12,00775602801400000,Crank,2,NaN,ZS0607 Series Pothole Guard
13,1040500383,Pin B8×50,2,GB/T882-1986,ZS0607 Series Pothole Guard
14,1040500212,Split pin 3.2×20,2,GB/T91-2000,ZS0607 Series Pothole Guard
15,00775602800001060,Crank trolley,2,NaN,ZS0607 Series Pothole Guard
16,00775602800001070,Crank Pin,2,NaN,ZS0607 Series Pothole Guard
17,1040300094,Washer 8,2,GB/T96.1-2002,ZS0607 Series Pothole Guard
18,1110100353,Gas spring,2,NaN,ZS0607 Series Pothole Guard
19,1040000288,Nut M8×25,10,GB/T5783-2000,ZS0607 Series Pothole Guard
20,00775302802000000,Conduction band,1,NaN,ZS0607 Series Pothole Guard
21,1040200503,Nut M8-8,10,GB/T889.1-2000,ZS0607 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775302801400000,Tray lock seat I,2,NaN,ZS0607 Series Pothole Guard
1,00775302801800000,Right pothole plate \n(ZS0607HD/HA/DCS),1,2022.10 Revise,ZS0607 Series Pothole Guard
2,00775302811600000,Right pothole plate \n(ZS0607DC/AC/ACW),1,NaN,ZS0607 Series Pothole Guard
3,1040500066,Pin B16×55,2,GB/T882-1986,ZS0607 Series Pothole Guard
4,1020705980,Conduction band,2,NaN,ZS0607 Series Pothole Guard
5,1040200100,Nut M4-8,4,GB/T6170-2000,ZS0607 Series Pothole Guard
6,1040300044,Washer 4,4,GB/T93-1987,ZS0607 Series Pothole Guard
7,1040301697,Washer 4,4,GB/T97.1-2002,ZS0607 Series Pothole Guard
8,1020521804,Limit switch \n(ZS0607HD),2,NaN,ZS0607 Series Pothole Guard
9,1020520944,Limit switch \n(ZS0607DC/HA/AC/ACW),2,NaN,ZS0607 Series Pothole Guard
10,1020521812,Limit switch (ZS0607DCS),2,2022.10 Revise,ZS0607 Series Pothole Guard
11,1040101189,Screw M4×40-8.8,4,GB/T70.1-2000,ZS0607 Series Pothole Guard
12,00775306320201030,Switch plate,2,NaN,ZS0607 Series Pothole Guard
13,00775306320201040,Switch shield,2,NaN,ZS0607 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,00775202802000000,Guide mechanism,1,NaN,ZS0407 Series Pothole Guard
1,1040000689,Bolt M8×35-8.8,4,GB/T5783-2000,ZS0407 Series Pothole Guard
2,1040200503,Nut M8,4,GB/T889.1-2000,ZS0407 Series Pothole Guard
3,00775202800001010,Limited bolt post,2,NaN,ZS0407 Series Pothole Guard
4,1040500212,Split pin 3.2×20,2,GB/T91-2000,ZS0407 Series Pothole Guard
5,1040500383,PinB8×50,2,GB/T882-1986,ZS0407 Series Pothole Guard
6,00775602800001060,Crank trolley,2,NaN,ZS0407 Series Pothole Guard
7,1040300052,Washer 16,10,GB/T97.1-2002,ZS0407 Series Pothole Guard
8,1040500054,Pin4×40,10,GB/T91-2000,ZS0407 Series Pothole Guard
9,00775202800201190,PinΦ25,2,NaN,ZS0407 Series Pothole Guard
10,00775202801600000,Crank,2,NaN,ZS0407 Series Pothole Guard
11,1040500066,PinB16×55,2,GB/T882-1986,ZS0407 Series Pothole Guard
12,00775202800001020,Crank linkage,2,NaN,ZS0407 Series Pothole Guard
13,1110100346,Gas spring,2,NaN,ZS0407 Series Pothole Guard
14,1040300063,Washer 8,10,GB/T93-1987,ZS0407 Series Pothole Guard
15,1040300066,Washer 8,10,GB/T97.1-2002,ZS0407 Series Pothole Guard
16,1040201078,Nut M8,2,GB/T6170-2000,ZS0407 Series Pothole Guard
17,1040501520,Pin B16×50,6,GB/T882-2000,ZS0407 Series Pothole Guard
18,00775202801200000,Right pothole plate,1,NaN,ZS0407 Series Pothole Guard
19,00775202801400000,Left pothole plate,1,NaN,ZS0407 Series Pothole Guard
20,00775602800001130,Crank washer,2,NaN,ZS0407 Series Pothole Guard
21,00775306320201030,Switch plate,2,NaN,ZS0407 Series Pothole Guard
22,1020521041,Limit switch,2,NaN,ZS0407 Series Pothole Guard
23,1040300044,Washer 4,4,GB/T93-1987,ZS0407 Series Pothole Guard
24,1040301697,Washer 4,4,GB/T97.1-2002,ZS0407 Series Pothole Guard
25,1040101189,Screw M4×40-8.8,4,GB/T70.1-2000,ZS0407 Series Pothole Guard
26,1029906965,Conduction band,2,NaN,ZS0407 Series Pothole Guard
27,1040102717,Screw M8×40,4,GB/T70.3-2000,ZS0407 Series Pothole Guard

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush 38×44×30,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...
1,00775602801210000,Guide support,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...
2,00775602801201020,Spring support,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...
3,00775602801201030,Spring,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...
4,1054400308,Composite bush 25×30×35,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...
5,00775702801401010,Guide rod (ZS1414 series),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...
6,00775602801201010,Guide rod,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Guide Mecha...

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush 38×44×30,2,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
1,00775402801210000,Guide support,1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
2,00775602801201020,Spring support,1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
3,00775602801201030,Spring,1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
4,1054400308,Composite bush 25×30×35,1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
5,00775602801201010,Guide rod \n (ZS0608/ZS0808 series),1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
6,00775302802001010,Guide rod \n (ZS0607 series),1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...
7,00775202802001010,Guide rod \n (ZS0407 series),1,NaN,ZS0808/ZS0608/ZS0607/ZS0407 Series Guide Mecha...

,Material No.,Item and Spec,Units,Remark,Section
0,1040102356,Screw M8×25-8.8,8,GB/T70.3-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
1,00775602800601010,Limited post,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
2,00775602800601030,Cushion rubber,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
3,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
4,1040300054,Washer 12,1,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
5,00775606300201030,Key switch gasket,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
6,00775602801601040,Protecting bush II,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
7,00775702870210000,Hydraulic Tray box \n (ZS1414AC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
8,00775602860210000,Hydraulic Tray box \n(ZS1212/1012/0812AC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
9,1020005472,"Hydraulic pump drive motor \n24V,3.3KW",1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
10,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
11,1040004607,Bolt3/8-24UNF-1-10,2,ASME B18.2.1-2010,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
12,1010001904,Gear pump 5cc,1,5cc-PGP511A0050 \nAA1H2ND4D3B1B1,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
13,00775602800601020,Motor support,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
14,1040200867,Nut M5,4,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
15,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...

,Material No.,Item and Spec,Units,Remark,Section
0,1040100378,Screw M5×20-8.8,4,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
1,1040200503,Nut M8-8,8,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
2,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
3,1040300051,Washer 6-200HV,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
4,1040300062,Washer 6,1,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
5,1040100237,Screw M6×30-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
6,1020104319,Motor driver,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
7,1040101606,Screw M8×12-8.8,4,GB/T70.3-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
8,1011300151,Tank,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
9,1010306187,Control valve \n(ZS1414/1212/1012/0812AC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
10,1010306289,Control valve \n(ZS1414/1212/1012/0812AC-Li),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
11,1040000267,Bolt M8×20-8.,6,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
12,1040300066,Washer 8-200HV,8,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
13,1040300063,Washer 8,4,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
14,1040004517,Bolt M8×16-8.8,4,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
15,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
16,1020104088,Ground control assembly,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
17,1020521389,Key switch,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
18,1020304979,Breaker,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...
19,1020502039,Emergency stop button,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC Series Hydraulic...

,Material No.,Item and Spec,Units,Remark,Section
0,1040102356,Screw M8×25-8.8,8,GB/T70.3-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
1,00775602800601010,Limited post,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
2,00775602800601030,Cushion rubber,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
3,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
4,1040300054,Washer 12,1,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
5,00775606300201030,Key switch gasket,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
6,1040100106,Screw M4×10-4.8,2,GB/T818-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
7,1040300044,Washer 4,4,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
8,1040301697,Washer 4-160HV,4,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
9,00775602801601040,Protecting bush II,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
10,00775602800601040,Waterproof coverplate \n(ZS1414/1212/1012HD),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
11,00775702800420000,Hydraulic Tray box \n(ZS1414HD/ZS1414DC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
12,00775702870210000,Hydraulic Tray box \n(ZS1414HA),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
13,00775602860210000,Hydraulic Tray box \n(ZS1212/1012/0812HA),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
14,00775602800620000,Hydraulic Tray box \n(ZS1212/1012/0812DC \nZS1...,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
15,1020005103,DC motor 24V，4.5KW \n(ZS1414/1212/1012/0812DC ...,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
16,1020005472,"Hydraulic pump drive motor \n24V,3.3KW \n(ZS14...",1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
17,00775602800601020,Motor support,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
18,1040200867,Nut M5,4,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
19,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...

,Material No.,Item and Spec,Units,Remark,Section
0,1040100378,Screw M5×20-8.8,4,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
1,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
2,1040004607,Bolt 3/8-24UNF-1-10.,2,ASME B18.2.1-2010,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
3,1040200503,Nut M8-8,8,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
4,1010001904,Gear pump \n(ZS1414/ZS1212/ZS1012/ \nZS0812H...,1,5cc-PGP511A0050 \nAA1H2ND4D3B1B1,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
5,1010001885,Hydraulic pump \n(ZS0812DC Series),1,4cc-PGP505A0040 \nAA1H2ND4D4B1B1,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
6,1011300151,Tank,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
7,1040101606,Screw M8×12-8.8,4,GB/T70.3-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
8,1010305936,Control valve \n(ZS1414/1212/1012HD \nZS1414/1...,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
9,1010306182,Control valve \n(ZS1414/1212/1012HD-Li \nZS141...,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
10,1010306187,Control valve \n(ZS1414/1212/1012/0812DC),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
11,1010306289,Control valve \n(ZS1414/1212/1012/0812DC-Li),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
12,1040000267,Bolt M8×20-8,6,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
13,1040300066,Washer 8-200HV,8,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
14,00775605200801010,Valve support \n(仅 ZS1414/1212/1012HD Series),1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
15,1040300063,Washer 8,4,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
16,1040004517,Bolt M8×16-8.8,4,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
17,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
18,1020104088,Ground control assembly,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
19,1020521389,Key switch,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
20,1020304979,Breaker,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...
21,1020502039,Emergency stop button,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812HD(HA/DC) Series Hy...

,Material No.,Item and Spec,Units,Remark,Section
0,1020005692,Motor driver,1,NaN,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
1,1109900765,Hydraulic door lock,1,1109900765,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
3,1040300062,Washer 6,8,GB/T93-1987,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
4,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
5,1020604247,Flat fuse,1,NaN,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
6,1020604246,Fuse holder,1,NaN,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
8,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
9,1040300060,Washer 5,2,GB/T93-1987,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
11,1020300083,Common relay,1,NaN,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
12,1020304982,Buzzer,2,NaN,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2
13,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012HD Series Hydraulic Tray 2

,Material No.,Item and Spec,Units,Remark,Section
0,1020104201,Motor driver,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
1,1109900765,Hydraulic door lock,1,1109900765,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
3,1040300062,Washer 6,8,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
4,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
5,1020604247,Flat fuse,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
6,1020604246,Fuse holder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
8,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
9,1040300060,Washer 5,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
11,1020304604,Contactor,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...
12,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812AC(HA) Series Hydra...

,Material No.,Item and Spec,Units,Remark,Section
0,1020005175,Motor driver,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
1,1109900765,Hydraulic door lock,1,1109900765,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
3,1040300062,Washer 6,8,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
4,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
5,1020604247,Flat fuse,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
6,1020604246,Fuse holder,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
8,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
9,1040300060,Washer 5,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
11,1020304604,Contactor,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
12,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
13,1020605226,Follow current protector,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
14,1040201605,Locknut M4-8,2,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
15,1040301697,Washer 4-160HV,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...
16,1040100618,Screw M4×16-8.8,2,GB/T818-2000,ZS1414/ZS1212/ZS1012/ZS0812DC Series Hydraulic...

,Material No.,Item and Spec,Units,Remark,Section
0,1040102356,Screw M8×25-8.8,8,GB/T70.3-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
1,00775602800601010,Limited post,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
2,00775602800601030,Cushion rubber,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
3,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
4,1040300054,Washer 12,1,GB/T93-1987,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
5,00775606300201030,Key switch gasket,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
6,1040100106,Screw M4×10-4.8,2,GB/T818-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
7,1040300044,Washer 4,4,GB/T93-1987,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
8,1040301697,Washer 4-160HV,4,GB/T97.1-2002,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
9,00775602801601040,Protecting bush II,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
10,00775602800601040,Waterproof coverplate \n(ZS0808/ZS0608HD Series),1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
11,00775602860210000,Hydraulic Tray box \n (ZS0808HA Series),1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
12,00775602800620000,Hydraulic Tray box (ZS0808DC/ \nZS0808HD/ZS060...,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
13,1020005472,Hydraulic pump drive motor \n24V，3.3KW \n(ZS...,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
14,1020005153,DC motor \n(ZS0808/ZS0608HD \nZS0808/ZS0608DC ...,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
15,00775602800601020,Driver support,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1040200867,Bolt M5,4,GB/T889.1-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
1,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
2,1040100378,Screw M5×20-8.8,4,GB/T70.1-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
3,1040300067,Washer 10,2,GB/T93-1987,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
4,1040004607,Bolt 3/8-24UNF-1-10.,2,ASME B18.2.1-2010,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
5,1040200503,Nut M8-8,8,GB/T889.1-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
6,1010001885,Hydraulic pump,1,4cc-PGP505A0040 \nAA1H2ND4D4B1B1,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
7,1011300151,Tank,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
8,1040101606,Screw M8×12-8.8,4,GB/T70.3-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
9,1010305936,Control valve \n(ZS0808HD/0808HA/0608HD),1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
10,1010306182,Control valve \n (ZS0808HD-Li/0808HA-Li/0608H...,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
11,1010306187,Control valve \n (ZS0808DC/0608DC),1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
12,1010306289,Control valve \n(ZS0808DC-Li/0608DC-Li),1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
13,1040000267,Bolt M8×20-8.8,6,GB/T5783-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
14,1040300066,Washer 8-200HV,8,GB/T97.1-2002,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
15,1040300063,Washer 8,4,GB/T93-1987,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
16,1040004517,Bolt M8×16-8.8,4,GB/T5783-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
17,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
18,1020104088,Ground control assembly,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
19,1020521389,Key switch,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
20,1020304979,Breaker,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1
21,1020502039,Emergency stop button,1,NaN,ZS0808/ZS0608HD(DC/HA) Series Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1040102356,Screw M8×25-8.8,8,GB/T70.3-2000,ZS0808AC Series Hydraulic Tray 1
1,00775602800601010,Limited post,1,NaN,ZS0808AC Series Hydraulic Tray 1
2,00775602800601030,Cushion rubber,1,NaN,ZS0808AC Series Hydraulic Tray 1
3,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS0808AC Series Hydraulic Tray 1
4,1040300054,Washer 12,1,GB/T93-1987,ZS0808AC Series Hydraulic Tray 1
5,00775606300201030,Key switch gasket,1,NaN,ZS0808AC Series Hydraulic Tray 1
6,00775602801601040,Protecting bush II,1,NaN,ZS0808AC Series Hydraulic Tray 1
7,00775602860210000,Hydraulic Tray box,1,NaN,ZS0808AC Series Hydraulic Tray 1
8,1020005472,Hydraulic pump drive motor \n24V，3.3KW,1,NaN,ZS0808AC Series Hydraulic Tray 1
9,1040300067,Washer 10,2,GB/T93-1987,ZS0808AC Series Hydraulic Tray 1
10,1040004607,Bolt 3/8-24UNF-1-10.,2,ASME B18.2.1-2010,ZS0808AC Series Hydraulic Tray 1
11,1010001885,Hydraulic pump,1,4cc-PGP505A0040 \nAA1H2ND4D4B1B1,ZS0808AC Series Hydraulic Tray 1
12,00775602800601020,Motor support,1,NaN,ZS0808AC Series Hydraulic Tray 1
13,1040200867,Nut M5,4,GB/T889.1-2000,ZS0808AC Series Hydraulic Tray 1
14,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS0808AC Series Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1040100378,Screw M5×20-8.8,4,GB/T70.1-2000,ZS0808AC Series Hydraulic Tray 1
1,1040200503,Nut M8-8,8,GB/T889.1-2000,ZS0808AC Series Hydraulic Tray 1
2,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0808AC Series Hydraulic Tray 1
3,1040300051,Washer 6-200HV,2,GB/T97.1-2002,ZS0808AC Series Hydraulic Tray 1
4,1040300062,Washer 6,1,GB/T93-1987,ZS0808AC Series Hydraulic Tray 1
5,1040100237,Screw M6×30-8.8,2,GB/T70.1-2000,ZS0808AC Series Hydraulic Tray 1
6,1020104319,Motor driver,1,NaN,ZS0808AC Series Hydraulic Tray 1
7,1040101606,Screw M8×12-8.8,4,GB/T70.3-2000,ZS0808AC Series Hydraulic Tray 1
8,1011300151,Tank,1,NaN,ZS0808AC Series Hydraulic Tray 1
9,1010306187,Control valve \n (ZS0808AC),1,NaN,ZS0808AC Series Hydraulic Tray 1
10,1010306289,Control valve \n(ZS0808AC-Li),1,NaN,ZS0808AC Series Hydraulic Tray 1
11,1040000267,Bolt M8×20-8.8,6,GB/T5783-2000,ZS0808AC Series Hydraulic Tray 1
12,1040300066,Washer 8-200HV,8,GB/T97.1-2002,ZS0808AC Series Hydraulic Tray 1
13,1040300063,Washer 8,4,GB/T93-1987,ZS0808AC Series Hydraulic Tray 1
14,1040004517,Bolt M8×16-8.8,4,GB/T5783-2000,ZS0808AC Series Hydraulic Tray 1
15,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0808AC Series Hydraulic Tray 1
16,1020104088,Ground control assembly,1,NaN,ZS0808AC Series Hydraulic Tray 1
17,1020521389,Key switch,1,NaN,ZS0808AC Series Hydraulic Tray 1
18,1020304979,Breaker,1,NaN,ZS0808AC Series Hydraulic Tray 1
19,1020502039,Emergency stop button,1,NaN,ZS0808AC Series Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1020005692,Motor driver,1,NaN,ZS0808/ZS0608HD Series Hydraulic Tray 2
1,1109900765,Hydraulic door lock,1,1109900765,ZS0808/ZS0608HD Series Hydraulic Tray 2
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS0808/ZS0608HD Series Hydraulic Tray 2
3,1040300062,Washer 6,8,GB/T93-1987,ZS0808/ZS0608HD Series Hydraulic Tray 2
4,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808/ZS0608HD Series Hydraulic Tray 2
5,1020605230,Flat fuse,1,NaN,ZS0808/ZS0608HD Series Hydraulic Tray 2
6,1020604246,Fuse holder,1,NaN,ZS0808/ZS0608HD Series Hydraulic Tray 2
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS0808/ZS0608HD Series Hydraulic Tray 2
8,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS0808/ZS0608HD Series Hydraulic Tray 2
9,1040300060,Washer 5,2,GB/T93-1987,ZS0808/ZS0608HD Series Hydraulic Tray 2
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608HD Series Hydraulic Tray 2
11,1020300083,Common relay,1,NaN,ZS0808/ZS0608HD Series Hydraulic Tray 2
12,1020304982,Buzzer,2,NaN,ZS0808/ZS0608HD Series Hydraulic Tray 2
13,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608HD Series Hydraulic Tray 2

,Material No.,Item and Spec,Units,Remark,Section
0,1020104201,Motor driver,1,NaN,ZS0808AC/HA Hydraulic Tray 2
1,1109900765,Hydraulic door lock,1,1109900765,ZS0808AC/HA Hydraulic Tray 2
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS0808AC/HA Hydraulic Tray 2
3,1040300062,Washer 6,8,GB/T93-1987,ZS0808AC/HA Hydraulic Tray 2
4,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808AC/HA Hydraulic Tray 2
5,1020605230,Flat fuse,1,NaN,ZS0808AC/HA Hydraulic Tray 2
6,1020604246,Fuse holder,1,NaN,ZS0808AC/HA Hydraulic Tray 2
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS0808AC/HA Hydraulic Tray 2
8,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS0808AC/HA Hydraulic Tray 2
9,1040300060,Washer 5,2,GB/T93-1987,ZS0808AC/HA Hydraulic Tray 2
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0808AC/HA Hydraulic Tray 2
11,1020304603,Contactor,1,NaN,ZS0808AC/HA Hydraulic Tray 2
12,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0808AC/HA Hydraulic Tray 2

,Material No.,Item and Spec,Units,Remark,Section
0,1020005175,Motor driver,1,NaN,ZS0808/ZS0608DC Series Hydraulic Tray 2
1,1109900765,Hydraulic door lock,1,1109900765,ZS0808/ZS0608DC Series Hydraulic Tray 2
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS0808/ZS0608DC Series Hydraulic Tray 2
3,1040300062,Washer 6,8,GB/T93-1987,ZS0808/ZS0608DC Series Hydraulic Tray 2
4,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808/ZS0608DC Series Hydraulic Tray 2
5,1020605230,Flat fuse,1,NaN,ZS0808/ZS0608DC Series Hydraulic Tray 2
6,1020604246,Fuse holder,1,NaN,ZS0808/ZS0608DC Series Hydraulic Tray 2
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS0808/ZS0608DC Series Hydraulic Tray 2
8,1040300048,Washer 5-200HV,6,GB/T97.1-2002,ZS0808/ZS0608DC Series Hydraulic Tray 2
9,1040300060,Washer 5,2,GB/T93-1987,ZS0808/ZS0608DC Series Hydraulic Tray 2
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC Series Hydraulic Tray 2
11,1020304603,Contactor,1,NaN,ZS0808/ZS0608DC Series Hydraulic Tray 2
12,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0808/ZS0608DC Series Hydraulic Tray 2
13,1020605226,Follow current protector,1,NaN,ZS0808/ZS0608DC Series Hydraulic Tray 2
14,1040201605,Locknut M4-8,2,GB/T889.1-2000,ZS0808/ZS0608DC Series Hydraulic Tray 2
15,1040301697,Washer 4-160HV,2,GB/T97.1-2002,ZS0808/ZS0608DC Series Hydraulic Tray 2
16,1040100618,Screw M4×16-8.8,2,GB/T818-2000,ZS0808/ZS0608DC Series Hydraulic Tray 2

,Material No.,Item and Spec,Units,Remark,Section
0,1040100421,Screw M8×20-8.8,6,GB/T70.3-2000,ZS0607HD/DC/ACW Series Hydraulic Tray 1
1,00775302800810000,Hydraulic Tray box \n (ZS0607HD Series),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
2,00775302810210000,Hydraulic Tray box \n(ZS0607DC/ACW Series),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
3,1010305936,Control valve \n (ZS0607HD),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
4,1010306182,Control valve \n (ZS0607HD-Li),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
5,1010306187,Control valve \n (ZS0607DC/ACW),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
6,1010306289,Control valve \n (ZS0607DC-Li/ACW-Li),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
7,1010001885,Hydraulic pump drive motor,1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
8,1040300067,Washer 10,2,GB/T93-1987,ZS0607HD/DC/ACW Series Hydraulic Tray 1
9,1040004607,Bolt 3/8-24UNF-1-10.9,2,ASME B18.2.1-2010,ZS0607HD/DC/ACW Series Hydraulic Tray 1
10,1020005153,Motor,1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
11,1040005783,Screw 1/4-20UNC×15-8.8,4,ASME B18.2.1-2010,ZS0607HD/DC/ACW Series Hydraulic Tray 1
12,1040200304,Nut M6-8,4,GB/T889-1986,ZS0607HD/DC/ACW Series Hydraulic Tray 1
13,1020005692,Motor driver \n (ZS0607HD Series),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
14,1020005175,Motor driver \n (ZS0607DC Series),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1
15,1020104202,Motor driver \n (ZS0607ACW Series),1,NaN,ZS0607HD/DC/ACW Series Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1040300051,Washer 6,2,GB/T97.1-2002,ZS0607HD/DC/ACW Hydraulic Tray 1
1,1011300149,Tank,1,NaN,ZS0607HD/DC/ACW Hydraulic Tray 1
2,1040004508,Bolt M10×45-8.8,2,GB/T5783-2000,ZS0607HD/DC/ACW Hydraulic Tray 1
3,1040200504,Nut M10,2,GB/T889.1-2000,ZS0607HD/DC/ACW Hydraulic Tray 1
4,1040301697,Washer 4,2,GB/T97.1-2002,ZS0607HD/DC/ACW Hydraulic Tray 1
5,1040300044,Washer 4,2,GB/T93-1987,ZS0607HD/DC/ACW Hydraulic Tray 1
6,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0607HD/DC/ACW Hydraulic Tray 1
7,1020521389,Key switch,1,NaN,ZS0607HD/DC/ACW Hydraulic Tray 1
8,1020304979,Breaker,1,NaN,ZS0607HD/DC/ACW Hydraulic Tray 1
9,1020502039,Emergency stop button,1,NaN,ZS0607HD/DC/ACW Hydraulic Tray 1
10,1020104088,Ground control assembly,1,NaN,ZS0607HD/DC/ACW Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,007753028B1201000,Hydraulic Tray box,1,NaN,ZS0607DCS Hydraulic Tray 1
1,1010002860,Power unit,1,NaN,ZS0607DCS Hydraulic Tray 1
2,1040100097,Screw M10×30-8.8,2,GB/T70.1-2000,ZS0607DCS Hydraulic Tray 1
3,1040300061,Washer 10-200HV,2,GB/T97.1-2002,ZS0607DCS Hydraulic Tray 1
4,1040300067,Washer 10,2,GB/T93-1987,ZS0607DCS Hydraulic Tray 1
5,007753028B1201130,Motor driver bracket,1,NaN,ZS0607DCS Hydraulic Tray 1
6,1020005354,Motor driver,1,NaN,ZS0607DCS Hydraulic Tray 1
7,1040100055,Screw M6×20,4,GB/T70.1-2000,ZS0607DCS Hydraulic Tray 1
8,1040300051,Washer 6-200HV,4,GB/T93-1987,ZS0607DCS Hydraulic Tray 1
9,1040300062,Washer 6,4,GB/T97.1-2002,ZS0607DCS Hydraulic Tray 1
10,1040301697,Washer 4,2,GB/T97.1-2002,ZS0607DCS Hydraulic Tray 1
11,1040300044,Washer 4,2,GB/T93-1987,ZS0607DCS Hydraulic Tray 1
12,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0607DCS Hydraulic Tray 1
13,1020521389,Key switch,1,NaN,ZS0607DCS Hydraulic Tray 1
14,1020304979,Breaker,1,NaN,ZS0607DCS Hydraulic Tray 1
15,1020502039,Emergency stop button,1,NaN,ZS0607DCS Hydraulic Tray 1
16,1020104088,Ground control assembly,1,NaN,ZS0607DCS Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1040100421,Screw M8×20-8.8,6,GB/T70.3-2000,ZS0607HA/AC Series Hydraulic Tray 1
1,00775302810210000,Hydraulic Tray box \n (ZS0607AC Series),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
2,00775302880410000,Hydraulic Tray box \nZS0607HA Series),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
3,1010305936,Control valve (ZS0607HA),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
4,1010306182,Control valve (ZS0607HA-Li),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
5,1010306187,Control valve (ZS0607AC),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
6,1010306289,Control valve (ZS0607AC-Li),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
7,1010001885,Hydraulic pump,1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
8,1040300067,Washer 10,2,GB/T93-1987,ZS0607HA/AC Series Hydraulic Tray 1
9,1040004607,Bolt 3/8-24UNF-1-10.9,2,ASME B18.2.1-\n2010,ZS0607HA/AC Series Hydraulic Tray 1
10,1020005153,Motor (ZS0607AC Series),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
11,1020005748,Hydraulic pump drive motor \n(ZS0607HA Series),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
12,1040005783,Screw 1/4-20UNC×15-8.8,4,ASME B18.2.1-\n2010,ZS0607HA/AC Series Hydraulic Tray 1
13,1040200304,Nut M6-8,4,GB/T889-1986,ZS0607HA/AC Series Hydraulic Tray 1
14,1020104201,Motor driver (ZS0607HA Series),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
15,1020104202,Motor driver (ZS0607AC Series),1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
16,1040300051,Washer 6,2,GB/T97.1-2002,ZS0607HA/AC Series Hydraulic Tray 1
17,1011300149,Tank,1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
18,1040004508,Bolt M10×45-8.8,2,GB/T5783-2000,ZS0607HA/AC Series Hydraulic Tray 1
19,1040200504,Nut M10,2,GB/T889.1-2000,ZS0607HA/AC Series Hydraulic Tray 1
20,1040301697,Washer 4,2,GB/T97.1-2002,ZS0607HA/AC Series Hydraulic Tray 1
21,1040300044,Washer 4,2,GB/T93-1987,ZS0607HA/AC Series Hydraulic Tray 1
22,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0607HA/AC Series Hydraulic Tray 1
23,1020521389,Key switch,1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
24,1020304979,Breaker,1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
25,1020502039,Emergency stop button,1,NaN,ZS0607HA/AC Series Hydraulic Tray 1
26,1020104088,Ground control assembly,1,NaN,ZS0607HA/AC Series Hydraulic Tray 1

,Material No.,Item and Spec,Units,Remark,Section
0,1020604245,Flat fuse,1,NaN,ZS0607 Series Hydraulic Tray 2
1,1020604246,Fuse holder,1,NaN,ZS0607 Series Hydraulic Tray 2
2,1040300048,Washer 5,2,GB/T97.1-2002,ZS0607 Series Hydraulic Tray 2
3,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0607 Series Hydraulic Tray 2
4,1020304978,Basin shaped horn \n(ZS0607DC/AC/ACW/DCS \nSer...,1,2022.10 Revise,ZS0607 Series Hydraulic Tray 2
5,1040100886,Screw M8×20-8.8,1,GB/T70.1-2008,ZS0607 Series Hydraulic Tray 2
6,1040300066,Washer 8,2,GB/T97.1-2002,ZS0607 Series Hydraulic Tray 2
7,1020304603,Contactor (ZS0607DC/HA/ \nAC/ACW/DCS Series),1,2022.10 Revise,ZS0607 Series Hydraulic Tray 2
8,1040100127,Screw M6×12-8.8,2,GB/T70.1-2000,ZS0607 Series Hydraulic Tray 2
9,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS0607 Series Hydraulic Tray 2
10,1040300051,Washer 6,2,GB/T97.1-2002,ZS0607 Series Hydraulic Tray 2
11,1109900765,Hydraulic door lock,1,NaN,ZS0607 Series Hydraulic Tray 2
12,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0607 Series Hydraulic Tray 2
13,1040300062,Washer 6,2,GB/T93-1987,ZS0607 Series Hydraulic Tray 2
14,1040200304,Nut M6-8,2,GB/T889-1986,ZS0607 Series Hydraulic Tray 2
15,1040100437,Screw M4×16-8.8,2,GB/T70.1-2000,ZS0607 Series Hydraulic Tray 2
16,1020605226,Follow current protector \n(ZS0607DC/DCS Series),1,NaN,ZS0607 Series Hydraulic Tray 2

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/1212/1012HD Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS1414/1212/1012HD Battery Tray
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS1414/1212/1012HD Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS1414/1212/1012HD Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS1414/1212/1012HD Battery Tray
5,00775702800620000,Battery Tray box \n(ZS1414HD),1,NaN,ZS1414/1212/1012HD Battery Tray
6,00775602801620000,Battery Tray box \n(ZS1212/ZS1012HD),1,NaN,ZS1414/1212/1012HD Battery Tray
7,00775602801601010,Coil III,1,NaN,ZS1414/1212/1012HD Battery Tray
8,1029907622,Vehicle-mounted battery \ncharger,1,NaN,ZS1414/1212/1012HD Battery Tray
9,1020521277,Main power switch,1,NaN,ZS1414/1212/1012HD Battery Tray
10,1040000267,Bolt M8×20-8.8,2,GB/T5783-2000,ZS1414/1212/1012HD Battery Tray
11,1040300063,Washer 8,2,GB/T93-1987,ZS1414/1212/1012HD Battery Tray
12,1040300066,Washer 8-200HV,5,GB/T97.1-2002,ZS1414/1212/1012HD Battery Tray
13,00775602801601070,Middle plate \n(ZS1414/ZS1212HD),1,NaN,ZS1414/1212/1012HD Battery Tray
14,00775502800220000,Middle plate (ZS1012HD),1,NaN,ZS1414/1212/1012HD Battery Tray
15,1040201078,Nut M8,2,GB/T6170-2000,ZS1414/1212/1012HD Battery Tray
16,1020999050,Battery,4,NaN,ZS1414/1212/1012HD Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,00775602801601020,Threaded rod \n(ZS1414/ZS1212HD),1,NaN,ZS1414/1212/1012HD Battery Tray
1,00775502800201010,Threaded rod \n (ZS1012HD),1,NaN,ZS1414/1212/1012HD Battery Tray
2,00775602800601010,NaN,1,NaN,ZS1414/1212/1012HD Battery Tray
3,00775602800601030,Cushion rubber,1,NaN,ZS1414/1212/1012HD Battery Tray
4,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS1414/1212/1012HD Battery Tray
5,1040300054,Washer 12,1,GB/T93-1987,ZS1414/1212/1012HD Battery Tray
6,1040200503,Nut M8,3,GB/T889.1-2000,ZS1414/1212/1012HD Battery Tray
7,1040100886,Screw M8×20,1,GB/T70.1-2008,ZS1414/1212/1012HD Battery Tray
8,00775602801601050,Limit plate I,1,NaN,ZS1414/1212/1012HD Battery Tray
9,1040200506,Nut M6-8,8,GB/T889.1-2000,ZS1414/1212/1012HD Battery Tray
10,1040100237,Screw M6×30-8.8,6,GB/T70.1-2000,ZS1414/1212/1012HD Battery Tray
11,00775602801601060,Limit plate II,1,NaN,ZS1414/1212/1012HD Battery Tray
12,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS1414/1212/1012HD Battery Tray
13,1020304978,Basin shaped horn,1,NaN,ZS1414/1212/1012HD Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
2,1040300051,Washer 6-200HV,8,GB/T97.1-2002,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
5,00775702800620000,Battery Tray box \n(ZS1414DC/HA/AC),1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
6,00775602801620000,Battery Tray box \n(ZS1212DC/HA/AC \nZS1012DC/...,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
7,00775602801601010,Coil III,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
8,1029907622,Vehicle-mounted battery \ncharger,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
9,1020521277,Main power switch,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
10,1040000267,Bolt M8×20-8.8,2,GB/T5783-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
11,1040300063,Washer 8,2,GB/T93-1987,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
12,1040300066,Washer 8-200HV,5,GB/T97.1-2002,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
13,00775602801601070,Middle plate \n(ZS1414DC/HA/AC \nZS1212DC/HA/AC),1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
14,00775502800220000,Middle plate \n(ZS1012DC/HA/AC \nZS0812DC/HA/AC),1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
15,1040201078,Nut M8,2,GB/T6170-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
16,1020999050,Battery,4,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,00775602801601020,Threaded rod \n(ZS1414DC/HA/AC \nZS1212DC/HA/AC),1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
1,00775502800201010,Threaded rod \n (ZS1012DC/HA/AC \nZS0812DC/HA...,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
2,00775602800601010,NaN,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
3,00775602800601030,Cushion rubber,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
4,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
5,1040300054,Washer 12,1,GB/T93-1987,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
6,1040200503,Nut M8,3,GB/T889.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
7,1040100886,Screw M8×20,1,GB/T70.1-2008,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
8,1040200506,Nut M6-8,8,GB/T889.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
9,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
10,1040201605,Locknut M4-8,1,GB/T889.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
11,1040102716,Screw M4×35,1,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
12,00775602801601050,Limit plate I,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
13,1040100237,Screw M6×30-8.8,6,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
14,00775602801601060,Limit plate II,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
15,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
16,1020304978,Basin shaped horn,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
17,1020304982,Buzzer,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
18,1020300083,Common relay \n(ZS1414/1212/1012/0812DC),1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray
19,1020305334,Common relay \n(ZS1414/1212/1012/0812HA \nZS14...,1,NaN,ZS1414/1212/1012/0812HA(DC/AC) Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/1212/1012HD-Li Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS1414/1212/1012HD-Li Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS1414/1212/1012HD-Li Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
5,00775702800620000,Battery Tray box \n(ZS1414HD-Li),1,NaN,ZS1414/1212/1012HD-Li Battery Tray
6,00775602801620000,Battery Tray box \n(ZS1212/ZS1012HD-Li),1,NaN,ZS1414/1212/1012HD-Li Battery Tray
7,00775602801601010,Coil.III,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
8,1029907623,Vehicle-mounted battery \ncharger,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
9,1040300060,Washer 5,2,GB/T93-1987,ZS1414/1212/1012HD-Li Battery Tray
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS1414/1212/1012HD-Li Battery Tray
11,1020521277,Main power switch,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
12,1020999017,Battery,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
13,00775602800601030,Cushion rubber,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
14,00775602800601010,Limited post,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
15,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS1414/1212/1012HD-Li Battery Tray
16,1040300054,Washer 12,1,GB/T93-1987,ZS1414/1212/1012HD-Li Battery Tray
17,1040003761,Bolt M6×25-8.8,4,GB/T5783-2000,ZS1414/1212/1012HD-Li Battery Tray
18,00775602820201070,Cushion rubber,4,NaN,ZS1414/1212/1012HD-Li Battery Tray
19,00775602820201080,Counterweight,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
20,1040100886,Screw M8×20,1,GB/T70.1-2000,ZS1414/1212/1012HD-Li Battery Tray
21,1040200503,Nut M8,1,GB/T889.1-2000,ZS1414/1212/1012HD-Li Battery Tray
22,1040300066,Washer 8,1,GB/T97.1-2002,ZS1414/1212/1012HD-Li Battery Tray
23,00775602820201010,Transparent plate,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
24,1020304978,Basin shaped horn,1,NaN,ZS1414/1212/1012HD-Li Battery Tray
25,1040100620,Screw M6×16,4,GB/T818-2000,ZS1414/1212/1012HD-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
5,00775702800620000,Battery Tray box \n (ZS1414DC-Li/HA-Li/AC-Li),1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
6,00775602801620000,Battery Tray box \n(ZS1212DC-Li/HA-Li/AC-Li ...,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
7,00775602801601010,Coil III,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
8,1029907623,Vehicle-mounted battery charger,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
9,1040300060,Washer 5,2,GB/T93-1987,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
11,1020521277,Main power switch,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
12,1020999017,Battery,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
13,00775602800601030,Cushion rubber,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
14,00775602800601010,Limited post,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
15,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
16,1040300054,Washer 12,1,GB/T93-1987,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
17,1040003761,Bolt M6×25-8.8,4,GB/T5783-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
18,00775602820201070,Rubber Washer,4,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
19,00775602820201080,Counterweight,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
20,1040100886,Screw M8×20,1,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040200503,Nut M8,1,GB/T889.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
1,1040300066,Washer 8,1,GB/T97.1-2002,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
2,1040200506,Nut M6-8,2,GB/T889.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
3,1040100237,Screw M6×30-8.8,2,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
4,00775602820201010,Transparent plate,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
5,1020304982,Buzzer,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
6,1020304978,Basin shaped horn,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
8,1020300083,Common relay \n(ZS1414/1212/1012DC-Li \nZS0812...,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
9,1020305334,Common relay \n(ZS1414/1212/ \n1012/0812HA-Li ...,1,NaN,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
10,1040201605,Nut M4-8,1,GB/T889.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray
11,1040102716,Screw M4×35,1,GB/T70.1-2000,ZS1414/1212/1012/0812HA(DC/AC)-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS0808/ZS0608DC(HA/AC) Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS0808/ZS0608DC(HA/AC) Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
5,00775602801620000,Battery Tray box,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
6,00775602801601010,Coil III,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
7,1029907622,Vehicle-mounted battery \ncharger,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
8,1020521277,Main power switch,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
9,1040000267,Bolt M8×20-8.8,2,GB/T5783-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
10,1040300063,Washer 8,2,GB/T93-1987,ZS0808/ZS0608DC(HA/AC) Battery Tray
11,1040300066,Washer 8,5,GB/T97.1-2002,ZS0808/ZS0608DC(HA/AC) Battery Tray
12,00775502800220000,Middle plate,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
13,1040201078,Nut M8,2,GB/T6170-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
14,1020999049,Battery,4,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
15,00775502800201010,Threaded rod,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
16,00775602800601010,Limited post,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
17,00775602800601030,Cushion rubber,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
18,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
19,1040300054,Washer 12,1,GB/T93-1987,ZS0808/ZS0608DC(HA/AC) Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040200503,Nut M8,3,GB/T889.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
1,1040100886,Screw M8×20,1,GB/T70.1-2008,ZS0808/ZS0608DC(HA/AC) Battery Tray
2,1040200506,Nut M6-8,8,GB/T889.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
3,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
4,1040201605,Locknut M4-8,1,GB/T889.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
5,1040102716,Screw M4×35,1,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
6,00775602801601050,Limit plate I,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
7,1040100237,Screw M6×30-8.8,6,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
8,00775602801601060,Limit plate II,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
9,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0808/ZS0608DC(HA/AC) Battery Tray
10,1020304978,Basin shaped horn,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
11,1020304982,Buzzer,1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
12,1020300083,Common relay \n(ZS0808HD/DC \nZS0608HD/DC),1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray
13,1020305334,Common relay \n(ZS0808HA/AC),1,NaN,ZS0808/ZS0608DC(HA/AC) Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808HD/ZS0608HD Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS0808HD/ZS0608HD Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS0808HD/ZS0608HD Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS0808HD/ZS0608HD Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS0808HD/ZS0608HD Battery Tray
5,00775602801620000,Battery Tray box,1,NaN,ZS0808HD/ZS0608HD Battery Tray
6,00775602801601010,Coil III,1,NaN,ZS0808HD/ZS0608HD Battery Tray
7,1029907623,Vehicle-mounted battery \ncharger,1,NaN,ZS0808HD/ZS0608HD Battery Tray
8,1020521277,Main power switch,1,NaN,ZS0808HD/ZS0608HD Battery Tray
9,1040000267,Bolt M8×20-8.8,2,GB/T5783-2000,ZS0808HD/ZS0608HD Battery Tray
10,1040300063,Washer 8,2,GB/T93-1987,ZS0808HD/ZS0608HD Battery Tray
11,1040300066,Washer 8-200HV,5,GB/T97.1-2002,ZS0808HD/ZS0608HD Battery Tray
12,00775502800220000,Middle plate,1,NaN,ZS0808HD/ZS0608HD Battery Tray
13,1040201078,Nut M8,2,GB/T6170-2000,ZS0808HD/ZS0608HD Battery Tray
14,1020999049,Battery,4,NaN,ZS0808HD/ZS0608HD Battery Tray
15,00775602801601020,Threaded rod,1,NaN,ZS0808HD/ZS0608HD Battery Tray
16,00775602800601010,NaN,1,NaN,ZS0808HD/ZS0608HD Battery Tray
17,00775602800601030,Cushion rubber,1,NaN,ZS0808HD/ZS0608HD Battery Tray
18,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS0808HD/ZS0608HD Battery Tray
19,1040300054,Washer 12,1,GB/T93-1987,ZS0808HD/ZS0608HD Battery Tray
20,1040200503,Nut M8,3,GB/T889.1-2000,ZS0808HD/ZS0608HD Battery Tray
21,1040100886,Screw M8×20,1,GB/T70.1-2008,ZS0808HD/ZS0608HD Battery Tray
22,00775602801601050,Limit plate I,1,NaN,ZS0808HD/ZS0608HD Battery Tray
23,1040200506,Nut M6-8,8,GB/T889.1-2000,ZS0808HD/ZS0608HD Battery Tray
24,1040100237,Screw M6×30-8.8,6,GB/T70.1-2000,ZS0808HD/ZS0608HD Battery Tray
25,00775602801601060,Limit plate II,1,NaN,ZS0808HD/ZS0608HD Battery Tray
26,1040000288,Bolt M8×25-8.8,1,GB/T5783-2000,ZS0808HD/ZS0608HD Battery Tray
27,1020304978,Basin shaped horn,1,NaN,ZS0808HD/ZS0608HD Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
5,00775602801620000,Battery Tray box,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
6,00775602801601010,Coil III,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
7,1029907623,Vehicle-mounted battery charger,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
8,1040300060,Washer 5,2,GB/T93-1987,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
9,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
10,1020521277,Main power switch,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
11,1020999016,Battery,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
12,00775602800601030,Cushion rubber,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
13,00775602800601010,Limited post,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
14,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
15,1040300054,Washer 12,1,GB/T93-1987,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
16,1040003761,Bolt M6×25-8.8,4,GB/T5783-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
17,00775602820201070,Rubber Washer,4,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
18,00775602820201080,Counterweight,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
19,1040100886,Screw M8×20,1,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040200503,Nut M8,1,GB/T889.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
1,1040300066,Washer 8,1,GB/T97.1-2002,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
2,1040200506,Nut M6-8,4,GB/T889.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
3,1040100237,Screw M6×30-8.8,4,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
4,00775602820201010,Transparent plate,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
5,1020304982,Buzzer,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
6,1020304978,Basin shaped horn,1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
7,1040100620,Screw M6×16,4,GB/T818-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
8,1020300083,Common relay \n (ZS0808/0608DC-Li),1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
9,1020305334,Common relay \n (ZS0808HA-Li/AC-Li),1,NaN,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
10,1040201605,Nut M4-8,1,GB/T889.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray
11,1040102716,Screw M4×35,1,GB/T70.1-2000,ZS0808/ZS0608DC(HA/AC)-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0808/ZS0608HD-Li Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS0808/ZS0608HD-Li Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS0808/ZS0608HD-Li Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
5,00775602801620000,Battery Tray box,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
6,00775602801601010,Coil.III,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
7,1029907623,Vehicle-mounted battery \ncharger,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
8,1040300060,Washer 5,2,GB/T93-1987,ZS0808/ZS0608HD-Li Battery Tray
9,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0808/ZS0608HD-Li Battery Tray
10,1020521277,Main power switch,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
11,1020999016,Battery,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
12,00775602800601030,Cushion rubber,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
13,00775602800601010,Limited post,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
14,1040100519,Screw M12×80-8.8,1,GB/T70.1-2000,ZS0808/ZS0608HD-Li Battery Tray
15,1040300054,Washer 12,1,GB/T93-1987,ZS0808/ZS0608HD-Li Battery Tray
16,1040003761,Bolt M6×25-8.8,4,GB/T5783-2000,ZS0808/ZS0608HD-Li Battery Tray
17,00775602820201070,Rubber Washer,4,NaN,ZS0808/ZS0608HD-Li Battery Tray
18,00775602820201080,Counterweight,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
19,1040100886,Screw M8×20,1,GB/T70.1-2000,ZS0808/ZS0608HD-Li Battery Tray
20,1040200503,Nut M8,1,GB/T889.1-2000,ZS0808/ZS0608HD-Li Battery Tray
21,1040300066,Washer 8,1,GB/T97.1-2002,ZS0808/ZS0608HD-Li Battery Tray
22,00775602820201010,Transparent plate,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
23,1020304978,Basin shaped horn,1,NaN,ZS0808/ZS0608HD-Li Battery Tray
24,1040100620,Screw M6×16,4,GB/T818-2000,ZS0808/ZS0608HD-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
1,1040300062,Washer 6,8,GB/T93-1987,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
2,1040300051,Washer 6,8,GB/T97.1-2002,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
5,00775302830410000,Battery Tray box,1,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
6,007753028B2010000,Battery Tray box (ZS0607DCS),1,2022.10 Revise,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
7,1020300083,Common relay \n(ZS0607HD/DC/ DCS),1,2022.10 Revise,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
8,1020305334,Common relay \n(ZS0607HA/AC/ACW),1,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
9,1040102716,Screw M4×35,1,GB/T70.1-2000,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
10,1040201078,Nut M8,2,GB/T6170-2000,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
11,1040300230,Washer 8,2,GB/T97.1-2002,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
12,00775402801001010,Threaded rod,1,GB/T5783-2000,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
13,1020999018,Battery,4,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
14,1020999151,Battery (ZS0607DCS),2,2022.10 Revise,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
15,1020521277,Main power switch,1,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
16,1020304982,Buzzer,1,NaN,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
17,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray
18,1040200506,Nut M6-8,4,GB/T889.1-2000,ZS0607HD(DC/HA/AC/ACW/DCS) Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040000076,Bolt M6×25-8.8,2,GB/T5783-2000,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
1,1040300062,Washer 6,4,GB/T93-1987,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
2,1040300051,Washer 6,4,GB/T97.1-2002,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
3,1109900766,Battery door lock,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
4,00775602801601040,Protecting bush II,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
5,00775302821010000,Battery Tray box,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
6,1020300083,Common relay \n (ZS0607HD-Li/DC-Li),1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
7,1020305334,Common relay \n (ZS0607HA-Li/AC-Li/ACW-Li),1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
8,1040102716,Screw M4×35,1,GB/T70.1-2000,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
9,1040201078,Nut M8,2,GB/T6170-2000,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
10,1040300230,Washer 8,2,GB/T97.1-2002,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
11,00775402801001010,Threaded rod,1,GB/T5783-2000,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
12,1020999016,Battery,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
13,00775602820201030,Rubber Washer,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
14,00775302821020000,Counterweight,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
15,1020521277,Main power switch,1,NaN,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
16,1029805610,Buzzer,1,1020304982,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
17,1040100055,Screw M6×20-8.8,2,GB/T70.1-2000,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray
18,1040200506,Nut M6-8,4,GB/T889.1-2000,ZS0607HD(DC/HA/AC/ACW)-Li Battery Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1040201078,Nut M8,2,GB/T6170-2000,ZS0407DC Tray
1,1040300063,Washer 8,1,GB/T93-1987,ZS0407DC Tray
2,1040300066,Washer 8-200HV,1,GB/T97.1-2002,ZS0407DC Tray
3,00775202800801040,Plate,1,NaN,ZS0407DC Tray
4,00775202800801050,Cushion rubber,1,NaN,ZS0407DC Tray
5,00775202800831010,Screw post,1,NaN,ZS0407DC Tray
6,1020903382,Battery,2,NaN,ZS0407DC Tray
7,1010002079,Power unit,1,NaN,ZS0407DC Tray
8,1040100097,Screw M10×30-8.8,4,NaN,ZS0407DC Tray
9,00775202800810000,Tray box,1,NaN,ZS0407DC Tray
10,00775202800801020,T-plate Ⅱ,1,NaN,ZS0407DC Tray
11,1040300067,Washer 10,2,GB/T93-1987,ZS0407DC Tray
12,1020605226,Continuous-flow protector,1,NaN,ZS0407DC Tray
13,1040300051,Washer 6-200HV,18,GB/T97.1-2002,ZS0407DC Tray
14,1040300062,Washer 6,16,GB/T93-1987,ZS0407DC Tray
15,1040100055,Screw M6×20-8.8,10,GB/T70.1-2000,ZS0407DC Tray
16,1020300083,Common relay,1,NaN,ZS0407DC Tray
17,00775202800821010,Installation pad,1,NaN,ZS0407DC Tray
18,1020604246,Fuse holder,1,NaN,ZS0407DC Tray
19,1040102341,Screw M8×12-8.8,2,GB/T70.1-2000,ZS0407DC Tray
20,1040300048,Washer 5-200HV,4,GB/T97.1-2002,ZS0407DC Tray
21,1040300060,Washer 5,2,GB/T93-1987,ZS0407DC Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1020005354,Motor driver,1,NaN,ZS0407DC Tray
1,1020304603,DC contractor,1,NaN,ZS0407DC Tray
2,1029907625,Vehicle-mounted battery charger,1,NaN,ZS0407DC Tray
3,1040100619,Screw M5×10,2,GB/T818-2000,ZS0407DC Tray
4,1040100617,Screw M4×10-8.8,2,GB/T818-2000,ZS0407DC Tray
5,1040300044,Washer 4,6,GB/T93-1987,ZS0407DC Tray
6,1040301697,Washer 4-160HV,6,GB/T97.1-2002,ZS0407DC Tray
7,1040102168,Screw M4×10,4,GB/T70-1985,ZS0407DC Tray
8,00775602801601010,Coil Ⅲ,1,NaN,ZS0407DC Tray
9,1040300060,Washer 5,2,GB/T93-1987,ZS0407DC Tray
10,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0407DC Tray
11,1020521277,Main power switch,1,NaN,ZS0407DC Tray
12,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0407DC Tray
13,1020104088,Ground control assembly,1,NaN,ZS0407DC Tray
14,1020521389,Key switch,1,NaN,ZS0407DC Tray
15,1020304979,Breaker,1,NaN,ZS0407DC Tray
16,1020502039,Emergency stop button,1,NaN,ZS0407DC Tray
17,1040101212,Screw M6×20-8.8,8,GB/T818-2000,ZS0407DC Tray
18,1101000131,Panel lock,2,NaN,ZS0407DC Tray
19,1040200506,Nut,8,GB/T889.1-2000,ZS0407DC Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1020999015,Battery,1,NaN,ZS0407DC-Li Tray
1,1010002218,Power unit,1,NaN,ZS0407DC-Li Tray
2,1040100097,Screw M10×30-8.8,4,NaN,ZS0407DC-Li Tray
3,00775202810410000,Tray box,1,NaN,ZS0407DC-Li Tray
4,00775202800801020,T-plate II,1,NaN,ZS0407DC-Li Tray
5,1040300067,Washer 10,2,GB/T93-1987,ZS0407DC-Li Tray
6,1020605226,Continuous-flow protector,1,NaN,ZS0407DC-Li Tray
7,1020300083,Common relay,1,NaN,ZS0407DC-Li Tray
8,1040300051,Washer 6-200HV,18,GB/T97.1-2002,ZS0407DC-Li Tray
9,1040300062,Washer 6,16,GB/T93-1987,ZS0407DC-Li Tray
10,1040100055,Screw M6×20-8.8,10,GB/T70.1-2000,ZS0407DC-Li Tray
11,00775202810421010,Installation pad,1,NaN,ZS0407DC-Li Tray
12,1020604246,Fuse holder,1,NaN,ZS0407DC-Li Tray
13,1040102341,Cross Recess Head Screw \nM5×14-8.8,2,NaN,ZS0407DC-Li Tray
14,1040300048,Washer 5-200HV,4,GB/T97.1-2002,ZS0407DC-Li Tray
15,1040300060,Washer 5,2,GB/T93-1987,ZS0407DC-Li Tray
16,1020005354,Motor driver,1,NaN,ZS0407DC-Li Tray
17,1020304603,DC contractor,1,NaN,ZS0407DC-Li Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1029907626,Vehicle-mounted battery charger,1,NaN,ZS0407DC-Li Tray
1,1040100619,Screw M5×10,2,GB/T818-2000,ZS0407DC-Li Tray
2,1040100617,Screw M4×10-8.8,2,GB/T818-2000,ZS0407DC-Li Tray
3,1040300044,Washer 4,6,GB/T93-1987,ZS0407DC-Li Tray
4,1040301697,Washer 4-160HV,6,GB/T97.1-2002,ZS0407DC-Li Tray
5,1040102168,Screw M4×10,4,GB/T70-1985,ZS0407DC-Li Tray
6,00775602801601010,Coil III,1,NaN,ZS0407DC-Li Tray
7,1040300060,Washer 5,2,GB/T93-1987,ZS0407DC-Li Tray
8,1040102341,Screw M5×12-8.8,2,GB/T70.1-2000,ZS0407DC-Li Tray
9,1020521277,Main power switch,1,NaN,ZS0407DC-Li Tray
10,1029804041,Screw M4×25-4.8,2,GB/T70.1-2000,ZS0407DC-Li Tray
11,1020104088,Ground control assembly,1,NaN,ZS0407DC-Li Tray
12,1020521389,Key switch,1,NaN,ZS0407DC-Li Tray
13,1020304979,Breaker,1,NaN,ZS0407DC-Li Tray
14,1020502039,Emergency stop button,1,NaN,ZS0407DC-Li Tray
15,1040101212,Screw M6×20-8.8,8,GB/T818-2000,ZS0407DC-Li Tray
16,1101000131,Panel lock,2,NaN,ZS0407DC-Li Tray
17,1040200506,Nut,8,GB/T889.1-2000,ZS0407DC-Li Tray

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush \n44×38×30,36,NaN,ZS1414 Series Scissor Arm Pin
1,00775600300001140,Gasket,20,NaN,ZS1414 Series Scissor Arm Pin
2,00775700300400000,Internal scissor arm I,1,NaN,ZS1414 Series Scissor Arm Pin
3,00775700300200000,External scissor arm I,1,NaN,ZS1414 Series Scissor Arm Pin
4,00775700301000000,Internal scissor arm II,1,NaN,ZS1414 Series Scissor Arm Pin
5,00775700300600000,External scissor arm II,4,NaN,ZS1414 Series Scissor Arm Pin
6,00775700301200000,Internal scissor arm III,1,NaN,ZS1414 Series Scissor Arm Pin
7,00775700301400000,Internal scissor arm IV,1,NaN,ZS1414 Series Scissor Arm Pin
8,00775700301600000,Internal scissor arm V,1,NaN,ZS1414 Series Scissor Arm Pin
9,00775700301800000,Internal scissor arm VI,1,NaN,ZS1414 Series Scissor Arm Pin
10,00775700302000000,External scissor arm VI,1,NaN,ZS1414 Series Scissor Arm Pin
11,00775700300001020,End pipe trunking II,3,NaN,ZS1414 Series Scissor Arm Pin
12,1054400309,Composite bush \n44×38×50,4,NaN,ZS1414 Series Scissor Arm Pin
13,00775700302200000,External scissor armVII,1,NaN,ZS1414 Series Scissor Arm Pin
14,00775700300800000,External scissor arm III,3,NaN,ZS1414 Series Scissor Arm Pin
15,00775700300001010,End pipe trunking I,3,NaN,ZS1414 Series Scissor Arm Pin
16,00775600300001100,Nylon cover II,18,NaN,ZS1414 Series Scissor Arm Pin
17,1990201051,Clamp φ60-φ80,9,NaN,ZS1414 Series Scissor Arm Pin
18,1040200504,Nut M10-8,20,GB/T889.1-2000,ZS1414 Series Scissor Arm Pin
19,1040000025,Bolt M10×80-8.8,20,GB/T5782-2000,ZS1414 Series Scissor Arm Pin
20,00775700300001030,Axle I,12,NaN,ZS1414 Series Scissor Arm Pin
21,1040300984,Retaining ring 38,20,GB/T894.1-1986,ZS1414 Series Scissor Arm Pin
22,1054400311,Composite bush \n44×38×20,16,NaN,ZS1414 Series Scissor Arm Pin
23,00775600300001120,"Spacer, bearing",8,NaN,ZS1414 Series Scissor Arm Pin
24,00775600300001020,Axle II,8,NaN,ZS1414 Series Scissor Arm Pin
25,00775700300001040,Axle IV,4,NaN,ZS1414 Series Scissor Arm Pin
26,1040200503,Nut M8-8,4,GB/T889.1-2000,ZS1414 Series Scissor Arm Pin
27,00775600000001050,Articulated pin,4,NaN,ZS1414 Series Scissor Arm Pin
28,1040000689,Bolt M8×35-8.8,4,GB/T5782-2000,ZS1414 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush \n44×38×30,36,NaN,ZS1212 Series Scissor Arm Pin
1,00775600300001140,Gasket,20,NaN,ZS1212 Series Scissor Arm Pin
2,00775600300400000,Internal scissor arm I,1,NaN,ZS1212 Series Scissor Arm Pin
3,00775600300200000,External scissor arm I,1,NaN,ZS1212 Series Scissor Arm Pin
4,00775600301000000,Internal scissor arm II,1,NaN,ZS1212 Series Scissor Arm Pin
5,00775600300600000,External scissor arm II,4,NaN,ZS1212 Series Scissor Arm Pin
6,00775600301200000,Internal scissor arm III,1,NaN,ZS1212 Series Scissor Arm Pin
7,00775600301400000,Internal scissor arm IV,1,NaN,ZS1212 Series Scissor Arm Pin
8,00775600301800000,Internal scissor arm V,1,NaN,ZS1212 Series Scissor Arm Pin
9,00775600302200000,Internal scissor arm VI,1,NaN,ZS1212 Series Scissor Arm Pin
10,00775600302400000,External scissor arm VI,1,NaN,ZS1212 Series Scissor Arm Pin
11,00775600300001080,End pipe trunking II,3,NaN,ZS1212 Series Scissor Arm Pin
12,1054400309,Composite bush \n44×38×50,4,NaN,ZS1212 Series Scissor Arm Pin
13,00775600302800000,External scissor armVII,1,NaN,ZS1212 Series Scissor Arm Pin
14,00775600300800000,External scissor arm III,3,NaN,ZS1212 Series Scissor Arm Pin
15,00775600300001070,End pipe trunking I,3,NaN,ZS1212 Series Scissor Arm Pin
16,00775600300001100,Nylon cover II,18,NaN,ZS1212 Series Scissor Arm Pin
17,1990201051,Clamp φ60-φ80,9,NaN,ZS1212 Series Scissor Arm Pin
18,1040200504,Nut M10-8,20,GB/T889.1-2000,ZS1212 Series Scissor Arm Pin
19,1040000025,Bolt M10×80-8.8,20,GB/T5782-2000,ZS1212 Series Scissor Arm Pin
20,00775600300001010,Axle I,12,NaN,ZS1212 Series Scissor Arm Pin
21,1040300984,Retaining ring 38,20,GB/T894.1-1986,ZS1212 Series Scissor Arm Pin
22,1054400311,Composite bush \n44×38×20,16,NaN,ZS1212 Series Scissor Arm Pin
23,00775600300001120,"Spacer, bearing",8,NaN,ZS1212 Series Scissor Arm Pin
24,00775600300001020,Axle II,8,NaN,ZS1212 Series Scissor Arm Pin
25,00775600300001040,Axle IV,4,NaN,ZS1212 Series Scissor Arm Pin
26,1040200503,Nut M8-8,4,GB/T889.1-2000,ZS1212 Series Scissor Arm Pin
27,00775600000001050,Articulated pin,4,NaN,ZS1212 Series Scissor Arm Pin
28,1040000689,Bolt M8×35-8.8,4,GB/T5782-2000,ZS1212 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush \n44×38×30,22,NaN,ZS1012 Series Scissor Arm Pin
1,00775600300001140,Gasket,17,NaN,ZS1012 Series Scissor Arm Pin
2,00775600300400000,Internal scissor arm I,1,NaN,ZS1012 Series Scissor Arm Pin
3,00775600300200000,External scissor arm I,1,NaN,ZS1012 Series Scissor Arm Pin
4,00775600301000000,Internal scissor arm II,1,NaN,ZS1012 Series Scissor Arm Pin
5,00775600300600000,External scissor arm II,3,NaN,ZS1012 Series Scissor Arm Pin
6,00775600301200000,Internal scissor arm III,1,NaN,ZS1012 Series Scissor Arm Pin
7,00775600301400000,Internal scissor arm IV,1,NaN,ZS1012 Series Scissor Arm Pin
8,00775500300200000,Internal scissor arm V,1,NaN,ZS1012 Series Scissor Arm Pin
9,00775600302400000,External scissor arm VI,1,NaN,ZS1012 Series Scissor Arm Pin
10,1054400309,Composite bush \n44×38×50,4,NaN,ZS1012 Series Scissor Arm Pin
11,00775500300001010,End pipe trunking III,1,NaN,ZS1012 Series Scissor Arm Pin
12,00775600300001080,End pipe trunking II,1,NaN,ZS1012 Series Scissor Arm Pin
13,00775600300800000,External scissor arm III,3,NaN,ZS1012 Series Scissor Arm Pin
14,1040200504,Nut M10-8,16,GB/T889.1-2000,ZS1012 Series Scissor Arm Pin
15,00775600300001010,Axle I,9,NaN,ZS1012 Series Scissor Arm Pin
16,1040000025,Bolt M10×80-8.8,16,GB/T5782-2000,ZS1012 Series Scissor Arm Pin
17,00775600300001070,End pipe trunking I,3,NaN,ZS1012 Series Scissor Arm Pin
18,00775600300001100,Nylon cover II,14,NaN,ZS1012 Series Scissor Arm Pin
19,1990201051,Clamp,7,NaN,ZS1012 Series Scissor Arm Pin
20,1040300984,Retaining ring38,16,GB/T894.1-1986,ZS1012 Series Scissor Arm Pin
21,1054400311,Composite bush \n44×38×20,16,NaN,ZS1012 Series Scissor Arm Pin
22,00775600300001120,"Spacer, bearing",8,NaN,ZS1012 Series Scissor Arm Pin
23,00775600300001020,Axle II,8,NaN,ZS1012 Series Scissor Arm Pin
24,00775600300001040,Axle IV,4,NaN,ZS1012 Series Scissor Arm Pin
25,1040200503,Nut M8-8,4,GB/T889.1-2000,ZS1012 Series Scissor Arm Pin
26,00775600000001050,Articulated pin,4,NaN,ZS1012 Series Scissor Arm Pin
27,1040000689,Bolt M8×35-8.8,4,GB/T5782-2000,ZS1012 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush \n44×38×30,16,NaN,ZS0812 Series Scissor Arm Pin
1,00775600300001140,Gasket,13,NaN,ZS0812 Series Scissor Arm Pin
2,00775600300400000,Internal scissor arm I,1,NaN,ZS0812 Series Scissor Arm Pin
3,00775600300200000,External scissor arm I,1,NaN,ZS0812 Series Scissor Arm Pin
4,00775600301000000,Internal scissor arm II,1,NaN,ZS0812 Series Scissor Arm Pin
5,00775600300600000,External scissor arm II,2,NaN,ZS0812 Series Scissor Arm Pin
6,00775400330200000,Internal scissor arm III,1,NaN,ZS0812 Series Scissor Arm Pin
7,00775600302200000,Internal scissor arm VI,1,NaN,ZS0812 Series Scissor Arm Pin
8,00775600302400000,External scissor arm VI,1,NaN,ZS0812 Series Scissor Arm Pin
9,1054400309,Composite bush \n44×38×50,4,NaN,ZS0812 Series Scissor Arm Pin
10,00775600300001080,End pipe trunking II,2,NaN,ZS0812 Series Scissor Arm Pin
11,00775600302800000,External scissor armVII,1,NaN,ZS0812 Series Scissor Arm Pin
12,00775600300800000,External scissor arm III,1,NaN,ZS0812 Series Scissor Arm Pin
13,1054400311,Composite bush \n44×38×20,8,NaN,ZS0812 Series Scissor Arm Pin
14,00775600300001120,"Spacer, bearing",4,NaN,ZS0812 Series Scissor Arm Pin
15,1040200504,Nut M10-8,14,GB/T889.1-2000,ZS0812 Series Scissor Arm Pin
16,1040000025,Bolt M10×80-8.8,14,GB/T5782-2000,ZS0812 Series Scissor Arm Pin
17,00775600300001020,Axle II,4,NaN,ZS0812 Series Scissor Arm Pin
18,1040300984,Retaining ring38,12,GB/T894.1-1986,ZS0812 Series Scissor Arm Pin
19,00775600300001010,Axle I,8,NaN,ZS0812 Series Scissor Arm Pin
20,00775600300001070,End pipe trunking I,2,NaN,ZS0812 Series Scissor Arm Pin
21,00775600300001100,Nylon cover II,12,NaN,ZS0812 Series Scissor Arm Pin
22,1990201051,Clamp,6,NaN,ZS0812 Series Scissor Arm Pin
23,00775600300001040,Axle IV,2,NaN,ZS0812 Series Scissor Arm Pin
24,1040000689,Bolt M8×35-8.8,2,GB/T5782-2000,ZS0812 Series Scissor Arm Pin
25,00775600000001050,Articulated pin,2,NaN,ZS0812 Series Scissor Arm Pin
26,1040200503,Nut M8-8,4,GB/T889.1-2000,ZS0812 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,00775400300400000,Internal scissor arm I,1,NaN,ZS0808 Series Scissor Arm Pin
1,00775400300200000,External scissor arm I,1,NaN,ZS0808 Series Scissor Arm Pin
2,00775400300600000,Internal scissor arm II,1,NaN,ZS0808 Series Scissor Arm Pin
3,00775600300600000,External scissor arm II,2,NaN,ZS0808 Series Scissor Arm Pin
4,00775400301000000,Internal scissor arm III,1,NaN,ZS0808 Series Scissor Arm Pin
5,00775400301200000,Internal scissor arm IV,1,NaN,ZS0808 Series Scissor Arm Pin
6,00775400300800000,External scissor arm II,1,NaN,ZS0808 Series Scissor Arm Pin
7,00775600302800000,External scissor armVII,1,NaN,ZS0808 Series Scissor Arm Pin
8,00775600300800000,External scissor arm III,1,NaN,ZS0808 Series Scissor Arm Pin
9,1040200504,Nut M10-8,12,GB/T889.1-2000,ZS0808 Series Scissor Arm Pin
10,1040000025,Bolt M10×80-8.8,12,GB/T5782-2000,ZS0808 Series Scissor Arm Pin
11,00775600300001020,Axle II,4,NaN,ZS0808 Series Scissor Arm Pin
12,1054400311,Composite bush \n44×38×20,8,NaN,ZS0808 Series Scissor Arm Pin
13,00775600300001120,"Spacer, bearing",4,NaN,ZS0808 Series Scissor Arm Pin
14,00775600300001090,Gasket,10,NaN,ZS0808 Series Scissor Arm Pin
15,1040300984,Retaining ring 38,12,GB/T894.1-1986,ZS0808 Series Scissor Arm Pin
16,1054400310,Composite bush \n44×38×30,24,NaN,ZS0808 Series Scissor Arm Pin
17,00775400300001010,Axle I,8,NaN,ZS0808 Series Scissor Arm Pin
18,00775600300001080,End pipe trunking II,2,NaN,ZS0808 Series Scissor Arm Pin
19,1040000689,Bolt M8×35-8.8,2,GB/T5782-2000,ZS0808 Series Scissor Arm Pin
20,00775600000001050,Articulated pin,2,NaN,ZS0808 Series Scissor Arm Pin
21,1040200503,Nut M8-8,2,GB/T889.1-2000,ZS0808 Series Scissor Arm Pin
22,00775400300001020,Axle IV,2,NaN,ZS0808 Series Scissor Arm Pin
23,00775600300001070,End pipe trunking I,2,NaN,ZS0808 Series Scissor Arm Pin
24,1054400309,Composite bush \n44×38×50,4,NaN,ZS0808 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,1054400310,Composite bush \n44×38×30,18,NaN,ZS0608 Series Scissor Arm Pin
1,00775600300001140,Gasket,10,NaN,ZS0608 Series Scissor Arm Pin
2,00775400300400000,Internal scissor arm I,1,NaN,ZS0608 Series Scissor Arm Pin
3,00775400300200000,External scissor arm I,1,NaN,ZS0608 Series Scissor Arm Pin
4,00775400300600000,Internal scissor arm II,1,NaN,ZS0608 Series Scissor Arm Pin
5,00775600300600000,External scissor arm II,1,NaN,ZS0608 Series Scissor Arm Pin
6,00775300300200000,Internal scissor arm III,1,NaN,ZS0608 Series Scissor Arm Pin
7,00775300300400000,External scissor arm III,1,NaN,ZS0608 Series Scissor Arm Pin
8,1054400309,Composite \nbush44×38×50,4,NaN,ZS0608 Series Scissor Arm Pin
9,00775500300001010,End pipe trunking III,1,NaN,ZS0608 Series Scissor Arm Pin
10,00775600300800000,External scissor arm III,1,NaN,ZS0608 Series Scissor Arm Pin
11,00775400300001020,Axle II,2,NaN,ZS0608 Series Scissor Arm Pin
12,1040200503,NutM8-8,2,GB/T889.1-2000,ZS0608 Series Scissor Arm Pin
13,00775600000001050,Articulated pin,2,NaN,ZS0608 Series Scissor Arm Pin
14,1040000689,BoltM8×35-8.8,2,GB/T5782-2000,ZS0608 Series Scissor Arm Pin
15,1054400311,Composite bush \n44×38×20,8,NaN,ZS0608 Series Scissor Arm Pin
16,00775600300001120,"Spacer, bearing",4,NaN,ZS0608 Series Scissor Arm Pin
17,1040200504,Nut M10-8,11,GB/T889.1-2000,ZS0608 Series Scissor Arm Pin
18,1040000025,Bolt M10×80-8.8,11,GB/T5782-2000,ZS0608 Series Scissor Arm Pin
19,00775600300001020,Axle II,4,NaN,ZS0608 Series Scissor Arm Pin
20,1040300984,Retaining ring 38,9,GB/T894.1-1986,ZS0608 Series Scissor Arm Pin
21,00775400300001010,Axle I,5,NaN,ZS0608 Series Scissor Arm Pin
22,00775600300001070,End pipe trunking I,2,NaN,ZS0608 Series Scissor Arm Pin
23,00775600300001100,Nylon cover II,10,NaN,ZS0608 Series Scissor Arm Pin
24,1990201051,Clamp,5,NaN,ZS0608 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,00775300310400000,Internal scissor arm I,1.0,NaN,ZS0607 Series Scissor Arm Pin
1,00775300310200000,External scissor arm I,1.0,NaN,ZS0607 Series Scissor Arm Pin
2,00775300310600000,Internal scissor arm II,1.0,NaN,ZS0607 Series Scissor Arm Pin
3,00775300311200000,External scissor arm II,2.0,NaN,ZS0607 Series Scissor Arm Pin
4,00775300310800000,Internal scissor arm III,1.0,NaN,ZS0607 Series Scissor Arm Pin
5,00775300311000000,Internal scissor arm IV,1.0,NaN,ZS0607 Series Scissor Arm Pin
6,00775300311600000,External scissor arm IV,1.0,NaN,ZS0607 Series Scissor Arm Pin
7,00775300311800000,External scissor arm V,1.0,NaN,ZS0607 Series Scissor Arm Pin
8,00775300311400000,External scissor arm III,1.0,NaN,ZS0607 Series Scissor Arm Pin
9,1040000072,Bolt M10×65-8.8,12.0,GB/T5782-2000,ZS0607 Series Scissor Arm Pin
10,1040200504,Nut M10-8,12.0,GB/T889.1-2000,ZS0607 Series Scissor Arm Pin
11,00775300310001020,Axle II,4.0,NaN,ZS0607 Series Scissor Arm Pin
12,1054400337,Composite bush \n38×32×20,8.0,NaN,ZS0607 Series Scissor Arm Pin
13,00775300310001100,"Spacer, bearing",4.0,NaN,ZS0607 Series Scissor Arm Pin
14,00775300310001120,Gasket,10.0,NaN,ZS0607 Series Scissor Arm Pin
15,1040300153,Retaining ring 38,12.0,GB/T894.1-1986,ZS0607 Series Scissor Arm Pin
16,1054400336,Composite bush \n38×32×20,24.0,NaN,ZS0607 Series Scissor Arm Pin
17,00775300310001010,Axle I,8.0,NaN,ZS0607 Series Scissor Arm Pin
18,00775300310001070,End pipe trunking II,2.0,NaN,ZS0607 Series Scissor Arm Pin
19,1040000689,Bolt M8×35-8.8,NaN,NaN,ZS0607 Series Scissor Arm Pin
20,00775600000001050,Articulated pin,2.0,GB/T5782-2000,ZS0607 Series Scissor Arm Pin
21,00775300310001030,Axle III,2.0,NaN,ZS0607 Series Scissor Arm Pin
22,1040200503,Nut M8-8,2.0,GB/T889.1-2000,ZS0607 Series Scissor Arm Pin
23,00775300310001060,End pipe trunking I,2.0,NaN,ZS0607 Series Scissor Arm Pin
24,1054400338,Composite bush \n38×32×50,4.0,NaN,ZS0607 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,00775200310400000,Internal scissor arm I,1,NaN,ZS0407 Series Scissor Arm Pin
1,00775200310200000,External scissor arm I,1,NaN,ZS0407 Series Scissor Arm Pin
2,00775200310600000,Internal scissor arm II,1,NaN,ZS0407 Series Scissor Arm Pin
3,00775200311200000,External scissor arm II,2,NaN,ZS0407 Series Scissor Arm Pin
4,00775200310800000,Internal scissor arm III,1,NaN,ZS0407 Series Scissor Arm Pin
5,00775200311000000,Internal scissor arm IV,1,NaN,ZS0407 Series Scissor Arm Pin
6,00775200311600000,External scissor arm IV,1,NaN,ZS0407 Series Scissor Arm Pin
7,00775200311800000,External scissor arm V,1,NaN,ZS0407 Series Scissor Arm Pin
8,00775200311400000,External scissor arm III,1,NaN,ZS0407 Series Scissor Arm Pin
9,1040200503,Nut M8-8,13,GB/T889.1-2000,ZS0407 Series Scissor Arm Pin
10,1040000469,Bolt M8×55-8.8,11,GB/T5782-2000,ZS0407 Series Scissor Arm Pin
11,00775200310001020,Axle II,2,NaN,ZS0407 Series Scissor Arm Pin
12,1054400340,Composite bush \n30×25×20,4,NaN,ZS0407 Series Scissor Arm Pin
13,00775200310001060,"Spacer, bearing",2,NaN,ZS0407 Series Scissor Arm Pin
14,00775200310001100,Gasket,11,NaN,ZS0407 Series Scissor Arm Pin
15,1040300154,Retaining ring 25,11,GB/T894.1-1986,ZS0407 Series Scissor Arm Pin
16,1054400341,Composite bush \n30×25×30,26,NaN,ZS0407 Series Scissor Arm Pin
17,00775200310001010,Axle I,9,NaN,ZS0407 Series Scissor Arm Pin
18,00775200310001070,End pipe trunking,4,NaN,ZS0407 Series Scissor Arm Pin
19,1040000689,Bolt M8×35-8.8,2,GB/T5782-2000,ZS0407 Series Scissor Arm Pin
20,00775600000001050,Articulated pin,2,NaN,ZS0407 Series Scissor Arm Pin
21,00775200310001030,Axle III,2,NaN,ZS0407 Series Scissor Arm Pin
22,1054400342,Composite bush \n30×25×50,4,NaN,ZS0407 Series Scissor Arm Pin

,Material No.,Item and Spec,Units,Remark,Section
0,1010201559,Upper lift cylinder,1,NaN,ZS1414 Series Scissor Arm Accessory
1,1040102034,Screw M8×60-10.9,8,GB/T70.1-2000,ZS1414 Series Scissor Arm Accessory
2,1040300063,Washer 8,8,GB/T93-1987,ZS1414 Series Scissor Arm Accessory
3,1010306749,Cylinder control valve \n(ZS1414HD/ZS1414DC/ \...,1,NaN,ZS1414 Series Scissor Arm Accessory
4,1010306750,Cylinder control valve \n(ZS1414HD-Li/ZS1414D...,1,NaN,ZS1414 Series Scissor Arm Accessory
5,1040000126,Bolt M12×100-8.8,4,GB/T5782-2000,ZS1414 Series Scissor Arm Accessory
6,1040300526,Washer 12,8,GB/T97.1-2002,ZS1414 Series Scissor Arm Accessory
7,00775700302400000,Safety arm,2,NaN,ZS1414 Series Scissor Arm Accessory
8,1040200507,Nut M12-8,12,GB/T889.1-2000,ZS1414 Series Scissor Arm Accessory
9,1021403993,Pressure sensor,1,NaN,ZS1414 Series Scissor Arm Accessory
10,1010307396,Cylinder control valve,1,NaN,ZS1414 Series Scissor Arm Accessory
11,00775600000001030,Limit block \n(Indoor Series),2,NaN,ZS1414 Series Scissor Arm Accessory
12,00775600330001010,Limit block \n(Outdoor Series),2,2022.10 Revise,ZS1414 Series Scissor Arm Accessory
13,1040300051,Washer 6,6,GB/T97.1-2002,ZS1414 Series Scissor Arm Accessory
14,1040300062,Washer 6,6,GB/T93-1987,ZS1414 Series Scissor Arm Accessory
15,1040100620,Screw M6×16,6,GB/T818-2000,ZS1414 Series Scissor Arm Accessory
16,1010201560,Lower lift cylinder,1,NaN,ZS1414 Series Scissor Arm Accessory
17,1040000101,Bolt M12×40-8.8,8,GB/T5782-2000,ZS1414 Series Scissor Arm Accessory
18,00775600302600000,Pressing plate,2,NaN,ZS1414 Series Scissor Arm Accessory
19,00775600300001110,Plastic pad,40,NaN,ZS1414 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,1010201628,Upper lift cylinder,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
1,1040102034,Screw M8×60-10.9,8,GB/T70.1-2000,ZS1212/ZS1012 Series Scissor Arm Accessory
2,1040300063,Washer 8,8,GB/T93-1987,ZS1212/ZS1012 Series Scissor Arm Accessory
3,1010306627,Cylinder control valve \n(ZS1212HD/ZS1212DC/ \...,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
4,1010306625,Cylinder control valve \n(ZS1212HD-Li/ZS1212D...,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
5,1010306629,Cylinder control valve \n(ZS1012HD/ZS1012DC/ \...,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
6,1010306626,Cylinder control valve \n(ZS1012HD-Li/ZS1012D...,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
7,1040000126,Bolt M12×100-8.8,4,GB/T5782-2000,ZS1212/ZS1012 Series Scissor Arm Accessory
8,1040300526,Washer 12,8,GB/T97.1-2002,ZS1212/ZS1012 Series Scissor Arm Accessory
9,00775700302400000,Safety arm,2,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
10,1040200507,Nut M12-8,12,GB/T889.1-2000,ZS1212/ZS1012 Series Scissor Arm Accessory
11,1021403993,Pressure sensor,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
12,1010307396,Cylinder control valve,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
13,00775600000001030,Limit block \n(Indoor Series),2,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
14,00775600330001010,Limit block \n(Outdoor Series),2,2022.10 Revise,ZS1212/ZS1012 Series Scissor Arm Accessory
15,1040300051,Washer 6-200HV,6,GB/T97.1-2002,ZS1212/ZS1012 Series Scissor Arm Accessory
16,1040300062,Washer 6,6,GB/T93-1987,ZS1212/ZS1012 Series Scissor Arm Accessory
17,1040100620,Screw M6×16,6,GB/T818-2000,ZS1212/ZS1012 Series Scissor Arm Accessory
18,1010201629,Lower lift cylinder,1,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
19,1040000101,Bolt M12×40-8.8,8,GB/T5782-2000,ZS1212/ZS1012 Series Scissor Arm Accessory
20,00775600302600000,Pressing plate,2,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
21,00775600300001110,Plastic pad(ZS1212series),40,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory
22,00775600300001110,Plastic pad(ZS1012series),32,NaN,ZS1212/ZS1012 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,1010201629,Lower lift cylinder,1,NaN,ZS0812 Series Scissor Arm Accessory
1,1040102034,Screw M8×60-10.9,8,GB/T70.1-2000,ZS0812 Series Scissor Arm Accessory
2,1021403993,Pressure sensor,1,NaN,ZS0812 Series Scissor Arm Accessory
3,1040300063,Washer 8,8,GB/T93-1987,ZS0812 Series Scissor Arm Accessory
4,1010307396,Cylinder control valve,1,NaN,ZS0812 Series Scissor Arm Accessory
5,1040000126,Bolt M12×100-8.8,2,GB/T5782-2000,ZS0812 Series Scissor Arm Accessory
6,1040300526,Washer 12,4,GB/T97.1-2002,ZS0812 Series Scissor Arm Accessory
7,00775700302400000,Safety arm,2,NaN,ZS0812 Series Scissor Arm Accessory
8,1040200507,Nut M12-8,2,GB/T889.1-2000,ZS0812 Series Scissor Arm Accessory
9,00775600000001030,Limit block,2,NaN,ZS0812 Series Scissor Arm Accessory
10,1040300051,Washer 6-200HV,4,GB/T97.1-2002,ZS0812 Series Scissor Arm Accessory
11,1040300062,Washer 6,4,GB/T93-1987,ZS0812 Series Scissor Arm Accessory
12,1040100620,Screw M6×16,4,GB/T818-2000,ZS0812 Series Scissor Arm Accessory
13,1040000101,Bolt M12×40-8.8,8,GB/T5782-2000,ZS0812 Series Scissor Arm Accessory
14,1040300526,Washer 12,8,GB/T97.1-2002,ZS0812 Series Scissor Arm Accessory
15,00775600300001110,Plastic pad,24,NaN,ZS0812 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,1990201051,Clamp φ60-φ80,6,NaN,ZS0808 Series Scissor Arm Accessory
1,00775600300001100,Nylon cover II,12,NaN,ZS0808 Series Scissor Arm Accessory
2,00775600300001080,End pipe trunking II,2,NaN,ZS0808 Series Scissor Arm Accessory
3,1089900652,Sealing strip 16×3,6,NaN,ZS0808 Series Scissor Arm Accessory
4,1040000126,Bolt M12×100-8.8,2,GB/T5782-2000,ZS0808 Series Scissor Arm Accessory
5,00775700302400000,Safety arm,1,NaN,ZS0808 Series Scissor Arm Accessory
6,1040300526,Washer 12,4,GB/T97.1-2002,ZS0808 Series Scissor Arm Accessory
7,1040200507,Nut M12-8,2,GB/T889.1-2000,ZS0808 Series Scissor Arm Accessory
8,1054400310,Composite bush 38×44×30,4,NaN,ZS0808 Series Scissor Arm Accessory
9,1010201627,Lift cylinder,1,NaN,ZS0808 Series Scissor Arm Accessory
10,1040300051,Washer 6,4,GB/T97.1-2002,ZS0808 Series Scissor Arm Accessory
11,1040300062,Washer 6,4,GB/T93-1987,ZS0808 Series Scissor Arm Accessory
12,1040100620,Screw M6×16-8.8,4,GB/T818-2000,ZS0808 Series Scissor Arm Accessory
13,00775600000001030,Limit block \n(Indoor Series),2,NaN,ZS0808 Series Scissor Arm Accessory
14,00775600330001010,Limit block \n(Outdoor Series),2,2022.10 Revise,ZS0808 Series Scissor Arm Accessory
15,1040102034,Screw M8×60-10.9,4,GB/T70.1-2000,ZS0808 Series Scissor Arm Accessory
16,1040300063,Washer 8,4,GB/T93-1987,ZS0808 Series Scissor Arm Accessory
17,1010307396,Cylinder control valve,1,NaN,ZS0808 Series Scissor Arm Accessory
18,1021403993,Pressure sensor,1,NaN,ZS0808 Series Scissor Arm Accessory
19,00775600300001110,Plastic pad,24,NaN,ZS0808 Series Scissor Arm Accessory
20,00775600300001070,End pipe trunking I,2,NaN,ZS0808 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,1990201051,Clamp φ60-φ80,5,NaN,ZS0608 Series Scissor Arm Accessory
1,00775600300001100,Nylon cover II,10,NaN,ZS0608 Series Scissor Arm Accessory
2,00775500300001010,End pipe trunking III,1,NaN,ZS0608 Series Scissor Arm Accessory
3,1089900652,Sealing strip 16×3,6,NaN,ZS0608 Series Scissor Arm Accessory
4,1040000126,Bolt M12×100-8.8,2,GB/T5782-2000,ZS0608 Series Scissor Arm Accessory
5,00775700302400000,Safety arm,1,NaN,ZS0608 Series Scissor Arm Accessory
6,1040300526,Washer 12,4,GB/T97.1-2002,ZS0608 Series Scissor Arm Accessory
7,1040200507,Nut M12-8,2,GB/T889.1-2000,ZS0608 Series Scissor Arm Accessory
8,1054400310,Composite bush 38×44×30,4,NaN,ZS0608 Series Scissor Arm Accessory
9,1010201627,Lift cylinder,1,NaN,ZS0608 Series Scissor Arm Accessory
10,1040300051,Washer 6,4,GB/T97.1-2002,ZS0608 Series Scissor Arm Accessory
11,1040300062,Washer 6,4,GB/T93-1987,ZS0608 Series Scissor Arm Accessory
12,1040100620,Screw M6×16-8.8,4,GB/T818-2000,ZS0608 Series Scissor Arm Accessory
13,00775600000001030,Limit block,2,NaN,ZS0608 Series Scissor Arm Accessory
14,1040102034,Screw M8×60-10.9,4,GB/T70.1-2000,ZS0608 Series Scissor Arm Accessory
15,1040300063,Washer 8,4,GB/T93-1987,ZS0608 Series Scissor Arm Accessory
16,1010307396,Cylinder control valve,1,NaN,ZS0608 Series Scissor Arm Accessory
17,1021403993,Pressure sensor,1,NaN,ZS0608 Series Scissor Arm Accessory
18,00775600300001110,Plastic pad,24,NaN,ZS0608 Series Scissor Arm Accessory
19,00775600300001070,End pipe trunking I,2,NaN,ZS0608 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,1990201051,Clamp φ60-φ80,6,NaN,ZS0607 Series Scissor Arm Accessory
1,00775300310001090,Nylon cover II,12,NaN,ZS0607 Series Scissor Arm Accessory
2,00775300310001070,End pipe trunking II,2,NaN,ZS0607 Series Scissor Arm Accessory
3,1089900652,Sealing strip 16×3,6,NaN,ZS0607 Series Scissor Arm Accessory
4,1040000025,Bolt M10×80-8.8,2,GB/T5782-2000,ZS0607 Series Scissor Arm Accessory
5,00775300342000000,Safety arm,1,NaN,ZS0607 Series Scissor Arm Accessory
6,1040300061,Washer 10,4,GB/T97.1-2002,ZS0607 Series Scissor Arm Accessory
7,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS0607 Series Scissor Arm Accessory
8,1054400336,Composite bush 38×32×30,4,NaN,ZS0607 Series Scissor Arm Accessory
9,1010201474,Lift cylinder,1,NaN,ZS0607 Series Scissor Arm Accessory
10,1040300051,Washer 6,4,GB/T97.1-2002,ZS0607 Series Scissor Arm Accessory
11,1040300062,Washer 6,4,GB/T93-1987,ZS0607 Series Scissor Arm Accessory
12,1040100620,Screw M6×16-8.8,4,GB/T818-2000,ZS0607 Series Scissor Arm Accessory
13,00775300000011070,Limit block \n(Indoor Series),2,NaN,ZS0607 Series Scissor Arm Accessory
14,00775300360001010,Limit block \n(Outdoor Series),2,2022.10 Revise,ZS0607 Series Scissor Arm Accessory
15,1040102034,Screw M8×60-10.9,4,GB/T70.1-2000,ZS0607 Series Scissor Arm Accessory
16,1040300063,Washer 8,4,GB/T93-1987,ZS0607 Series Scissor Arm Accessory
17,1010308649,Cylinder control valve,1,NaN,ZS0607 Series Scissor Arm Accessory
18,1021403993,Pressure sensor,1,NaN,ZS0607 Series Scissor Arm Accessory
19,00775600300001110,Plastic pad,24,NaN,ZS0607 Series Scissor Arm Accessory
20,00775300310001060,End pipe trunking I,2,NaN,ZS0607 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,00775200310001090,Nylon cover II,16,NaN,ZS0407 Series Scissor Arm Accessory
1,1990202404,Clamp φ40-φ60,8,NaN,ZS0407 Series Scissor Arm Accessory
2,1040000025,Bolt M10×80-8.8,2,GB/T5782-2000,ZS0407 Series Scissor Arm Accessory
3,1040300061,Washer 10,4,GB/T97.1-2002,ZS0407 Series Scissor Arm Accessory
4,00775200312000000,Safety arm,1,NaN,ZS0407 Series Scissor Arm Accessory
5,1040200504,Nut M10-8,2,GB/T889.1-2000,ZS0407 Series Scissor Arm Accessory
6,1010308648,Cylinder control valve,1,NaN,ZS0407 Series Scissor Arm Accessory
7,1040300063,Washer 8,4,GB/T93-1987,ZS0407 Series Scissor Arm Accessory
8,1040102034,Screw M8×60-10.9,4,GB/T70.1-2000,ZS0407 Series Scissor Arm Accessory
9,1054400341,Composite bush,4,NaN,ZS0407 Series Scissor Arm Accessory
10,1010201561,Lower lift cylinder,1,NaN,ZS0407 Series Scissor Arm Accessory
11,00775600300001110,Plastic pad,24,NaN,ZS0407 Series Scissor Arm Accessory
12,1021403993,Pressure sensor,1,NaN,ZS0407 Series Scissor Arm Accessory

,Material No.,Item and Spec,Units,Remark,Section
0,00775700102800000,Lower components,1,NaN,ZS1414 Series Platform Installation
1,1040000156,Bolt M8×60,6,GB/T5783-2000,ZS1414 Series Platform Installation
2,1040300066,Washer 8,12,GB/T97.1-2002,ZS1414 Series Platform Installation
3,1040200503,Nut M8-8,6,GB/T889.1-2000,ZS1414 Series Platform Installation
4,1040101640,Screw M3×10-A2-70,2,GB/T818-2000,ZS1414 Series Platform Installation
5,1040201166,Nut M3-A2-70,4,GB/T6170-200,ZS1414 Series Platform Installation
6,00775700100600000,Guard rails II,1,NaN,ZS1414 Series Platform Installation
7,1040200867,Nut M5,6,GB/T889.1-2000,ZS1414 Series Platform Installation
8,00775606300801010,Power mounting plate,1,NaN,ZS1414 Series Platform Installation
9,1040102341,Screw M5×12-8.8,6,GB/T70.1-2000,ZS1414 Series Platform Installation
10,00775706601010000,Platform AC assembly,1,NaN,ZS1414 Series Platform Installation
11,1100400025,D Pin 6.3×55,2,NaN,ZS1414 Series Platform Installation
12,00775600102000000,Guard rails III,1,NaN,ZS1414 Series Platform Installation
13,00775700100400000,Guard rails I,1,NaN,ZS1414 Series Platform Installation
14,1101000163,Spring hinge,2,NaN,ZS1414 Series Platform Installation
15,00775600101800000,Platform gate,1,NaN,ZS1414 Series Platform Installation
16,1040200506,Nut M6-8,12,GB/T889.1-2000,ZS1414 Series Platform Installation
17,1040300051,Washer 6,24,GB/T97.1-2002,ZS1414 Series Platform Installation
18,1040001185,Bolt M6×55-8.8,12,GB/T5783-2000,ZS1414 Series Platform Installation
19,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS1414 Series Platform Installation
20,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS1414 Series Platform Installation
21,00775600100001020,Gasket I,2,NaN,ZS1414 Series Platform Installation
22,00775600102200000,Mounting pulley assembly,2,NaN,ZS1414 Series Platform Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775600102800000,Lower components,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
1,1040000156,Bolt M8×60,6,GB/T5783-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
2,1040300066,Washer 8,12,GB/T97.1-2002,ZS1212/ZS1012/ZS0812 Series Platform Installation
3,1040200503,Nut M8-8,6,GB/T889.1-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
4,1040101640,Screw M3×10-A2-70,2,GB/T818-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
5,1040201166,Nut M3-A2-70,4,GB/T6170-200,ZS1212/ZS1012/ZS0812 Series Platform Installation
6,00775600101000000,Guard rails II,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
7,1040200867,Nut M5,6,GB/T889.1-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
8,00775606300801010,Power mounting plate,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
9,1040102341,Screw M5×12-8.8,6,GB/T70.1-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
10,00775606630400000,Platform AC assembly\n（ZS1212Series）,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
11,00775506630200000,Platform AC assembly\n（ZS1012Series）,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
12,007754065C0430010,Platform AC assembly\n（ZS0812Series）,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
13,1100400025,D Pin 6.3×55,2,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
14,00775600102000000,Guard rails III,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
15,00775600100400000,Guard rails I,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
16,1101000163,Spring hinge,2,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
17,00775600101800000,Platform gate,1,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
18,1040200506,Nut M6-8,12,GB/T889.1-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
19,1040300051,Washer 6,24,GB/T97.1-2002,ZS1212/ZS1012/ZS0812 Series Platform Installation
20,1040001185,Bolt M6×55-8.8,12,GB/T5783-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
21,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS1212/ZS1012/ZS0812 Series Platform Installation
22,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
23,00775600100001020,Gasket I,2,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation
24,00775600102200000,Mounting pulley assembly,2,NaN,ZS1212/ZS1012/ZS0812 Series Platform Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775400102800000,Lower components,1,NaN,ZS0808/ZS0608 Series Platform Installation
1,1040101640,Screw M3×10-A2-70,2,GB/T818-2000,ZS0808/ZS0608 Series Platform Installation
2,1040201166,Nut M3-A2-70,4,GB/T6170-2000,ZS0808/ZS0608 Series Platform Installation
3,1040000469,Bolt M6-8,12,GB/T889.1-2000,ZS0808/ZS0608 Series Platform Installation
4,1040300066,Washer 8,34,GB/T97.1-2002,ZS0808/ZS0608 Series Platform Installation
5,1040200503,Nut M8-8,16,GB/T889.1-2000,ZS0808/ZS0608 Series Platform Installation
6,00775400101600000,Cranked link,2,NaN,ZS0808/ZS0608 Series Platform Installation
7,1040000156,Bolt M8×60-8.8,6,GB/T5782-2000,ZS0808/ZS0608 Series Platform Installation
8,00775400100800000,Guard rails II,1,NaN,ZS0808/ZS0608 Series Platform Installation
9,1040200867,Nut M5,6,GB/T889.1-2000,ZS0808/ZS0608 Series Platform Installation
10,00775606300801010,Power mounting plate,1,NaN,ZS0808/ZS0608 Series Platform Installation
11,1040102341,Screw M5×12-8.8,6,GB/T70.1-2000,ZS0808/ZS0608 Series Platform Installation
12,00775406640200000,Platform AC assembly,1,NaN,ZS0808/ZS0608 Series Platform Installation
13,1100400025,D Pin 6.3×55,2,NaN,ZS0808/ZS0608 Series Platform Installation
14,00775400102400000,Guard rails mounting \nbase II,1,NaN,ZS0808/ZS0608 Series Platform Installation
15,00775400102200000,Guard rails III,1,NaN,ZS0808/ZS0608 Series Platform Installation
16,00775400100400000,Guard rails I,1,NaN,ZS0808/ZS0608 Series Platform Installation
17,00775600101800000,Platform gate,1,NaN,ZS0808/ZS0608 Series Platform Installation
18,1101000163,Spring hinge,2,NaN,ZS0808/ZS0608 Series Platform Installation
19,1040200506,Nut M6-8,12,GB/T889.1-2000,ZS0808/ZS0608 Series Platform Installation
20,1040300051,Washer 6,24,GB/T97.1-2002,ZS0808/ZS0608 Series Platform Installation
21,1040001185,Bolt M6×50-8.8,12,GB/T5783-2000,ZS0808/ZS0608 Series Platform Installation
22,00775400102000000,Guard rails mounting \nbase I,1,NaN,ZS0808/ZS0608 Series Platform Installation
23,00775600102200000,Mounting pulley assembly,2,NaN,ZS0808/ZS0608 Series Platform Installation
24,00775600100001020,Gasket I,2,NaN,ZS0808/ZS0608 Series Platform Installation
25,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS0808/ZS0608 Series Platform Installation
26,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS0808/ZS0608 Series Platform Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775300102800000,Lower components,1,NaN,ZS0607 Series Platform Installation
1,1040101640,Screw M3×10-A2-70,2,GB/T818-2000,ZS0607 Series Platform Installation
2,1040201166,Nut M3-A2-70,4,GB/T6170-2000,ZS0607 Series Platform Installation
3,1040000469,Bolt M6-8,12,GB/T889.1-2000,ZS0607 Series Platform Installation
4,1040300066,Washer 8,34,GB/T97.1-2002,ZS0607 Series Platform Installation
5,1040200503,Nut M8-8,16,GB/T889.1-2000,ZS0607 Series Platform Installation
6,00775300101000000,Guard rails II,1,NaN,ZS0607 Series Platform Installation
7,1040000156,Bolt M8×60-8.8,6,GB/T5782-2000,ZS0607 Series Platform Installation
8,00775300102400000,Guard rails IV,2,NaN,ZS0607 Series Platform Installation
9,1040200867,Nut M5,6,GB/T889.1-2000,ZS0607 Series Platform Installation
10,00775606300801010,Power mounting plate,1,NaN,ZS0607 Series Platform Installation
11,1040102341,Screw M5×12-8.8,6,GB/T70.1-2000,ZS0607 Series Platform Installation
12,00775306650200000,Platform AC assembly,1,NaN,ZS0607 Series Platform Installation
13,1100400025,D Pin 6.3×55,2,NaN,ZS0607 Series Platform Installation
14,00775300102000000,Guard rails III,1,NaN,ZS0607 Series Platform Installation
15,00775600101800000,Platform gate,1,NaN,ZS0607 Series Platform Installation
16,1101000163,Spring hinge,2,NaN,ZS0607 Series Platform Installation
17,1040200506,Nut M6-8,12,GB/T889.1-2000,ZS0607 Series Platform Installation
18,1040300051,Washer 6,24,GB/T97.1-2002,ZS0607 Series Platform Installation
19,1040001185,Bolt M6×50-8.8,12,GB/T5783-2000,ZS0607 Series Platform Installation
20,00775300100400000,Guard rails I,2,NaN,ZS0607 Series Platform Installation
21,00775600102200000,Mounting pulley assembly,2,NaN,ZS0607 Series Platform Installation
22,00775600100001020,Gasket I,2,NaN,ZS0607 Series Platform Installation
23,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS0607 Series Platform Installation
24,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS0607 Series Platform Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775200102800000,Lower components,1,NaN,ZS0407 Series Platform Installation
1,1040101640,Screw M3×10-A2-70,1,GB/T818-2000,ZS0407 Series Platform Installation
2,1040201166,Nut M3-A2-70,2,GB/T6170-2000,ZS0407 Series Platform Installation
3,00775200102400000,Guard rails IV,2,NaN,ZS0407 Series Platform Installation
4,1040200503,Nut M8-8,4,GB/T889.1-2000,ZS0407 Series Platform Installation
5,1040300066,Washer 8,10,GB/T97.1-2002,ZS0407 Series Platform Installation
6,1040000469,Bolt M8×55-8.8,6,GB/T5782-2000,ZS0407 Series Platform Installation
7,1040200867,Nut M5,6,GB/T889.1-2000,ZS0407 Series Platform Installation
8,1040102341,Screw M5×12-8.8,6,GB/T70.1-2000,ZS0407 Series Platform Installation
9,00775606300801010,Power mounting plate,1,NaN,ZS0407 Series Platform Installation
10,00775206650810000,Platform AC assembly,1,NaN,ZS0407 Series Platform Installation
11,1100400025,D Pin 6.3×55,2,NaN,ZS0407 Series Platform Installation
12,00775200100800000,Guard rails III,1,NaN,ZS0407 Series Platform Installation
13,1101000163,Spring hinge,2,NaN,ZS0407 Series Platform Installation
14,00775200101000000,Platform gate,1,NaN,ZS0407 Series Platform Installation
15,1040200506,Nut M6-8,12,GB/T889.1-2000,ZS0407 Series Platform Installation
16,1040300051,Washer 6,24,GB/T97.1-2002,ZS0407 Series Platform Installation
17,1040002803,Bolt M6×50-8.8,12,GB/T5782-2000,ZS0407 Series Platform Installation
18,00775600102200000,Mounting pulley \nassembly,2,NaN,ZS0407 Series Platform Installation
19,00775600100001020,Gasket I,2,NaN,ZS0407 Series Platform Installation
20,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS0407 Series Platform Installation
21,1040102718,Screw M8×50-8.8,8,GB/T70.3-2000,ZS0407 Series Platform Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775600101810000,Platform Gate Weldment,1,NaN,Platform Gate
1,00775200101010000,Platform Gate Weldment \n（ZS0407 Series only）,1,NaN,Platform Gate
2,00775600101801020,Spring,1,NaN,Platform Gate
3,00775600101801010,Key cylinder,1,NaN,Platform Gate
4,1040200503,Nut M8-8,1,GB/T889.1-2000,Platform Gate
5,1040300066,Washer 8,1,GB/T97.1-2002,Platform Gate
6,1040000469,Bolt M8×55,1,GB/T5783-2000,Platform Gate

,Material No.,Item and Spec,Units,Remark,Section
0,1040300082,Retaining ring 47,1,GB/T893.1-1986,Platform Pulley Installation
1,1050201257,Bearing 6204-2RS,1,GB/T276-1994,Platform Pulley Installation
2,00775600102201010,Platform mounting \npulley,1,NaN,Platform Pulley Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040000156,Bolt M8×60,6,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
1,1040300066,Washer 8,12,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
2,1040200503,Nut M8-8,6,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
3,00775600100600000,Guard rails I,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
4,00775600101400000,Guard rails III,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
5,1999904986,Storage box,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
6,1040102341,Screw M5×12-8.8,4,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
7,1040300048,Washer 5,4,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
8,1040200867,Nut M5,4,GB/T889.1-2000,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
9,00775600101200000,Guard rails II,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
10,1100400025,D Pin 6.3×55,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
11,00775600102600000,Pulley assembly,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
12,00775600100800000,Pedal,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
13,1040000114,Bolt M10×25,2,GB/T5783-2000,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
14,1040300067,Washer 10,2,GB/T93-1987,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
15,1040300061,Washer 10,2,GB/T97.1-2002,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
16,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
17,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
18,00775600100001020,Gasket I,2,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...
19,00775600101600000,Lower components,1,NaN,ZS1414/ZS1212/ZS1012/ZS0812 Series Extension D...

,Material No.,Item and Spec,Units,Remark,Section
0,1040000156,Bolt M8×60,14,GB/T5783-2000,ZS0808/ZS0608 Series Extension Deck Installation
1,1040300066,Washer 8,28,GB/T97.1-2002,ZS0808/ZS0608 Series Extension Deck Installation
2,1040200503,Nut M8-8,14,GB/T889.1-2000,ZS0808/ZS0608 Series Extension Deck Installation
3,00775400101800000,Lower components,1,NaN,ZS0808/ZS0608 Series Extension Deck Installation
4,00775400101400000,Cranked link,4,NaN,ZS0808/ZS0608 Series Extension Deck Installation
5,00775400100600000,Guard rails I,1,NaN,ZS0808/ZS0608 Series Extension Deck Installation
6,00775400101200000,Guard rails III,1,NaN,ZS0808/ZS0608 Series Extension Deck Installation
7,1999904986,Storage box,1,NaN,ZS0808/ZS0608 Series Extension Deck Installation
8,1040102341,Screw M5×12-8.8,4,GB/T70.1-2000,ZS0808/ZS0608 Series Extension Deck Installation
9,1040300048,Washer 5,4,GB/T97.1-2002,ZS0808/ZS0608 Series Extension Deck Installation
10,1040200867,Nut M5,4,GB/T889.1-2000,ZS0808/ZS0608 Series Extension Deck Installation
11,1100400025,D PIN 6.3×55,2,NaN,ZS0808/ZS0608 Series Extension Deck Installation
12,00775400101000000,Guard rails II,1,NaN,ZS0808/ZS0608 Series Extension Deck Installation
13,1040000114,Bolt M10×25,2,GB/T5783-2000,ZS0808/ZS0608 Series Extension Deck Installation
14,1040300067,Washer 10,2,GB/T93-1987,ZS0808/ZS0608 Series Extension Deck Installation
15,1040300061,Washer 10,2,GB/T97.1-2002,ZS0808/ZS0608 Series Extension Deck Installation
16,00775600100800000,Pedal,1,NaN,ZS0808/ZS0608 Series Extension Deck Installation
17,00775600102600000,Pulley assembly,2,NaN,ZS0808/ZS0608 Series Extension Deck Installation
18,00775600100001020,Gasket I,2,NaN,ZS0808/ZS0608 Series Extension Deck Installation
19,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS0808/ZS0608 Series Extension Deck Installation
20,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS0808/ZS0608 Series Extension Deck Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040000156,Bolt M8×60,14,GB/T5783-2000,ZS0607 Series Extension Deck Installation
1,1040300066,Washer 8,28,GB/T97.1-2002,ZS0607 Series Extension Deck Installation
2,1040200503,Nut M8-8,14,GB/T889.1-2000,ZS0607 Series Extension Deck Installation
3,00775300101600000,Lower components,1,NaN,ZS0607 Series Extension Deck Installation
4,00775300100600000,Guard rails I,2,NaN,ZS0607 Series Extension Deck Installation
5,00775300101400000,Guard rails IV,1,NaN,ZS0607 Series Extension Deck Installation
6,00775300100800000,Guard rails II,1,NaN,ZS0607 Series Extension Deck Installation
7,00775300101200000,Guard rails III,1,NaN,ZS0607 Series Extension Deck Installation
8,1999904986,Storage box,1,NaN,ZS0607 Series Extension Deck Installation
9,1040102341,Screw M5×12-8.8,4,GB/T70.1-2000,ZS0607 Series Extension Deck Installation
10,1040300048,Washer 5,4,GB/T97.1-2002,ZS0607 Series Extension Deck Installation
11,1040200867,Nut M5,4,GB/T889.1-2000,ZS0607 Series Extension Deck Installation
12,1100400025,D Pin 6.3×55,2,NaN,ZS0607 Series Extension Deck Installation
13,1040000114,Bolt M10×25,2,GB/T5783-2000,ZS0607 Series Extension Deck Installation
14,1040300067,Washer 10,2,GB/T93-1987,ZS0607 Series Extension Deck Installation
15,1040300061,Washer 10,2,GB/T97.1-2002,ZS0607 Series Extension Deck Installation
16,00775600100800000,Pedal,1,NaN,ZS0607 Series Extension Deck Installation
17,00775600102600000,Pulley assembly,2,NaN,ZS0607 Series Extension Deck Installation
18,00775600100001020,Gasket I,2,NaN,ZS0607 Series Extension Deck Installation
19,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS0607 Series Extension Deck Installation
20,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS0607 Series Extension Deck Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040000469,Bolt M8×55-8.8,6,GB/T5783-2000,ZS0407 Series Extension Deck Installation
1,1040300066,Washer 8,12,GB/T97.1-2002,ZS0407 Series Extension Deck Installation
2,1040200503,Nut M8-8,6,GB/T889.1-2000,ZS0407 Series Extension Deck Installation
3,00775200101200000,Lower components,1,NaN,ZS0407 Series Extension Deck Installation
4,00775200102200000,Guard rails III,1,NaN,ZS0407 Series Extension Deck Installation
5,00775200102000000,Guard rails I,1,NaN,ZS0407 Series Extension Deck Installation
6,00775200101800000,Guard rails II,1,NaN,ZS0407 Series Extension Deck Installation
7,1999904986,Storage box,1,NaN,ZS0407 Series Extension Deck Installation
8,1040102341,Screw M5×12-8.8,4,GB/T70.1-2000,ZS0407 Series Extension Deck Installation
9,1040300048,Washer 5,4,GB/T97.1-2002,ZS0407 Series Extension Deck Installation
10,1040200867,Nut M5,4,GB/T889.1-2000,ZS0407 Series Extension Deck Installation
11,1100400025,D Pin 6.3×55,2,NaN,ZS0407 Series Extension Deck Installation
12,1040000114,Bolt M10×25,2,GB/T5783-2000,ZS0407 Series Extension Deck Installation
13,1040300067,Washer 10,2,GB/T93-1987,ZS0407 Series Extension Deck Installation
14,1040300061,Washer 10,2,GB/T97.1-2002,ZS0407 Series Extension Deck Installation
15,00775600100800000,Pedal,1,NaN,ZS0407 Series Extension Deck Installation
16,00775600102600000,Pulley assembly,2,NaN,ZS0407 Series Extension Deck Installation
17,00775600100001020,Gasket I,2,NaN,ZS0407 Series Extension Deck Installation
18,1040102718,Screw M8×50,8,GB/T70.1-2000,ZS0407 Series Extension Deck Installation
19,00775600102400000,Platform pin mounting \nbase,2,NaN,ZS0407 Series Extension Deck Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1040500606,Pin B10×45,1,GB/T882-2008,Pedal Installation
1,1040500214,Split pin 3.2×40,1,GB/T91-2000,Pedal Installation
2,1040200504,Nut M10-8,1,GB/T889.1-2000,Pedal Installation
3,1040300061,Washer 10,1,GB/T97.1-2002,Pedal Installation
4,00775600100801020,Pedal,1,NaN,Pedal Installation
5,00775600100801040,Sleeve,1,NaN,Pedal Installation
6,00775600100801050,Plate,1,NaN,Pedal Installation
7,00775600100801030,Spring,1,NaN,Pedal Installation
8,00775600100801060,Bayonet lock,1,NaN,Pedal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1.0,NaN,ZS1414 Series Decal Installation
1,00775207010403010,Label- Safety Rules (Indoor Series),1.0,NaN,ZS1414 Series Decal Installation
2,00775307010402010,Label- Safety Rules(Outdoor Series),1.0,2022.10 Revise,ZS1414 Series Decal Installation
3,00775207010403070,Danger- Tip-over Hazard,1.0,NaN,ZS1414 Series Decal Installation
4,00775307080402030,Label- Read the Instructions Carefully,2.0,NaN,ZS1414 Series Decal Installation
5,00775307080202090,Label- Lanyard Anchorage Point,4.0,NaN,ZS1414 Series Decal Installation
6,00775707030201020,"Label- Capacity, 260kg (Indoor Series)",1.0,NaN,ZS1414 Series Decal Installation
7,00775507010201030,"Label- Capacity, 350kg(Outdoor Series)",NaN,2022.10 Revise,ZS1414 Series Decal Installation
8,00775307080202210,Label- Forklift Hole,2.0,NaN,ZS1414 Series Decal Installation
9,00775307080202010,Label- Lifting and tying,4.0,NaN,ZS1414 Series Decal Installation
10,00775307080402150,Label- Emergency Lowering,1.0,NaN,ZS1414 Series Decal Installation
11,00775307080401050,Label- AC Power to Platform,1.0,NaN,ZS1414 Series Decal Installation
12,00775607010401030,"Label- Wheels Load, 1280kg",4.0,NaN,ZS1414 Series Decal Installation
13,00775307080402110,Instruction- Main Power Switch Operation,1.0,NaN,ZS1414 Series Decal Installation
14,00775307080402060,Danger- Explosion and Fire Hazard,1.0,NaN,ZS1414 Series Decal Installation
15,00775307040401040,Danger- Crushing Hazard,5.0,NaN,ZS1414 Series Decal Installation
16,00775307040401050,Label- Safety Arm,4.0,NaN,ZS1414 Series Decal Installation
17,00775307080402170,Label- Max Manual Force (Indoor Series),1.0,NaN,ZS1414 Series Decal Installation
18,00775307010402030,Label- Max Manual Force(Outdoor Series),1.0,2022.10 Revise,ZS1414 Series Decal Installation
19,00775307080401060,Label- Platform Power Rated Voltage,1.0,NaN,ZS1414 Series Decal Installation
20,00775307040401100,Danger- Tip-over Hazard,1.0,NaN,ZS1414 Series Decal Installation
21,00775307080402130,Label- Pre-operation Inspection,1.0,NaN,ZS1414 Series Decal Installation
22,00775307080202140,Label- Charger Power Supply,1.0,NaN,ZS1414 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775207020201020,Label- Lithium-ion Battery \n(ZS1414HD/DC/HA/A...,2,NaN,ZS1414 Series Decal Installation
1,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS1414 Series Decal Installation
2,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS1414 Series Decal Installation
3,00775307040401060,Label- Use safety arm,1,NaN,ZS1414 Series Decal Installation
4,00775307080401020,Label- Electrocution hazard,1,NaN,ZS1414 Series Decal Installation
5,00775307010402050,Label- Battery tray quality warranty \n(ZS1414...,1,2022.10 Revise,ZS1414 Series Decal Installation
6,00775607010401040,Label- Battery tray quality warranty \n( ZS141...,1,2022.10 Revise,ZS1414 Series Decal Installation
7,00775307020401010,Label- Brake release \n(ZS1414HD/HA/HD-Li/HA-L...,1,NaN,ZS1414 Series Decal Installation
8,00775609900401040,Nameplate,1,NaN,ZS1414 Series Decal Installation
9,00775307080401080,Label- non-insulated,1,NaN,ZS1414 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1,NaN,ZS1212 Series Decal Installation
1,00775207010403010,Label- Safety Rules (Indoor Series),1,NaN,ZS1212 Series Decal Installation
2,00775307010402010,Label- Safety Rules(Outdoor Series),1,2022.10 Revise,ZS1212 Series Decal Installation
3,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS1212 Series Decal Installation
4,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS1212 Series Decal Installation
5,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS1212 Series Decal Installation
6,00775607010201020,"Label- Capacity, 350kg (Indoor Series)",1,NaN,ZS1212 Series Decal Installation
7,00775607030401020,"Label- Capacity, 350kg(Outdoor Series)",1,2022.10 Revise,ZS1212 Series Decal Installation
8,00775307080202210,Label- Forklift Hole,2,NaN,ZS1212 Series Decal Installation
9,00775307080202010,Label- Lifting and tying,4,NaN,ZS1212 Series Decal Installation
10,00775307080402150,Label- Emergency Lowering,1,NaN,ZS1212 Series Decal Installation
11,00775307080401050,Label- AC Power to Platform,1,NaN,ZS1212 Series Decal Installation
12,00775607010401030,"Label- Wheels Load, 1280kg",4,NaN,ZS1212 Series Decal Installation
13,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS1212 Series Decal Installation
14,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS1212 Series Decal Installation
15,00775307040401040,Danger- Crushing Hazard,5,NaN,ZS1212 Series Decal Installation
16,00775307040401050,Label- Safety Arm,4,NaN,ZS1212 Series Decal Installation
17,00775307080402170,Label- Max Manual Force (Indoor Series),1,NaN,ZS1212 Series Decal Installation
18,00775307010402030,Label- Max Manual Force(Outdoor Series),1,2022.10 Revise,ZS1212 Series Decal Installation
19,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS1212 Series Decal Installation
20,00775307040401100,Danger- Tip-over Hazard,1,NaN,ZS1212 Series Decal Installation
21,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS1212 Series Decal Installation
22,00775307080202140,Label- Charger Power Supply,1,NaN,ZS1212 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775207020201020,Label- Lithium-ion Battery \n(ZS1212HD/DC/HA/A...,2,NaN,ZS1212 Series Decal Installation
1,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS1212 Series Decal Installation
2,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS1212 Series Decal Installation
3,00775307040401060,Label- Use safety arm,1,NaN,ZS1212 Series Decal Installation
4,00775307080401020,Label- Electrocution hazard,1,NaN,ZS1212 Series Decal Installation
5,00775307010402050,Label- Battery tray quality warranty \n(ZS1212...,1,2022.10 Revise,ZS1212 Series Decal Installation
6,00775607010401040,Label- Battery tray quality warranty \n( ZS121...,1,2022.10 Revise,ZS1212 Series Decal Installation
7,00775307020401010,Label- Brake release \n(ZS1212HD/HA/HD-Li/HA-L...,1,NaN,ZS1212 Series Decal Installation
8,00775609900401040,Nameplate,1,NaN,ZS1212 Series Decal Installation
9,00775307080401080,Label- non-insulated,1,NaN,ZS1212 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1,NaN,ZS1012 Series Decal Installation
1,00775307010402010,Label- Safety Rules,1,NaN,ZS1012 Series Decal Installation
2,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS1012 Series Decal Installation
3,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS1012 Series Decal Installation
4,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS1012 Series Decal Installation
5,00775507010201030,"Label- Capacity, 350kg",1,NaN,ZS1012 Series Decal Installation
6,00775307080202210,Label- Forklift Hole,2,NaN,ZS1012 Series Decal Installation
7,00775307080202010,Label- Lifting and tying,4,NaN,ZS1012 Series Decal Installation
8,00775307080402150,Label- Emergency Lowering,1,NaN,ZS1012 Series Decal Installation
9,00775307080401050,Label- AC Power to Platform,1,NaN,ZS1012 Series Decal Installation
10,00775507010401040,"Label- Wheel Load, 1183kg",4,NaN,ZS1012 Series Decal Installation
11,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS1012 Series Decal Installation
12,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS1012 Series Decal Installation
13,00775307040401040,Danger- Crushing Hazard,5,NaN,ZS1012 Series Decal Installation
14,00775307040401050,Label- Safety Arm,4,NaN,ZS1012 Series Decal Installation
15,00775307010402030,Label- Max Manual Force,1,NaN,ZS1012 Series Decal Installation
16,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS1012 Series Decal Installation
17,00775307040401100,Danger- Tip-over Hazard,1,NaN,ZS1012 Series Decal Installation
18,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS1012 Series Decal Installation
19,00775307080202140,Label- Charger Power Supply,1,NaN,ZS1012 Series Decal Installation
20,00775207020201020,Label- Lithium-ion Battery \n(ZS1012HD/DC/HA/A...,2,NaN,ZS1012 Series Decal Installation
21,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS1012 Series Decal Installation
22,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS1012 Series Decal Installation
23,00775307040401060,Label- Use safety arm,1,NaN,ZS1012 Series Decal Installation
24,00775307080401020,Label- Electrocution hazard,1,NaN,ZS1012 Series Decal Installation
25,00775307010402050,Label- Battery tray quality warranty,1,NaN,ZS1012 Series Decal Installation
26,00775307020401010,Label- Brake release \n(ZS1012HD/HA/HD-Li/HA-L...,1,NaN,ZS1012 Series Decal Installation
27,00775609900401040,Nameplate,1,NaN,ZS1012 Series Decal Installation
28,00775307080401080,Label- non-insulated,1,NaN,ZS1012 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1,NaN,ZS0812 Series Decal Installation
1,00775307010402010,Label- Safety Rules,1,NaN,ZS0812 Series Decal Installation
2,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS0812 Series Decal Installation
3,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS0812 Series Decal Installation
4,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS0812 Series Decal Installation
5,00775407060201020,"Label- Capacity, 450kg",1,NaN,ZS0812 Series Decal Installation
6,00775407080201020,"Label- Capacity, 450kg",1,NaN,ZS0812 Series Decal Installation
7,00775307080202210,Label- Forklift Hole,2,NaN,ZS0812 Series Decal Installation
8,00775307080202010,Label- Lifting and tying,4,NaN,ZS0812 Series Decal Installation
9,00775307080402150,Label- Emergency Lowering,1,NaN,ZS0812 Series Decal Installation
10,00775307080401050,Label- AC Power to Platform,1,NaN,ZS0812 Series Decal Installation
11,00775507010401040,"Label- Wheel Load, 1183kg",4,NaN,ZS0812 Series Decal Installation
12,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS0812 Series Decal Installation
13,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS0812 Series Decal Installation
14,00775307040401040,Danger- Crushing Hazard,3,NaN,ZS0812 Series Decal Installation
15,00775307040401050,Label- Safety Arm,2,NaN,ZS0812 Series Decal Installation
16,00775307010402030,Label- Max Manual Force,1,NaN,ZS0812 Series Decal Installation
17,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS0812 Series Decal Installation
18,00775307040401100,Danger- Tip-over Hazard,1,NaN,ZS0812 Series Decal Installation
19,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS0812 Series Decal Installation
20,00775307080202140,Label- Charger Power Supply,1,NaN,ZS0812 Series Decal Installation
21,00775207020201020,Label- Lithium-ion Battery \n(ZS0812DC/AC/HA/H...,2,NaN,ZS0812 Series Decal Installation
22,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS0812 Series Decal Installation
23,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS0812 Series Decal Installation
24,00775307040401060,Label- Use safety arm,1,NaN,ZS0812 Series Decal Installation
25,00775307080401020,Label- Electrocution hazard,1,NaN,ZS0812 Series Decal Installation
26,00775307010402050,Label- Battery tray quality warranty,1,NaN,ZS0812 Series Decal Installation
27,00775307020401010,Label- Brake release \n(ZS0812HA/HD Series only),1,NaN,ZS0812 Series Decal Installation
28,00775609900401040,Nameplate,1,NaN,ZS0812 Series Decal Installation
29,00775307080401080,Label- non-insulated,1,NaN,ZS0812 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1,NaN,ZS0808 Series Decal Installation
1,00775207010403010,Label- Safety Rules (Indoor Series),1,NaN,ZS0808 Series Decal Installation
2,00775307010402010,Label- Safety Rules (Outdoor Series),1,2022.10 Revise,ZS0808 Series Decal Installation
3,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS0808 Series Decal Installation
4,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS0808 Series Decal Installation
5,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS0808 Series Decal Installation
6,00775307040201020,"Label- Capacity, 230kg (Indoor Series)",1,NaN,ZS0808 Series Decal Installation
7,00775407040201030,"Label- Capacity, 230kg(Outdoor Series)",1,2022.10 Revise,ZS0808 Series Decal Installation
8,00775307080202210,Label- Forklift Hole,2,NaN,ZS0808 Series Decal Installation
9,00775307080202010,Label- Lifting and tying,4,NaN,ZS0808 Series Decal Installation
10,00775307080402150,Label- Emergency Lowering,1,NaN,ZS0808 Series Decal Installation
11,00775307080401050,Label- AC Power to Platform,1,NaN,ZS0808 Series Decal Installation
12,00775307010402020,"Label- Wheel Load, 830kg",4,NaN,ZS0808 Series Decal Installation
13,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS0808 Series Decal Installation
14,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS0808 Series Decal Installation
15,00775307040401040,Danger- Crushing Hazard,3,NaN,ZS0808 Series Decal Installation
16,00775307040401050,Label- Safety Arm,2,NaN,ZS0808 Series Decal Installation
17,00775307080402170,Label- Max Manual Force (Indoor Series),1,NaN,ZS0808 Series Decal Installation
18,00775307010402030,Label- Max Manual Force(Outdoor Series),1,2022.10 Revise,ZS0808 Series Decal Installation
19,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS0808 Series Decal Installation
20,00775307040401100,Danger- Tip-over Hazard,1,NaN,ZS0808 Series Decal Installation
21,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS0808 Series Decal Installation
22,00775307080202140,Label- Charger Power Supply,1,NaN,ZS0808 Series Decal Installation
23,00775207020201020,Label- Lithium-ion Battery \n(ZS0808HD/DC/HA/A...,2,NaN,ZS0808 Series Decal Installation
24,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS0808 Series Decal Installation
25,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS0808 Series Decal Installation
26,00775307040401060,Label- Use safety arm,1,NaN,ZS0808 Series Decal Installation
27,00775307080401020,Label- Electrocution hazard,1,NaN,ZS0808 Series Decal Installation
28,00775307010402050,Label- Battery tray quality warranty,1,NaN,ZS0808 Series Decal Installation
29,00775307020401010,Label- Brake release \n(ZS0808HD/HA/HD-Li/HA-L...,1,NaN,ZS0808 Series Decal Installation
30,00775609900401040,Nameplate,1,NaN,ZS0808 Series Decal Installation
31,00775307080401080,Label- non-insulated,1,NaN,ZS0808 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1,NaN,ZS0608 Series Decal Installation
1,00775307010402010,Label- Safety Rules,1,NaN,ZS0608 Series Decal Installation
2,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS0608 Series Decal Installation
3,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS0608 Series Decal Installation
4,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS0608 Series Decal Installation
5,00775307010202040,"Label- Capacity, 380kg",1,NaN,ZS0608 Series Decal Installation
6,00775307080202210,Label- Forklift Hole,2,NaN,ZS0608 Series Decal Installation
7,00775307080202010,Label- Lifting and tying,4,NaN,ZS0608 Series Decal Installation
8,00775307080402150,Label- Emergency Lowering,1,NaN,ZS0608 Series Decal Installation
9,00775307080401050,Label- AC Power to Platform,1,NaN,ZS0608 Series Decal Installation
10,00775307010402020,"Label- Wheel Load, 830kg",4,NaN,ZS0608 Series Decal Installation
11,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS0608 Series Decal Installation
12,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS0608 Series Decal Installation
13,00775307040401040,Danger- Crushing Hazard,3,NaN,ZS0608 Series Decal Installation
14,00775307040401050,Label- Safety Arm,2,NaN,ZS0608 Series Decal Installation
15,00775307010402030,Label- Max Manual Force,1,NaN,ZS0608 Series Decal Installation
16,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS0608 Series Decal Installation
17,00775307040401100,Danger- Tip-over Hazard,1,NaN,ZS0608 Series Decal Installation
18,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS0608 Series Decal Installation
19,00775307080202140,Label- Charger Power Supply,1,NaN,ZS0608 Series Decal Installation
20,00775207020201020,Label- Lithium-ion Battery \n(ZS0608HD-Li/ZS06...,2,NaN,ZS0608 Series Decal Installation
21,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS0608 Series Decal Installation
22,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS0608 Series Decal Installation
23,00775307040401060,Label- Use safety arm,1,NaN,ZS0608 Series Decal Installation
24,00775307080401020,Label- Electrocution hazard,1,NaN,ZS0608 Series Decal Installation
25,00775307010402050,Label- Battery tray quality warranty,1,NaN,ZS0608 Series Decal Installation
26,00775307020401010,Label- Brake release \n(ZS0608HD/ZS0608HD-Li o...,1,NaN,ZS0608 Series Decal Installation
27,00775609900401040,Nameplate,1,NaN,ZS0608 Series Decal Installation
28,00775307080401080,Label- non-insulated,1,NaN,ZS0608 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation and Safety \nManual,1,NaN,ZS0607 Series Decal Installation
1,00775207010403010,Label- Safety Rules (Indoor Series),1,NaN,ZS0607 Series Decal Installation
2,00775307010402010,Label- Safety Rules (Outdoor Series),1,2022.10 Revise,ZS0607 Series Decal Installation
3,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS0607 Series Decal Installation
4,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS0607 Series Decal Installation
5,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS0607 Series Decal Installation
6,00775307040201020,"Label- Capacity, 230kg (Indoor Series)",1,NaN,ZS0607 Series Decal Installation
7,00775407040201030,"Label- Capacity, 230kg (Outdoor Series)",1,2022.10 Revise,ZS0607 Series Decal Installation
8,00775307080202210,Label- Forklift Hole,2,NaN,ZS0607 Series Decal Installation
9,00775307080202010,Label- Lifting and tying,4,NaN,ZS0607 Series Decal Installation
10,00775307080402150,Label- Emergency Lowering,1,NaN,ZS0607 Series Decal Installation
11,00775307080401050,Label- AC Power to Platform,1,NaN,ZS0607 Series Decal Installation
12,00775307040401030,"Label- Wheel Load, 580kg",4,NaN,ZS0607 Series Decal Installation
13,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS0607 Series Decal Installation
14,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS0607 Series Decal Installation
15,00775307040401040,Danger- Crushing Hazard,3,NaN,ZS0607 Series Decal Installation
16,00775307040401050,Label- Safety Arm,2,NaN,ZS0607 Series Decal Installation
17,00775307080402170,Label- Max Manual Force (Indoor Series),1,NaN,ZS0607 Series Decal Installation
18,00775307010402030,Label- Max Manual Force(Outdoor Series),1,2022.10 Revise,ZS0607 Series Decal Installation
19,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS0607 Series Decal Installation
20,00775307040401100,Danger- Tip-over Hazard,1,NaN,ZS0607 Series Decal Installation
21,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS0607 Series Decal Installation
22,00775307080202140,Label- Charger Power Supply,1,NaN,ZS0607 Series Decal Installation
23,00775207020201020,Label- Lithium-ion Battery \n(ZS0607HD/HA/AC/D...,2,NaN,ZS0607 Series Decal Installation
24,00775307080401040,Label- High pressure liquid hazard,1,NaN,ZS0607 Series Decal Installation
25,00775307040401070,"Label- Notice, Close tray",2,NaN,ZS0607 Series Decal Installation
26,00775307040401060,Label- Use safety arm,1,NaN,ZS0607 Series Decal Installation
27,00775307080401020,Label- Electrocution hazard,1,NaN,ZS0607 Series Decal Installation
28,00775307040401080,Label- Battery tray quality warranty,1,NaN,ZS0607 Series Decal Installation
29,00775307020401010,Label- Brake release \n(ZS0607HD/HA/HD-Li/HA...,1,NaN,ZS0607 Series Decal Installation
30,00775609900401040,Nameplate,1,NaN,ZS0607 Series Decal Installation
31,00775307080401080,Label- non-insulated,1,NaN,ZS0607 Series Decal Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775307080402040,Label- Store the Operation \nand Safety Manual,1,NaN,ZS0407 Series Decal Installation
1,00775207010403010,Label- Safety Rules (Indoor Series),1,NaN,ZS0407 Series Decal Installation
2,00775307010402010,Label- Safety Rules (Outdoor Series),1,2022.10 Revise,ZS0407 Series Decal Installation
3,00775207010403070,Danger- Tip-over Hazard,1,NaN,ZS0407 Series Decal Installation
4,00775307080402030,Label- Read the Instructions Carefully,2,NaN,ZS0407 Series Decal Installation
5,00775307080202090,Label- Lanyard Anchorage Point,4,NaN,ZS0407 Series Decal Installation
6,00775207010203030,"Label- Capacity, 240kg (Indoor Series)",1,NaN,ZS0407 Series Decal Installation
7,00775207060401010,"Label- Capacity, 240kg (Outdoor Series)",1,2022.10 Revise,ZS0407 Series Decal Installation
8,00775307080202210,Label- Forklift Hole,2,NaN,ZS0407 Series Decal Installation
9,00775307080202010,Label- Lifting and tying,4,NaN,ZS0407 Series Decal Installation
10,00775307080402150,Label- Emergency Lowering,1,NaN,ZS0407 Series Decal Installation
11,00775207010403040,"Label- Wheel Load, 390kg",4,NaN,ZS0407 Series Decal Installation
12,00775307080402110,Instruction- Main Power Switch Operation,1,NaN,ZS0407 Series Decal Installation
13,00775307080402060,Danger- Explosion and Fire Hazard,1,NaN,ZS0407 Series Decal Installation
14,00775207010403020,Danger- Crushing Hazard,3,NaN,ZS0407 Series Decal Installation
15,00775207010403060,Label- Safety Arm,2,NaN,ZS0407 Series Decal Installation
16,00775307080402170,Label- Max Manual Force (Indoor Series),1,NaN,ZS0407 Series Decal Installation
17,00775307010402030,Label- Max Manual Force(Outdoor Series),1,2022.10 Revise,ZS0407 Series Decal Installation
18,00775207010403050,Danger- Tip-over Hazard,1,NaN,ZS0407 Series Decal Installation
19,00775307080402130,Label- Pre-operation Inspection,1,NaN,ZS0407 Series Decal Installation
20,00775207020201020,Label- Lithium-ion Battery \n(ZS0407DC-Li only),1,NaN,ZS0407 Series Decal Installation
21,00775307080401060,Label- Platform Power Rated Voltage,1,NaN,ZS0407 Series Decal Installation
22,00775307080401050,Label- AC Power to Platform,1,NaN,ZS0407 Series Decal Installation
23,00775307080202140,Label- Charger Power Supply,1,NaN,ZS0407 Series Decal Installation
24,00775609900401040,Nameplate,1,NaN,ZS0407 Series Decal Installation
25,00775307080401080,Label- non-insulated,1,NaN,ZS0407 Series Decal Installation

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

,Material No.,Item and Spec,Units,Remark,Section
0,1020704297,Core,5,HQ-005-M,Male Plug
1,1020704362,Heavy-duty connector \nterminal,1,CEM-0.75,Male Plug
2,1029905127,Upper shell,1,H3A-MTG-PG11,Male Plug
3,1022396108,Nylon cable gland,1,HSK-P11B,Male Plug

,Material No.,Item and Spec,Units,Remark,Section
0,1020704296,Core,5,HQ-005-F,Female Plug
1,1020704363,Heavy-duty connector \nterminal,1,CEF-0.75,Female Plug
2,1029905078,Lower shell,1,H3A-MAGSV-PG11,Female Plug
3,1022396108,Nylon cable gland,1,HSK-P11B,Female Plug

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

,Material No.,Item and Spec,Units,Remark,Section
3,1029908611,Breaker,1,2DX0X028028T,Left Drive Motor (Motion Motor)

,Material No.,Item and Spec,Units,Remark,Section
3,1029908611,Breaker,1,2DX0X028028T,Right Drive Motor (Motion Motor)

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

,Material No.,Item and Spec,Units,Remark,Section
12,1140103526,High pressure articulating \njoint,2,WH10LRKDSOMDCF,ZS0407/ZS0607 Steering Cylinder

,Material No.,Item and Spec,Units,Remark,Section
14,1140103526,High pressure articulating \njoint,2,WH10LRKDSOMDCF,ZS0608/ZS0808 Steering Cylinder

,Material No.,Item and Spec,Units,Remark,Section
14,1140114039,Hydraulic pipe joint,2,GE10LREDOMD,ZS0812/ZS1012/ZS1212/ZS1414 Steering Cylinder

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

,Material No.,Item and Spec,Units,Remark,Section
1,1010306554,Check valve,1,STCV08-0-000A,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
2,1010309213,Proportional solenoid \nvalve,1,PJ2012200,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
3,1019902191,Damping,1,STTY002-1.9,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
5,1081004551,O ring,1,10.77×2.62 HNBR 90SH,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
6,1019803186,Plug,6,4BN-02W/D,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
7,1011200142,Plug,1,4BN-04W/D,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
9,1011200145,Plug,1,4BN-06W/D,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
10,1010308648,Lower lifting cylinder \ncontrol valve (ZS0407),1,ST5664-AC00,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
11,1010308649,Lower lifting cylinder \ncontrol valve (ZS0607),1,ST5665-AC00,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
12,1010307396,Lower lifting cylinder \ncontrol valve \nZS060...,1,BLF-ST5149-AC00,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
13,1140114040,Hydraulic pipe joint,1,GE10LR3/8EDOMD,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
14,1140102034,Screw,4,M8×60-10.9,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
15,1040300063,Gasket,4,GB/T93-1987,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...
16,00775305290401010,Spring,1,SUS304,ZS0407/ZS0607/ZS0608/ZS0808/ZS0812/ZS1012/ZS12...

Empty DataFrame
Columns: [Material No., Item and Spec, Units, Remark, Section]
Index: []

,Material No.,Item and Spec,Units,Remark,Section
1,1010306554,Check valve,1,STCV08-0-000A,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
2,1010306784,Solenoid valve,1,STS0-S08-01,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
3,1019902188,Damping,1,STTY002-1.3,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
5,1019803186,Plug,1,4BN-02W/D,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
6,1011200142,Plug,5,4BN-04W/D,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
7,1019808293,Coil,1,4BN-04W/D,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
8,1081004551,O ring,1,10.77×2.62 NBR 90SH,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
11,1010306629,Upper lifting cylinder \ncontrol valve \n(ZS10...,1,ST5044-AE0C,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
12,1010306626,Upper lifting cylinder \ncontrol valve \n (ZS...,1,ST5044-AC0C,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
13,1010306627,Upper lifting cylinder \ncontrol valve \n (ZS...,1,ST5044-AE0A.A,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
14,1010306625,Upper lifting cylinder \ncontrol valve \n (ZS...,1,ST5044-AC0A,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
15,1010306749,Upper lifting cylinder \ncontrol valve \n (ZS...,1,ST5144-AE00,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
16,1010306750,Upper lifting cylinder \ncontrol valve \n (ZS...,1,ST5144-AC00,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
17,1140114040,Hydraulic pipe joint,1,GE10LR3/8EDOMD,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
18,1140102034,Screw,4,M8×60-10.9,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...
19,1040300063,Gasket,4,GB/T93-1987,ZS1012/ZS1212/ZS1414 Upper Lifting Cylinder Co...

,Material No.,Item and Spec,Units,Remark,Section
26,1010002079,Power unit,1,DC-F55-1.6/E-\n1.2/24/24-4PH-C,ZS0407DC Power Unit Installation
27,1140114039,Hydraulic pipe joint,1,GE10LREDOMD,ZS0407DC Power Unit Installation
28,1140114041,Hydraulic pipe joint,2,GE08LREDOMD,ZS0407DC Power Unit Installation
29,1140114187,Pressure testing joint,1,"SD-M16×2-F-\nG1/4""",ZS0407DC Power Unit Installation
30,1010100097,Screw,2,M10×30-8.8,ZS0407DC Power Unit Installation
31,1040300067,Gasket,2,GB/T93-1987,ZS0407DC Power Unit Installation
32,1040300061,Gasket,2,10-200HV,ZS0407DC Power Unit Installation

,Material No.,Item and Spec,Units,Remark,Section
1,1010306548,Relief valve,1,STRV08-G-210A,ZS0607 Platform Control Valve
2,1010306550,Solenoid valve,1,SV10-40-0-N-0,ZS0607 Platform Control Valve
3,1010306565,Pressure-gradient control \nvalve,1,FR10-30F-0-N-/M3.5,ZS0607 Platform Control Valve
4,1010306564,Solenoid valve,1,SC08-47A-0-N-0,ZS0607 Platform Control Valve
5,1019809041,Damping,1,STTY002-1.0,ZS0607 Platform Control Valve
6,1010306595,Relief valve,1,STRV08-B-120A,ZS0607 Platform Control Valve
7,1029906518,Coil,2,4303620,ZS0607 Platform Control Valve
8,1029906519,Coil,1,4303720,ZS0607 Platform Control Valve
9,1019803186,Plug,15,4BN-02WD,ZS0607 Platform Control Valve
10,1011200142,Plug,1,4BN-04WD,ZS0607 Platform Control Valve
11,1011200145,Plug,1,4BN-06WD,ZS0607 Platform Control Valve
12,1010306187,Platform Control Valve,1,ST4895-AE00,ZS0607 Platform Control Valve
13,1140114036,Hydraulic pipe joint,1,GE12LREDOMD,ZS0607 Platform Control Valve
14,1140114039,Hydraulic pipe joint,2,GE10LREDOMD,ZS0607 Platform Control Valve
15,1140114040,Hydraulic pipe joint,3,GE10LR3/8EDOMD,ZS0607 Platform Control Valve
16,1140114187,Pressure joint,1,"SD-M16×2-F-G1/4""",ZS0607 Platform Control Valve
17,1140101476,Tube to swivel,2,EW10LOMDCF,ZS0607 Platform Control Valve
18,1140107463,Joint,1,EW12LOMD,ZS0607 Platform Control Valve
19,1040100421,Screw,4,M8×20-8.8,ZS0607 Platform Control Valve

,Material No.,Item and Spec,Units,Remark,Section
1,1010306548,Relief valve,1,STRV08-G-210A,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
2,1010306550,Solenoid valve,1,SV10-40-0-N-0,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
3,1010306565,Pressure-gradient control valve,1,FR10-30F-0-N-/M3.5,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
4,1010306564,Solenoid valve,1,SC08-47A-0-N-0,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
5,1019809041,Damping,1,STTY002-1.0,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
6,1010306595,Relief valve,1,STRV08-B-120A,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
7,1029906518,Coil,2,4303620,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
8,1029906519,Coil,1,4303720,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
9,1019803186,Plug,15,4BN-02WD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
10,1011200142,Plug,1,4BN-04WD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
11,1011200145,Plug,1,4BN-06WD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
12,1010306187,Platform Control Valve \n(DC series),1,ST4895-AE00,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
13,1010306289,Platform Control Valve \n(DC-Li series),1,ST4895-AC00,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
14,1140114039,Hydraulic pipe joint,2,GE10LREDOMD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
15,1140114038,Hydraulic pipe joint,1,GE08LR3/8EDOMD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
16,1140114036,Hydraulic pipe joint,2,GE12LREDOMD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
17,1140114040,Hydraulic pipe joint,1,GE10LR3/8EDOMD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
18,1140107463,Joint,2,EW12LOMD,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
19,1140114187,Pressure joint,1,"SD-M16×2-F-G1/4""",ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...
20,1040100421,Screw,4,M8×20-8.8,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Plat...

,Material No.,Item and Spec,Units,Remark,Section
0,1011300149,Hydraulic oil tank,1,CX-008L-F,ZS0607 Oil Tank Installation
1,1140207362,Male stud connector,1,GE12LR3/4EDOMDCF,ZS0607 Oil Tank Installation
2,1140101478,Tube to swivel,1,EW15LOMDCF,ZS0607 Oil Tank Installation
3,1040004508,Bolt,2,M10×45-8.8,ZS0607 Oil Tank Installation
4,1040300061,Gasket,2,10-200HV,ZS0607 Oil Tank Installation
5,1040200504,Nut,2,M10-8,ZS0607 Oil Tank Installation

,Material No.,Item and Spec,Units,Remark,Section
0,1011300151,Hydraulic oil tank \n(DC series),1,JC19A16-025L-F,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Oil ...
1,1011300210,Hydraulic oil tank \n(DC series),1,ZL20025L,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Oil ...
2,1140101479,Tube to swivel,2,EW18LOMDCF,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Oil ...
3,11140207362,Male stud connector,1,GE12LR3/4EDOMDCF,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Oil ...
4,1040101606,Screw,4,M8×12-8.8,ZS0608/ZS0808/ZS0812/ZS1012/ZS1212/ZS1414 Oil ...

,Material No.,Item and Spec,Units,Remark,Section
14,1010002071,Gear pump,1,2ABPF04LJ36SB09L-TLT,ZS0607Gear Pump Installation
15,1140112823,Male stud connector,1,GE10L7/8UNFOMDCF,ZS0607Gear Pump Installation
16,1140108135,Joint,1,GE15L7/8UNFOMD,ZS0607Gear Pump Installation
17,1140101478,Tube to swivel,1,EW15LOMDCF,ZS0607Gear Pump Installation
18,1040004607,Bolt,2,3/8-24UNF-1-10.9,ZS0607Gear Pump Installation
19,1040300067,Gasket,2,GB/T93-1987,ZS0607Gear Pump Installation

,Material No.,Item and Spec,Units,Remark,Section
14,1010002078,Gear pump,1,2ABPF04LJ36SB09L-TLT,ZS0608/ZS0808/ZS0812 Gear Pump Installation
15,1140114035,Hydraulic pipe joint \n (ZS0608),1,M18×1.5-3/4-16UNF,ZS0608/ZS0808/ZS0812 Gear Pump Installation
16,1140103421,Male stud connector \n(ZS0808/ZS0812),1,GE12L7/8UNFOMDCF,ZS0608/ZS0808/ZS0812 Gear Pump Installation
17,1140114034,Hydraulic pipe joint,1,GE18L7/8UNFOMD,ZS0608/ZS0808/ZS0812 Gear Pump Installation
18,1040004607,Bolt,2,3/8-24UNF-1-10.9,ZS0608/ZS0808/ZS0812 Gear Pump Installation
19,1040300067,Gasket,2,GB/T93-1987,ZS0608/ZS0808/ZS0812 Gear Pump Installation

,Material No.,Item and Spec,Units,Remark,Section
14,1010002078,Gear pump,1,2ABPF05LJ36SB09L-TLT,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
15,1140114035,Hydraulic pipe joint,1,M18×1.5-3/4-16UNF,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
16,1140114034,Hydraulic pipe joint,1,GE18L7/8UNFOMD,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
17,1040004607,Bolt,2,3/8-24UNF-1-10.9,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
18,1040300067,Gasket,2,GB/T93-1987,ZS1012/ZS1212/ZS1414DC Gear Pump Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775700000001040,Lower sliding block I,1.0,NaN,ZS1414 Series Pin Installation
1,00775600300001140,Gasket,2.0,NaN,ZS1414 Series Pin Installation
2,1054400310,Composite bush,2.0,NaN,ZS1414 Series Pin Installation
3,1040200504,Nut M10-8,2.0,GB/T889.1-2000,ZS1414 Series Pin Installation
4,1040000025,Bolt M10×80-8.8,2.0,GB/T5783-2000,ZS1414 Series Pin Installation
...,...,...,...,...,...
2738,1010002078,Gear pump,1.0,2ABPF05LJ36SB09L-TLT,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
2739,1140114035,Hydraulic pipe joint,1.0,M18×1.5-3/4-16UNF,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
2740,1140114034,Hydraulic pipe joint,1.0,GE18L7/8UNFOMD,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
2741,1040004607,Bolt,2.0,3/8-24UNF-1-10.9,ZS1012/ZS1212/ZS1414DC Gear Pump Installation
2742,1040300067,Gasket,2.0,GB/T93-1987,ZS1012/ZS1212/ZS1414DC Gear Pump Installation

,Material No.,Item and Spec,Units,Remark,Section
0,00775700000001040,Lower sliding block I,1.0,NaN,ZS1414 Series Pin Installation
1,00775600300001140,Gasket,2.0,NaN,ZS1414 Series Pin Installation
2,1054400310,Composite bush,2.0,NaN,ZS1414 Series Pin Installation
3,1040200504,Nut M10-8,2.0,GB/T889.1-2000,ZS1414 Series Pin Installation
4,1040000025,Bolt M10×80-8.8,2.0,GB/T5783-2000,ZS1414 Series Pin Installation

100%|██████████| 1/1 [00:03<00:00,  3.76s/it]

- Спросить у Миши про запчасти, в описании которых встречается ещё одна модель, помимо основной, в которой они встречаются
- Что делать с такими в описании (Cubota): ZT138J-ZT24JE-V Turntable Decal Assembly - что значит тире?