In [2]:
import os
import camelot
import pandas as pd
from tqdm import tqdm
from IPython.display import display
import warnings
import re
import numpy as np
import pdfplumber

warnings.filterwarnings("ignore")

folder = os.getcwd()
pdf_files = [os.path.join(folder, f) for f in os.listdir(folder) if f.lower().endswith(".pdf")]


def extract_numbers(name):

    nums = re.findall(r'\d+', name)
    return tuple(map(int, nums))

replacements = {
    'Ⅰ': 'I',
    'Ⅱ': 'II',
    'Ⅲ': 'III',
    'Ⅳ': 'IV',
    'Ⅴ': 'V',
    'Ⅵ': 'VI',
    'Ⅶ': 'VII',
    'Ⅷ': 'VIII',
    'Ⅸ': 'IX',
    'Ⅹ': 'X'
}

def extract_tables_camelot(pdf_path: str, out_dir="tables", pages="all", title_height=120):

    os.makedirs(out_dir, exist_ok=True)

    tables_lattice = camelot.read_pdf(
        pdf_path,
        pages=pages,
        flavor="lattice",
        line_scale=80
    )

    lattice_pages = set()
    text_pages = set()

    with pdfplumber.open(pdf_path) as pdf:

        for i, t in enumerate(tables_lattice):

            page_num = int(t.page)          
            page_idx = page_num - 1        
            lattice_pages.add(page_num)

            t.to_csv(
                os.path.join(out_dir, f"lattice_p{page_num}_{i}.csv"),
                index=False
            )

            page = pdf.pages[page_idx]

            x1, y1, x2, y2 = t._bbox
            page_w = page.width
            page_h = page.height

            table_top = page_h - y2

            left   = max(0, min(x1, page_w))
            right  = max(0, min(x2, page_w))
            top    = max(0, min(table_top - title_height, page_h))
            bottom = max(0, min(table_top, page_h))

            if right > left and bottom > top:
                title_box = (left, top, right, bottom)
                title_text = page.crop(title_box, strict=False).extract_text(
                    x_tolerance=2,
                    y_tolerance=2
                ) or ""

                if title_text.strip():
                    text_pages.add(page_num)
            else:
                title_text = ""

            with open(
                os.path.join(out_dir, f"text_p{page_num}_{i}.txt"),
                "w",
                encoding="utf-8"
            ) as f:
                f.write(title_text.strip())

    return None       


def join_ordered(series):
    vals = series.dropna().astype(str).str.strip()
    vals = [v for v in vals if v]
    seen = set()
    result = []
    for v in vals:
        if v not in seen:
            seen.add(v)
            result.append(v)
    return "; ".join(result) if result else None

def merge_parts(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if 'Qty' in df.columns:
        agg_map = {
            "Qty": "sum",
        }
    elif 'Код материалов' in df.columns:
        agg_map = {
            "Кол-во": "sum",
        }
    elif '件数' in df.columns:
        agg_map = {
            '件数': 'sum'
        }
    elif 'Units' in df.columns:
        agg_map = {
            'Units': 'sum'
        }

    if "Item and Spec" in df.columns:

        agg_map["Item and Spec"] = join_ordered
    if "Remark" in df.columns:
        agg_map["Remark"] = join_ordered

    if 'Наименование и спецификация' in df.columns:
        agg_map['Наименование и спецификация'] = join_ordered

    if 'Примечание' in df.columns:
        agg_map['Примечание'] = join_ordered

    if 'Версия' in df.columns:
        agg_map['Версия'] = join_ordered

    if 'Rev.' in df.columns:
        agg_map['Rev.'] = join_ordered

    if "名称及规格" in df.columns:
        agg_map["名称及规格"] = join_ordered

    if "备注" in df.columns:
        agg_map["备注"] = join_ordered

    if "Section" in df.columns:
        agg_map["Section"] = join_ordered

    if 'Material No.' in df.columns:
        df_agg = df.groupby("Material No.", as_index=False).agg(agg_map)
    elif 'Код материалов' in df.columns:
        df_agg = df.groupby("Код материалов", as_index=False).agg(agg_map)
    elif '物料编码' in df.columns:
        df_agg = df.groupby("物料编码", as_index=False).agg(agg_map)


    return df_agg

In [61]:
b = 36
e = b+1

for i, pth in enumerate(tqdm(pdf_files[b:e])):
    
    filename = os.path.basename(pth)          
    filename = os.path.splitext(filename)[0]
    print(f'Обработка файла: {filename}')

    # extract_tables_camelot(pth, filename, pages="all", title_height=800)

    dfs = []

    for file in sorted(os.listdir(filename), key=extract_numbers):

        if not file.startswith("lattice_") or not file.lower().endswith(".csv"):
            continue

        path = os.path.join(filename, file)

        if os.path.getsize(path) == 0:  
            continue
        df_i = pd.read_csv(path, converters={1: str})

        if (
            df_i.empty
            or df_i.shape[1] < 4
            or not any(col in df_i.columns for col in ['NO.', 'Код материалов', 'No.', 'Код мат-ла', 'Serial No.', 'Part No.', '物料编码', 'п/п  Код материалов', 'Код'])
            ):
            continue

        # если китаец насрал пробел в начале таблицы
        if 'NO.' in df_i.iloc[0].values or 'Material No.' in df_i.iloc[0].values:
            df_i.columns = df_i.iloc[0]  
            df_i = df_i[1:].reset_index(drop=True) 

        for col in ['NO.', 'No.', '№ п/п', '№ \nп/п', 'Serial No.', '序号', '№ \n\nп/п', '№ \r\nп/п', '№']:
            if col in df_i.columns:
                df_i = df_i.drop(col, axis=1)

        idx = file.replace("lattice_", "").rsplit(".", 1)[0]
        section_val = os.path.join(filename, f"text_{idx}.txt")
        
        with open(section_val, "r", encoding="utf-8") as f:
            lines = f.read().splitlines()

        skip_titles = [
            'Руководство по деталъная структура',
            'Альбом чертежей деталей и узлов коленчатого подъемника для высотных работ',
            'Альбом чертежей деталей и компонентов',
            'Parts Manual',
            '零部件图册'
        ]

        if lines and lines[0] in skip_titles:
            lines = lines[1:]
                
        if lines and lines[0] in ['Альбом чертежей деталей и узлов коленчатого', 'Альбом чертежей деталей и узлов коленчатого подъемника для']:
            lines = lines[2:]

        lines_joined = " ".join(lines)
            
        df_i["Section"] = lines_joined
        
        df_i = df_i[df_i.iloc[:, 0].replace('', pd.NA).notna()]
        display(df_i)
        df_i = df_i[df_i.iloc[:, 0] != '/']
        dfs.append(df_i)

    df_all = pd.concat(dfs, ignore_index=True)
    display(df_all)
    df_all.to_excel('dfs.xlsx', index=False)

    for old_col in ['во', 'Кол-\nво', 'Кол-\r\nво', 'Кол-в\nо \nштук', 'Кол-\nво \nшту\nк', 'Кол-во \nштук', 'Cantidad', 'Кол-во\n\nштук', 'Кол-во\r\nштук', 'Кол-\n\nво \n\nшту\n\nк', 'Кол-во \r\nштук', 'Кол-в\r\nо \r\nштук', 'Кол-\r\nво \r\nшту\r\nк', 'Кол-во штук', 'Кол-в', 'Колич\r\nество', 'Кол-в\r\nо\r\nштук']:
        if old_col in df_all.columns.tolist():
            if 'Кол-во' in df_all.columns.tolist():
                df_all['Кол-во'] = df_all.loc[:, old_col].combine_first(df_all['Кол-во'])
            else:
                df_all['Кол-во'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Кол-во' in df_all.columns:
        col = df_all.pop("Кол-во")  
        df_all.insert(2, "Кол-во", col) 

    for old_col in ['Наименование и \nспецификация', 'Наименование и \r\nспецификация', 'Наименование и\n\nспецификация', 'Nombre y especificación', 'Наименование и \r\nспецификация', 'Наименование и\r\nспецификация', 'Наименование и', 'Наименование\r\nи', 'Наименование']:
        if old_col in df_all.columns.tolist():
            if 'Наименование и спецификация' in df_all.columns:
                df_all['Наименование и спецификация'] = df_all.loc[:, old_col].combine_first(df_all['Наименование и спецификация'])
            else:
                df_all['Наименование и спецификация'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Наименование и спецификация' in df_all.columns:
        col = df_all.pop("Наименование и спецификация")  
        df_all.insert(1, "Наименование и спецификация", col) 

    for old_col in ['Name and Spec.', 'Spec and Item']:
        if old_col in df_all.columns:
            if 'Item and Spec' in df_all.columns:
                df_all['Item and Spec'] = df_all.loc[:, old_col].combine_first(df_all['Item and Spec'])
            else:
                df_all['Item and Spec'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Item and Spec' in df_all.columns:
        col = df_all.pop('Item and Spec')  
        df_all.insert(1, 'Item and Spec', col) 

    for old_col in ['Примечани\nе', 'Observaciones', 'Примечани\n\nе', 'Примечани\r\nе', '№ позиции', 'Примеч\r\nание']:
        if old_col in df_all.columns:
            if 'Примечание' in df_all.columns:
                df_all['Примечание'] = df_all.loc[:, old_col].combine_first(df_all['Примечание'])
            else:
                df_all['Примечание'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Примечание' in df_all.columns:
        col = df_all.pop('Примечание')  
        df_all.insert(3, 'Примечание', col) 

    for old_col in ['Qty.', 'Unit']:
        if old_col in df_all.columns:
            if 'Qty' in df_all.columns:
                df_all['Qty'] = df_all.loc[:, old_col].combine_first(df_all['Qty'])
            else:
                df_all['Qty'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Qty' in df_all.columns:
        col = df_all.pop('Qty')  
        df_all.insert(2, 'Qty', col) 
        
    for old_col in ['Código de material', 'Код мат-ла', 'п/п  Код материалов', 'Код']:
        if old_col in df_all.columns:
            if 'Код материалов' in df_all.columns:
                df_all['Код материалов'] = df_all.loc[:, old_col].combine_first(df_all['Код материалов'])
            else:
                df_all['Код материалов'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Код материалов' in df_all.columns:
        col = df_all.pop('Код материалов')  
        df_all.insert(0, 'Код материалов', col) 

    if 'Версия  Кол-' in df_all.columns:
        df_all['Версия'] = df_all.loc[:, 'Версия  Кол-'].combine_first(df_all['Версия'])
        df_all = df_all.drop(columns='Версия  Кол-')

    for old_col in ['Part No.']:
        if old_col in df_all.columns:
            if 'Material No.' in df_all.columns:
                df_all['Material No.'] = df_all.loc[:, old_col].combine_first(df_all['Material No.'])
            else:
                df_all['Material No.'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Material No.' in df_all.columns:
        col = df_all.pop('Material No.')  
        df_all.insert(0, 'Material No.', col) 

    for old_col in ['Note']:
        if old_col in df_all.columns:
            if 'Remark' in df_all.columns:
                df_all['Remark'] = df_all.loc[:, old_col].combine_first(df_all['Remark'])
            else:
                df_all['Remark'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Remark' in df_all.columns:
        col = df_all.pop('Remark')  
        df_all.insert(3, 'Remark', col) 

    for col in ['Кол-во', 'Qty', '件数']:
        if col in df_all.columns:
            df_all[col] = df_all[col].replace({'/': 0, '、': 0, 'A': 0})
            df_all[col] = df_all[col].fillna(0)
            df_all[col] = df_all[col].astype(int)
    
    df_all.to_excel('df_all.xlsx', index=False)
    df_all = pd.read_excel('df_all.xlsx')
    test_1 = pd.read_excel('dfs.xlsx')
    assert test_1.shape[0] == df_all.shape[0]

    for col in ['Material No.', 'Код материалов', '物料编码']:
        if col in df_all.columns:
            df_all = df_all[df_all[col] != '']
            df_all = df_all[~df_all[col].isna()]

    display(df_all.head())

    if 'Material No.' in df_all.columns and df_all['Material No.'].astype(str).str.contains('NO-NUMBER').any():
        df_all['Material No.'] = df_all['Material No.'].str.split('\n').str[0]
        df_all = df_all[~df_all['Material No.'].astype(str).str.startswith('NO-NUMBER')]

    if 'Код материалов' in df_all.columns and df_all['Код материалов'].astype(str).str.contains('NO-NUMBER').any():
        df_all = df_all[~df_all['Код материалов'].astype(str).str.startswith('NO-NUMBER')]

    cols = df_all.select_dtypes(include='object').columns
    df_all[cols] = (df_all[cols].replace(r'\s*\n\s*', ' ', regex=True))
    df_all[cols] = df_all[cols].replace(replacements, regex=True)

    if 'Item and Spec' in df_all.columns:
        df_all['Item and Spec'] = df_all['Item and Spec'].replace('/', np.nan)
    
    if '物料编码' in df_all.columns:
        mask = df_all['物料编码'].str.contains(r'^\d+\s+\D', na=False)
        extracted = df_all.loc[mask, '物料编码'].str.extract(r'^(\d+)\s+(.*)$')
        df_all.loc[mask, '物料编码'] = extracted[0]
        df_all.loc[mask, '名称及规格'] = extracted[1]

    df_merged = merge_parts(df_all) 
   
    assert (df_all.shape[0] - df_all.iloc[:, 0].duplicated().sum() - df_merged.shape[0]) == 0

    lst = ['ZS1623RT', 'ZA10RJE', 'ZA14J', 'ZA14JE-Li', 'ZA14NJE', 'ZA16J', 'ZA16JERT', 'ZA18J', 'ZA20J', 'ZA20JE', 'ZA20JERT', 'ZA22J-V' ,'ZA22J', 'ZA24J', 'ZA32J(H-образ.)', 'ZA32J(X-образ.)', 'ZT42J-V', 'ZA42J', '', '', '', '', '', '', '', '', '' ,'', '', 'ZT20J', 'ZT22J-V', 'ZT26J', 'ZT26JS-V', 'ZT30J', 'ZT32J-V', 'ZT32J', 'ZT34J']
    df_merged['Models'] = lst[b]

    df_merged.to_excel(f'{filename}.xlsx', index=False)

  0%|          | 0/1 [00:00<?, ?it/s]

Обработка файла: ZT34J

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773406200210000,Электрический шкаф\r\nуправления платформой в\...,1,NaN,Рабочая платформа00771100100000000
1,1040200503,Гайка M8-8,6,GB/T 889.1-2000,Рабочая платформа00771100100000000
2,1040302480,Шайба 8-200HV,12,GB/T 96.1-2002,Рабочая платформа00771100100000000
3,00773406300201030,Резиновая прокладка,2,NaN,Рабочая платформа00771100100000000
4,1040004619,Болт M8×35-8.8,4,GB/T 5783-2000,Рабочая платформа00771100100000000
5,1040201896,Гайка M6-8,13,GB/T 889.1-2000,Рабочая платформа00771100100000000
6,1040300771,Шайба 6-200HV,23,GB/T 97.1-2002,Рабочая платформа00771100100000000
7,00773400100261110,Упор,2,NaN,Рабочая платформа00771100100000000
8,1040006017,Винт M6×25-A2-70,9,GB/T 70.1-2000,Рабочая платформа00771100100000000
9,00773400100260020,Защитный кожух,1,NaN,Рабочая платформа00771100100000000
10,00773400200261060,Болт,2,NaN,Рабочая платформа00771100100000000
11,00773400100261050,Подшип.,2,NaN,Рабочая платформа00771100100000000
12,1040005844,Болт M6×10-A2-70,4,GB/T 5783-2000,Рабочая платформа00771100100000000
13,00773400100261030,Плита II,1,NaN,Рабочая платформа00771100100000000
14,1040102646,Винт M6×12-8.8,2,GB/T 70.3-2000,Рабочая платформа00771100100000000
15,00773400100261080,Перегородка,2,NaN,Рабочая платформа00771100100000000
16,1020521022,Педальный переключатель,1,NaN,Рабочая платформа00771100100000000
17,00771400100201020,Самодельная шайба,3,NaN,Рабочая платформа00771100100000000
18,00771400100401080,Самодельный болт,1,NaN,Рабочая платформа00771100100000000
19,1040004653,Болт M12×30-10.9,18,GB/T 5783-2000,Рабочая платформа00771100100000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040302490,Шайба 12-200HV,16,GB/T 97.1-2002,Рабочая платформа00771100100000000
1,00771600100001040,Регулировочная прокладка\r\nкачающегося цилиндра,1,NaN,Рабочая платформа00771100100000000
2,1040301511,Шайба 24-200HV,3,GB/T 97.1-2002,Рабочая платформа00771100100000000
3,1040201111,Гайка M24-10,1,GB/T 889.1-2000,Рабочая платформа00771100100000000
4,1040302821,Шайба 12-200HV,2,GB/T 96.1-2002,Рабочая платформа00771100100000000
5,00771600100200000,Узел платформы,1,NaN,Рабочая платформа00771100100000000
6,00771600100400000,Узел кронштейна,1,NaN,Рабочая платформа00771100100000000
7,1040102372,Винт M4×20-A2-70,2,GB/T 70.1-2000,Рабочая платформа00771100100000000
8,00771600101400000,Защитная крышка\r\nгидравлического клапана\r\n...,1,NaN,Рабочая платформа00771100100000000
9,00771600101600000,Сварная конструкция рамы\r\nгидравлического кл...,1,NaN,Рабочая платформа00771100100000000
10,00771600101000000,Кронштейн фильтра,1,NaN,Рабочая платформа00771100100000000
11,1040101643,Винт M6×30-A2-70,2,GB/T 70.1-2000,Рабочая платформа00771100100000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773400100230000,Вращающаяся дверь,1,NaN,Узел платформы 00771600100200000
1,1101000138,Возвратный шарнир,2,NaN,Узел платформы 00771600100200000
2,1040006016,Винт M6×10-A2-70,16,GB/T 70.3-2000,Узел платформы 00771600100200000
3,00771600100210000,Сварная конструкция\r\nплатформы,1,NaN,Узел платформы 00771600100200000
4,00773400100201020,Сердцевина замка,1,NaN,Узел платформы 00771600100200000
5,00775600101801020,Пружина,1,NaN,Узел платформы 00771600100200000
6,1040004522,Болт,1,GB/T 5783-2000,Узел платформы 00771600100200000
7,1040301515,Шайба 8-200HV,2,GB/T 97.1-2002,Узел платформы 00771600100200000
8,1040201880,Гайка M8-6,1,GB/T 802-1988,Узел платформы 00771600100200000
9,1040201902,Гайка M6-6,12,GB/T 802-1988,Узел платформы 00771600100200000
10,1040300771,Шайба 6-200HV,14,GB/T 97.1-2002,Узел платформы 00771600100200000
11,00773400100201010,Перегородка I,1,NaN,Узел платформы 00771600100200000
12,1040300735,Шайба 6-200HV,10,GB/T 96.1-2002,Узел платформы 00771600100200000
13,1040102773,Винт M6×40-8.8,6,GB/T 70.1-2000,Узел платформы 00771600100200000
14,1040102774,Винт M6×15-8.8,6,GB/T 70.1-2000,Узел платформы 00771600100200000
15,1999904986,Файловая коробка,1,NaN,Узел платформы 00771600100200000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004619,Болт M8×35-8.8,4,GB/T 5783-2000,Узел кронштейна 00771600100400000
1,1040301515,Шайба 8-200HV,16,GB/T 97.1-2002,Узел кронштейна 00771600100400000
2,00773400100401020,Прижимная планка,2,NaN,Узел кронштейна 00771600100400000
3,1040004654,Болт M16×1.5×40-10.9,8,GB/T 5787-1986,Узел кронштейна 00771600100400000
4,1040301511,Шайба 24-200HV,8,GB/T 97.1-2002,Узел кронштейна 00771600100400000
5,00771600100420000,Переходный держатель,1,NaN,Узел кронштейна 00771600100400000
6,1021404016,Датчик веса,1,NaN,Узел кронштейна 00771600100400000
7,00771600100410000,Сварная деталь кронштейна,1,NaN,Узел кронштейна 00771600100400000
8,00771600100001030,Защитный крюк платформы II,2,NaN,Узел кронштейна 00771600100400000
9,1040302493,Шайба 20-200HV,4,GB/T 97.1-2002,Узел кронштейна 00771600100400000
10,1040004499,Болт M20×45-8.8,4,GB/T 5783-2000,Узел кронштейна 00771600100400000
11,1040201089,Гайка M8-8,6,GB/T 6170-2000,Узел кронштейна 00771600100400000
12,00773400100401040,Вкладыш,3,NaN,Узел кронштейна 00771600100400000
13,1040301510,Шайба,6,GB/T 93-1987,Узел кронштейна 00771600100400000
14,1040103118,Винт M8×100-8.8,6,GB/T 70.1-2000,Узел кронштейна 00771600100400000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040201089,Гайка M8-8,4,GB/T 6170-2000,Консоль 00771400210000000
1,1040301515,Шайба 8-200HV,30,GB/T 97.1-2002,Консоль 00771400210000000
2,00771400210001220,Шнек консоли I,4,NaN,Консоль 00771400210000000
3,00771400210001190,Коробка трубопроводов консоли,1,NaN,Консоль 00771400210000000
4,00771400210001210,Верхняя зажимная пластина\r\nтрубопровода консоли,2,NaN,Консоль 00771400210000000
5,00771400210001200,Нижняя зажимная пластина\r\nтрубопровода консоли,2,NaN,Консоль 00771400210000000
6,1021404015,Датчик наклона,1,NaN,Консоль 00771400210000000
7,00771400200001200,Защитный кожух датчика,1,NaN,Консоль 00771400210000000
8,1040103111,Винт M8×16-8.8,2,GB/T 70.1-2000,Консоль 00771400210000000
9,00771400210200000,Верхний шатун,1,NaN,Консоль 00771400210000000
10,00771400210001120,Самосмазывающийся\r\nподшипник II,2,NaN,Консоль 00771400210000000
11,00771400210001080,Распорная втулка качающегося\r\nцилиндра,1,NaN,Консоль 00771400210000000
12,1010201527,Качающийся цилиндр,1,NaN,Консоль 00771400210000000
13,1040102037,Винт M8×70-10.9-DKL,2,GB/T 70.1-2000,Консоль 00771400210000000
14,00771400210001020,Передний штифт верхнего\r\nшатуна,1,NaN,Консоль 00771400210000000
15,1040200503,Гайка M8-8,10,GB/T 889.1-2000,Консоль 00771400210000000
16,00771400210001110,Самосмазывающийся\r\nподшипник,2,NaN,Консоль 00771400210000000
17,00771400210400000,Нижний шатун,1,NaN,Консоль 00771400210000000
18,1040103116,Винт M8×75-10.9,8,GB/T 70.1-2000,Консоль 00771400210000000
19,00771400210001070,Передний штифт нижнего\r\nшатуна,1,NaN,Консоль 00771400210000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771400210001130,Самосмазывающийся\r\nподшипник III,2,NaN,Консоль 00771400210000000
1,00771400210001170,Распорная втулка\r\nгидроцилиндра выравнивания...,1,NaN,Консоль 00771400210000000
2,1040004511,Болт M12×30-8.8,2,GB/T 5783-2000,Консоль 00771400210000000
3,00771400210001180,Стопорный штифт,2,NaN,Консоль 00771400210000000
4,00771400210001030,Штифт гидроцилиндра\r\nверхнего шатуна,1,NaN,Консоль 00771400210000000
5,00771400210001140,Самосмазывающийся\r\nподшипник IV,4,NaN,Консоль 00771400210000000
6,00771400210800000,Опора II,1,NaN,Консоль 00771400210000000
7,00771400210001040,Задний штифт верхнего шатуна,1,NaN,Консоль 00771400210000000
8,00771400210001160,Распорная втулка\r\nгидроцилиндра выравнивания...,1,NaN,Консоль 00771400210000000
9,00771400211000000,Гидроцилиндр изменения\r\nвылета консоли,1,NaN,Консоль 00771400210000000
10,00773400400001020,Передний штифт верхнего\r\nшатуна,1,NaN,Консоль 00771400210000000
11,00771400210001010,Штифт нижнего шатуна,1,NaN,Консоль 00771400210000000
12,00771400210001060,Нижний штифт опоры,1,NaN,Консоль 00771400210000000
13,00771400210001050,Верхний штифт опоры,1,NaN,Консоль 00771400210000000
14,00771400211200000,Регулируемый трубный зажим,2,NaN,Консоль 00771400210000000
15,1040004590,Болт M8×14-8.8,4,GB/T 5783-2000,Консоль 00771400210000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004570,Болт M16×30-8.8,2,GB/T5783-2000,Стрела в сборе 00771600300000000
1,00773400400001250,Стопорный штифт,2,NaN,Стрела в сборе 00771600300000000
2,00771600301001170,Штифт гидроцилиндра,2,NaN,Стрела в сборе 00771600300000000
3,00771600300201110,Диск,2,NaN,Стрела в сборе 00771600300000000
4,00771600301010000,Гидроцилиндр\r\nвыдвижения-втягивания,1,NaN,Стрела в сборе 00771600300000000
5,1040004522,Болт M8×50-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
6,1040301515,Шайба 8,3,GB/T97.1-2002,Стрела в сборе 00771600300000000
7,00771600800001100,Труб. зажим I,4,NaN,Стрела в сборе 00771600300000000
8,1040101643,Винт M6×30-A2-70,2,GB/T70.1-2000,Стрела в сборе 00771600300000000
9,1040302487,Шайба 6,2,NaN,Стрела в сборе 00771600300000000
10,00771400710001080,Основание крепления кабеля,1,NaN,Стрела в сборе 00771600300000000
11,00771600300200000,1-я секция стрелы,1,NaN,Стрела в сборе 00771600300000000
12,00771600301220000,Боковая противопылевая щетка,2,NaN,Стрела в сборе 00771600300000000
13,00771600301410000,Верхняя противопылевая щетка,1,NaN,Стрела в сборе 00771600300000000
14,00771600301230000,Нижняя противопылевая щетка,1,NaN,Стрела в сборе 00771600300000000
15,1040004591,Болт M4×8-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
16,1040302484,Шайба4,4,NaN,Стрела в сборе 00771600300000000
17,00771900310001060,Крышка датчика,1,NaN,Стрела в сборе 00771600300000000
18,1040002433,Болт M10×20-8.8,16,GB/T5783-2000,Стрела в сборе 00771600300000000
19,00771400301401080,Регулировочная прокладка IV,8,NaN,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773400300001140,Регулировочная прокладка V,12,NaN,Стрела в сборе 00771600300000000
1,00771100301270000,Сухарь,6,NaN,Стрела в сборе 00771600300000000
2,1040004508,Болт M10×45-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
3,1040302489,Шайба 10,36,NaN,Стрела в сборе 00771600300000000
4,1040002434,Болт M10×25-8.8,10,GB/T5783-2000,Стрела в сборе 00771600300000000
5,1040201111,Гайка M24,3,GB/T889-1986,Стрела в сборе 00771600300000000
6,1040201092,Гайка M24,3,GB/T6170-2000,Стрела в сборе 00771600300000000
7,1040301511,Шайба M24,1,GB/T97.1-2002,Стрела в сборе 00771600300000000
8,1040200741,Гайка M20,2,GB/T889.1-2000,Стрела в сборе 00771600300000000
9,1040201093,Гайка M20,2,GB/T6170-2000,Стрела в сборе 00771600300000000
10,1040302493,Шайба M20,2,NaN,Стрела в сборе 00771600300000000
11,00771600301070000,Устройство для регулировки\r\nнатяжения,1,NaN,Стрела в сборе 00771600300000000
12,1040002434,Болт M10×25-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
13,00771600301050000,Неподвижный шкив,2,NaN,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040002435,Болт M10×35-8.8,10,GB/T5783-2000,Стрела в сборе 00771600300000000
1,1040302489,Шайба 10,24,NaN,Стрела в сборе 00771600300000000
2,00771600301001400,Прижимная планка,2,NaN,Стрела в сборе 00771600300000000
3,00771600300400000,2-я секция,1,NaN,Стрела в сборе 00771600300000000
4,00771100301270000,Сухарь,10,NaN,Стрела в сборе 00771600300000000
5,00771400301401080,Регулировочная прокладка IV,8,NaN,Стрела в сборе 00771600300000000
6,00773400300001140,Регулировочная прокладка V,8,NaN,Стрела в сборе 00771600300000000
7,1040002433,Болт M10×20-8.8,8,GB/T5783-2000,Стрела в сборе 00771600300000000
8,00771600301450000,Сухарь,2,NaN,Стрела в сборе 00771600300000000
9,00771600301401050,Регулировочная прокладка,4,NaN,Стрела в сборе 00771600300000000
10,1040002434,Болт M10×25-8.8,10,GB/T5783-2000,Стрела в сборе 00771600300000000
11,00771600301430000,Сухарь,2,NaN,Стрела в сборе 00771600300000000
12,00771600301460000,Сухарь,1,NaN,Стрела в сборе 00771600300000000
13,00771600301410000,Верхняя противопылевая щетка,1,NaN,Стрела в сборе 00771600300000000
14,00771600301420000,Боковая противопылевая щетка,2,NaN,Стрела в сборе 00771600300000000
15,1040200507,Гайка M12,5,GB/T889.1-2000,Стрела в сборе 00771600300000000
16,1040201381,Гайка M12,4,GB/T6170-2000,Стрела в сборе 00771600300000000
17,1040302490,Шайба 12,14,GB/T97.1-2002,Стрела в сборе 00771600300000000
18,00771600300401160,Ограничительная труба,6,NaN,Стрела в сборе 00771600300000000
19,00771600301001110,2-й стальной канат выдвижения\r\nстрелы,4,NaN,Стрела в сборе 00771600300000000
20,1040200161,Гайка M16,2,GB/T889-1986,Стрела в сборе 00771600300000000
21,1040201382,Гайка M16,2,GB/T6170-2000,Стрела в сборе 00771600300000000
22,1040302492,Шайба 16,2,NaN,Стрела в сборе 00771600300000000
23,00771600301001120,2-й стальной канат втягивания\r\nстрелы,2,NaN,Стрела в сборе 00771600300000000
24,1040004509,Болт M10×50-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
25,00771600301001430,Соед. планка,2,NaN,Стрела в сборе 00771600300000000
26,00771600301110000,Сварная конструкция\r\nнаправляющего шкива,2,NaN,Стрела в сборе 00771600300000000
27,00771600301001410,Защитная пластина стального\r\nканата,2,NaN,Стрела в сборе 00771600300000000
28,1040004511,Болт M12×30-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
29,1040200504,Гайка M10,4,GB/T889.1-2000,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600300600000,3-я секция стрелы,1,NaN,Стрела в сборе 00771600300000000
1,00771100301270000,Сухарь,10,NaN,Стрела в сборе 00771600300000000
2,00773400300001140,Регулировочная прокладка V,12,NaN,Стрела в сборе 00771600300000000
3,00771400301401080,Регулировочная прокладка IV,12,NaN,Стрела в сборе 00771600300000000
4,1040302489,Шайба 10,36,NaN,Стрела в сборе 00771600300000000
5,1040002433,Болт M10×20-8.8,16,GB/T5783-2000,Стрела в сборе 00771600300000000
6,00771600301630000,Сухарь,2,NaN,Стрела в сборе 00771600300000000
7,00771400301401090,Регулировочная прокладка V,4,NaN,Стрела в сборе 00771600300000000
8,1040002434,Болт M10×25-8.8,11,GB/T5783-2000,Стрела в сборе 00771600300000000
9,1040002435,Болт M10×35-8.8,10,GB/T5783-2000,Стрела в сборе 00771600300000000
10,00771600301430000,Сухарь,2,NaN,Стрела в сборе 00771600300000000
11,00771600301420000,Боковая противопылевая\r\nщетка,2,NaN,Стрела в сборе 00771600300000000
12,00771600301610000,Верхняя противопылевая\r\nщетка,1,NaN,Стрела в сборе 00771600300000000
13,00771400301601020,Не требующий смазки\r\nподшипник,2,NaN,Стрела в сборе 00771600300000000
14,00771600301001290,Цапфа шкива IV,1,NaN,Стрела в сборе 00771600300000000
15,00771600301001020,Шкив выдвижения стрелы II,1,NaN,Стрела в сборе 00771600300000000
16,00771600301001210,Штифт шкива IV,1,NaN,Стрела в сборе 00771600300000000
17,00771600301001350,Стопорный штифт,1,NaN,Стрела в сборе 00771600300000000
18,1040004595,Болт M10×180-8.8,3,GB/T5782-2000,Стрела в сборе 00771600300000000
19,00771600301001060,Шкив выдвижения стрелы II\r\nЗащитная пластина,2,NaN,Стрела в сборе 00771600300000000
20,1040200504,Гайка M10,3,GB/T889.1-2000,Стрела в сборе 00771600300000000
21,00771600301440000,Сухарь,2,NaN,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600300800000,4-я секция стрелы,1,NaN,Стрела в сборе 00771600300000000
1,00771100301270000,Сухарь,4,NaN,Стрела в сборе 00771600300000000
2,00771400301401080,Регулировочная прокладка IV,4,NaN,Стрела в сборе 00771600300000000
3,00773400300001140,Регулировочная прокладка V,4,NaN,Стрела в сборе 00771600300000000
4,1040302489,Шайба 10,22,NaN,Стрела в сборе 00771600300000000
5,1040002433,Болт M10×20-8.8,8,GB/T5783-2000,Стрела в сборе 00771600300000000
6,00771600301630000,Сухарь,2,NaN,Стрела в сборе 00771600300000000
7,00771400301401090,Регулировочная прокладка V,4,NaN,Стрела в сборе 00771600300000000
8,1040002434,Болт M10×25-8.8,2,GB/T5783-2000,Стрела в сборе 00771600300000000
9,1040002435,Болт M10×35-8.8,2,GB/T5783-2000,Стрела в сборе 00771600300000000
10,00771600301430000,Сухарь,2,NaN,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040002434,Болт M10×25-8.8,10,GB/T5783-2000,Стрела в сборе 00771600300000000
1,00771600301001250,Стопорный штифт,2,NaN,Стрела в сборе 00771600300000000
2,00771600301001190,Штифт шкива II,2,NaN,Стрела в сборе 00771600300000000
3,00771600301001160,Цапфа шкива II,2,NaN,Стрела в сборе 00771600300000000
4,00771400200001040,φ32 Подшипник с волоконным\r\nпокрытием,2,NaN,Стрела в сборе 00771600300000000
5,00771600301001080,Шкив втягивания стрелы II\r\nЗащитная пластина,2,NaN,Стрела в сборе 00771600300000000
6,00771600301001040,Шкив втягивания стрелы II,2,NaN,Стрела в сборе 00771600300000000
7,00771600301001260,Прижимная планка шкива II,2,NaN,Стрела в сборе 00771600300000000
8,1040302489,Шайба 10,46,NaN,Стрела в сборе 00771600300000000
9,1040004509,Болт M10×50-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
10,1040004535,Болт M10×60-8.8,8,GB/T5782-2000,Стрела в сборе 00771600300000000
11,1040002433,Болт M10×20-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
12,00771600301001120,2-й стальной канат втягивания\r\nстрелы,2,NaN,Стрела в сборе 00771600300000000
13,1040201111,Гайка M24,3,GB/T889-1986,Стрела в сборе 00771600300000000
14,1040201092,Гайка M24,3,GB/T6170-2000,Стрела в сборе 00771600300000000
15,1040301511,Шайба 24,3,NaN,Стрела в сборе 00771600300000000
16,1040004512,Болт M12×60-8.8,2,GB/T5783-2000,Стрела в сборе 00771600300000000
17,00771600301001220,Монтажная панель датчика,2,NaN,Стрела в сборе 00771600300000000
18,1040302490,Шайба 12,14,NaN,Стрела в сборе 00771600300000000
19,00771600301001320,Пружина,2,NaN,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600301031030,Основание,1,NaN,Стрела в сборе 00771600300000000
1,00771600301001310,Изогнутая пластина,1,NaN,Стрела в сборе 00771600300000000
2,1040301515,Шайба 8,3,NaN,Стрела в сборе 00771600300000000
3,1040004517,Болт M8×16-8.8,3,GB/T5783-2000,Стрела в сборе 00771600300000000
4,1040002442,Болт M12×70-8.8,3,GB/T5783-2000,Стрела в сборе 00771600300000000
5,00771600301001140,Стопор,1,NaN,Стрела в сборе 00771600300000000
6,00771600301001130,Кронштейн стального каната II,1,NaN,Стрела в сборе 00771600300000000
7,00771600300200000,1-я секция стрелы,1,NaN,Стрела в сборе 00771600300000000
8,00771600300400000,2-я секция,1,NaN,Стрела в сборе 00771600300000000
9,00771600300600000,3-я секция стрелы,1,NaN,Стрела в сборе 00771600300000000
10,00771600301001090,1-й стальной канат\r\nвыдвижения стрелы,2,NaN,Стрела в сборе 00771600300000000
11,00771600301010000,Гидроцилиндр\r\nвыдвижения-втягивания,1,NaN,Стрела в сборе 00771600300000000
12,1040200507,Гайка M12,5,GB/T889.1-2000,Стрела в сборе 00771600300000000
13,00771600301150000,Блок роликов стального каната,1,NaN,Стрела в сборе 00771600300000000
14,1040000227,Болт M12×140-8.8,1,GB/T5782-2000,Стрела в сборе 00771600300000000
15,00771600301001350,Стопорный штифт,2,NaN,Стрела в сборе 00771600300000000
16,00771600301001180,Штифт шкива I,2,NaN,Стрела в сборе 00771600300000000
17,00771600301001330,Не требующий смазки\r\nподшипник,2,NaN,Стрела в сборе 00771600300000000
18,00771600301001150,Цапфа шкива I,2,NaN,Стрела в сборе 00771600300000000
19,00771600301001070,Шкив втягивания стрелы I\r\nЗащитная пластина,2,NaN,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600301001030,Шкив втягивания стрелы I,2,NaN,Стрела в сборе 00771600300000000
1,00771600301001240,Прижимная планка шкива I,2,NaN,Стрела в сборе 00771600300000000
2,00771600301001010,Шкив выдвижения стрелы I,1,NaN,Стрела в сборе 00771600300000000
3,00773400300001050,Подшип.,2,NaN,Стрела в сборе 00771600300000000
4,00771600301001270,Цапфа шкива III,1,NaN,Стрела в сборе 00771600300000000
5,00771600301001200,Болт M10×20-8.8,4,GB/T5783-2000,Стрела в сборе 00771600300000000
6,00771600301001120,Штифт шкива III,1,NaN,Стрела в сборе 00771600300000000
7,00771600301001100,1-й стальной канат втягивания\r\nстрелы,2,NaN,Стрела в сборе 00771600300000000
8,1040000279,Болт M10×180-8.8,1,GB/T5782-2000,Стрела в сборе 00771600300000000
9,1040302512,Шайба 10,6,NaN,Стрела в сборе 00771600300000000
10,00771600301001280,Сухарь,2,NaN,Стрела в сборе 00771600300000000
11,1040004594,Болт M10×140-8.8,2,GB/T5782-2000,Стрела в сборе 00771600300000000
12,1040004593,Болт M10×55-8.8,6,GB/T5783-2000,Стрела в сборе 00771600300000000
13,1040002435,Болт M10×35-8.8,6,GB/T5783-2000,Стрела в сборе 00771600300000000
14,00771600301120000,Кронштейн направляющего\r\nшкива,1,NaN,Стрела в сборе 00771600300000000
15,00771600301001360,Шкив выдвижения стрелы I\r\nКронштейн,1,NaN,Стрела в сборе 00771600300000000
16,1040200504,Гайка M10,20,GB/T889-1986,Стрела в сборе 00771600300000000
17,00773402810001260,Подшип.,2,NaN,Стрела в сборе 00771600300000000
18,00771600301131020,Втулка вала,1,NaN,Стрела в сборе 00771600300000000
19,00771600301131011,Направляющий шкив,1,NaN,Стрела в сборе 00771600300000000
20,00771600301140000,Штифт,1,NaN,Стрела в сборе 00771600300000000
21,1040004517,Болт M8×16-8.8,3,GB/T5783-2000,Стрела в сборе 00771600300000000

,Код мат-ла,Наименование и спецификация,Кол-в\r\nо\r\nштук,Примечание,Section
0,00771600300000000,Стрела в сборе,1,NaN,Буксирная система 00771600700000000
1,00771600701200000,Длинная стальная буксируемая\r\nцепь,1,NaN,Буксирная система 00771600700000000
2,00771600700400000,Опорная труба длинной цепи,1,NaN,Буксирная система 00771600700000000
3,00771600701400000,Короткая стальная буксируемая\r\nцепь,1,NaN,Буксирная система 00771600700000000
4,00771600700600000,Опорная труба короткой цепи,1,NaN,Буксирная система 00771600700000000
5,00771600700001110,Опорная плита,6,NaN,Буксирная система 00771600700000000
6,1040002433,Болт M10×20-8.8,12,GB/T5783-2000,Буксирная система 00771600700000000
7,1040302489,Шайба 10-200HV,44,GB/T97.1-2002,Буксирная система 00771600700000000
8,00771600700001060,Внешний трубный зажим,6,NaN,Буксирная система 00771600700000000
9,00771600700001050,Внутренний трубный зажим,6,NaN,Буксирная система 00771600700000000
10,1040102773,Винт M6×40-8.8,12,GB/T70.1-2000,Буксирная система 00771600700000000
11,00771600700001070,Регулировочная прокладка,2,NaN,Буксирная система 00771600700000000
12,1040301502,Шайба 10,8,GB/T93-1987,Буксирная система 00771600700000000
13,1040103121,Винт M10×35-8.8,16,GB/T70.2-2000,Буксирная система 00771600700000000
14,1040004565,Болт M10×30-8.8,8,GB/T5783-2016,Буксирная система 00771600700000000
15,00771600701600000,Неподвижный кронштейн,1,NaN,Буксирная система 00771600700000000
16,00771600700001030,Сухарь,2,NaN,Буксирная система 00771600700000000
17,00771600700001040,Неподвижная плита,2,NaN,Буксирная система 00771600700000000
18,1040103115,Винт M8×65-8.8,9,GB/T70.1-2000,Буксирная система 00771600700000000
19,00771600700001080,Регулировочная прокладка,2,NaN,Буксирная система 00771600700000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600700800000,Кронштейн опорной трубы,1,NaN,Буксирная система 00771600700000000
1,00771400700001010,Шайба,4,NaN,Буксирная система 00771600700000000
2,1040301515,Шайба 8-200HV,13,GB/T97.1-2002,Буксирная система 00771600700000000
3,1040200503,Гайка M8-8,20,GB/T889.1-2000,Буксирная система 00771600700000000
4,1040102738,Винт M8×55-8.8,5,GB/T70.1-2000,Буксирная система 00771600700000000
5,1040102648,Винт M8×25-A2-70,6,GB/T70.2-2000,Буксирная система 00771600700000000
6,00771600701000000,Поворотный кронштейн,1,NaN,Буксирная система 00771600700000000
7,1040200504,Гайка M10-8,24,GB/T889.1-2000,Буксирная система 00771600700000000
8,00771600700001010,Прижимной блок трубопровода,8,NaN,Буксирная система 00771600700000000
9,00771400710001020,Прижимная планка,4,NaN,Буксирная система 00771600700000000
10,1040004656,Болт M10×65-8.8,4,GB/T5782-2000,Буксирная система 00771600700000000
11,1040101995,Винт M10×30-8.8,4,GB/T70.1-2000,Буксирная система 00771600700000000
12,00771600700001090,Трубный направляющий шкив,1,NaN,Буксирная система 00771600700000000
13,00771600700001130,Прижимная планка,2,NaN,Буксирная система 00771600700000000
14,00771600700001120,Трубный зажим,4,NaN,Буксирная система 00771600700000000
15,00771600700001100,Трубная опорная планка,1,NaN,Буксирная система 00771600700000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600800200000,Конструкция поворотной,1,NaN,Поворотная платформа в сборе 00771600800000000
1,00771600800001160,Уплотнительная пластина,3,NaN,Поворотная платформа в сборе 00771600800000000
2,1040300735,Шайба 6-200HV,18,GB/T96.1-2002,Поворотная платформа в сборе 00771600800000000
3,1040002738,Болт M6×12-A2-70,11,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
4,1040004507,Болт M10×40-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
5,1040302512,Шайба 10-200HV,2,GB/T96.1-2002,Поворотная платформа в сборе 00771600800000000
6,00771400800001140,Изогнутая пластина,1,NaN,Поворотная платформа в сборе 00771600800000000
7,1040302513,Шайба 16-200HV,1,GB/T96.1-2002,Поворотная платформа в сборе 00771600800000000
8,1040302492,Шайба 16-200HV,5,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
9,1040002445,Болт M16×35-8.8,1,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
10,1040201875,Гайка M10×8,4,GB/T889.1-2000,Поворотная платформа в сборе 00771600800000000
11,1040004517,Болт M8×16-8.8,8,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
12,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
13,00771400800001220,Монтажный кронштейн,1,NaN,Поворотная платформа в сборе 00771600800000000
14,1040004508,Болт M10×45-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
15,00771400800001100,Вкладыш,1,NaN,Поворотная платформа в сборе 00771600800000000
16,00771400800001110,Регулировочная прокладка,3,NaN,Поворотная платформа в сборе 00771600800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040002434,Болт M10×25-8.8,8,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
1,00773400300001200,Стопорный штифт,1,NaN,Поворотная платформа в сборе 00771600800000000
2,00771400800001030,Штифт,1,NaN,Поворотная платформа в сборе 00771600800000000
3,00771600800001180,Уплотнительная пластина,1,NaN,Поворотная платформа в сборе 00771600800000000
4,00771400801800000,Штепсель в сборке,1,NaN,Поворотная платформа в сборе 00771600800000000
5,00771600800001230,Накладка колодки,1,NaN,Поворотная платформа в сборе 00771600800000000
6,1040300735,Шайба 6-200HV,18,GB/T96.1-2002,Поворотная платформа в сборе 00771600800000000
7,1040002738,Болт M6×12-A2-70,11,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
8,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
9,1040004517,Болт M8×16-8.8,8,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
10,00771600800001050,Монтажный кронштейн,1,NaN,Поворотная платформа в сборе 00771600800000000
11,1040001631,Болт M6×20-A2-70,7,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
12,00771100800001120,Кронштейн электрического,1,NaN,Поворотная платформа в сборе 00771600800000000
13,00771400800001190,Монтажный кронштейн,1,NaN,Поворотная платформа в сборе 00771600800000000
14,1040201865,Гайка M6-8,2,GB/T6170-2000,Поворотная платформа в сборе 00771600800000000
15,00771600800001190,Уплотнительная пластина,1,NaN,Поворотная платформа в сборе 00771600800000000
16,00771600800001200,Уплотнительная пластина,1,NaN,Поворотная платформа в сборе 00771600800000000
17,1040004518,Болт M8×20-8.8,4,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
18,1040301510,Шайба 8,4,GB/T93-1987,Поворотная платформа в сборе 00771600800000000
19,1040200504,Гайка M10-8,5,GB/T889.1-2000,Поворотная платформа в сборе 00771600800000000
20,1040103205,Винт M12×100-8.8,1,GB/T70.1-2000,Поворотная платформа в сборе 00771600800000000
21,00771400800001010,Стопорный штифт,1,NaN,Поворотная платформа в сборе 00771600800000000
22,1040100087,Болт M12×25-8.8,4,GB/T70.1-2000,Поворотная платформа в сборе 00771600800000000
23,00771600801800000,Стопорный кронштейн,1,NaN,Поворотная платформа в сборе 00771600800000000
24,00771600800001300,Опорная плита аккумулятора,1,NaN,Поворотная платформа в сборе 00771600800000000
25,00771600800001260,Дождезащитная пластина,1,NaN,Поворотная платформа в сборе 00771600800000000
26,00771600800001250,Тяга II,1,NaN,Поворотная платформа в сборе 00771600800000000
27,00771600800001090,Прижимная планка I,1,NaN,Поворотная платформа в сборе 00771600800000000
28,00771600800001240,Тяга I,1,NaN,Поворотная платформа в сборе 00771600800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040002434,Болт M10×25-8.8,8,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
1,1040301502,Шайба 10,11,GB/T93-1987,Поворотная платформа в сборе 00771600800000000
2,1040302489,Шайба 10-200HV,18,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
3,00771600800001120,Кронштейн главного клапана,1,NaN,Поворотная платформа в сборе 00771600800000000
4,00771600800001290,Радиатор Соед. планка,1,NaN,Поворотная платформа в сборе 00771600800000000
5,1040004499,Болт M20×40-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
6,00773400400001170,Стопорный штифт,2,NaN,Поворотная платформа в сборе 00771600800000000
7,00771600800001070,Штифт II,1,NaN,Поворотная платформа в сборе 00771600800000000
8,1040002450,Болт M16×80-8.88,1,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
9,1040201882,Гайка M16-8,1,GB/T6172-2000,Поворотная платформа в сборе 00771600800000000
10,1040002433,Болт M10×20-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
11,00771600801400000,Сварка тяги,1,NaN,Поворотная платформа в сборе 00771600800000000
12,00771100800001080,Капот Соед. планка,1,NaN,Поворотная платформа в сборе 00771600800000000
13,00771400800001170,Кожух зубчатого венца,1,NaN,Поворотная платформа в сборе 00771600800000000
14,00771600801600000,Сварка тяги II,1,NaN,Поворотная платформа в сборе 00771600800000000
15,00771600800400000,Кронштейн масляного бака,1,NaN,Поворотная платформа в сборе 00771600800000000
16,1040004565,Болт M10×30-8.8-DKL,11,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
17,00771400800001160,Резиновая прокладка,2,NaN,Поворотная платформа в сборе 00771600800000000
18,00771600801000000,Кронштейн электрического,1,NaN,Поворотная платформа в сборе 00771600800000000
19,00771400800001150,Прокл-ка,4,NaN,Поворотная платформа в сборе 00771600800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600800001220,Контроллер Соед. планка,1,NaN,Поворотная платформа в сборе 00771600800000000
1,1040200504,Гайка M10-8,5,GB/T889.1-200,Поворотная платформа в сборе 00771600800000000
2,00771400802400000,Кронштейн электрического,1,NaN,Поворотная платформа в сборе 00771600800000000
3,1040004615,Болт M16×110-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
4,1040002458,Болт M8×40-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
5,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
6,00771600800001100,Труб. зажим I,2,NaN,Поворотная платформа в сборе 00771600800000000
7,1040001631,Болт M6×20-A2-70,7,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
8,1040301610,Шайба 6,5,GB/T93-1987,Поворотная платформа в сборе 00771600800000000
9,1040300735,Шайба 6-200HV,18,GB/T96.1-2002,Поворотная платформа в сборе 00771600800000000
10,00771600800001210,Уплотнительная пластина,1,NaN,Поворотная платформа в сборе 00771600800000000
11,1040200161,Гайка M16-8,4,GB/T889-1986,Поворотная платформа в сборе 00771600800000000
12,1040302492,Шайба 16-200HV,5,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
13,1040005847,Болт M16×50-10.9,4,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
14,1040301510,Шайба 8,4,GB/T93-1987,Поворотная платформа в сборе 00771600800000000
15,1040004518,Болт M8×20-8.8,4,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
16,00771600800001320,Резиновая прокладка,1,NaN,Поворотная платформа в сборе 00771600800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771600800001010,Не требующий смазки,4,NaN,Поворотная платформа в сборе 00771600800000000
1,00771600800001040,Распорная втулка I,1,NaN,Поворотная платформа в сборе 00771600800000000
2,00771600800600000,Гидроцилиндр изменения,1,NaN,Поворотная платформа в сборе 00771600800000000
3,1040004499,Болт M20×40-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
4,00773400400001170,Стопорный штифт,2,NaN,Поворотная платформа в сборе 00771600800000000
5,00771600800001030,Штифт,1,NaN,Поворотная платформа в сборе 00771600800000000
6,00771600800001060,Распорная втулка II,1,NaN,Поворотная платформа в сборе 00771600800000000
7,00771600800001110,Прокл-ка,2,NaN,Поворотная платформа в сборе 00771600800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004565,Болт M10×30-8.8-DKL,11,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000
1,1040301502,Шайба 10,11,GB/T93-1987,Поворотная платформа в сборе 00771600800000000
2,1040302489,Шайба 10-200HV,18,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
3,00771600800001020,Опорный блок,1,NaN,Поворотная платформа в сборе 00771600800000000
4,00771600800001150,Концевой выключатель\r\nmонтажная панель,1,NaN,Поворотная платформа в сборе 00771600800000000
5,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Поворотная платформа в сборе 00771600800000000
6,1040200503,Гайка M8-8,2,GB/T889.1-2000,Поворотная платформа в сборе 00771600800000000
7,00771600800001130,Монтажная панель\r\nвращающегося соединения,1,NaN,Поворотная платформа в сборе 00771600800000000
8,1040004519,Болт M8×25-8.8,2,GB/T5783-2000,Поворотная платформа в сборе 00771600800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1031500371,"Поворотный подшипник m=8,\r\nz=130",1,NaN,Поворотный механизм 00771600900000000
1,1040005853,Болт M20×140-10.9,60,GB/T1228-1991,Поворотный механизм 00771600900000000
2,1040302502,Шайба 20,65,GB/T1230-1991,Поворотный механизм 00771600900000000
3,1040004501,Болт M20×60-10.9,5,GB/T5783-2000,Поворотный механизм 00771600900000000
4,1030202324,Поворотный редуктор,1,NaN,Поворотный механизм 00771600900000000
5,1040301503,Шайба 12,2,GB/T93-1987,Поворотный механизм 00771600900000000
6,1040004029,Болт M12×35-10.9,2,GB/T5783-2000,Поворотный механизм 00771600900000000
7,1010101004,Поворотный двигатель,1,NaN,Поворотный механизм 00771600900000000
8,00771400900001010,Фиксирующий штифт,1,NaN,Поворотный механизм 00771600900000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004519,Болт M8×25-8.8,2,GB/T5783-2000,Противовес сборе 00771601000000000
1,1040302483,Шайба 24-200HV,6,GB/T96.1-2002,Противовес сборе 00771601000000000
2,1040004530,Болт M24×70-10.9,6,GB/T1228-1991,Противовес сборе 00771601000000000
3,1040004500,Болт M30×50-8.8,2,GB/T5783-2000,Противовес сборе 00771601000000000
4,1040301515,Шайба 8-200HV,2,GB/T97.1-2002,Противовес сборе 00771601000000000
5,00771601000001060,Плита Tp6,1,NaN,Противовес сборе 00771601000000000
6,1040004678,Болт останова двери M10×70,1,NaN,Противовес сборе 00771601000000000
7,00771601000001070,Противовес,1,NaN,Противовес сборе 00771601000000000
8,00771601000001050,Противовес,1,NaN,Противовес сборе 00771601000000000
9,1040200113,Гайка M10-8,2,GB/T6170-2000,Противовес сборе 00771601000000000
10,00771101000001020,Кронштейн индикатора,1,NaN,Противовес сборе 00771601000000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040001640,Винт M6×25-A2-70,30,GB/T5783-2000,Капот сборе 00771601100000000
1,1040300735,Шайба 6-200HV,60,GB/T96.1-2002,Капот сборе 00771601100000000
2,1040201902,Гайка M6-6,30,GB/T802-1988,Капот сборе 00771601100000000
3,00771601100001040,Уплотняющая плита Tp2,1,NaN,Капот сборе 00771601100000000
4,00771601100001070,Уплотняющая плита Tp2,1,NaN,Капот сборе 00771601100000000
5,00771601100001080,Уплотняющая плита Tp2,1,NaN,Капот сборе 00771601100000000
6,1040200504,Гайка M10-8,2,GB/T889.1-2000,Капот сборе 00771601100000000
7,00771601102001020,Круглая сталь 10,1,NaN,Капот сборе 00771601100000000
8,1040200113,Гайка M10-8,4,GB/T6170-2000,Капот сборе 00771601100000000
9,1040302512,Шайба 10-200HV,8,GB/T96.1-2002,Капот сборе 00771601100000000
10,00771601102001010,Угловая сталь L75×50×6,1,NaN,Капот сборе 00771601100000000
11,1040004507,Болт M10×40-8.8,2,GB/T5783-2000,Капот сборе 00771601100000000
12,00771601100001010,Прижимная планка,2,NaN,Капот сборе 00771601100000000
13,1040302492,Шайба 16-200HV,6,GB/T97.1-2002,Капот сборе 00771601100000000
14,1040301505,Шайба 16,14,GB/T93-1987,Капот сборе 00771601100000000
15,1040201382,Гайка M16-8,14,GB/T6170-2000,Капот сборе 00771601100000000
16,00771601101200000,Монтажный кронштейн левого,2,NaN,Капот сборе 00771601100000000
17,1110100317,Пневматическая пружина\r\n2065UF,4,NaN,Капот сборе 00771601100000000
18,00771601100400000,Сварка левого переднего,1,NaN,Капот сборе 00771601100000000
19,00771601101001020,Винт Φ10,1,NaN,Капот сборе 00771601100000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771601101001010,Плита Tp5,1,NaN,Капот сборе 00771601100000000
1,00771601100001140,Подкладка Tp10,2,NaN,Капот сборе 00771601100000000
2,1040201089,Гайка M8-8,46,GB/T6170-2000,Капот сборе 00771601100000000
3,1040301510,Шайба 8,30,GB/T93-1987,Капот сборе 00771601100000000
4,1101000089,Петля CCM-Z270,6,NaN,Капот сборе 00771601100000000
5,00771601101400000,Монтажный кронштейн левого,1,NaN,Капот сборе 00771601100000000
6,1040302480,Шайба 8-200HV,72,GB/T96.1-2002,Капот сборе 00771601100000000
7,1040004520,Болт M8×30-8.8,34,GB/T5783-2000,Капот сборе 00771601100000000
8,1040100105,Винт M6×25-8.8,27,GB/T70.1-2000,Капот сборе 00771601100000000
9,1040300771,Шайба 6-200HV,27,GB/T97.1-2002,Капот сборе 00771601100000000
10,00771101100001080,Монтажная панель сердцевины,1,NaN,Капот сборе 00771601100000000
11,1100700163,Дверная ручка 26983-09,3,NaN,Капот сборе 00771601100000000
12,1109900765,Гидравлический дверной замок,1,NaN,Капот сборе 00771601100000000
13,1110100324,Пневматическая пружина\r\n555800,2,NaN,Капот сборе 00771601100000000
14,00771601100600000,Сварка левого заднего капота,1,NaN,Капот сборе 00771601100000000
15,1109900766,Замок аккумулятора,2,NaN,Капот сборе 00771601100000000
16,00771401110001020,Монтажная панель сердцевины,1,NaN,Капот сборе 00771601100000000
17,00771601100001100,Трос привода левого переднего,1,NaN,Капот сборе 00771601100000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771601100001090,Уплотняющая плита Tp2,1,NaN,Капот сборе 00771601100000000
1,00771601100001060,Уплотняющая плита Tp2,1,NaN,Капот сборе 00771601100000000
2,00771601100001050,Уплотняющая плита Tp2,1,NaN,Капот сборе 00771601100000000
3,00771601101600000,Монтажный кронштейн,1,NaN,Капот сборе 00771601100000000
4,00771601103200000,Регулировочная пластина,3,NaN,Капот сборе 00771601100000000
5,1040004518,Болт M8×20-8.8,4,GB/T5783-2000,Капот сборе 00771601100000000
6,00771601100200000,Сварка правого переднего,1,NaN,Капот сборе 00771601100000000
7,00771601103600000,Кронштейн,1,NaN,Капот сборе 00771601100000000
8,00771601103001010,Дверное полотно Tp3,1,NaN,Капот сборе 00771601100000000
9,1109800044,Замок с язычком YKGS282SS,1,NaN,Капот сборе 00771601100000000
10,00771601100001020,Изогнутая пластина Tp5,1,NaN,Капот сборе 00771601100000000
11,00771101103001020,Губка изоляции T6,1,NaN,Капот сборе 00771601100000000
12,1040302861,Шайба 8,5,GB/T97.1-2002,Капот сборе 00771601100000000
13,1040202307,Винт M8--A2-70,5,GB/T6170-2015,Капот сборе 00771601100000000
14,1101000152,Петля CCM-Z165,1,NaN,Капот сборе 00771601100000000
15,1040103077,Винт с выпуклой головкой и,5,GB/T818-2000,Капот сборе 00771601100000000
16,00771601100001120,Монтажная панель,1,NaN,Капот сборе 00771601100000000
17,1999905631,Петля LC254-1,1,NaN,Капот сборе 00771601100000000
18,00771101103201010,Плита Tp2,1,NaN,Капот сборе 00771601100000000
19,1040201772,Винт M4--A2-70,8,GB/T6170-2000,Капот сборе 00771601100000000
20,1040302410,Шайба 4-200HV,8,GB/T97.1-2002,Капот сборе 00771601100000000
21,1029903782,Винт с выпуклой головкой и,8,GB/T818-2000,Капот сборе 00771601100000000
22,00771601100800000,Сварка правого заднего капота,1,NaN,Капот сборе 00771601100000000
23,00771101100001020,Монтажная панель,1,NaN,Капот сборе 00771601100000000
24,1040200113,Гайка M10-8,4,GB/T6170-2000,Капот сборе 00771601100000000
25,1040004678,Болт останова двери M10×70,2,NaN,Капот сборе 00771601100000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040002464,Болт M16×50-8.8,4,GB/T5782-2000,Шасси в сборе 00771402800000000
1,00773400400001250,Стопорный штифт,4,NaN,Шасси в сборе 00771402800000000
2,00771602800001210,Плавающий гидроцилиндр II,2,NaN,Шасси в сборе 00771402800000000
3,00771602801400000,Плавающий гидроцилиндр,2,NaN,Шасси в сборе 00771402800000000
4,00771602800001170,Плавающий гидроцилиндр I,2,NaN,Шасси в сборе 00771402800000000
5,00771602800001420,Регулировочная прокладка\r\nползуна качающейся...,4,NaN,Шасси в сборе 00771402800000000
6,00771602800001430,Регулировочная прокладка\r\nползуна качающейся...,4,NaN,Шасси в сборе 00771402800000000
7,1040004508,Болт M10×45-8.8,6,GB/T5783-2000,Шасси в сборе 00771402800000000
8,1040302489,Шайба 10-200HV,98,GB/T97.1-2002,Шасси в сборе 00771402800000000
9,00771602803400000,Узел ползуна качающейся рамы,2,NaN,Шасси в сборе 00771402800000000
10,1040004509,Болт M10×50-8.8,24,GB/T5783-2000,Шасси в сборе 00771402800000000
11,00771602800001240,Верхняя регулировочная\r\nпрокладка выносной о...,12,NaN,Шасси в сборе 00771402800000000
12,00772102800001020,Верхняя регулировочная\r\nпрокладка выносной о...,4,NaN,Шасси в сборе 00771402800000000
13,00772102801400000,Сухарь,8,NaN,Шасси в сборе 00771402800000000
14,1040004507,Болт M10×40-8.8,52,GB/T5783-2000,Шасси в сборе 00771402800000000
15,1040101122,Винт M10×35-8.8,4,GB/T70.3-2000,Шасси в сборе 00771402800000000
16,00771602800001220,Регулировочная прокладка,96,NaN,Шасси в сборе 00771402800000000
17,00772102800001010,Боковая регулировочная\r\nпрокладка выносной о...,32,NaN,Шасси в сборе 00771402800000000
18,00772102801200000,Сухарь,32,NaN,Шасси в сборе 00771402800000000
19,00772102800800000,Сухарь,8,NaN,Шасси в сборе 00771402800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004565,Болт M10×30-8.8-DKL,16,GB/T5783-2016,Шасси в сборе 00771402800000000 Наименование и...
1,00771602800001300,Плита,4,NaN,Шасси в сборе 00771402800000000 Наименование и...
2,1040004245,Болт M8×55-8.8,4,GB/T27-1988,Шасси в сборе 00771402800000000 Наименование и...
3,00771602803200000,Ограничительный штифт,4,NaN,Шасси в сборе 00771402800000000 Наименование и...
4,1040101492,Болт M10×25-8.8,8,GB/T70.1-2000,Шасси в сборе 00771402800000000 Наименование и...
5,00771602800400000,Сварная конструкция\r\nкачающейся рамы,1,NaN,Шасси в сборе 00771402800000000 Наименование и...
6,00771602801200000,Гидроцилиндр\r\nвыдвижения-втягивания\r\nвынос...,4,NaN,Шасси в сборе 00771402800000000 Наименование и...
7,00771602800001320,Регулировочная прокладка\r\nгидроцилиндра\r\nв...,48,NaN,Шасси в сборе 00771402800000000 Наименование и...
8,00771602800001310,Нажимная пластина\r\nгидроцилиндра\r\nвыдвижен...,8,NaN,Шасси в сборе 00771402800000000 Наименование и...
9,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Шасси в сборе 00771402800000000 Наименование и...
10,1040002265,Болт M8×25-10.9,16,GB/T5873-2000,Шасси в сборе 00771402800000000 Наименование и...
11,00771602800610000,Сварная конструкция выносной\r\nопоры,4,NaN,Шасси в сборе 00771402800000000 Наименование и...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004507,Болт M10×40-8.8,4,GB/T5782-2000,Шасси в сборе 00771602800000000
1,1040302489,Шайба 10-200HV,4,GB/T97.1-2002,Шасси в сборе 00771602800000000
2,00771602800001480,Плита,2,NaN,Шасси в сборе 00771602800000000
3,00771602801600000,Буксирная система,4,NaN,Шасси в сборе 00771602800000000
4,1040002178,Болт M6×30-A2-70,16,GB/T5783-2000,Шасси в сборе 00771602800000000
5,1040300771,Шайба 6-200HV,16,GB/T97.1-2002,Шасси в сборе 00771602800000000
6,00771602800001350,Не требующий смазки\r\nподшипник III,2,NaN,Шасси в сборе 00771602800000000
7,00771602800001140,Качающийся штифт,1,NaN,Шасси в сборе 00771602800000000
8,00771602800001410,Износостойкая прокладка\r\nкачающего вала,1,NaN,Шасси в сборе 00771602800000000
9,00773400400001170,Стопорный штифт,1,NaN,Шасси в сборе 00771602800000000
10,1040004499,Болт M20×45-8.8,1,GB/T5783-2000,Шасси в сборе 00771602800000000

,№ п\r\n/п,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примечание,Section
0,1,00771602800610000,Сварная конструкция выносной\r\nопоры,4,NaN,Шасси в сборе 00771602800000000
1,2,1040100421,Винт M8×20-8.8,8,GB/T70.3-2000,Шасси в сборе 00771602800000000
2,3,00771602802200000,Гидроцилиндр рулевого управления,4,NaN,Шасси в сборе 00771602800000000
3,4,00771602800001190,Перегородка,4,NaN,Шасси в сборе 00771602800000000
4,5,00771602800001180,Монтажная панель датчика,4,NaN,Шасси в сборе 00771602800000000
5,6,00771602800001200,Перекрывающая пластина,4,NaN,Шасси в сборе 00771602800000000
6,7,1040100857,Винт M6×15-8.8,20,GB/T70.1-2008,Шасси в сборе 00771602800000000
7,8,1040002434,Болт M10×25-8.8,64,GB/T5783-2000,Шасси в сборе 00771602800000000
8,9,1040302489,Шайба 10-200HV,64,GB/T97.1-2002,Шасси в сборе 00771602800000000
9,10,00771602800001010,Верхний поворотный главный\r\nштифт,4,NaN,Шасси в сборе 00771602800000000
10,11,00771602800001020,Износостойкая пластина,8,NaN,Шасси в сборе 00771602800000000
11,12,00771602800001470,Не требующий смазки подшипник\r\nIV,8,NaN,Шасси в сборе 00771602800000000
12,13,00771602802000000,Сварная конструкция поворотной\r\nрамы,4,NaN,Шасси в сборе 00771602800000000
13,14,1040004520,Болт M8×30-8.8,4,GB/T5783-2000,Шасси в сборе 00771602800000000
14,15,00773400300001070,Подшип.,8,NaN,Шасси в сборе 00771602800000000
15,16,00771602801000000,Гидроцилиндр рулевого управления,4,NaN,Шасси в сборе 00771602800000000
16,17,00771602800001450,Гидроцилиндр рулевого управления\r\npаспорная ...,4,NaN,Шасси в сборе 00771602800000000
17,18,00771602800001080,Гидроцилиндр рулевого управления,4,NaN,Шасси в сборе 00771602800000000
18,19,00771602800001330,Не требующий смазки подшипник I,4,NaN,Шасси в сборе 00771602800000000
19,20,1040004511,Болт M12×30-8.8,4,GB/T5783-2000,Шасси в сборе 00771602800000000
20,21,00773400200001070,Стопорный штифт,4,NaN,Шасси в сборе 00771602800000000
21,22,00771602800001130,Нижняя перекрывающая пластина,4,NaN,Шасси в сборе 00771602800000000
22,23,00771602800001120,Нижний поворотный главный\r\nштифт,4,NaN,Шасси в сборе 00771602800000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040101980,Винт M16×50-10.9-DKL,72,GB/T70.1-2000,Шасси в сборе 00771602800000000
1,00771602802000000,Сварная конструкция\r\nповоротной рамы,4,NaN,Шасси в сборе 00771602800000000
2,1040000575,Болт M12×35-10.9,8,GB/T5783-2000,Шасси в сборе 00771602800000000
3,1040302490,Шайба 12-200HV,8,GB/T97.1-2002,Шасси в сборе 00771602800000000
4,1010100907,Ходовой двигатель,4,NaN,Шасси в сборе 00771602800000000
5,1030202306,Ходовой редуктор,4,NaN,Шасси в сборе 00771602800000000
6,1030800680,Шина,2,NaN,Шасси в сборе 00771602800000000
7,1030800681,NaN,2,NaN,Шасси в сборе 00771602800000000
8,1040201907,Шестигранная фланцевая\r\nгайка M22×1.5-10,40,GB/T6177.2-2016,Шасси в сборе 00771602800000000

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примечание,Section
0,1000000792,Дизельный двигатель,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
1,1040001631,Болт M6×20-A2-70,4,GB/T5783-2000,Монтаж двигателя (Deutz Двигатель) 00771607100...
2,1040003912,Болт M16×50-10.9-DKL,4,GB/T5783-2000,Монтаж двигателя (Deutz Двигатель) 00771607100...
3,00773407100201020,Изогнутая пластина II,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
4,1030400480,Эластичная муфта в сборе,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
5,1040004033,Болт M10×25-10.9,8,GB/T5783-2000,Монтаж двигателя (Deutz Двигатель) 00771607100...
6,00773407100201070,Крышка муфты,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
7,1040100875,Болт M10×25-8.8,12,GB/T70.1-2008,Монтаж двигателя (Deutz Двигатель) 00771607100...
8,1040004513,Болт M14×40-10.9,4,GB/T5783-2000,Монтаж двигателя (Deutz Двигатель) 00771607100...
9,1040302491,Шайба 14-200HV,4,GB/T97.1-2002,Монтаж двигателя (Deutz Двигатель) 00771607100...
10,00771400800001020,Самосмазывающийся подшипник,2,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
11,00771607100210000,Кронштейн двигателя,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
12,00773407100201050,Подкладка,4,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
13,1040200161,Гайка M16-8,4,GB/T889-1986,Монтаж двигателя (Deutz Двигатель) 00771607100...
14,1009900942,Демпфер двигателя,8,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
15,00773407100201010,Изогнутая пластина I,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
16,1040301016,Шайба 16-300HV,4,GB/T97.1-2002,Монтаж двигателя (Deutz Двигатель) 00771607100...
17,00773407100201030,Изогнутая пластина IV,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...
18,1040301867,Шайба 14-140HV,4,GB/T97.1-2002,Монтаж двигателя (Deutz Двигатель) 00771607100...
19,1040000490,Болт M12×30-10.9,4,GB/T5783-2000,Монтаж двигателя (Deutz Двигатель) 00771607100...
20,00773407100201040,Изогнутая пластина III,1,NaN,Монтаж двигателя (Deutz Двигатель) 00771607100...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771607110410000,Топливный бак в сборе,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
1,00771607100401070,Топливная труба,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
2,1990202279,Хомут червяка и червячного\r\nколеса,12,NaN,Топливная система (Deutz Двигатель) 0077160710...
3,00771607100401030,Топливная труба I,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
4,1990200692,"Клейкая лента, покрытая слоем\r\nпластмассы",5,NaN,Топливная система (Deutz Двигатель) 0077160710...
5,1040302487,Шайба 6-200HV,4,GB/T97.1-2002,Топливная система (Deutz Двигатель) 0077160710...
6,1040004663,Винт M6×12-8.8,4,GB/T5782-2000,Топливная система (Deutz Двигатель) 0077160710...
7,00771607100401050,Топливная труба III,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
8,1040004619,Болт M8×35-8.8,2,GB/T5783-2000,Топливная система (Deutz Двигатель) 0077160710...
9,1040302489,Шайба 10-200HV,2,GB/T97.1-2002,Топливная система (Deutz Двигатель) 0077160710...
10,1040002458,Болт M8×40-8.8,2,GB/T5783-2000,Топливная система (Deutz Двигатель) 0077160710...
11,00771607100401040,Топливная труба II,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
12,1000400478,Водо-масляный сепаратор,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
13,00771607100401060,Топливная труба IV,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
14,00771107100401070,Изогнутая пластина,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
15,1040004518,Болт M8×20-8.8,4,GB/T5783-2000,Топливная система (Deutz Двигатель) 0077160710...
16,1040004565,Болт M10×30-8.8-DKL,2,GB/T5783-2016,Топливная система (Deutz Двигатель) 0077160710...
17,00773407100401050,Штуцер II,5,NaN,Топливная система (Deutz Двигатель) 0077160710...
18,1081000673,Комбин. уплот. шайба,10,NaN,Топливная система (Deutz Двигатель) 0077160710...
19,00773407100401060,Пустотелый болт M16×1.5×35,5,NaN,Топливная система (Deutz Двигатель) 0077160710...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1149901739,Быстросъемная муфта,2,NaN,Топливная система (Deutz Двигатель) 0077160710...
1,00771407100401070,Топливная труба VI,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
2,1149901738,Быстросъемная муфта,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
3,00773407100401030,Изогнутая пластина III,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
4,1040004519,Болт M8×25-8.8,2,GB/T5783-2000,Топливная система (Deutz Двигатель) 0077160710...
5,1040301515,Шайба 8-200HV,3,GB/T97.1-2002,Топливная система (Deutz Двигатель) 0077160710...
6,1040200504,Гайка M10-8,2,GB/T889.1-2000,Топливная система (Deutz Двигатель) 0077160710...
7,1040001631,Болт M6×20-A2-70,5,GB/T5783-2000,Топливная система (Deutz Двигатель) 0077160710...
8,1040300771,Шайба 6-200HV,5,GB/T97.1-2002,Топливная система (Deutz Двигатель) 0077160710...
9,00771607100401020,Изогнутая пластина,1,NaN,Топливная система (Deutz Двигатель) 0077160710...
10,1040301735,Шайба 8-100HV,5,GB/T97.1-2002,Топливная система (Deutz Двигатель) 0077160710...
11,1040201896,Гайка M6-8,5,GB/T889.1-2015,Топливная система (Deutz Двигатель) 0077160710...
12,1040201874,Гайка M8-8,2,GB/T889.1-2000,Топливная система (Deutz Двигатель) 0077160710...
13,1040002434,Болт M10×25-8.8,4,GB/T5783-2000,Топливная система (Deutz Двигатель) 0077160710...
14,1040200503,Гайка M8-8,8,GB/T889.1-2000,Топливная система (Deutz Двигатель) 0077160710...
15,1040302480,Шайба 8-200HV,4,GB/T96.1-2002,Топливная система (Deutz Двигатель) 0077160710...
16,1040302512,Шайба 10-200HV,4,GB/T96.1-2002,Топливная система (Deutz Двигатель) 0077160710...

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примечание,Section
0,1040004519,Болт M8×25-8.8,20,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
1,1040301515,Шайба 8-200HV,39,GB/T97.1-2002,Система теплоотдачи (Deutz Двигатель) 00771607...
2,00771407100601240,Плита III,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
3,00771407100601160,Плита I,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
4,00771407100601150,Плита II,2,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
5,00771607100601130,Ветровой щит,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
6,00771607100601120,Изогнутая пластина II,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
7,1040004619,Болт M8×35-8.8,4,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
8,00771407100601100,Изогнутая пластина IV,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
9,00771407100601290,Губка изоляции,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
10,1040004517,Болт M8×16-8.8,11,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
11,00771607100601110,Изогнутая пластина I,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
12,1000300735,Расширительный бак,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
13,1040200503,Гайка M8-8,20,GB/T889.1-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
14,1990202282,Хомут червяка и червячного колеса,2,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
15,1990202279,Хомут червяка и червячного колеса,6,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
16,00771607100601090,Паровой шланг I,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
17,00771607100601070,Паровой шланг II,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
18,00771607100601080,Водопроводная труба,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
19,1990202288,Хомут спирального червяка и\r\nчервячного колеса,6,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
20,00771907100601040,Штуцер шланга III,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
21,1000300702,Вентилятор в сборе,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
22,00771407100601050,Штуцер шланга II,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
23,00771407100601260,Паровой шланг\r\nIII,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
24,00771407100601250,Штуцер,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
25,00771407100601060,Штуцер шланга I,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
26,00771607100601290,Губка изоляции II,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
27,1040002262,Болт M12×55-10.9,4,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
28,1040301031,Шайба 12-300HV,8,GB/T96.1-2002,Система теплоотдачи (Deutz Двигатель) 00771607...
29,00771407100601170,Подкладка,6,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
30,1000300701,Блок радиатора,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
31,1040200507,Гайка M12-8,4,GB/T889.1-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
32,00771407100601110,Изогнутая пластина III,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1000100391,Агрегат воздушного фильтра,1,NaN,Впускная система (Deutz Двигатель) 00771607100...
1,00771407100801010,Впускная труба I,1,NaN,Впускная система (Deutz Двигатель) 00771607100...
2,1990202290,Хомут спирального червяка и\r\nчервячного колеса,3,NaN,Впускная система (Deutz Двигатель) 00771607100...
3,00771407100801020,Впускная труба II,1,NaN,Впускная система (Deutz Двигатель) 00771607100...
4,00771407100801040,Впускная стальная труба,1,NaN,Впускная система (Deutz Двигатель) 00771607100...
5,1990202289,Хомут спирального червяка и\r\nчервячного колеса,2,NaN,Впускная система (Deutz Двигатель) 00771607100...
6,00771407100801030,Впускная труба III,1,NaN,Впускная система (Deutz Двигатель) 00771607100...
7,1040301515,Шайба 8-200HV,2,GB/T97.1-2002,Впускная система (Deutz Двигатель) 00771607100...
8,1040004619,Болт M8×35-8.8,2,GB/T5783-2000,Впускная система (Deutz Двигатель) 00771607100...
9,1040200503,Гайка M8-8,2,GB/T889.1-2000,Впускная система (Deutz Двигатель) 00771607100...
10,1000100391,Агрегат воздушного фильтра,1,NaN,Впускная система (Deutz Двигатель) 00771607100...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771407101001020,Воздуховыпускной труба-хвост,1,NaN,Выхлопная система (Deutz Двигатель) 0077160710...
1,1040004519,Болт M8×25-8.8,16,GB/T5783-2000,Выхлопная система (Deutz Двигатель) 0077160710...
2,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Выхлопная система (Deutz Двигатель) 0077160710...
3,00771407101001030,Усилительная планка,1,NaN,Выхлопная система (Deutz Двигатель) 0077160710...
4,1040200503,Гайка M8-8,16,GB/T889.1-2000,Выхлопная система (Deutz Двигатель) 0077160710...
5,00771607101001010,Выхлопная труба I,1,NaN,Выхлопная система (Deutz Двигатель) 0077160710...
6,00771407121001050,Уплотнительная прокладка I,2,NaN,Выхлопная система (Deutz Двигатель) 0077160710...
7,00771407121001010,Глушитель,1,NaN,Выхлопная система (Deutz Двигатель) 0077160710...
8,1040102216,Винт M10×65-10.9-DKL,4,GB/T70.1-2000,Выхлопная система (Deutz Двигатель) 0077160710...
9,1040301502,Шайба 10,4,GB/T93-1987,Выхлопная система (Deutz Двигатель) 0077160710...
10,00771407111010000,Кронштейн,1,NaN,Выхлопная система (Deutz Двигатель) 0077160710...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1000000796,Дизельный двигатель,1,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
1,00771607110201030,Изогнутая пластина III,1,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
2,00771107120201030,Крышка муфты,1,GB/T5783-2000,Монтаж двигателя (Kohler Двигатель) 0077160711...
3,1040302489,Шайба 10-200HV,12,GB/T97.1-2002,Монтаж двигателя (Kohler Двигатель) 0077160711...
4,1040003028,Болт 3/8-16UNC-2A×30-10.9,12,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
5,1040300561,Шайба 6-200HV,4,GB/T97.1-2002,Монтаж двигателя (Kohler Двигатель) 0077160711...
6,1040002269,Болт M6×16-10.9,4,GB/T5783-2000,Монтаж двигателя (Kohler Двигатель) 0077160711...
7,1040101835,Винт 5/16-18UNC-2A×25-10.9,8,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
8,1009805949,Эластичная муфта в сборе,1,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
9,00771607110201010,Изогнутая пластина I,2,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
10,1040003912,Болт M16×50-10.9-DKL,4,GB/T5783-2000,Монтаж двигателя (Kohler Двигатель) 0077160711...
11,1040301016,Шайба 16-300HV,4,GB/T97.1-2002,Монтаж двигателя (Kohler Двигатель) 0077160711...
12,1009900942,Демпфер двигателя,8,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
13,00773407100201050,Подкладка,4,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
14,1040201887,Гайка M16-8,4,GB/T889.1-2000,Монтаж двигателя (Kohler Двигатель) 0077160711...
15,00771607110201020,Изогнутая пластина II,1,NaN,Монтаж двигателя (Kohler Двигатель) 0077160711...
16,1040004029,Болт M12×35-10.9,14,GB/T5783-2000,Монтаж двигателя (Kohler Двигатель) 0077160711...
17,1040300041,Шайба 12-200HV,14,GB/T97.1-2002,Монтаж двигателя (Kohler Двигатель) 0077160711...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771607110401060,Топливная труба IV,1,NaN,Топливная система(Kohler Двигатель)00771607110...
1,00771607110401070,Топливная труба V,1,NaN,Топливная система(Kohler Двигатель)00771607110...
2,00771607110401020,Изогнутая пластина,1,NaN,Топливная система(Kohler Двигатель)00771607110...
3,1040004518,Болт M8×20-8.8,3,GB/T5783-2000,Топливная система(Kohler Двигатель)00771607110...
4,1040301735,Шайба GB/T97.1-2002 8-100HV,7,NaN,Топливная система(Kohler Двигатель)00771607110...
5,1040201874,Гайка M8-8,4,GB/T889.1-2000,Топливная система(Kohler Двигатель)00771607110...
6,1990200692,"Клейкая лента, покрытая слоем\r\nпластмассы",5,NaN,Топливная система(Kohler Двигатель)00771607110...
7,1040302487,Шайба 6-200HV,7,GB/T97.1-2002,Топливная система(Kohler Двигатель)00771607110...
8,1040004663,Винт M6×12-8.8,7,GB/T5782-2000,Топливная система(Kohler Двигатель)00771607110...
9,00771607110401030,Топливная труба I,1,NaN,Топливная система(Kohler Двигатель)00771607110...
10,1990202279,Хомут червяка и червячного\r\nколеса,9,NaN,Топливная система(Kohler Двигатель)00771607110...
11,00771607110410000,Топливный бак в сборе,1,NaN,Топливная система(Kohler Двигатель)00771607110...
12,1040302480,Шайба 8-200HV,4,GB/T96.1-2002,Топливная система(Kohler Двигатель)00771607110...
13,1040302512,Шайба 10-200HV,4,GB/T96.1-2002,Топливная система(Kohler Двигатель)00771607110...
14,1040200503,Гайка M8-8,4,GB/T889.1-2000,Топливная система(Kohler Двигатель)00771607110...
15,1040002434,Болт M10×25-8.8,4,GB/T5783-2000,Топливная система(Kohler Двигатель)00771607110...
16,00773407100401060,Пустотелый болт M16×1.5×35,2,NaN,Топливная система(Kohler Двигатель)00771607110...
17,1081000673,Комбин. уплот. шайба,4,NaN,Топливная система(Kohler Двигатель)00771607110...
18,00773407100401050,Штуцер II,2,NaN,Топливная система(Kohler Двигатель)00771607110...
19,1000400478,Водо-масляный сепаратор,1,NaN,Топливная система(Kohler Двигатель)00771607110...
20,00771607110401040,Топливная труба II,1,NaN,Топливная система(Kohler Двигатель)00771607110...
21,00771607110401050,Топливная труба III,1,NaN,Топливная система(Kohler Двигатель)00771607110...
22,1040002458,Болт M8×40-8.8,4,GB/T5783-2000,Топливная система(Kohler Двигатель)00771607110...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771607110601200,Плита III,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
1,00771607110601190,Плита II,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
2,00771607110601180,Плита I,2,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
3,00771607110601170,Ветровой щитВетровой щит,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
4,00771607110601160,Изогнутая пластина III,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
5,00771607110601150,Изогнутая пластина II,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
6,1040004619,Болт M8×35-8.8,4,GB/T5783-2000,Система теплоотдачи(Kohler Двигатель) 00771607...
7,00771107120601010,Монтажная панель водяного\r\nбака,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
8,1000300735,Расширительный бак,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
9,00771607110601110,Паровой шланг\r\nIII,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
10,00771607110601120,Паровой шланг\r\nIV,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
11,00771607110601090,Паровой шланг\r\nI,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
12,00771607110601130,Тройной штуцер,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
13,00771607110601100,Паровой шланг II,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
14,1990202279,Хомут червяка и червячного\r\nколеса,8,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
15,00771607110601050,шланг III,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
16,00771607110601070,Выпускная труба,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
17,00771607110601040,шланг\r\nII,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
18,00771607110601030,шланг I,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...
19,00771607110601080,Водопроводная труба,1,NaN,Система теплоотдачи(Kohler Двигатель) 00771607...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771607110601060,Возвратная труба,1,NaN,Топливная система(Kohler Двигатель) 0077160711...
1,1990202281,Хомут червяка и червячного\r\nколеса,2,NaN,Топливная система(Kohler Двигатель) 0077160711...
2,00771607110601020,шланг IV,1,NaN,Топливная система(Kohler Двигатель) 0077160711...
3,1990202287,Хомут спирального червяка и\r\nчервячного колеса,8,NaN,Топливная система(Kohler Двигатель) 0077160711...
4,00773407130601210,Губка изоляции,1,NaN,Топливная система(Kohler Двигатель) 0077160711...
5,1040200170,Гайка M12-8,4,GB/T889-1986,Топливная система(Kohler Двигатель) 0077160711...
6,1040300041,Шайба 12-200HV,8,GB/T97.1-2002,Топливная система(Kohler Двигатель) 0077160711...
7,1040002262,Болт M12×55-10.9,4,GB/T5783-2000,Топливная система(Kohler Двигатель) 0077160711...
8,00771407100601170,Подкладка,6,NaN,Топливная система(Kohler Двигатель) 0077160711...
9,1000300826,Блок радиатора,1,NaN,Топливная система(Kohler Двигатель) 0077160711...
10,1040201874,Гайка M8-8,19,GB/T889.1-2000,Топливная система(Kohler Двигатель) 0077160711...
11,00771607110601140,Изогнутая пластина I,1,NaN,Топливная система(Kohler Двигатель) 0077160711...
12,1040004517,Болт M8×16-8.8,10,NaN,Топливная система(Kohler Двигатель) 0077160711...
13,1040301735,Шайба 8-100HV,30,GB/T97.1-2002,Топливная система(Kohler Двигатель) 0077160711...
14,1040000239,Болт M8×25-8.8,15,GB/T5782-2000,Топливная система(Kohler Двигатель) 0077160711...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1990202287,Хомут спирального червяка и\r\nчервячного колеса,3,NaN,Впускная система (Kohler Двигатель) 0077160711...
1,00771607110801040,Впускная труба I,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
2,1990202281,Хомут червяка и червячного\r\nколеса,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
3,00771607110801050,Впускная труба II,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
4,00771607110801010,Впускная стальная труба,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
5,00771607110801030,Впускная труба III,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
6,1990202289,Хомут спирального червяка и\r\nчервячного колеса,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
7,00771607110801070,Изогнутая пластина II,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
8,1040004517,Болт M8×16-8.8,4,GB/T5783-2000,Впускная система (Kohler Двигатель) 0077160711...
9,1040301735,Шайба 8-100HV,4,GB/T97.1-2002,Впускная система (Kohler Двигатель) 0077160711...
10,1990202288,Хомут спирального червяка и\r\nчервячного колеса,3,NaN,Впускная система (Kohler Двигатель) 0077160711...
11,1040004619,Болт M8×35-8.8,5,GB/T5783-2000,Впускная система (Kohler Двигатель) 0077160711...
12,1040301515,Шайба 8-200HV,7,GB/T97.1-2002,Впускная система (Kohler Двигатель) 0077160711...
13,00771607110801020,Впускная труба IV,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
14,1009900902,Агрегат воздушного фильтра,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
15,00771407100801010,Впускная труба I,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
16,1990202290,Хомут спирального червяка и\r\nчервячного колеса,2,NaN,Впускная система (Kohler Двигатель) 0077160711...
17,1040201874,Гайка M8-8,2,GB/T889.1-2000,Впускная система (Kohler Двигатель) 0077160711...
18,00771607110801060,Изогнутая пластина I,1,NaN,Впускная система (Kohler Двигатель) 0077160711...
19,00771607110801080,Труб. зажим,1,NaN,Впускная система (Kohler Двигатель) 0077160711...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771407101001020,Воздуховыпускной труба-хвост,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
1,1040004519,Болт M8×25-8.8,18,GB/T5783-2000,Выхлопная система (Kohler Двигатель) 007716071...
2,1040301735,Шайба 8-100HV,32,GB/T97.1-2002,Выхлопная система (Kohler Двигатель) 007716071...
3,00771407101001030,Усилительная планка,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
4,1040201874,Гайка M8-8,24,GB/T889.1-2000,Выхлопная система (Kohler Двигатель) 007716071...
5,00771607111001030,Выхлопная труба\r\nII,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
6,00771407121001050,Уплотнительная прокладка I,2,NaN,Выхлопная система (Kohler Двигатель) 007716071...
7,00771407121001010,Глушитель,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
8,1040004520,Болт M8×30-8.8,4,GB/T5783-2000,Выхлопная система (Kohler Двигатель) 007716071...
9,00771607111010000,Кронштейн,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
10,00771607111001010,Теплоизоляционная плита,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
11,1040004619,Болт M8×35-8.8,6,GB/T5783-2000,Выхлопная система (Kohler Двигатель) 007716071...
12,00771607111001040,Уплотнительная прокладка II,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...
13,00771607111001020,Выхлопная труба\r\nI,1,NaN,Выхлопная система (Kohler Двигатель) 007716071...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1000000735,Дизельный двигатель,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
1,1040201896,Гайка M6-8,4,GB/T889-1986,Монтаж двигателя (Cummins Двигатель) 007716071...
2,1040002178,Болт M6×30-A2-70,4,GB/T5783-2000,Монтаж двигателя (Cummins Двигатель) 007716071...
3,00771407120201030,Изогнутая пластина III,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
4,00771407120201020,Изогнутая пластина II,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
5,1030400480,Эластичная муфта в сборе,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
6,1040004033,Болт M10×25-10.9,8,GB/T5783-2000,Монтаж двигателя (Cummins Двигатель) 007716071...
7,00771407120201050,Крышка муфты,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
8,1040302489,Шайба 10-200HV,12,GB/T97.1-2002,Монтаж двигателя (Cummins Двигатель) 007716071...
9,1040002435,Болт M10×35-8.8,12,GB/T5783-2000,Монтаж двигателя (Cummins Двигатель) 007716071...
10,00771400800001020,Самосмазывающийся\r\nподшипник,2,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
11,00771607120210000,Кронштейн двигателя,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
12,1040200161,Гайка M16-8,4,GB/T889-1986,Монтаж двигателя (Cummins Двигатель) 007716071...
13,00773407100201050,Подкладка,4,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
14,1009900942,Демпфер двигателя,8,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
15,00771407120201010,Изогнутая пластина I,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
16,00771407120201040,Изогнутая пластина IV,1,NaN,Монтаж двигателя (Cummins Двигатель) 007716071...
17,1040004653,Болт M12×30-10.9,16,GB/T5783-2000,Монтаж двигателя (Cummins Двигатель) 007716071...
18,1040302490,Шайба 12-200HV,16,GB/T97.1-2002,Монтаж двигателя (Cummins Двигатель) 007716071...
19,1040302492,Шайба 16-200HV,4,GB/T97.1-2002,Монтаж двигателя (Cummins Двигатель) 007716071...
20,1040003912,Болт M16×50-10.9-DKL,4,GB/T5783-2000,Монтаж двигателя (Cummins Двигатель) 007716071...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040200503,Гайка M8-8,8,GB/T889.1-2000,Топливная система (Cummins Двигатель) 00771607...
1,1040302480,Шайба 8-200HV,4,GB/T96.1-2002,Топливная система (Cummins Двигатель) 00771607...
2,00771607110410000,Топливный бак в сборе,1,NaN,Топливная система (Cummins Двигатель) 00771607...
3,1040302512,Шайба 10-200HV,4,GB/T96.1-2002,Топливная система (Cummins Двигатель) 00771607...
4,1040002434,Болт M10×25-8.8,4,GB/T5783-2000,Топливная система (Cummins Двигатель) 00771607...
5,1040005844,Болт M6×10-A2-70,5,GB/T5783-2000,Топливная система (Cummins Двигатель) 00771607...
6,1040300771,Шайба 6-200HV,5,GB/T97.1-2002,Топливная система (Cummins Двигатель) 00771607...
7,1990200692,"Клейкая лента, покрытая слоем\r\nпластмассы",5,NaN,Топливная система (Cummins Двигатель) 00771607...
8,00771607120401020,Топливная труба I,1,NaN,Топливная система (Cummins Двигатель) 00771607...
9,00771607120401050,Топливная труба IV,1,NaN,Топливная система (Cummins Двигатель) 00771607...
10,1040002458,Болт M8×40-8.8,2,GB/T5783-2000,Топливная система (Cummins Двигатель) 00771607...
11,1081000673,Комбин. уплот. шайба,4,NaN,Топливная система (Cummins Двигатель) 00771607...
12,00773407100401050,Штуцер II,2,NaN,Топливная система (Cummins Двигатель) 00771607...
13,00773407100401060,Пустотелый болт M16×1.5×35,2,NaN,Топливная система (Cummins Двигатель) 00771607...
14,00771607120401030,Топливная труба II,1,NaN,Топливная система (Cummins Двигатель) 00771607...
15,1140114594,Быстросъемная муфта,2,NaN,Топливная система (Cummins Двигатель) 00771607...
16,00771607120401040,Топливная труба III,1,NaN,Топливная система (Cummins Двигатель) 00771607...
17,1040301515,Шайба 8-200HV,7,GB/T97.1-2002,Топливная система (Cummins Двигатель) 00771607...
18,1040004619,Болт M8×35-8.8,2,GB/T5783-2000,Топливная система (Cummins Двигатель) 00771607...
19,1140114596,Быстросъемная муфта,1,NaN,Топливная система (Cummins Двигатель) 00771607...
20,1990202279,Хомут червяка и червячного\r\nколеса,8,NaN,Топливная система (Cummins Двигатель) 00771607...
21,1140114593,Быстросъемная муфта,1,NaN,Топливная система (Cummins Двигатель) 00771607...
22,00771607120401010,Изогнутая пластина,1,NaN,Топливная система (Cummins Двигатель) 00771607...
23,1040004518,Болт M8×20-8.8,3,GB/T5783-2000,Топливная система (Cummins Двигатель) 00771607...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771407120601180,Изогнутая пластина III,2,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
1,00771407120601170,Болт M8×35-8.8,2,GB/T5783-2000,Система теплоотдачи(Cummins Двигатель) 0077160...
2,00771607120601150,Болт M8×16-8.8,1,GB/T5783-2000,Система теплоотдачи(Cummins Двигатель) 0077160...
3,00771407120601140,Изогнутая пластина I,2,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
4,00771407120601130,Расширительный бак,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
5,1040004619,Гайка M8-8,4,GB/T889.1-2000,Система теплоотдачи(Cummins Двигатель) 0077160...
6,1040004517,Блок радиатора,11,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
7,00771607120601110,Хомут червяка и червячного\r\nколеса,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
8,1000300735,Паровой шланг I,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
9,1040200503,Паровой шланг II,22,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
10,1000300776,шланг\r\nII,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
11,1990202279,Вентилятор в сборе,4,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
12,00771607120601050,Водопроводная труба,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
13,00771607120601060,Болт M10×35-8.8,1,GB/T5783-2000,Система теплоотдачи(Cummins Двигатель) 0077160...
14,00771407120601020,Прокладка вентилятора,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
15,1000300809,Гайка M10-8,1,GB/T889.1-2000,Система теплоотдачи(Cummins Двигатель) 0077160...
16,00771607120601040,Шайба 10-200HV,1,GB/T97.1-2002,Система теплоотдачи(Cummins Двигатель) 0077160...
17,1040002435,Болт M10×45-8.8,4,GB/T5783-2000,Система теплоотдачи(Cummins Двигатель) 0077160...
18,00771407120601080,Штуцер шланга II,1,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...
19,1040200504,Возвратная труба,4,NaN,Система теплоотдачи(Cummins Двигатель) 0077160...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040302489,Хомут спирального червяка и\r\nчервячного колеса,8,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
1,1040004508,Хомут червяка и червячного\r\nколеса,4,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
2,00771407120601100,Штуцер шланга I,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
3,00771407120601010,Хомут спирального червяка и\r\nчервячного колеса,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
4,1990202288,Подкладка,3,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
5,1990202282,Болт M12×55-10.9,2,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
6,00771407120601090,Шайба 12-300HV,1,GB/T96.1-2002,Система теплоотдачи (Deutz Двигатель) 00771607...
7,1990202287,Гайка M12-8,3,GB/T889.1-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
8,00771407100601170,Изогнутая пластина II,6,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
9,1040002262,Изогнутая пластина III,4,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
10,1040301031,Болт M8×35-8.8,4,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
11,1040200507,Болт M8×16-8.8,4,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
12,00771407120601120,Изогнутая пластина I,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
13,00771407120601190,Плита III,1,NaN,Система теплоотдачи (Deutz Двигатель) 00771607...
14,1040004520,Болт M8×30-8.8,2,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...
15,1040301515,Шайба 8-200HV,33,GB/T97.1-2002,Система теплоотдачи (Deutz Двигатель) 00771607...
16,1040004519,Болт M8×25-8.8,16,GB/T5783-2000,Система теплоотдачи (Deutz Двигатель) 00771607...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771407120801060,Впускная труба III,1,NaN,Впускная система (Cummins Двигатель) 007716071...
1,1990202290,Хомут спирального червяка и\r\nчервячного колеса,2,NaN,Впускная система (Cummins Двигатель) 007716071...
2,1000100391,Агрегат воздушного фильтра,1,NaN,Впускная система (Cummins Двигатель) 007716071...
3,00771407120801030,Впускная труба II,1,NaN,Впускная система (Cummins Двигатель) 007716071...
4,00771407120801020,Впускная стальная труба,1,NaN,Впускная система (Cummins Двигатель) 007716071...
5,1040004519,Болт M8×25-8.8,4,GB/T5783-2000,Впускная система (Cummins Двигатель) 007716071...
6,00771407120801050,Изогнутая пластина II,1,NaN,Впускная система (Cummins Двигатель) 007716071...
7,00771407120801010,Впускная труба I,1,NaN,Впускная система (Cummins Двигатель) 007716071...
8,1990202289,Хомут спирального червяка и\r\nчервячного колеса,3,NaN,Впускная система (Cummins Двигатель) 007716071...
9,00771407120801040,Изогнутая пластина I,1,NaN,Впускная система (Cummins Двигатель) 007716071...
10,1040004619,Болт M8×35-8.8,2,GB/T5783-2000,Впускная система (Cummins Двигатель) 007716071...
11,1040301515,Шайба 8-200HV,6,GB/T97.1-2002,Впускная система (Cummins Двигатель) 007716071...
12,1040200503,Гайка M8-8,4,GB/T889.1-2000,Впускная система (Cummins Двигатель) 007716071...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771407101001020,Воздуховыпускной труба-хвост,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
1,00771407101001030,Усилительная планка,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
2,00771607121001040,Выхлопная труба II,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
3,00771407121001020,Выхлопная труба I,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
4,00771407121001050,Уплотнительная прокладка I,2,NaN,Выхлопная система (Cummins Двигатель) 00771607...
5,00771407121001010,Глушитель,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
6,00771407121001030,Кронштейн,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
7,1040002434,Болт M10×25-8.8,8,GB/T5783-2000,Выхлопная система (Cummins Двигатель) 00771607...
8,1040302489,Шайба 10-200HV,8,GB/T97.1-2002,Выхлопная система (Cummins Двигатель) 00771607...
9,1040200503,Гайка M8-8,16,GB/T889.1-2000,Выхлопная система (Cummins Двигатель) 00771607...
10,00771407121001060,Уплотнительная прокладка II,1,NaN,Выхлопная система (Cummins Двигатель) 00771607...
11,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Выхлопная система (Cummins Двигатель) 00771607...
12,1040004519,Болт M8×25-8.8,16,GB/T5783-2000,Выхлопная система (Cummins Двигатель) 00771607...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101478,Прямоугольный\r\nкомпозитный штуцер,1,EW15LOMDCF,Монтаж гидравлической детали рамы (Двигатель) ...
1,1149902023,Удлиненный прямой\r\nсоединитель,1,GE15L11/16UNOMDCF-L65,Монтаж гидравлической детали рамы (Двигатель) ...
2,1149901795,Прямой соединитель,1,GE15L11/16UNOMDCF,Монтаж гидравлической детали рамы (Двигатель) ...
3,1140113353,Прямой соединитель,1,GE12L3/4UNFOMDCF,Монтаж гидравлической детали рамы (Двигатель) ...
4,1140108034,Регулируемое\r\nсоединение,1,WEE08L9/16UNFOMDCF,Монтаж гидравлической детали рамы (Двигатель) ...
5,1040000575,Болт,2,M12×35-10.9,Монтаж гидравлической детали рамы (Двигатель) ...
6,1040302490,Шайба,2,12-200HV,Монтаж гидравлической детали рамы (Двигатель) ...
7,1010100630,Ходовой двигатель,1,K-C-45DN-E-RNF-F55-S-N-\r\nN-AF-F18-NNN-NNN,Монтаж гидравлической детали рамы (Двигатель) ...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004518,Болт,4,M8×20-8.8,Монтаж гидравлической детали рамы (Клапан расш...
1,1040301510,Шайба,4,8,Монтаж гидравлической детали рамы (Клапан расш...
2,1040301515,Шайба,4,8-200HV,Монтаж гидравлической детали рамы (Клапан расш...
3,1010306668,Клапан расширения\r\nмоста рулевого\r\nуправления,1,R930074145,Монтаж гидравлической детали рамы (Клапан расш...
4,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
5,1140101941,Прямой соединитель,1,GE10LR3/8EDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
6,1140101463,Прямой соединитель,1,GE12LR1/2EDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
7,1140108469,Прямой соединитель,6,GE08LR3/8EDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140102959,Тройный композитный\r\nштуцер,3,EL08LOMDCF,Монтаж гидравлической детали рамы (Клапан упра...
1,1140107801,Композитный штуцер 45°,2,EV08LOMDCF,Монтаж гидравлической детали рамы (Клапан упра...
2,1149900295,Тройный композитный\r\nштуцер,2,ET08LOMDCF,Монтаж гидравлической детали рамы (Клапан упра...
3,1140111237,Прямой соединитель,5,GE08LREDOMDCF,Монтаж гидравлической детали рамы (Клапан упра...
4,1010306670,Клапан управления ходом,1,R988111242,Монтаж гидравлической детали рамы (Клапан упра...
5,1040301515,Шайба,4,8-200HV,Монтаж гидравлической детали рамы (Клапан упра...
6,1040301510,Шайба,4,8,Монтаж гидравлической детали рамы (Клапан упра...
7,1040004518,Болт,4,M8×20-8.8,Монтаж гидравлической детали рамы (Клапан упра...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101470,Прямой соединитель,4,GE16SR3/4EDOMDCF,Монтаж гидравлической детали рамы (Разделитель...
1,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж гидравлической детали рамы (Разделитель...
2,1010306669,Разделительный клапан\r\nхода,1,R988111231,Монтаж гидравлической детали рамы (Разделитель...
3,1140101464,Прямой соединитель,8,GE15LREDOMDCF,Монтаж гидравлической детали рамы (Разделитель...
4,1140101489,Тройный композитный\r\nштуцер,2,EL15LOMDCF,Монтаж гидравлической детали рамы (Разделитель...
5,1060300302,Композитный\r\nпереходник,1,RED15/08LOMDCF,Монтаж гидравлической детали рамы (Разделитель...
6,1040301515,Шайба,4,8-200HV,Монтаж гидравлической детали рамы (Разделитель...
7,1040301510,Шайба,4,8,Монтаж гидравлической детали рамы (Разделитель...
8,1040004518,Болт,4,M8×20-8.8,Монтаж гидравлической детали рамы (Разделитель...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004552,Болт,4,M6×15-8.8,Монтаж гидравлической детали рамы (Подъемный к...
1,1040301509,Шайба,4,6,Монтаж гидравлической детали рамы (Подъемный к...
2,1040302487,Шайба,4,6-200HV,Монтаж гидравлической детали рамы (Подъемный к...
3,1010306671,Подъемный клапан,1,R930072050,Монтаж гидравлической детали рамы (Подъемный к...
4,1140111237,Прямой соединитель,8,GE08LREDOMDCF,Монтаж гидравлической детали рамы (Подъемный к...
5,1140102959,Тройный\r\nкомпозитный\r\nштуцер,2,EL08LOMDCF,Монтаж гидравлической детали рамы (Подъемный к...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004518,Болт,4,M8×20-8.8,Монтаж гидравлической детали рамы (Клапан расш...
1,1040301510,Шайба,4,8,Монтаж гидравлической детали рамы (Клапан расш...
2,1040004518,Болт,4,M8×20-8.8,Монтаж гидравлической детали рамы (Клапан расш...
3,1010306667,Клапан расширения\r\nмоста рулевого\r\nуправления,1,R930074148,Монтаж гидравлической детали рамы (Клапан расш...
4,1140101941,Прямой соединитель,1,GE10LR3/8EDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
5,1140101463,Прямой соединитель,1,GE12LR1/2EDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
6,1140101477,Тройный композитный\r\nштуцер,1,EW12LOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
7,1140108469,Прямой соединитель,6,GE08LR3/8EDOMDCF,Монтаж гидравлической детали рамы (Клапан расш...
8,1140102959,Тройный композитный\r\nштуцер,2,EL08LOMDCF,Монтаж гидравлической детали рамы (Клапан расш...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140107814,Прямой соединитель,1,GE08L7/16UNFOMDCF,Монтаж гидравлической детали поворотной платфо...
1,1010001791,Основной насос,1,JR-R-S45B-LS-21-20-NN-N-3\r\n-C2NE-A8N-NNN-JJJ...,Монтаж гидравлической детали поворотной платфо...
2,1140105246,Прямой соединитель,1,GE15L7/8UNFOMDCF,Монтаж гидравлической детали поворотной платфо...
3,1140101484,Тройный композитный\r\nштуцер,1,ET15LOMDCF,Монтаж гидравлической детали поворотной платфо...
4,1019901008,Прямоугольный\r\nкомпозитный штуцер,1,GZ15LCF,Монтаж гидравлической детали поворотной платфо...
5,1140114652,Прямой соединитель,2,GEO28LM27×2OMDCF,Монтаж гидравлической детали поворотной платфо...
6,1140101478,Прямоугольный\r\nкомпозитный штуцер,3,EW15LOMDCF,Монтаж гидравлической детали поворотной платфо...
7,1149901793,Прямой соединитель,3,GEO15LM27×2OMDCF,Монтаж гидравлической детали поворотной платфо...
8,1140111291,Тройный композитный\r\nштуцер,2,EL12LOMDCF,Монтаж гидравлической детали поворотной платфо...
9,1010002059,Закрытый насос,1,MP1-P-28R-AM-NNN-MA4-\r\nC2-F-G4-R-D22-N-345-3...,Монтаж гидравлической детали поворотной платфо...
10,1010002058,Закрытый насос,1,MP1-P-28R-AM-NNN-MA4-\r\nC2-F-G5-R-D22-N-345-3...,Монтаж гидравлической детали поворотной платфо...
11,1140113942,Прямой соединитель,4,GEO12LM14×1.5OMDCF,Монтаж гидравлической детали поворотной платфо...
12,1140114651,Удлиненный прямой\r\nсоединитель,2,GEO16SM27×2OMDCF-L65,Монтаж гидравлической детали поворотной платфо...
13,1040302490,Шайба,6,12-200HV,Монтаж гидравлической детали поворотной платфо...
14,1040000575,Болт,6,M12×35-10.9,Монтаж гидравлической детали поворотной платфо...
15,1140114653,Прямой соединитель,2,GEO16SM27×2OMDCF,Монтаж гидравлической детали поворотной платфо...
16,1140101478,Прямоугольный\r\nкомпозитный штуцер,1,EW15LOMDCF,Монтаж гидравлической детали поворотной платфо...
17,1140112718,Прямой переходник,1,GR22/15LCFX,Монтаж гидравлической детали поворотной платфо...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040201089,Гайка M8-8,4,GB/T6170-2000,Монтаж гидравлической детали поворотной платфо...
1,1040301510,Шайба 8,4,GB/T93-1987,Монтаж гидравлической детали поворотной платфо...
2,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж гидравлической детали поворотной платфо...
3,1040004519,Болт M8×25-8.8,4,GB/T5783-2000,Монтаж гидравлической детали поворотной платфо...
4,1140105928,Прямой соединитель,2,GE22LR1/2EDOMDCF,Монтаж гидравлической детали поворотной платфо...
5,1140108904,Прямоугольный\r\nкомпозитный штуцер,2,EW22LOMDCF,Монтаж гидравлической детали поворотной платфо...
6,1010400306,Радиатор,1,M9115175,Монтаж гидравлической детали поворотной платфо...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1010601136,Подпиточный фильтр,1,MFXBN/HC100GC10W\r\n0.0/-B3.5,Монтаж гидравлической детали поворотной платфо...
1,1140207362,Прямой соединитель,2,GE12LR3/4EDOMDCF,Монтаж гидравлической детали поворотной платфо...
2,1140101477,Прямоугольный\r\nкомпозитный штуцер,2,EW12LOMDCF,Монтаж гидравлической детали поворотной платфо...
3,1040302489,Шайба 10-200HV,4,GB/T97.1-2002,Монтаж гидравлической детали поворотной платфо...
4,1040301502,Шайба 10,4,GB/T93-1987,Монтаж гидравлической детали поворотной платфо...
5,1040002433,Болт M10×20-8.8,4,GB/T5783-2000,Монтаж гидравлической детали поворотной платфо...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1010601137,Фильтр высокого\r\nдавления,1,MFMON95OH\r\n5A4.0/-B7,Монтаж гидравлической детали поворотной платфо...
1,1140101523,Прямой соединитель,1,GE20SREDOMDCF,Монтаж гидравлической детали поворотной платфо...
2,1140101534,Прямоугольный\r\nкомпозитный штуцер,2,EW20SOMDCF,Монтаж гидравлической детали поворотной платфо...
3,1040004518,Болт,4,GB/T5783-2000,Монтаж гидравлической детали поворотной платфо...
4,1040301510,Шайба 8,4,GB/T93-1987,Монтаж гидравлической детали поворотной платфо...
5,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж гидравлической детали поворотной платфо...
6,1010305956,Обратный клапан,1,RHV20SREDOMDCF,Монтаж гидравлической детали поворотной платфо...

,Код мат-ла,Наименование и\r\nспецификация,Кол-в\r\nо\r\nштук,Примечание,Section
0,1140101462,Прямой соединитель,1,GE12LREDOMDCF,Монтаж гидравлической детали поворотной платфо...
1,1010001903,Насос аварийного\r\nэлектродвигателя,1,800660021,Монтаж гидравлической детали поворотной платфо...
2,1040302489,Шайба 10-200HV,2,GB/T97.1-2002,Монтаж гидравлической детали поворотной платфо...
3,1040301502,Шайба 10,2,GB/T93-1987,Монтаж гидравлической детали поворотной платфо...
4,1040002433,Болт M10×20-8.8,2,GB/T5783-2000,Монтаж гидравлической детали поворотной платфо...
5,1140102408,Прямой соединитель,1,GE08SREDOMDCF,Монтаж гидравлической детали поворотной платфо...
6,1140103135,Прямоугольный\r\nкомпозитный штуцер,1,EW08SOMDCF,Монтаж гидравлической детали поворотной платфо...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101478,Прямоугольный\r\nкомпозитный штуцер,2,EW15LOMDCF,Монтаж гидравлической детали поворотной платфо...
1,1140101464,Прямой соединитель,5,GE15LREDOMDCF,Монтаж гидравлической детали поворотной платфо...
2,1140108469,Прямой соединитель,2,GE08LR3/8EDOMDCF,Монтаж гидравлической детали поворотной платфо...
3,1140101629,Шестигранная заглушка,3,VSTI3/8EDCF,Монтаж гидравлической детали поворотной платфо...
4,1140101462,Прямой соединитель,1,GE12LREDOMDCF,Монтаж гидравлической детали поворотной платфо...
5,1140101941,Прямой соединитель,1,GE10LR3/8EDOMDCF,Монтаж гидравлической детали поворотной платфо...
6,1140108469,Прямой соединитель,1,GE08LR3/8EDOMDCF,Монтаж гидравлической детали поворотной платфо...
7,1140102812,Прямой соединитель,1,GE18LREDOMDCF,Монтаж гидравлической детали поворотной платфо...
8,1140101711,Тройный композитный\r\nштуцер,1,EL20SOMDCF,Монтаж гидравлической детали поворотной платфо...
9,1140101523,Прямой соединитель,1,GE20SREDOMDCF,Монтаж гидравлической детали поворотной платфо...
10,1140103359,переходник,1,RED20/08SOMDCF,Монтаж гидравлической детали поворотной платфо...
11,1140103362,Прямой соединитель,1,GE28LREDOMDCF,Монтаж гидравлической детали поворотной платфо...
12,1060300324,Тройный композитный\r\nштуцер,1,EL28LOMDCF,Монтаж гидравлической детали поворотной платфо...
13,1140114591,переходник,1,RED28/15LOMDCF,Монтаж гидравлической детали поворотной платфо...
14,1140101478,Прямоугольный\r\nкомпозитный штуцер,1,EW15LOMDCF,Монтаж гидравлической детали поворотной платфо...
15,1140107803,Прямоугольный\r\nкомпозитный штуцер,1,EV28LOMDCF,Монтаж гидравлической детали поворотной платфо...
16,1140101475,Прямоугольный\r\nкомпозитный штуцер,1,EW08LOMDCF,Монтаж гидравлической детали поворотной платфо...
17,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж гидравлической детали поворотной платфо...
18,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж гидравлической детали поворотной платфо...
19,1040004519,Шайба M8×25-8.8,4,GB/T5783-2000,Монтаж гидравлической детали поворотной платфо...
20,1010306665,Главный клапан,1,R930073949,Монтаж гидравлической детали поворотной платфо...
21,1040301510,Шайба 8,4,GB/T93-1987,Монтаж гидравлической детали поворотной платфо...
22,1040201089,Гайка M8-8,2,GB/T6170-2000,Монтаж гидравлической детали поворотной платфо...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101477,Прямоугольный\r\nкомпозитный\r\nштуцер,2,EW12LOMDCF,Монтаж гидравлической детали платформы 0077160...
1,1140101463,Прямой соединитель,2,GE12LR1/2EDOMDCF,Монтаж гидравлической детали платформы 0077160...
2,1010601138,Фильтр высокого\r\nдавления,1,MFMON55OB 5A4.0/-B7,Монтаж гидравлической детали платформы 0077160...
3,1040301515,Шайба 8-200HV,8,GB/T97.1-2002,Монтаж гидравлической детали платформы 0077160...
4,1040301510,Шайба 8,8,GB/T93-1987,Монтаж гидравлической детали платформы 0077160...
5,1040004516,Болт M8×15-8.8,4,GB/T5783-2000,Монтаж гидравлической детали платформы 0077160...
6,1040004518,Болт M8×20-8.8,4,GB/T5783-2000,Монтаж гидравлической детали платформы 0077160...
7,1010306666,Клапан управления\r\nплатформы,1,R930074149,Монтаж гидравлической детали платформы 0077160...
8,1140101464,Прямой соединитель,1,GE15LREDOMDCF,Монтаж гидравлической детали платформы 0077160...
9,1140101462,Прямой соединитель,1,GE12LREDOMDCF,Монтаж гидравлической детали платформы 0077160...
10,1140101477,Прямоугольный\r\nкомпозитный\r\nштуцер,1,EW12LOMDCF,Монтаж гидравлической детали платформы 0077160...
11,1140114646,Длинный прямой\r\nсоединитель,2,GE08LR3/8EDOMDCF-L60,Монтаж гидравлической детали платформы 0077160...
12,1140108469,Прямой соединитель,4,GE08LR3/8EDOMDCF,Монтаж гидравлической детали платформы 0077160...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140107814,Прямой соединитель,2,GE08L7/16UNFOMDCF,Монтаж гидравлической детали платформы (Монтаж...
1,1140101475,Прямоугольный\r\nкомпозитный\r\nштуцер,2,EW08LOMDCF,Монтаж гидравлической детали платформы (Монтаж...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101483,Тройный композитный\r\nштуцер,1,EL12LOMDCF,Монтаж центрального вращающегося соединения 00...
1,1140101463,Прямой соединитель,1,GE12LR1/2EDOMDCF,Монтаж центрального вращающегося соединения 00...
2,1140101941,Прямой соединитель,2,GE10LR3/8EDOMDCF,Монтаж центрального вращающегося соединения 00...
3,1140101793,Тройный композитный\r\nштуцер,1,ET10LOMDCF,Монтаж центрального вращающегося соединения 00...
4,1140101484,Тройный композитный\r\nштуцер,1,ET15LOMDCF,Монтаж центрального вращающегося соединения 00...
5,1140101464,Прямой соединитель,2,GE15LREDOMDCF,Монтаж центрального вращающегося соединения 00...
6,1140101527,Прямой соединитель,4,GE16SREDOMDCF,Монтаж центрального вращающегося соединения 00...
7,1040302490,Шайба 12-200HV,4,GB/T97.1-2002,Монтаж центрального вращающегося соединения 00...
8,1040300054,Шайба 12,4,GB/T93-1987,Монтаж центрального вращающегося соединения 00...
9,1040004644,Болт M12×45-10.9,4,GB/T5783-2000,Монтаж центрального вращающегося соединения 00...
10,1140114650,Длинный прямой\r\nсоединитель,1,GE15LREDOMDCF-L110,Монтаж центрального вращающегося соединения 00...
11,1149902020,Длинный прямой\r\nсоединитель,2,GE15LREDOMDCF-L120,Монтаж центрального вращающегося соединения 00...
12,1140101478,Прямоугольный\r\nкомпозитный штуцер,1,EW15LOMDCF,Монтаж центрального вращающегося соединения 00...
13,1149902021,переходник,1,GZR22/15LCF,Монтаж центрального вращающегося соединения 00...
14,1140101808,Тройной штуцер,1,T22LCFX,Монтаж центрального вращающегося соединения 00...
15,1140101632,Прямоугольный\r\nкомпозитный штуцер,4,EW16SOMDCF,Монтаж центрального вращающегося соединения 00...
16,1140114649,Длинный прямой\r\nсоединитель,4,GE16SREDOMDCF-L110,Монтаж центрального вращающегося соединения 00...
17,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж центрального вращающегося соединения 00...
18,1011200183,Центральное\r\nвращающееся\r\nсоединение,1,ZHZY47,Монтаж центрального вращающегося соединения 00...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101479,Прямоугольный\r\nкомпозитный\r\nштуцер,1,EW18LOMDCF,Монтаж блока балансировочных клапанов(Амплит. ...
1,1140102812,Прямой соединитель,1,GE18LREDOMDCF,Монтаж блока балансировочных клапанов(Амплит. ...
2,1040102739,Винт M8×60-8.8,4,GB/T70.1-2000,Монтаж блока балансировочных клапанов(Амплит. ...
3,1140101475,Прямоугольный\r\nкомпозитный\r\nштуцер,1,EW08LOMDCF,Монтаж блока балансировочных клапанов(Амплит. ...
4,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж блока балансировочных клапанов(Амплит. ...
5,1010306672,Амплитудный\r\nуравнительный\r\nклапан,1,R930074600,Монтаж блока балансировочных клапанов(Амплит. ...
6,1140101464,Прямой соединитель,2,GE15LREDOMDCF,Монтаж блока балансировочных клапанов(Амплит. ...
7,1140101478,Прямоугольный\r\nкомпозитный\r\nштуцер,2,EW15LOMDCF,Монтаж блока балансировочных клапанов(Амплит. ...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1010306160,Балансировочный клапан\r\nвыдвижения-втягивания,1,R988115496,Монтаж блока балансировочных клапанов(Балансир...
1,1040004603,Винт M8×75-8.8,4,GB/T70.1-2000,Монтаж блока балансировочных клапанов(Балансир...
2,1140101464,Прямой соединитель,2,GE15LREDOMDCF,Монтаж блока балансировочных клапанов(Балансир...
3,1140101478,Прямоугольный\r\nкомпозитный штуцер,2,EW15LOMDCF,Монтаж блока балансировочных клапанов(Балансир...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж блока балансировочных клапанов (Вращающ...
1,1010306674,Вращающийся\r\nбалансировочный клапан,1,R930002746,Монтаж блока балансировочных клапанов (Вращающ...
2,1030600279,Прямой соединитель,2,GE08LR1/2EDOMDCF,Монтаж блока балансировочных клапанов (Вращающ...
3,1140107801,Прямоугольный\r\nкомпозитный штуцер,2,EV08LOMDCF,Монтаж блока балансировочных клапанов (Вращающ...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101475,Прямоугольный\r\nкомпозитный штуцер,2,EW08LOMDCF,Монтаж блока балансировочных клапанов (Баланси...
1,1140108469,Прямой соединитель,2,GE08LR3/8EDOMDCF,Монтаж блока балансировочных клапанов (Баланси...
2,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж блока балансировочных клапанов (Баланси...
3,1040301510,Шайба 8,4,GB/T93-1987,Монтаж блока балансировочных клапанов (Баланси...
4,1040004522,Болт M8×50-8.8,4,GB/T5783-2000,Монтаж блока балансировочных клапанов (Баланси...
5,1010306020,Балансировочный клапан,1,R988091176,Монтаж блока балансировочных клапанов (Баланси...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101475,Прямоугольный\r\nкомпозитный\r\nштуцер,2,EW08LOMDCF,Монтаж блока балансировочных клапанов (Баланси...
1,1140108469,Прямой соединитель,2,GE08LR3/8EDOMDCF,Монтаж блока балансировочных клапанов (Баланси...
2,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж блока балансировочных клапанов (Баланси...
3,1040301510,Шайба 8,4,GB/T93-1987,Монтаж блока балансировочных клапанов (Баланси...
4,1040004522,Болт M8×50-8.8,4,GB/T5783-2000,Монтаж блока балансировочных клапанов (Баланси...
5,1010306020,Балансировочный\r\nклапан,1,R988091176,Монтаж блока балансировочных клапанов (Баланси...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101475,Прямоугольный\r\nкомпозитный\r\nштуцер,1,EW08LOMDCF,Монтаж блока балансировочных клапанов (Баланси...
1,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Монтаж блока балансировочных клапанов (Баланси...
2,1010306736,Балансировочный\r\nклапан колебания,1,R988112499,Монтаж блока балансировочных клапанов (Баланси...
3,1040004599,Болт M8×60-8.8,4,GB/T5782-2000,Монтаж блока балансировочных клапанов (Баланси...
4,1040301510,Шайба 8,4,GB/T93-1987,Монтаж блока балансировочных клапанов (Баланси...
5,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж блока балансировочных клапанов (Баланси...
6,1140101464,Прямой соединитель,1,GE15LREDOMDCF,Монтаж блока балансировочных клапанов (Баланси...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140101475,Прямоугольный\r\nкомпозитный\r\nштуцер,2,EW08LOMDCF,Монтаж блока балансировочных клапанов (Баланси...
1,1140108469,Прямой соединитель,2,GE08LR3/8EDOMDCF,Монтаж блока балансировочных клапанов (Баланси...
2,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж блока балансировочных клапанов (Баланси...
3,1040301510,Шайба 8,4,GB/T93-1987,Монтаж блока балансировочных клапанов (Баланси...
4,1040004522,Болт M8×50-8.8,4,GB/T5783-2000,Монтаж блока балансировочных клапанов (Баланси...
5,1010306020,Балансировочный\r\nклапан,1,R988091176,Монтаж блока балансировочных клапанов (Баланси...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1140108469,Прямой соединитель,2,GE08LR3/8EDOMDCF,Монтаж блока балансировочных клапанов (Баланси...
1,1040301515,Шайба 8-200HV,4,GB/T97.1-2002,Монтаж блока балансировочных клапанов (Баланси...
2,1040301510,Шайба 8,4,GB/T93-1987,Монтаж блока балансировочных клапанов (Баланси...
3,1040004522,Болт M8×50-8.8,4,GB/T5783-2000,Монтаж блока балансировочных клапанов (Баланси...
4,1010306020,Балансировочный\r\nклапан,1,R988091176,Монтаж блока балансировочных клапанов (Баланси...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1040004511,Болт M12×30-8.8,4,GB/T5783-2000,Гидравлический бак 00771405201600000
1,1040300054,Шайба 12,4,GB/T93-1987,Гидравлический бак 00771405201600000
2,1040302490,Шайба 12-200HV,4,GB/T97.1-2002,Гидравлический бак 00771405201600000
3,1149901683,Прямой соединитель,1,GE42LREDOMDCF,Гидравлический бак 00771405201600000
4,1140103362,Прямой соединитель,2,GE28LREDOMDCF,Гидравлический бак 00771405201600000
5,1140101462,Прямой соединитель,2,GE12LREDOMDCF,Гидравлический бак 00771405201600000
6,1140101464,Прямой соединитель,3,GE15LREDOMDCF,Гидравлический бак 00771405201600000
7,1140111237,Прямой соединитель,1,GE08LREDOMDCF,Гидравлический бак 00771405201600000
8,1019901354,Уровнемер-термометр,1,FSA-176-1.0/T/10,Гидравлический бак 00771405201600000
9,007716052016000000,Корпус бака,1,NaN,Гидравлический бак 00771405201600000
10,00771405201601010,Резиновая прокладка\r\nперекрывающей пластины,1,NaN,Гидравлический бак 00771405201600000
11,00771405201620000,Перекрывающая пластина\r\nв сборе,1,NaN,Гидравлический бак 00771405201600000
12,1040301510,Шайба 8,16,GB/T93-1987,Гидравлический бак 00771405201600000
13,1040301515,Шайба 8-200HV,16,GB/T97.1-2002,Гидравлический бак 00771405201600000
14,1040004518,Болт M8×20-8.8,12,GB/T5783-2000,Гидравлический бак 00771405201600000
15,1010500340,Воздушный фильтр\r\nмасляного бака,1,BFP30G3W1.0,Гидравлический бак 00771405201600000
16,1040004519,Болт M8×25-8.8,4,GB/T5783-2000,Гидравлический бак 00771405201600000
17,1010601139,Обратный масляный\r\nфильтр,1,RFMON185B\r\nD10A1.0/-V300,Гидравлический бак 00771405201600000
18,1140101992,Шестигранная заглушка,11,VSTI1/2EDCF,Гидравлический бак 00771405201600000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1022200683,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
1,1022270089,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
2,1020705067,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
3,/,Разгрузочный клапан,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
4,/,Клапан выдвижения\r\nстрелы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
5,/,Клапан выдвижения\r\nстрелы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
6,/,Клапан поворота влево\r\nповоротной платформы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
7,/,Клапан опускания стрелы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
8,/,Клапан втягивания стрелы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
9,/,Клапан поворота вправо\r\nповоротной платформы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
10,/,Расходный клапан шасси,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
11,/,Расходный клапан\r\nплатформы,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
12,/,Клапан аварийного\r\nопускания,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
13,1020700540,Оконечное сопротивление,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
14,1020700540,Оконечное сопротивление,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
15,/,Диагностика двигателя\r\nШтепсель,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
16,/,Вставной модуль\r\nдвигателя A,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1029905348,Аккумулятор,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
1,/,Общественная земля,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
2,/,Реле вспомогательного\r\nсилового насоса,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
3,/,Водо-масляный сепаратор,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
4,/,Топливный насос,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
5,00771606200420000,Пучок кабеля ECU,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
6,/,Радиатор,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
7,1021404019,Датчик угла наклона\r\nкузова относительно гор...,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
8,1029906298,Концевой выключатель\r\nугла поворота поворотн...,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
9,/,Контактное кольцо\r\nШтепсель 1,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
10,/,Контактное кольцо\r\nШтепсель 2,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
11,/,Уровень топлива,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
12,1020304982,Аварийный зуммер,1,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
13,/,Уличный фонарь\r\n(Опциональная установка),/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
14,/,Промежуточный модуль\r\nлампы аварийной\r\nсиг...,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
15,00771606200430000,Пучок кабеля стрелы,NaN,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...
16,00771606200610000,Кабельный жгут\r\nбуксируемой цепи,/,NaN,Пучок кабеля поворотной платформы (Kohler Двиг...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,1022200683,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
1,1022270089,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
2,1020705067,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
3,/,Разгрузочный клапан,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
4,/,Клапан выдвижения\r\nстрелы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
5,/,Клапан выдвижения\r\nстрелы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
6,/,Клапан поворота влево\r\nповоротной платформы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
7,/,Клапан опускания стрелы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
8,/,Клапан втягивания стрелы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
9,/,Клапан поворота вправо\r\nповоротной платформы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
10,/,Расходный клапан шасси,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
11,/,Расходный клапан\r\nплатформы,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
12,/,Клапан аварийного\r\nопускания,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
13,1020700540,Оконечное сопротивление,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
14,1020700540,Оконечное сопротивление,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
15,/,Диагностика двигателя\r\nШтепсель,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
16,/,Вставной модуль двигателя\r\nA,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
17,1029905348,Аккумулятор,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Общественная земля,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
1,/,Реле вспомогательного\r\nсилового насоса,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
2,/,Водо-масляный сепаратор,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
3,/,Топливный насос,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
4,00771606200420000,Пучок кабеля ECU,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
5,/,Радиатор,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
6,1021404019,Датчик угла наклона кузова\r\nотносительно гор...,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
7,1029906298,Концевой выключатель\r\nугла поворота поворотн...,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
8,/,Контактное кольцо\r\nШтепсель 1,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
9,/,Контактное кольцо\r\nШтепсель 2,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
10,/,Уровень топлива,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
11,1020304982,Аварийный зуммер,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
12,/,Уличный фонарь\r\n(Опциональная установка),/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
13,/,Промежуточный модуль\r\nлампы аварийной сигнал...,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
14,00771606200430000,Пучок кабеля стрелы,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
15,00771606200610000,Кабельный жгут\r\nбуксируемой цепи,1,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
16,/,Разъемный соединитель\r\nящика ручного управления,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...
17,/,GPS Разъемный\r\nсоединитель,/,NaN,Пучок кабеля поворотной платформы (Deutz Двига...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771606200220030,Электрический шкаф\r\nуправления поворотной\r\...,1,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
1,00771606200220030,Электрический шкаф\r\nуправления поворотной\r\...,0,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
2,00771606200220030,Электрический шкаф\r\nуправления поворотной\r\...,0,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
3,/,Разгрузочный клапан,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
4,/,Клапан выдвижения\r\nстрелы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
5,/,Клапан выдвижения\r\nстрелы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
6,/,Клапан поворота влево\r\nповоротной платформы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
7,/,Клапан опускания стрелы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
8,/,Клапан втягивания стрелы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
9,/,Клапан поворота вправо\r\nповоротной платформы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
10,/,Расходный клапан шасси,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
11,/,Расходный клапан\r\nплатформы,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
12,/,Клапан аварийного\r\nопускания,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
13,00771606200230020,Пучок кабеля ECU,1,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
14,1029905348,Положительный полюс\r\nаккумулятора,1,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
15,/,Общественная земля,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Реле вспомогательного\r\nсилового насоса,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
1,/,Водо-масляный сепаратор,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
2,/,Радиатор,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
3,1021404019,Датчик угла наклона\r\nкузова относительно гор...,1,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
4,1029906298,Концевой выключатель\r\nугла поворота поворотн...,1,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
5,/,Контактное кольцо\r\nШтепсель 1,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
6,/,Контактное кольцо\r\nШтепсель 2,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
7,/,Уровень топлива,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
8,1020304982,Аварийный зуммер,1,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
9,/,Уличный фонарь\r\n(Опциональная установка),/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
10,/,Промежуточный модуль\r\nлампы аварийной\r\nсиг...,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
11,00771606200430000,Пучок кабеля стрелы,NaN,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
12,00771606200610000,Кабельный жгут\r\nбуксируемой цепи,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
13,/,Разъемный соединитель\r\nящика ручного управления,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...
14,/,GPS Разъемный\r\nсоединитель,/,NaN,Пучок кабеля поворотной платформы (Cummins Дви...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Клапан заднего хода с\r\nправой стороны,/,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
1,/,Клапан переднего хода с\r\nправой стороны,/,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
2,/,Клапан заднего хода с\r\nлевой стороны,/,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
3,/,Клапан переднего хода с\r\nлевой стороны,/,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
4,1020305006,Контактор постоянного\r\nтока для подогрева,1,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
5,/,Уровень охлаждающей\r\nжидкости,/,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
6,/,Засорение воздушного\r\nфильтра,/,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...
7,00771606200410000,Пучок кабеля поворотной\r\nплатформы,1,NaN,ECU Пучок кабеля (Kohler Двигатель) 0077160620...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Уровень\r\nохлаждающей\r\nжидкости,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
1,/,Засорение\r\nвоздушного\r\nфильтра,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
2,1020305006,Контактор\r\nпостоянного\r\nтока для подогрева,1,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
3,/,Индикатор зарядки,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
4,/,Клапан\r\nзаднего\r\nхода\r\nс\r\nправой стороны,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
5,/,Клапан переднего хода с\r\nправой стороны,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
6,/,Клапан\r\nзаднего\r\nхода\r\nс\r\nлевой стороны,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
7,/,Клапан переднего хода с\r\nлевой стороны,/,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...
8,00771606200430010,Пучок\r\nкабеля\r\nповоротной платформы,1,NaN,ECU Пучок кабеля (Deutz Двигатель TD2.9) 00771...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Клапан заднего хода с\r\nправой стороны,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
1,/,Клапан переднего хода с\r\nправой стороны,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
2,/,Клапан заднего хода с\r\nлевой стороны,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
3,/,Клапан переднего хода с\r\nлевой стороны,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
4,1020700540,Оконечное сопротивление,1,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
5,/,Диагностика двигателя\r\nШтуцер,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
6,1020305006,Контактор постоянного\r\nтока для подогрева,1,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
7,/,Реле стартерного двигателя,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
8,00771606200430010,Пучок кабеля поворотной\r\nплатформы,1,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
9,/,Уровень охлаждающей\r\nжидкости,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
10,/,Засорение воздушного\r\nфильтра,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
11,/,Индикатор зарядки,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...
12,/,Двигатель ECU Штепсель,/,NaN,ECU Пучок кабеля (Cummins Двигатель) 007716062...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Промежуточный модуль\r\nконцевого выключателя,/,NaN,Пучок кабеля стрелы 00771606200430000
1,1020516032,Бесконтактный\r\nвыключатель защиты от\r\nосла...,1,NaN,Пучок кабеля стрелы 00771606200430000
2,1020516032,Бесконтактный\r\nвыключатель защиты от\r\nосла...,1,NaN,Пучок кабеля стрелы 00771606200430000
3,1020700540,Оконечное сопротивление,1,NaN,Пучок кабеля стрелы 00771606200430000
4,1021404017,Датчик длины стрелы,1,NaN,Пучок кабеля стрелы 00771606200430000
5,1021404018,Датчик угла стрелы,1,NaN,Пучок кабеля стрелы 00771606200430000
6,00771606200410000,Пучок кабеля поворотной\r\nплатформы,0,NaN,Пучок кабеля стрелы 00771606200430000
7,1029906298,Концевой выключатель\r\nдлины стрелы,1,NaN,Пучок кабеля стрелы 00771606200430000
8,1029906298,Концевой выключатель\r\nдлины стрелы,1,NaN,Пучок кабеля стрелы 00771606200430000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,/,Переключатель защиты от\r\nпридавливания 1\r\n...,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
1,/,Переключатель защиты от\r\nпридавливания 2\r\n...,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
2,/,Клапан подъема при\r\nвыравнивании платформы,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
3,/,Клапан подъема консоли,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
4,/,Клапан поворота влево\r\nплатформы,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
5,/,Клапан поворота вправо\r\nплатформы,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
6,/,Клапан опускания консоли,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
7,/,Клапан опускания при\r\nвыравнивании платформы,/,NaN,Пучок кабелей рабочей платформы 00771406200440000
8,1020700540,Оконечное сопротивление,1,NaN,Пучок кабелей рабочей платформы 00771406200440000
9,1021404015,Датчик угла наклона\r\nплатформы,1,NaN,Пучок кабелей рабочей платформы 00771406200440000
10,1021404016,Датчик веса,1,NaN,Пучок кабелей рабочей платформы 00771406200440000
11,1020521022,Педальный переключатель,1,NaN,Пучок кабелей рабочей платформы 00771406200440000
12,00771606200210000,Электрический шкаф\r\nуправления платформой,1,NaN,Пучок кабелей рабочей платформы 00771406200440000

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примечание,Section
0,1029906298,Концевой выключатель правой\r\nзадней оси,1,NaN,Кабельный жгут шасси 00771606200460000
1,1021404304,Датчик угла поворота правого\r\nзаднего колеса,1,NaN,Кабельный жгут шасси 00771606200460000
2,1029906298,Концевой выключатель заднего\r\nлевого моста,1,NaN,Кабельный жгут шасси 00771606200460000
3,1021404304,Датчик угла поворота левого\r\nзаднего колеса,1,NaN,Кабельный жгут шасси 00771606200460000
4,/,Клапан переднего гидроцилиндра\r\nподъема-опус...,/,NaN,Кабельный жгут шасси 00771606200460000
5,/,Клапан заднего гидроцилиндра\r\nподъема-опускания,/,NaN,Кабельный жгут шасси 00771606200460000
6,/,Контактное кольцо Штепсель 1,/,NaN,Кабельный жгут шасси 00771606200460000
7,/,Контактное кольцо Штепсель 2,/,NaN,Кабельный жгут шасси 00771606200460000
8,/,Плавающий клапан управления,/,NaN,Кабельный жгут шасси 00771606200460000
9,/,Двухскоростной клапан,/,NaN,Кабельный жгут шасси 00771606200460000
10,/,Тормозной клапан,/,NaN,Кабельный жгут шасси 00771606200460000
11,1029906298,Концевой выключатель переднего\r\nгидроцилиндр...,NaN,NaN,Кабельный жгут шасси 00771606200460000
12,1029906298,Концевой выключатель левой\r\nпередней оси,NaN,NaN,Кабельный жгут шасси 00771606200460000
13,1021404304,Датчик угла поворота левого\r\nпереднего колеса,NaN,NaN,Кабельный жгут шасси 00771606200460000
14,1029906298,Концевой выключатель правой\r\nпередней оси,NaN,NaN,Кабельный жгут шасси 00771606200460000
15,1021404304,Датчик угла поворота правого\r\nпереднего колеса,NaN,NaN,Кабельный жгут шасси 00771606200460000
16,/,Клапан втягивания передней оси,/,NaN,Кабельный жгут шасси 00771606200460000
17,/,Клапан втягивания правого\r\nпереднего колеса ...,/,NaN,Кабельный жгут шасси 00771606200460000

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примечание,Section
0,/,Клапан втягивания левого\r\nпереднего колеса п...,/,NaN,Кабельный жгут шасси 00771606200460000
1,/,Клапан выдвижения левого\r\nпереднего колеса п...,/,NaN,Кабельный жгут шасси 00771606200460000
2,/,Клапан выдвижения правого\r\nпереднего колеса ...,/,NaN,Кабельный жгут шасси 00771606200460000
3,/,Клапан выдвижения передней оси,/,NaN,Кабельный жгут шасси 00771606200460000
4,/,Клапан выдвижения левого заднего\r\nколеса при...,/,NaN,Кабельный жгут шасси 00771606200460000
5,/,Клапан выдвижения правого\r\nзаднего колеса пр...,/,NaN,Кабельный жгут шасси 00771606200460000
6,/,Клапан выдвижения задней оси,/,NaN,Кабельный жгут шасси 00771606200460000
7,/,Клапан втягивания задней оси,/,NaN,Кабельный жгут шасси 00771606200460000
8,/,Усадочный клапан заднего правого\r\nрулевого м...,/,NaN,Кабельный жгут шасси 00771606200460000
9,/,Усадочный клапан заднего левого\r\nрулевого ме...,/,NaN,Кабельный жгут шасси 00771606200460000
11,/,Вставной модуль контроллера\r\nшасси,/,NaN,Кабельный жгут шасси 00771606200460000

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примеч\r\nание,Section
0,00771606200450010,Провод от положительного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
1,00771606200450070,Провод от положительного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
2,1020605356,Кольцевой предохранитель,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
3,0067220632181001A-c,Кронштейн кольцевого\r\nпредохранителя,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
4,1020402443,Изоляционная гайка,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
5,1020305006,Контактор постоянного тока,0,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
6,00771606200450100,Провод от реле к подогревателю,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
7,1029905348,Аккумулятор,0,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
8,00771606200450020,Провод от отрицательного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
9,1029900667,Ручной переключатель,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
10,00771606200450030,От ручного переключателя к\r\nжгуту заземления,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
11,00771606200450060,Провод от двигателя к\r\nотрицательному заземл...,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
12,1020605356,Кольцевой предохранитель,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
13,0067220632181001A-c,Кронштейн кольцевого\r\nпредохранителя,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
14,1020402443,Изоляционная гайка,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...
15,00771606200450050,Провод от вспомогательного\r\nсилового насоса ...,1,NaN,Кабель аккумулятора (Kohler Двигатель) 0077140...

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примеч\r\nание,Section
0,00771606200434010,Провод от положительного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
1,00771606200434060,Провод от положительного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
2,1020605356,Кольцевой предохранитель,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
3,0067220632181001A-c,Кронштейн кольцевого\r\nпредохранителя,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
4,1020402443,Изоляционная гайка,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
5,1020305006,Контактор постоянного тока,0,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
6,00771606200434070,Провод от реле к подогревателю,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
7,1029905348,Аккумулятор,0,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
8,00771606200434020,Провод от отрицательного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
9,1029900667,Ручной переключатель,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
10,00771606200434030,От ручного переключателя к\r\nжгуту заземления,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
11,00771406200434050,Провод от двигателя к\r\nотрицательному заземл...,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
12,1020605356,Кольцевой предохранитель,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
13,0067220632181001A-c,Кронштейн кольцевого\r\nпредохранителя,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
14,1020402443,Изоляционная гайка,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...
15,00771606200434040,Провод от вспомогательного\r\nсилового насоса ...,1,NaN,Кабель аккумулятора (Deutz Двигатель TD2.9)007...

,Код мат-ла,Наименование и спецификация,Кол-во\r\nштук,Примеч\r\nание,Section
0,00771606200450010,Провод от положительного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
1,00771606200434060,Провод от положительного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
2,1020605356,Кольцевой предохранитель,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
3,0067220632181001A-c,Кронштейн кольцевого\r\nпредохранителя,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
4,1020402443,Изоляционная гайка,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
5,1020305006,Контактор постоянного тока,0,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
6,00771606200450100,Провод от реле к подогревателю,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
7,1029905348,Аккумулятор,0,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
8,00771606200450020,Провод от отрицательного\r\nполюса аккумулятор...,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
9,1029900667,Ручной переключатель,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
10,00771606200450030,От ручного переключателя к\r\nжгуту заземления,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
11,00771406200450060,Провод от двигателя к\r\nотрицательному заземл...,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
12,1020605356,Кольцевой предохранитель,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
13,0067220632181001A-c,Кронштейн кольцевого\r\nпредохранителя,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
14,1020402443,Изоляционная гайка,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...
15,00771606200450050,Провод от вспомогательного\r\nсилового насоса ...,1,NaN,Кабель аккумулятора (Cummins Двигатель) 007716...

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773407000201060,Знак заправки по руководству\r\nпо эксплуатации,1,NaN,Маркировка в сборе 00771607000000000
1,00773407000201070,Знак «Опасность поражения\r\nэлектрическим током»,2,NaN,Маркировка в сборе 00771607000000000
2,00771607000201080,Знак инструкции управления\r\nназемным блоком ...,1,NaN,Маркировка в сборе 00771607000000000
3,00773407000201150,Знак «Отключить\r\nаккумулятор»,1,NaN,Маркировка в сборе 00771607000000000
4,00773407000201160,Знак «К работе допускается\r\nтолько уполномоч...,1,NaN,Маркировка в сборе 00771607000000000
5,00773407000201170,Знак «Запрещается\r\nприкасаться»,1,NaN,Маркировка в сборе 00771607000000000
6,00773407000201210,Знак «Опасность защемления»,2,NaN,Маркировка в сборе 00771607000000000
7,00771409900601042,Паспортная табличка,1,NaN,Маркировка в сборе 00771607000000000
8,00773407000201240,Знак «Запрещается подъем»,4,NaN,Маркировка в сборе 00771607000000000
9,00773407000201250,Знак «При транспортировке\r\nнеобходимо встави...,1,NaN,Маркировка в сборе 00771607000000000
10,00773407000201260,Знак «Меры\r\nпредосторожности при\r\nиспользо...,1,NaN,Маркировка в сборе 00771607000000000
11,00773407000201270,Знак «Запрещается промывать\r\nвысоконапорной ...,3,NaN,Маркировка в сборе 00771607000000000
12,00773407000201310,Знак «Категорически\r\nзапрещается модифициров...,1,NaN,Маркировка в сборе 00771607000000000
13,00773407000201360,Знак колеса «Опасность\r\nопрокидывания»,4,NaN,Маркировка в сборе 00771607000000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773407000201370,Знак 1 «Взрывоопасно»,1,NaN,Маркировка в сборе 00771607000000000
1,00773407000201380,Знак 2 «Взрывоопасно»,1,NaN,Маркировка в сборе 00771607000000000
2,00773407000201400,Знак «Внимательно\r\nпрочитайте инструкцию»,1,NaN,Маркировка в сборе 00771607000000000
3,00773407000201420,Знак «Строповка»,4,NaN,Маркировка в сборе 00771607000000000
4,00773407000201430,Знак «Подъем»,2,NaN,Маркировка в сборе 00771607000000000
5,00773407000201440,Знак «Руководство по\r\nэксплуатации выключате...,1,NaN,Маркировка в сборе 00771607000000000
6,00773407000201450,Знак «Предэксплуатационная\r\nпроверка»,1,NaN,Маркировка в сборе 00771607000000000
7,00773407000201470,Знак предупреждения ожогов,1,NaN,Маркировка в сборе 00771607000000000
8,00771407000201080,Знак в виде синей стрелки,2,NaN,Маркировка в сборе 00771607000000000
9,00771407000201090,Знак в виде желтой стрелки,2,NaN,Маркировка в сборе 00771607000000000
10,00771407000201120,LOGO1 ЗУМЛИОН кузова,1,NaN,Маркировка в сборе 00771607000000000
11,00773407000201030,LOGO2 ЗУМЛИОН кузова,1,NaN,Маркировка в сборе 00771607000000000
12,00771407000201150,Дизельный бак,1,NaN,Маркировка в сборе 00771607000000000
13,00771407000201170,Экологический ярлык,1,NaN,Маркировка в сборе 00771607000000000
14,00771607000201010,Знак нагрузки колеса,4,NaN,Маркировка в сборе 00771607000000000
15,00771607000201020,Знак схемы безопасного\r\nрабочего диапазона,1,NaN,Маркировка в сборе 00771607000000000
16,00771607000201030,Знак «Опасность\r\nопрокидывания»,3,NaN,Маркировка в сборе 00771607000000000
17,00771607000201060,Знак напоминания и\r\nинструкции по\r\nтранспо...,1,NaN,Маркировка в сборе 00771607000000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773407000201070,Знак «Опасность поражения\r\nэлектрическим током»,4,NaN,Маркировка в сборе 00771607000000000
1,00773407000201090,"Знак «Опасность\r\nопрокидывания, столкновения»",1,NaN,Маркировка в сборе 00771607000000000
2,00773407000201190,Знак «Опасность\r\nпридавливания»,2,NaN,Маркировка в сборе 00771607000000000
3,00773407000201210,Знак «Опасность защемления»,1,NaN,Маркировка в сборе 00771607000000000
4,00773407000201240,Знак «Запрещается подъем»,2,NaN,Маркировка в сборе 00771607000000000
5,00773407000201260,Знак «Меры предосторожности\r\nпри использовании»,1,NaN,Маркировка в сборе 00771607000000000
6,00773407000201320,Знак «Опасность\r\nстолкновения»,2,NaN,Маркировка в сборе 00771607000000000
7,00773407000201390,Знак «Хранение руководства по\r\nэксплуатации»,1,NaN,Маркировка в сборе 00771607000000000
8,00773407000201410,Знак «Точка крепления\r\nстраховочного троса»,6,NaN,Маркировка в сборе 00771607000000000
9,00773407000201420,Знак «Строповка»,4,NaN,Маркировка в сборе 00771607000000000
10,00773407000201430,Знак «Подъем»,2,NaN,Маркировка в сборе 00771607000000000
11,00773407000201450,Знак «Предэксплуатационная\r\nпроверка»,1,NaN,Маркировка в сборе 00771607000000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00771407000201010,"Опасность опрокидывания,\r\nзнак сигнализации ...",1,NaN,Маркировка в сборе 00771607000000000
1,00771607000201070,Знак инструкции управления\r\nпультом управлен...,1,NaN,Маркировка в сборе 00771607000000000
2,00771407000201130,LOGO ЗУМЛИОН стрелы,1,NaN,Маркировка в сборе 00771607000000000
3,00773407000201010,LOGO ЗУМЛИОН платформы,1,NaN,Маркировка в сборе 00771607000000000
4,00773407000201050,ЗУМЛИОН противовеса,1,NaN,Маркировка в сборе 00771607000000000
5,00771407000201160,Гидравлический бак,1,NaN,Маркировка в сборе 00771607000000000
6,00771607000201020,Знак схемы безопасного\r\nрабочего диапазона,1,NaN,Маркировка в сборе 00771607000000000
7,00771607000201030,Знак «Опасность\r\nопрокидывания»,1,NaN,Маркировка в сборе 00771607000000000
8,00771607000201040,Номинальное значение уклона,1,NaN,Маркировка в сборе 00771607000000000
9,00771607000201050,Знак ZT34J,1,NaN,Маркировка в сборе 00771607000000000
10,00773407000201480,Низкий уровень масла,1,NaN,Маркировка в сборе 00771607000000000
11,00773407000201490,Высокий уровень масла,1,NaN,Маркировка в сборе 00771607000000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section
0,00773407000201180,Знак «Запрещается наступать»,4,NaN,Маркировка в сборе 00771607000000000
1,00773407000201200,Знак «Запрещается\r\nподдерживать руками или\r...,3,NaN,Маркировка в сборе 00771607000000000
2,00773407000201230,Знак «Отказ педали»,1,NaN,Маркировка в сборе 00771607000000000
3,00773407000201470,Знак предупреждения ожогов,1,NaN,Маркировка в сборе 00771607000000000
4,00771407000201080,Знак в виде синей стрелки,1,NaN,Маркировка в сборе 00771607000000000
5,00771407000201090,Знак в виде желтой стрелки,1,NaN,Маркировка в сборе 00771607000000000
6,00771407000201100,Знак в виде желтого\r\nтреугольника,2,NaN,Маркировка в сборе 00771607000000000
7,00771407000201110,Знак в виде синего\r\nтреугольника,2,NaN,Маркировка в сборе 00771607000000000

,Код мат-ла,Наименование и\r\nспецификация,Кол-во\r\nштук,Примечание,Section,Наименование и спецификация,Кол-в\r\nо\r\nштук,№ п\r\n/п,Примеч\r\nание
0,00773406200210000,Электрический шкаф\r\nуправления платформой в\...,1,NaN,Рабочая платформа00771100100000000,NaN,NaN,NaN,NaN
1,1040200503,Гайка M8-8,6,GB/T 889.1-2000,Рабочая платформа00771100100000000,NaN,NaN,NaN,NaN
2,1040302480,Шайба 8-200HV,12,GB/T 96.1-2002,Рабочая платформа00771100100000000,NaN,NaN,NaN,NaN
3,00773406300201030,Резиновая прокладка,2,NaN,Рабочая платформа00771100100000000,NaN,NaN,NaN,NaN
4,1040004619,Болт M8×35-8.8,4,GB/T 5783-2000,Рабочая платформа00771100100000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1269,00773407000201470,Знак предупреждения ожогов,1,NaN,Маркировка в сборе 00771607000000000,NaN,NaN,NaN,NaN
1270,00771407000201080,Знак в виде синей стрелки,1,NaN,Маркировка в сборе 00771607000000000,NaN,NaN,NaN,NaN
1271,00771407000201090,Знак в виде желтой стрелки,1,NaN,Маркировка в сборе 00771607000000000,NaN,NaN,NaN,NaN
1272,00771407000201100,Знак в виде желтого\r\nтреугольника,2,NaN,Маркировка в сборе 00771607000000000,NaN,NaN,NaN,NaN
1273,00771407000201110,Знак в виде синего\r\nтреугольника,2,NaN,Маркировка в сборе 00771607000000000,NaN,NaN,NaN,NaN

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section,№ п\n\n/п
0,00773406200210000,Электрический шкаф\n\nуправления платформой в\...,1,NaN,Рабочая платформа00771100100000000,NaN
1,1040200503,Гайка M8-8,6,GB/T 889.1-2000,Рабочая платформа00771100100000000,NaN
2,1040302480,Шайба 8-200HV,12,GB/T 96.1-2002,Рабочая платформа00771100100000000,NaN
3,00773406300201030,Резиновая прокладка,2,NaN,Рабочая платформа00771100100000000,NaN
4,1040004619,Болт M8×35-8.8,4,GB/T 5783-2000,Рабочая платформа00771100100000000,NaN

100%|██████████| 1/1 [00:02<00:00,  2.82s/it]

- Спросить у Миши про запчасти, в описании которых встречается ещё одна модель, помимо основной, в которой они встречаются
- Что делать с такими в описании (Cubota): ZT138J-ZT24JE-V Turntable Decal Assembly - что значит тире?